# Copyright 2019 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/cpp/library_headers.gni")
import("//zircon/kernel/kernel_rust_crate.gni")
import("//zircon/kernel/kernel_rust_mod.gni")

library_headers("headers") {
  headers = [
    "lib/user_copy/user_ptr.h",
    "lib/user_copy/user_iovec.h",
  ]
  public_deps = [
    # <lib/user_copy/user_ptr.h> has #include <ktl/type_traits.h>.
    "//zircon/kernel/lib/ktl:headers",
  ]
}

static_library("user_copy") {
  public_deps = [ ":headers" ]

  sources = [ "internal.cc" ]
  deps = [
    ":user-copy-rs",
    "//zircon/kernel/vm:headers",
  ]
}

group("tests") {
  testonly = true
}

source_set("kernel-tests") {
  testonly = true

  sources = [ "user_copy_tests.cc" ]
  deps = [
    ":headers",
    ":user_copy_rs_kernel_tests",
    "//zircon/kernel/lib/page",
    "//zircon/kernel/lib/unittest",
    "//zircon/system/ulib/zircon-internal",
  ]
}

group("phys-tests") {
  testonly = true
}

group("boot_tests") {
  testonly = true
}

kernel_rust_mod("user-copy-rs") {
  output_name = "user_copy"
  source_root = "src/mod.rs"
  sources = [
    "src/mod.rs",
    "src/user_iovec.rs",
    "src/user_ptr.rs",
    "src/user_string_view.rs",
  ]
  deps = [
    "//sdk/rust/zx-status",
    "//sdk/rust/zx-types",
    "//third_party/rust_crates:zerocopy",
  ]
}

kernel_rust_mod("user_copy_rs_kernel_tests") {
  testonly = true
  source_root = "tests/kernel.rs"
  sources = [ "tests/kernel.rs" ]
  deps = [
    "//sdk/rust/zx-status",
    "//sdk/rust/zx-types",
  ]
  test_deps = [ "//zircon/kernel/lib/unittest:unittest-rs" ]
}
