# Copyright 2023 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(is_host, "Python targets only build in a host toolchain")

# All of the lacewing example tests and their dependencies.
group("examples") {
  testonly = true
  public_deps = [
    "async_test_cases_example",
    "data_resource_access_test",
    "exoneration_failing_test",
    "hello_world_test",
    "multi_device_test_sl4f",
    "openwrt_ap_test",
    "power_cycle_test",
    "test_case_revive_example:run_wo_test_case_revive",
    "test_case_revive_example:test_case_revive_with_hard_reboot",
    "test_case_revive_example:test_case_revive_with_soft_reboot",
    "test_cases_example",
    "test_cases_revive_example",
    "test_soft_reboot:soft_reboot_test",
    "test_soft_reboot:soft_reboot_test.hermetic",
    "test_soft_reboot:soft_reboot_test_with_ffx_monitor",
    "test_soft_reboot:test_soft_reboot_sl4f",
  ]
}
