# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load(
    "//build/bazel/rules/rust:defs.bzl",
    "rustc_library",
)

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "cm_fidl_validator",
    srcs = [
        "src/error.rs",
        "src/lib.rs",
        "src/util.rs",
    ],
    crate_name = "cm_fidl_validator",
    edition = "2024",
    test_deps = [
        "//sdk/fidl/fuchsia.data:fuchsia.data_rust",
        "//sdk/fidl/fuchsia.io:fuchsia.io_rust",
        "//third_party/rust_crates/vendor:proptest",
        "//third_party/rust_crates/vendor:regex",
        "//third_party/rust_crates/vendor:test-case",
        "//third_party/rust_crates/vendor:url",
    ],
    visibility = [
        "//:__subpackages__",
    ],
    with_unit_tests = True,
    deps = [
        "//sdk/fidl/fuchsia.component.decl:fuchsia.component.decl_rust",
        "//src/lib/directed_graph",
        "//src/sys/lib/cm_graph",
        "//src/sys/lib/cm_types",
        "//third_party/rust_crates/vendor:itertools",
        "//third_party/rust_crates/vendor:thiserror",
    ],
)
