# Copyright 2023 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//src/connectivity/wlan/tests/core/test_lists.gni")
import("//src/connectivity/wlan/tests/wlancfg/test_lists.gni")

assert(is_host, "antlion tests only supported for host testing")

group("e2e_tests") {
  testonly = true
  public_deps =
      [ "wlan:e2e_tests" ] +
      # As tests are migrated out of the antlion directory, add them
      # to this group to ensure they are still included in the e2e
      # test suite for release testing.
      core_tests_for_fyi_long + wlancfg_tests_for_presubmit +
      wlancfg_tests_for_wlan_presubmit + wlancfg_tests_for_postsubmit +
      wlancfg_tests_for_fyi + wlancfg_tests_for_fyi_long
}
