# Copyright 2024 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bazel/bazel_fuchsia_test_package.gni")
import("//build/bazel/drivers/bazel_driver_package.gni")

bazel_driver_package("pkg") {
  testonly = true
  bazel_target = "//examples/drivers/template:pkg"
  package_name = "template"
}

bazel_fuchsia_test_package("template-test") {
  test_component_names = [ "template-test-bin" ]
  test_specs = {
    environments = basic_envs
    log_settings = {
      max_severity = "ERROR"
    }
  }
}
