# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bind/bind.gni")
import("//build/drivers.gni")

fuchsia_driver_dml("pci-sdhci-dml") {
  dml = "meta/pci-sdhci.dml"
  driver_name = "pci-sdhci"
}

driver_bind_rules("pci-sdhci-bind") {
  bind_output = "pci-sdhci.bindbc"
  dml_label = ":pci-sdhci-dml"
  tests = "meta/pci-sdhci-bind-test.json"
  deps = [
    "//src/devices/bind/fuchsia",
    "//src/devices/bind/fuchsia.acpi",
    "//src/devices/bind/fuchsia.pci",
  ]
}

fuchsia_cc_driver("pci-sdhci-driver") {
  output_name = "pci-sdhci"
  configs += [
    "//build/config:all_source",
    "//build/config/fuchsia:enable_zircon_asserts",
  ]
  sources = [ "pci-sdhci.cc" ]
  deps = [
    "//sdk/fidl/fuchsia.hardware.sdhci:fuchsia.hardware.sdhci_cpp",
    "//sdk/lib/driver/component/cpp",
    "//sdk/lib/driver/logging/cpp",
    "//src/devices/bind/fuchsia:fuchsia_cpp",
    "//src/devices/lib/driver:driver_runtime",
    "//src/devices/pci/lib/device-protocol-pci",
    "//zircon/system/ulib/sync",
  ]
}

fuchsia_driver_component("pci-sdhci") {
  dml_label = ":pci-sdhci-dml"
  component_name = "pci-sdhci"
  deps = [
    ":pci-sdhci-bind",
    ":pci-sdhci-driver",
  ]
  info = "meta/pci-sdhci-info.json"
}

fuchsia_driver_package("package") {
  package_name = "pci-sdhci"
  driver_components = [ ":pci-sdhci" ]
}

group("tests") {
  testonly = true
  deps = [ ":pci-sdhci-bind_test" ]
}
