# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")
load("//build/bazel/rules/host:defs.bzl", "go_binary_host_tool")
load("//tools/fidl/lib/fidlgentest:fidlgentest_go_test.bzl", "fidlgentest_go_test")

package(default_applicable_licenses = ["//:license"])

go_library(
    name = "codegen",
    srcs = [
        "codegen/codegen.go",
        "codegen/ir.go",
    ],
    embedsrcs = [
        "codegen/bits.tmpl",
        "codegen/enum.tmpl",
        "codegen/library.tmpl",
        "codegen/protocol.tmpl",
        "codegen/struct.tmpl",
        "codegen/table.tmpl",
        "codegen/union.tmpl",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/fidl/fidlgen_go/codegen",
    target_compatible_with = HOST_CONSTRAINTS,
    deps = ["//tools/fidl/lib/fidlgen"],
)

fidlgentest_go_test(
    name = "fidlgen_go_lib_tests",
    srcs = ["codegen/ir_test.go"],
    embed = [":codegen"],
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//tools:__pkg__"],
)

go_binary_host_tool(
    name = "fidlgen_go",
    srcs = ["main.go"],
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = [
        "//build/bazel/rules/fidl:__subpackages__",
    ],
    deps = [
        ":codegen",
        "//tools/fidl/lib/fidlgen",
    ],
)
