# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//src/starnix/lib/selinux/policy.gni")

sepolicy_source_set("userspace_base_policy") {
  testonly = true
  deps = [ "//src/starnix/lib/selinux/testdata:base_policy" ]
  sources = [ "test_policy.conf" ]
}

template("userspace_policy") {
  sepolicy_binary(target_name) {
    testonly = true
    prebuilt = "prebuilt/$target_name"
    deps = [ ":userspace_base_policy" ]
    sources = invoker.sources
  }
}

userspace_policy("anon_inode_policy") {
  sources = [ "anon_inode_policy.conf" ]
}

userspace_policy("append_policy") {
  sources = [ "append_policy.conf" ]
}

userspace_policy("audit_access_policy") {
  sources = [ "audit_access_policy.conf" ]
}

userspace_policy("binder_policy") {
  sources = [ "binder_policy.conf" ]
}

userspace_policy("bpf_policy") {
  sources = [ "bpf_policy.conf" ]
}

userspace_policy("capabilities_policy") {
  sources = [ "capabilities_policy.conf" ]
}

userspace_policy("fcntl_policy") {
  sources = [ "fcntl_policy.conf" ]
}

userspace_policy("file_transition_policy") {
  sources = [ "file_transition_policy.conf" ]
}

userspace_policy("fs_test_policy") {
  sources = [ "fs_test_policy.conf" ]
}

userspace_policy("genfscon_create_policy") {
  sources = [ "genfscon_create_policy.conf" ]
}

userspace_policy("inherit_policy") {
  sources = [ "inherit_policy.conf" ]
}

userspace_policy("invalidated_sid_initial_policy") {
  sources = [ "invalidated_sid_initial_policy.conf" ]
}

userspace_policy("invalidated_sid_reloaded_policy") {
  sources = [ "invalidated_sid_reloaded_policy.conf" ]
}

userspace_policy("io_uring_policy") {
  sources = [ "io_uring_policy.conf" ]
}

userspace_policy("ioctl_policy") {
  sources = [ "ioctl_policy.conf" ]
}

userspace_policy("memfd_class_policy") {
  sources = [ "memfd_class_policy.conf" ]
}

userspace_policy("memfd_transition_policy") {
  sources = [ "memfd_transition_policy.conf" ]
}

userspace_policy("minimal_policy") {
  sources = [ "//src/starnix/lib/selinux/testdata/composite_policies/new_file/minimal_policy.conf" ]
}

userspace_policy("mmap_policy") {
  sources = [ "mmap_policy.conf" ]
}

userspace_policy("mount_policy") {
  sources = [ "mount_policy.conf" ]
}

userspace_policy("mprotect_policy") {
  sources = [ "mprotect_policy.conf" ]
}

userspace_policy("netlink_audit_policy") {
  sources = [ "netlink_audit_policy.conf" ]
}

userspace_policy("netlink_xperms_policy") {
  sources = [ "netlink_xperms_policy.conf" ]
}

userspace_policy("open_perms_policy") {
  sources = [ "open_perms_policy.conf" ]
}

userspace_policy("overlayfs_policy") {
  sources = [ "overlayfs_policy.conf" ]
}

userspace_policy("perf_event_policy") {
  sources = [ "perf_event_policy.conf" ]
}

userspace_policy("pipe_policy") {
  sources = [ "pipe_policy.conf" ]
}

userspace_policy("ptrace_policy") {
  sources = [ "ptrace_policy.conf" ]
}

userspace_policy("sched_policy") {
  sources = [ "sched_policy.conf" ]
}

userspace_policy("selinuxfs_policy") {
  sources = [ "selinuxfs_policy.conf" ]
}

userspace_policy("socket_policy") {
  sources = [ "socket_policy.conf" ]
}

userspace_policy("syslog_policy") {
  sources = [ "syslog_policy.conf" ]
}

userspace_policy("timerslack_policy") {
  sources = [ "timerslack_policy.conf" ]
}

userspace_policy("tun_policy") {
  sources = [ "tun_policy.conf" ]
}

userspace_policy("userspace_initial_context_policy") {
  sources = [ "userspace_initial_context_policy.conf" ]
}

userspace_policy("xattr_access_policy") {
  sources = [ "xattr_access_policy.conf" ]
}

group("policies") {
  testonly = true
  deps = [
    ":anon_inode_policy",
    ":append_policy",
    ":audit_access_policy",
    ":binder_policy",
    ":bpf_policy",
    ":capabilities_policy",
    ":fcntl_policy",
    ":file_transition_policy",
    ":fs_test_policy",
    ":genfscon_create_policy",
    ":inherit_policy",
    ":invalidated_sid_initial_policy",
    ":invalidated_sid_reloaded_policy",
    ":io_uring_policy",
    ":ioctl_policy",
    ":memfd_class_policy",
    ":memfd_transition_policy",
    ":minimal_policy",
    ":mmap_policy",
    ":mount_policy",
    ":mprotect_policy",
    ":netlink_audit_policy",
    ":netlink_xperms_policy",
    ":open_perms_policy",
    ":overlayfs_policy",
    ":perf_event_policy",
    ":pipe_policy",
    ":ptrace_policy",
    ":sched_policy",
    ":selinuxfs_policy",
    ":socket_policy",
    ":syslog_policy",
    ":timerslack_policy",
    ":tun_policy",
    ":userspace_initial_context_policy",
    ":xattr_access_policy",
  ]
}
