# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/assembly/product_bundle_test_group.gni")
import("//build/testing/environments.gni")

product_bundle_test_group("x64") {
  product_bundle_name = "workbench_eng.x64"
  environments = [ aemu_env ]
  tests = [ "//bundles/buildbot/workbench" ]
}
