# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bind/bind.gni")
import("//build/components.gni")
import("//build/drivers.gni")

fuchsia_driver_dml("driver-serve-fidl-dml") {
  dml = "meta/driver-serve-fidl.dml"
  driver_name = "driver-serve-fidl"
}

driver_bind_rules("bind") {
  dml_label = ":driver-serve-fidl-dml"
  bind_output = "driver-serve-fidl.bindbc"
}

fuchsia_cc_driver("driver") {
  testonly = true
  output_name = "eval_driver_serve_fidl_cpp"
  sources = [ "src/driver.cc" ]
  deps = [
    "//sdk/lib/driver/component/cpp",
    "//sdk/lib/driver/logging/cpp",
    "//src/devices/lib/driver:driver_runtime",
  ]
}

fuchsia_driver_component("component") {
  testonly = true
  component_name = "eval_driver_serve_fidl"
  dml_label = ":driver-serve-fidl-dml"
  deps = [
    ":bind",
    ":driver",
  ]
  info = "meta/component-info.json"
}
