from _typeshed import Incomplete
from mobly.controllers.android_device_lib import errors as errors
from mobly.controllers.android_device_lib import (
    snippet_client_v2 as snippet_client_v2,
)
from mobly.controllers.android_device_lib.services import (
    base_service as base_service,
)

MISSING_SNIPPET_CLIENT_MSG: str

class Error(errors.ServiceError):
    SERVICE_TYPE: str

class SnippetManagementService(base_service.BaseService):
    def __init__(self, device, configs: Incomplete | None = ...) -> None: ...
    @property
    def is_alive(self): ...
    def get_snippet_client(self, name): ...
    def add_snippet_client(self, name, package) -> None: ...
    def remove_snippet_client(self, name) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def __getattr__(self, name): ...
