# Copyright 2023 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(is_host, "These tools should only be included via 'host_tools'.")

# Compiled tools that are depended on by shac checks under //scripts/shac.
group("shac") {
  testonly = true
  deps = [ "//bundles/buildbot/static_checks" ]
}
