# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bazel/bazel_host_tool.gni")

assert(is_host, "bazel_host_tool() can only be called in a host toolchain.")

bazel_host_tool("measure-tape") {
  bazel_target = ":measure-tape"
  bazel_output_path = "{{BAZEL_TARGET_OUT_DIR}}/measure-tape_/measure-tape"
  install_host_tool = true
}
