// Copyright 2026 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is automatically generated by //zircon/system/ulib/fbl/rust:fbl_bindgen_golden.

#![expect(dead_code)]
#![expect(non_camel_case_types)]
#![expect(non_upper_case_globals)]

#[derive(PartialEq, Eq, Copy, Clone, Debug, Hash)]
#[repr(C, align(8))]
pub struct __BindgenOpaqueArray8<T>(pub T);
impl<T: Copy + Default, const N: usize> Default for __BindgenOpaqueArray8<[T; N]> {
    fn default() -> Self {
        Self([<T as Default>::default(); N])
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fbl_internal_ContainerPtrTraits {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug)]
pub struct fbl_internal_CommonNodeStateBase {
    pub _address: u8,
}
pub const fbl_NodeOptions_None: fbl_NodeOptions = 0;
pub const fbl_NodeOptions_AllowCopy: fbl_NodeOptions = 1;
pub const fbl_NodeOptions_AllowCopyFromContainer: fbl_NodeOptions = 2;
pub const fbl_NodeOptions_AllowMove: fbl_NodeOptions = 4;
pub const fbl_NodeOptions_AllowMoveFromContainer: fbl_NodeOptions = 8;
pub const fbl_NodeOptions_AllowCopyMove: fbl_NodeOptions = 5;
pub const fbl_NodeOptions_AllowCopyMoveFromContainer: fbl_NodeOptions = 10;
pub const fbl_NodeOptions_AllowMultiContainerUptr: fbl_NodeOptions = 16;
pub const fbl_NodeOptions_AllowRemoveFromContainer: fbl_NodeOptions = 32;
pub const fbl_NodeOptions_AllowClearUnsafe: fbl_NodeOptions = 64;
pub const fbl_NodeOptions_ReservedBits: fbl_NodeOptions = 17293822569102704640;
pub type fbl_NodeOptions = u64;
pub type fbl_DoublyLinkedListNodeState_Base = fbl_internal_CommonNodeStateBase;
pub type fbl_DoublyLinkedListNodeState_PtrType<PtrType_> = PtrType_;
pub type fbl_DoublyLinkedListNodeState_PtrTraits = fbl_internal_ContainerPtrTraits;
pub type fbl_SinglyLinkedListNodeState_Base = fbl_internal_CommonNodeStateBase;
pub type fbl_SinglyLinkedListNodeState_PtrType<PtrType_> = PtrType_;
pub type fbl_SinglyLinkedListNodeState_PtrTraits = fbl_internal_ContainerPtrTraits;
#[repr(C)]
#[derive(Debug)]
pub struct fbl_bindgen_DummyObject {
    _unused: [u8; 0],
}
pub type fbl_bindgen_Canary32 = u32;
#[repr(C)]
#[derive(Debug)]
pub struct fbl_bindgen_CanaryContainer {
    pub canary: u32,
}
#[repr(C)]
#[derive(Debug)]
pub struct fbl_bindgen_SinglyNodeWrapper {
    pub state: __BindgenOpaqueArray8<[u8; 8usize]>,
}
#[repr(C)]
#[derive(Debug)]
pub struct fbl_bindgen_DoublyNodeWrapper {
    pub state: __BindgenOpaqueArray8<[u8; 16usize]>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fbl_bindgen_WAVLNodeWrapper {
    pub state: __BindgenOpaqueArray8<[u8; 32usize]>,
}
#[repr(C)]
#[derive(Debug)]
pub struct fbl_bindgen_RefCountedObject {
    pub _base: u32,
    pub value: ::core::ffi::c_int,
}
