# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/rust/rustc_library.gni")
import(
    "//third_party/github.com/google/experimental-emboss-rust/build_defs.gni")

emboss_rust_library("pw_bluetooth_att_emb") {
  source = "emboss/pw_bluetooth/att.emb"
}

emboss_rust_library("pw_bluetooth_hci_common_emb") {
  source = "emboss/pw_bluetooth/hci_common.emb"
}

emboss_rust_library("pw_bluetooth_hci_commands_emb") {
  source = "emboss/pw_bluetooth/hci_commands.emb"
  imports = [ "emboss/pw_bluetooth/hci_common.emb" ]
  import_dirs = [ "emboss" ]
  deps = [ ":pw_bluetooth_hci_common_emb" ]
}

emboss_rust_library("pw_bluetooth_hci_h4_emb") {
  source = "emboss/pw_bluetooth/hci_h4.emb"
}

emboss_rust_library("pw_bluetooth_l2cap_frames_emb") {
  source = "emboss/pw_bluetooth/l2cap_frames.emb"
}

rustc_library("sapphire-emboss") {
  edition = "2024"
  with_unit_tests = true
  sources = [ "src/lib.rs" ]
  deps = [
    ":pw_bluetooth_att_emb",
    ":pw_bluetooth_hci_commands_emb",
    ":pw_bluetooth_hci_common_emb",
    ":pw_bluetooth_hci_h4_emb",
    ":pw_bluetooth_l2cap_frames_emb",
    "//third_party/github.com/google/experimental-emboss-rust:emboss_runtime",
  ]
}

group("tests") {
  testonly = true
  deps = [ ":sapphire-emboss_test($host_toolchain)" ]
}
