# Copyright 2026 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/cpp/library_headers.gni")
import("//zircon/kernel/kernel_bindgen_crate.gni")
import("//zircon/kernel/kernel_rust_mod.gni")

library_headers("headers") {
  headers = []
  public_configs = [ "//zircon/kernel/switch:headers" ]
  public_deps = [ "//zircon/kernel/lib/libc:headers" ]
}

kernel_bindgen_crate("arch-types-bindings") {
  headers = [ "//zircon/kernel/include/arch.h" ]
  cpp = true
  non_rust_deps = [ ":headers" ]
  raw_lines = [ "#![no_std]" ]
  type_allowlist = [
    "UserEntryState",
    "GeneralRegsSource",
  ]
  rustified_enum = [ "GeneralRegsSource" ]
  std_derives = [
    "default",
    "eq",
    "partialeq",
  ]
  expect_lints = []
  notice_year = 2026
}

kernel_rust_mod("arch-rs") {
  output_name = "arch_rs"
  source_root = "src/mod.rs"
  sources = [
    "src/api.rs",
    "src/mod.rs",
    "src/ops.rs",
  ]
  deps = [
    ":arch-types-bindings",
    "//sdk/rust/zx-status",
    "//sdk/rust/zx-types",
  ]
  if (current_cpu == "arm64") {
    deps += [ "//zircon/kernel/arch/arm64:arch-arm64-rs" ]
  } else if (current_cpu == "riscv64") {
    deps += [ "//zircon/kernel/arch/riscv64:arch-riscv64-rs" ]
  } else if (current_cpu == "x64") {
    deps += [ "//zircon/kernel/arch/x86:arch-x86-rs" ]
  }
}

source_set("ffi") {
  sources = [ "arch_ffi.cc" ]
  deps = [ "//zircon/kernel/lib/ktl" ]
}
