# Copyright 2026 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//zircon/kernel/kernel_rust_mod.gni")

kernel_rust_mod("arch-rs") {
  output_name = "arch_rs"
  source_root = "src/mod.rs"
  sources = [
    "src/mod.rs",
    "src/ops.rs",
  ]
  deps = [ "//sdk/rust/zx-status" ]
  if (current_cpu == "arm64") {
    deps += [ "//zircon/kernel/arch/arm64:arch-arm64-rs" ]
  } else if (current_cpu == "riscv64") {
    deps += [ "//zircon/kernel/arch/riscv64:arch-riscv64-rs" ]
  } else if (current_cpu == "x64") {
    deps += [ "//zircon/kernel/arch/x86:arch-x86-rs" ]
  }
}

source_set("ffi") {
  sources = [ "arch_ffi.cc" ]
  deps = [ "//zircon/kernel/lib/ktl" ]
}
