# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")
load("//build/bazel/rules/host:defs.bzl", "go_binary_host_tool")
load("//build/bazel/rules/host_tests:host_go_test.bzl", "host_go_test")

package(default_applicable_licenses = ["//:license"])

go_library(
    name = "lib",
    srcs = [
        "assembly_input_archives.go",
        "assembly_manifests.go",
        "blobs.go",
        "debug_symbols.go",
        "images.go",
        "licenses.go",
        "modules.go",
        "product_bundle2.go",
        "product_size_checker_output.go",
        "sdk_archives.go",
        "tools.go",
        "upload.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/artifactory",
    target_compatible_with = HOST_CONSTRAINTS,
    deps = [
        "//tools/build",
        "//tools/lib/logger",
        "//tools/lib/osmisc",
    ],
)

go_library(
    name = "main",
    srcs = [
        "cmd/main.go",
        "cmd/up.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/artifactory/cmd",
    target_compatible_with = HOST_CONSTRAINTS,
    deps = [
        ":lib",
        "//third_party/golibs:github.com/google/subcommands",
        "//tools/build",
        "//tools/lib/color",
        "//tools/lib/iomisc",
        "//tools/lib/jsonutil",
        "//tools/lib/logger",
    ],
)

go_binary_host_tool(
    name = "artifactory",
    embed = [":main"],
    target_compatible_with = HOST_CONSTRAINTS,
)

host_go_test(
    name = "artifactory_lib_tests",
    srcs = [
        "assembly_input_archives_test.go",
        "assembly_manifests_test.go",
        "blobs_test.go",
        "debug_symbols_test.go",
        "images_test.go",
        "licenses_test.go",
        "modules_test.go",
        "product_bundle2_test.go",
        "product_size_checker_output_test.go",
        "sdk_archives_test.go",
        "tools_test.go",
    ],
    embed = [":lib"],
    visibility = ["//tools:__pkg__"],
    deps = [
        "//third_party/golibs:github.com/google/go-cmp/cmp",
        "//third_party/golibs:github.com/google/go-cmp/cmp/cmpopts",
        "//tools/lib/jsonutil",
    ],
)

host_go_test(
    name = "artifactory_main_tests",
    srcs = [
        "cmd/up_test.go",
    ],
    embed = [":main"],
    visibility = ["//tools:__pkg__"],
)
