// Copyright 2020 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package artifactory

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"go.fuchsia.dev/fuchsia/tools/build"
)

// LINT.IfChange(ExportedDebugSymbol)
// ExportedDebugSymbol represents an entry in the debug_symbols.json manifest
// generated by the 'build/api/client export_last_build_debug_symbols' command.
type ExportedDebugSymbol struct {
	// Debug is the path to the unstripped or separate debug file.
	Debug string `json:"debug"`

	// Stripped is the path to the stripped file if available.
	Stripped string `json:"stripped,omitempty"`

	// Dist is the path to the stripped binary for deployment/execution. If present.
	DestPath string `json:"dist,omitempty"`

	// BuildID is the lowercase ASCII hexadecimal representation of the
	// ELF build ID.
	BuildID string `json:"elf_build_id"`

	// CPU is the CPU architecture of the binary.
	CPU string `json:"cpu"`

	// OS is the operating system that the binary is for.
	OS string `json:"os"`

	// Label is the GN or Bazel label of the target generating the binary.
	Label string `json:"label"`

	// Type is the type of the binary.
	Type string `json:"type"`

	// Breakpad is the path to the breakpad symbol file for the debug binary, if
	// present.
	Breakpad string `json:"breakpad,omitempty"`

	// GSYM is the path to the GSYM symbol file for the debug binary, if
	// present.
	GSYM string `json:"gsym,omitempty"`
}

// LINT.ThenChange(//BUILD.gn:debug_symbols)

// DebugSymbolUploads runs the 'export_last_build_debug_symbols' command and
// parses the generated manifest describing debug binaries produced by the build, then
// returns a list of Uploads corresponding to the following files:
//
//   - The debug_symbols.json describing all entries.
//   - The build-ids.json file mapping build-id values to labels.
//   - The build-ids.txt file listing build-id values for Fuchsia binaries only.
//   - Debug binaries placed under {debugNamespace}/{buildid}.debug, {buildidNamespace}/{buildid}/debuginfo
//   - Stripped binaries, if available, are placed under {buildidNamespace}/{buildid}/executable.
//     Otherwise, that location is just a copy of the debug binary.
func DebugSymbolUploads(ctx context.Context, mods *build.Modules, outputNamespace, debugNamespace, buildidNamespace string) ([]Upload, error) {
	buildAPIClient, err := build.NewBuildAPIClient(mods.BuildDir())
	if err != nil {
		return nil, err
	}
	outputDir, err := os.MkdirTemp("", "debug_symbols")
	if err != nil {
		return nil, fmt.Errorf("cannot create export directory: %w", err)
	}
	// Generate only breakpad symbols, but not GSYM ones as the extraction
	// of the latter often fails with errors that look like:
	//
	// ERROR: DWARF conversion failed: : no functions to encode
	//
	err = buildAPIClient.ExportLastBuildDebugSymbols(outputDir, true, false)
	if err != nil {
		return nil, fmt.Errorf("failed to export debug symbols from last build: %w", err)
	}
	return debugSymbolUploads(ctx, outputDir, outputNamespace, debugNamespace, buildidNamespace)
}

func debugSymbolUploads(ctx context.Context, outputDir string, outputNamespace, debugNamespace, buildidNamespace string) ([]Upload, error) {
	outputManifest, err := os.ReadFile(filepath.Join(outputDir, "debug_symbols.json"))
	if err != nil {
		return nil, fmt.Errorf("could not read debug symbols from export manifest: %w", err)
	}

	var debug_symbols []ExportedDebugSymbol
	err = json.Unmarshal(outputManifest, &debug_symbols)
	if err != nil {
		return nil, fmt.Errorf("could not parse debug symbols from export manifest: %w", err)
	}

	var uploads []Upload

	uploads = append(uploads, Upload{
		Source:      filepath.Join(outputDir, "build-ids.txt"),
		Destination: filepath.Join(outputNamespace, "build-ids.txt"),
		Deduplicate: true,
		Compress:    true,
	})
	uploads = append(uploads, Upload{
		Source:      filepath.Join(outputDir, "build-ids.json"),
		Destination: filepath.Join(outputNamespace, "build-ids.json"),
		Deduplicate: true,
		Compress:    true,
	})

	uploads = append(uploads, Upload{
		Source:      filepath.Join(outputDir, "debug_symbols.json"),
		Destination: filepath.Join(outputNamespace, "debug_symbols.json"),
		Deduplicate: true,
		Compress:    true,
	})

	for _, debug_entry := range debug_symbols {
		id := debug_entry.BuildID
		if id == "" {
			return nil, fmt.Errorf("Debug symbol entry is missing BuildID value: %q", debug_entry)
		}

		// We upload all debug binaries to a flat namespace.
		debugSrc := filepath.Join(outputDir, debug_entry.Debug)
		uploads = append(uploads, Upload{
			Source:      debugSrc,
			Destination: fmt.Sprintf("%s/%s.debug", debugNamespace, id),
			Deduplicate: true,
			Compress:    true,
		})

		// Upload in debuginfod API format. Note that the same debug binary is
		// uploaded to both the /debuginfo and /executable path. This is compliant
		// with the debuginfod spec, as the distinction is used to support split
		// debug info modes.
		uploads = append(uploads, Upload{
			Source:      debugSrc,
			Destination: fmt.Sprintf("%s/%s/debuginfo", buildidNamespace, id),
			Deduplicate: true,
			Compress:    true,
		})
		if debug_entry.Stripped != "" {
			strippedSrc := filepath.Join(outputDir, debug_entry.Stripped)
			uploads = append(uploads, Upload{
				Source:      strippedSrc,
				Destination: fmt.Sprintf("%s/%s/executable", buildidNamespace, id),
				Deduplicate: true,
				Compress:    true,
			})
		} else {
			uploads = append(uploads, Upload{
				Source:      debugSrc,
				Destination: fmt.Sprintf("%s/%s/executable", buildidNamespace, id),
				Deduplicate: true,
				Compress:    true,
			})
		}

		// If we configured the build to output breakpad symbols, then
		// assert that the associated breakpad file here was present, as the
		// associated debug binary is.
		if debug_entry.Breakpad != "" {
			breakpadSrc := filepath.Join(outputDir, debug_entry.Breakpad)
			uploads = append(uploads, Upload{
				Source:      breakpadSrc,
				Destination: fmt.Sprintf("%s/%s.sym", debugNamespace, id),
				Deduplicate: true,
				Compress:    true,
			})
			uploads = append(uploads, Upload{
				Source:      breakpadSrc,
				Destination: fmt.Sprintf("%s/%s/breakpad", buildidNamespace, id),
				Deduplicate: true,
				Compress:    true,
			})
		}
		if debug_entry.GSYM != "" {
			gsymSrc := filepath.Join(outputDir, debug_entry.GSYM)
			uploads = append(uploads, Upload{
				Source:      gsymSrc,
				Destination: fmt.Sprintf("%s/%s.gsym", debugNamespace, id),
				Deduplicate: true,
				Compress:    true,
			})
			uploads = append(uploads, Upload{
				Source:      gsymSrc,
				Destination: fmt.Sprintf("%s/%s/gsym", buildidNamespace, id),
				Deduplicate: true,
				Compress:    true,
			})
		}
	}

	return uploads, nil
}
