# Copyright 2019 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/cpp/library_headers.gni")
import("//zircon/kernel/kernel_rust_mod.gni")

library_headers("headers") {
  headers = [ "dev/hw_watchdog/generic32/init.h" ]
  public_deps = [ "//sdk/lib/zbi-format" ]
}

source_set("ffi") {
  sources = [ "generic32_ffi.cc" ]
  public_deps = [ ":headers" ]
  deps = [
    "//zircon/kernel/lib/arch",
    "//zircon/kernel/lib/boot-options",
    "//zircon/kernel/lib/console",
    "//zircon/kernel/lib/init",
    "//zircon/kernel/vm:headers",
  ]
}

kernel_rust_mod("generic32-rs") {
  output_name = "generic32"
  source_root = "generic32.rs"
  sources = [ "generic32.rs" ]
  deps = [
    "//sdk/rust/zx-status",
    "//src/lib/ksync",
    "//src/lib/regio",
    "//src/lib/zr",
    "//third_party/rust_crates:pin-init",
    "//zircon/kernel/lib/debug",
  ]
  test_deps = [ "//zircon/kernel/lib/unittest:unittest-rs" ]
}

source_set("generic32") {
  public_deps = [ ":headers" ]
  deps = [
    ":ffi",
    ":generic32-rs",
    "//zircon/kernel/dev/pdev/hw_watchdog",
    "//zircon/kernel/lib/boot-options",
  ]
}
