# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bazel/bazel_fuchsia_test_package.gni")

bazel_fuchsia_test_package("pcf8563_test") {
  bazel_target = ":pcf8563-tests"
  test_component_names = [ "pcf8563_test" ]
  test_specs = {
    log_settings = {
      max_severity = "ERROR"
    }
  }
}
