# Copyright 2026 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//zircon/kernel/kernel_rust_mod.gni")

kernel_rust_mod("console_tests_rust") {
  source_root = "mod.rs"
  sources = [ "mod.rs" ]
  deps = [
    "//sdk/rust/zx-status",
    "//src/lib/kalloc",
    "//src/lib/zr",
  ]
  test_deps = [ "//zircon/kernel/lib/unittest:unittest-rs" ]
}

source_set("tests") {
  testonly = true
  sources = [ "console_tests.cc" ]
  deps = [
    ":console_tests_rust",
    "//zircon/kernel/lib/console",
    "//zircon/kernel/lib/unittest",
  ]
}
