import abc

from _typeshed import Incomplete
from mobly.snippet import errors as errors

RPC_RESPONSE_REQUIRED_FIELDS: Incomplete

class ClientBase(abc.ABC, metaclass=abc.ABCMeta):
    package: Incomplete
    log: Incomplete
    verbose_logging: bool
    def __init__(self, package, device) -> None: ...
    def __del__(self) -> None: ...
    def initialize(self) -> None: ...
    @abc.abstractmethod
    def before_starting_server(self): ...
    @abc.abstractmethod
    def start_server(self): ...
    @abc.abstractmethod
    def make_connection(self): ...
    def __getattr__(self, name): ...
    def set_snippet_client_verbose_logging(self, verbose) -> None: ...
    @abc.abstractmethod
    def restore_server_connection(self, port: Incomplete | None = ...): ...
    @abc.abstractmethod
    def check_server_proc_running(self): ...
    @abc.abstractmethod
    def send_rpc_request(self, request): ...
    @abc.abstractmethod
    def handle_callback(self, callback_id, ret_value, rpc_func_name): ...
    @abc.abstractmethod
    def stop(self): ...
    @abc.abstractmethod
    def close_connection(self): ...
