# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

package(default_applicable_licenses = ["//:license"])

# TODO(https://fxbug.dev/454452299): Replace dependencies on this build-only
# target with the following and delete this target:
# * Dependency on a `test_suite()` containing all the test targets in this
#   package once the tests build.
# * Depedency on a "..._rust_next" bindings target or (better) an executable
#   that uses the bindings once they are implemented.

filegroup(
    name = "build_only_tests",
    testonly = True,
    srcs = [
        "//src/lib/fidl/rust_next/fidl_next",
        "//src/lib/fidl/rust_next/fidl_next_bind",
        "//src/lib/fidl/rust_next/fidl_next_codec",
        "//src/lib/fidl/rust_next/fidl_next_protocol",
        "//src/lib/fidl/rust_next/fidl_next_util",
    ],
    visibility = ["//build/bazel/rules/tests:__pkg__"],
)
