indent_str = "\t"

# dtsfmt treats the string consts (such as `DRIVER_HOST_GPU`) as unidentified
# tokens; we need to suppress the error messages here. These unidentified
# tokens will be printed as-is, which is the correct behavior.
warn_on_unhandled_tokens = false
