// Copyright 2026 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package report

import (
	"context"
	"fmt"

	"go.fuchsia.dev/fuchsia/tools/check-licenses/v2/config"
	"go.fuchsia.dev/fuchsia/tools/check-licenses/v2/pipeline"
)

// AllowlistRenderer is a Stage 6 renderer that generates JSON configuration files
// to allowlist restricted license pattern usages.
type AllowlistRenderer struct {
	Config *config.MasterConfig
}

// NewAllowlistRenderer creates a new AllowlistRenderer.
func NewAllowlistRenderer(cfg *config.MasterConfig) *AllowlistRenderer {
	return &AllowlistRenderer{
		Config: cfg,
	}
}

func (r *AllowlistRenderer) Run(ctx context.Context, projects []*pipeline.Project, errors []pipeline.ComplianceError) error {
	for _, e := range errors {
		if e.CheckName == config.CheckNameAllLicensePatternUsagesMustBeApproved {
			fmt.Printf(" [Allowlist] Processing pattern violation: %s (%s)\n", e.LicenseID, e.Project)
			_, _ = r.Config.AddAllowlistEntry(e.Project, e.LicenseID, "TODO: Auto-generated by fx check-licenses fix", "Auto-generated allowlist entry")
		}
	}
	return nil
}
