// Copyright 2026 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package report

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"

	"go.fuchsia.dev/fuchsia/tools/check-licenses/v2/pipeline"
	"go.fuchsia.dev/fuchsia/tools/check-licenses/v2/readme"
)

// Policy check names corresponding to compliance engine rules.
const (
	CheckNameReadmeFuchsiaNeedsUpdate                              = "ReadmeFuchsiaNeedsUpdate"
	PolicyCheckAllFuchsiaAuthorSourceFilesMustHaveCopyrightHeaders = "AllFuchsiaAuthorSourceFilesMustHaveCopyrightHeaders"
	PolicyCheckAllProjectsMustHaveALicense                         = "AllProjectsMustHaveALicense"
	PolicyCheckAllLicenseTextsMustBeRecognized                     = "AllLicenseTextsMustBeRecognized"
	CheckNameAllLicensePatternUsagesMustBeApproved                 = "AllLicensePatternUsagesMustBeApproved"
)

// FixerRenderer is a Stage 6 renderer that mutates disk to automatically resolve
// policy compliance errors emitted by Stage 5.
type FixerRenderer struct {
	FuchsiaDir       string
	OutOfTreeReadmes map[string]string
	IsPrivateProject func(path string) bool
	ManifestNameFor  func(path string) string
	FixedCount       map[string][]string
	NewConfigFiles   []string
	mu               sync.Mutex
}

// NewFixerRenderer creates a new FixerRenderer without depending on v2/config directly.
func NewFixerRenderer(fuchsiaDir string, outOfTreeReadmes map[string]string, isPrivate func(string) bool, manifestName func(string) string) *FixerRenderer {
	return &FixerRenderer{
		FuchsiaDir:       fuchsiaDir,
		OutOfTreeReadmes: outOfTreeReadmes,
		IsPrivateProject: isPrivate,
		ManifestNameFor:  manifestName,
		FixedCount:       make(map[string][]string),
	}
}

func (r *FixerRenderer) Run(ctx context.Context, projects []*pipeline.Project, errors []pipeline.ComplianceError) error {
	for _, e := range errors {
		fmt.Printf(" [Fixer] Processing error: %s (%s)\n", e.CheckName, e.FilePath)
		r.applyFix(e)
	}
	return nil
}

func (r *FixerRenderer) applyFix(e pipeline.ComplianceError) {
	r.mu.Lock()
	defer r.mu.Unlock()

	switch e.CheckName {
	case CheckNameReadmeFuchsiaNeedsUpdate:
		r.FixedCount["README Updates"] = append(r.FixedCount["README Updates"], e.FilePath)

	case PolicyCheckAllFuchsiaAuthorSourceFilesMustHaveCopyrightHeaders:
		if err := r.applyCopyrightFix(e.FilePath); err != nil {
			fmt.Fprintf(os.Stderr, " [Fixer] Failed to apply copyright fix for %s: %v\n", e.FilePath, err)
		} else {
			r.FixedCount["Copyright Headers"] = append(r.FixedCount["Copyright Headers"], e.FilePath)
		}

	case PolicyCheckAllProjectsMustHaveALicense:
		if path, err := r.addPolicyException(e.CheckName, e.Project, "TODO: Auto-generated by fx check-licenses fix", "Auto-generated exception via fix"); err != nil {
			fmt.Fprintf(os.Stderr, " [Fixer] Failed to add policy exception for %s: %v\n", e.Project, err)
		} else {
			r.FixedCount["Policy Exceptions (Missing License)"] = append(r.FixedCount["Policy Exceptions (Missing License)"], e.Project)
			if path != "" {
				r.NewConfigFiles = append(r.NewConfigFiles, path)
			}
		}

	case PolicyCheckAllLicenseTextsMustBeRecognized:
		if path, err := r.addPolicyException(e.CheckName, e.FilePath, "TODO: Auto-generated by fx check-licenses fix", "Auto-generated exception via fix"); err != nil {
			fmt.Fprintf(os.Stderr, " [Fixer] Failed to add policy exception for %s: %v\n", e.FilePath, err)
		} else {
			r.FixedCount["Policy Exceptions (Unrecognized License)"] = append(r.FixedCount["Policy Exceptions (Unrecognized License)"], e.FilePath)
			if path != "" {
				r.NewConfigFiles = append(r.NewConfigFiles, path)
			}
		}

	case CheckNameAllLicensePatternUsagesMustBeApproved:
		if path, err := r.addAllowlistEntry(e.LicenseID, e.Project, "TODO: Auto-generated by fx check-licenses fix", "Auto-generated allowlist entry via fix"); err != nil {
			fmt.Fprintf(os.Stderr, " [Fixer] Failed to add allowlist entry for %s: %v\n", e.Project, err)
		} else {
			r.FixedCount["Allowlist Entries ("+e.LicenseID+")"] = append(r.FixedCount["Allowlist Entries ("+e.LicenseID+")"], e.Project)
			if path != "" {
				r.NewConfigFiles = append(r.NewConfigFiles, path)
			}
		}
	}
}

var copyrightRegex = regexp.MustCompile(`Copyright\s+\(?c\)?\s*\d{4}(?:\s*-\s*\d{4})?\s+The Fuchsia Authors`)

var commentPrefixes = map[string]string{
	".c": "//", ".cc": "//", ".cpp": "//", ".h": "//", ".hh": "//", ".hpp": "//",
	".inc": "//", ".go": "//", ".rs": "//", ".dart": "//", ".java": "//", ".js": "//",
	".ts": "//", ".tsx": "//", ".css": "//", ".proto": "//", ".gn": "#", ".gni": "#",
	".py": "#", ".sh": "#", ".bash": "#", ".zsh": "#", ".pl": "#", ".rb": "#",
	".yaml": "#", ".yml": "#", ".toml": "#", ".mk": "#", ".S": "//", ".asm": "//",
	".bat": "REM", ".cmd": "REM",
}

func (r *FixerRenderer) applyCopyrightFix(filePath string) error {
	absPath := filePath
	if !filepath.IsAbs(filePath) {
		absPath = filepath.Join(r.FuchsiaDir, filePath)
	}

	content, err := os.ReadFile(absPath)
	if err != nil {
		return err
	}

	if copyrightRegex.Match(content) {
		return nil
	}

	ext := strings.ToLower(filepath.Ext(absPath))
	prefix, ok := commentPrefixes[ext]
	if !ok {
		prefix = "//"
	}

	year := time.Now().Year()
	header := fmt.Sprintf("%s Copyright %d The Fuchsia Authors. All rights reserved.\n%s Use of this source code is governed by a BSD-style license that can be\n%s found in the LICENSE file.\n\n", prefix, year, prefix, prefix)

	var newBytes []byte
	lines := strings.Split(string(content), "\n")
	if len(lines) > 0 && strings.HasPrefix(lines[0], "#!") {
		newBytes = append(newBytes, []byte(lines[0]+"\n"+header)...)
		newBytes = append(newBytes, []byte(strings.Join(lines[1:], "\n"))...)
	} else {
		newBytes = append(newBytes, []byte(header)...)
		newBytes = append(newBytes, content...)
	}

	if err := os.WriteFile(absPath, newBytes, 0644); err != nil {
		return fmt.Errorf("failed to write file: %w", err)
	}
	return nil
}

type configFileMinimal struct {
	PolicyExceptions map[string][]allowlistEntryMinimal `json:"policy_exceptions,omitempty"`
	AllowedLicenses  map[string][]allowlistEntryMinimal `json:"allowed_licenses,omitempty"`
}

type allowlistEntryMinimal struct {
	Bug         string   `json:"bug"`
	Description string   `json:"description,omitempty"`
	Paths       []string `json:"paths"`
}

func (r *FixerRenderer) addPolicyException(checkName, targetPath, bug, description string) (string, error) {
	relPath := targetPath
	if filepath.IsAbs(relPath) {
		rel, err := filepath.Rel(r.FuchsiaDir, relPath)
		if err == nil {
			relPath = rel
		}
	}

	isPrivate := false
	if r.IsPrivateProject != nil {
		isPrivate = r.IsPrivateProject(relPath)
	} else if strings.HasPrefix(relPath, "vendor/") {
		isPrivate = true
	}

	configDir := filepath.Join(r.FuchsiaDir, "tools", "check-licenses", "assets", "configs", "policy_exceptions", checkName)
	if isPrivate {
		configDir = filepath.Join(r.FuchsiaDir, "vendor", "google", "tools", "check-licenses", "assets", "configs", "policy_exceptions", checkName)
	}

	if err := os.MkdirAll(configDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create config directory %s: %w", configDir, err)
	}

	baseName := r.findProjectBasename(relPath)
	destFile := filepath.Join(configDir, baseName+".json")

	if err := updateConfigFile(destFile, func(cfg *configFileMinimal) {
		if cfg.PolicyExceptions == nil {
			cfg.PolicyExceptions = make(map[string][]allowlistEntryMinimal)
		}
		entry := allowlistEntryMinimal{
			Bug:         bug,
			Description: description,
			Paths:       []string{relPath},
		}
		cfg.PolicyExceptions[checkName] = append(cfg.PolicyExceptions[checkName], entry)
	}); err != nil {
		return "", err
	}

	return destFile, nil
}

func (r *FixerRenderer) addAllowlistEntry(licenseName, projectPath, bug, description string) (string, error) {
	relPath := projectPath
	if filepath.IsAbs(relPath) {
		rel, err := filepath.Rel(r.FuchsiaDir, relPath)
		if err == nil {
			relPath = rel
		}
	}

	isPrivate := false
	if r.IsPrivateProject != nil {
		isPrivate = r.IsPrivateProject(relPath)
	} else if strings.HasPrefix(relPath, "vendor/") {
		isPrivate = true
	}

	category := "Restricted"
	configDir := filepath.Join(r.FuchsiaDir, "tools", "check-licenses", "assets", "configs", "allowed_licenses", category, licenseName)
	if isPrivate {
		configDir = filepath.Join(r.FuchsiaDir, "vendor", "google", "tools", "check-licenses", "assets", "configs", "allowed_licenses", category, licenseName)
	}

	if err := os.MkdirAll(configDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create config directory %s: %w", configDir, err)
	}

	baseName := r.findProjectBasename(relPath)
	destFile := filepath.Join(configDir, baseName+".json")

	if err := updateConfigFile(destFile, func(cfg *configFileMinimal) {
		if cfg.AllowedLicenses == nil {
			cfg.AllowedLicenses = make(map[string][]allowlistEntryMinimal)
		}
		entry := allowlistEntryMinimal{
			Bug:         bug,
			Description: description,
			Paths:       []string{relPath},
		}
		cfg.AllowedLicenses[licenseName] = append(cfg.AllowedLicenses[licenseName], entry)
	}); err != nil {
		return "", err
	}

	return destFile, nil
}

func updateConfigFile(destFile string, mutate func(*configFileMinimal)) error {
	var cfg configFileMinimal
	if data, err := os.ReadFile(destFile); err == nil {
		json.Unmarshal(data, &cfg)
	}

	mutate(&cfg)

	outData, err := json.MarshalIndent(cfg, "", "    ")
	if err != nil {
		return fmt.Errorf("failed to marshal JSON: %w", err)
	}
	outData = append(outData, '\n')

	if err := os.WriteFile(destFile, outData, 0644); err != nil {
		return fmt.Errorf("failed to write config file %s: %w", destFile, err)
	}
	return nil
}

func (r *FixerRenderer) findProjectBasename(targetPath string) string {
	cleanTargetPath := filepath.Clean(targetPath)
	absTargetPath := filepath.Join(r.FuchsiaDir, cleanTargetPath)

	metadataFiles := []string{"README.fuchsia", "Cargo.toml", "go.mod", "pubspec.yaml"}
	for _, mf := range metadataFiles {
		metaPath := filepath.Join(absTargetPath, mf)
		if _, err := os.Stat(metaPath); err == nil {
			if rootReadmes, subReadmes, err := readme.ParseAnyMetadata(metaPath); err == nil {
				if len(rootReadmes) > 0 && rootReadmes[0].Name != "" {
					return filepath.Base(rootReadmes[0].Name)
				}
				if len(subReadmes) > 0 && subReadmes[0].Name != "" {
					return filepath.Base(subReadmes[0].Name)
				}
			}
		}
	}

	if r.OutOfTreeReadmes != nil {
		if virtualReadmePath, ok := r.OutOfTreeReadmes[cleanTargetPath]; ok {
			absVirtualPath := virtualReadmePath
			if !filepath.IsAbs(absVirtualPath) {
				absVirtualPath = filepath.Join(r.FuchsiaDir, virtualReadmePath)
			}
			if _, err := os.Stat(absVirtualPath); err == nil {
				if rootReadmes, _, err := readme.ParseAnyMetadata(absVirtualPath); err == nil && len(rootReadmes) > 0 && rootReadmes[0].Name != "" {
					return filepath.Base(rootReadmes[0].Name)
				}
			}
		}
	}

	if r.ManifestNameFor != nil {
		if name := r.ManifestNameFor(cleanTargetPath); name != "" {
			return filepath.Base(name)
		}
	}

	dir := filepath.Dir(cleanTargetPath)
	if dir == "." || dir == "/" {
		return "root"
	}

	parts := strings.Split(cleanTargetPath, string(filepath.Separator))
	if len(parts) > 0 && parts[0] != "" {
		if parts[0] == "src" && len(parts) > 1 && parts[1] != "" {
			return parts[1]
		}
		if parts[0] == "vendor" && len(parts) > 2 && parts[2] != "" {
			return parts[2]
		}
		return parts[len(parts)-1]
	}
	return "project"
}

func (r *FixerRenderer) PrintSummary() {
	if len(r.FixedCount) == 0 {
		fmt.Println("\n✨ No issues found. Everything looks good!")
		return
	}

	fmt.Printf("\n✅ Applied fixes for the following categories:\n")

	var categories []string
	for cat := range r.FixedCount {
		categories = append(categories, cat)
	}
	sort.Strings(categories)

	for _, cat := range categories {
		paths := r.FixedCount[cat]
		fmt.Printf("\n[%s]\n", cat)
		sort.Strings(paths)
		for _, p := range paths {
			rel, _ := filepath.Rel(r.FuchsiaDir, p)
			if rel == "" {
				rel = p
			}
			fmt.Printf("  - %s\n", rel)
		}
	}

	if len(r.NewConfigFiles) > 0 {
		fmt.Printf("\n⚠️  ACTION REQUIRED:\n")
		fmt.Printf("You must file an OSRB bug for any newly added policy exceptions or allowlist entries.\n")
		fmt.Printf("Please update the 'bug' field in these files:\n")
		sort.Strings(r.NewConfigFiles)
		for _, path := range r.NewConfigFiles {
			rel, _ := filepath.Rel(r.FuchsiaDir, path)
			if rel == "" {
				rel = path
			}
			fmt.Printf("  - %s\n", rel)
		}
	}
}
