from _typeshed import Incomplete
from mobly import signals as signals

def assert_equal(
    first, second, msg: Incomplete | None = ..., extras: Incomplete | None = ...
) -> None: ...
def assert_not_equal(
    first, second, msg: Incomplete | None = ..., extras: Incomplete | None = ...
) -> None: ...
def assert_almost_equal(
    first,
    second,
    places: Incomplete | None = ...,
    msg: Incomplete | None = ...,
    delta: Incomplete | None = ...,
    extras: Incomplete | None = ...,
) -> None: ...
def assert_not_almost_equal(
    first,
    second,
    places: Incomplete | None = ...,
    msg: Incomplete | None = ...,
    delta: Incomplete | None = ...,
    extras: Incomplete | None = ...,
) -> None: ...
def assert_in(
    member,
    container,
    msg: Incomplete | None = ...,
    extras: Incomplete | None = ...,
) -> None: ...
def assert_not_in(
    member,
    container,
    msg: Incomplete | None = ...,
    extras: Incomplete | None = ...,
) -> None: ...
def assert_is(
    expr1, expr2, msg: Incomplete | None = ..., extras: Incomplete | None = ...
) -> None: ...
def assert_is_not(
    expr1, expr2, msg: Incomplete | None = ..., extras: Incomplete | None = ...
) -> None: ...
def assert_count_equal(
    first, second, msg: Incomplete | None = ..., extras: Incomplete | None = ...
) -> None: ...
def assert_less(
    a, b, msg: Incomplete | None = ..., extras: Incomplete | None = ...
) -> None: ...
def assert_less_equal(
    a, b, msg: Incomplete | None = ..., extras: Incomplete | None = ...
) -> None: ...
def assert_greater(
    a, b, msg: Incomplete | None = ..., extras: Incomplete | None = ...
) -> None: ...
def assert_greater_equal(
    a, b, msg: Incomplete | None = ..., extras: Incomplete | None = ...
) -> None: ...
def assert_is_none(
    obj, msg: Incomplete | None = ..., extras: Incomplete | None = ...
) -> None: ...
def assert_is_not_none(
    obj, msg: Incomplete | None = ..., extras: Incomplete | None = ...
) -> None: ...
def assert_is_instance(
    obj, cls, msg: Incomplete | None = ..., extras: Incomplete | None = ...
) -> None: ...
def assert_not_is_instance(
    obj, cls, msg: Incomplete | None = ..., extras: Incomplete | None = ...
) -> None: ...
def assert_regex(
    text,
    expected_regex,
    msg: Incomplete | None = ...,
    extras: Incomplete | None = ...,
) -> None: ...
def assert_not_regex(
    text,
    unexpected_regex,
    msg: Incomplete | None = ...,
    extras: Incomplete | None = ...,
) -> None: ...
def assert_raises(
    expected_exception, extras: Incomplete | None = ..., *args, **kwargs
): ...
def assert_raises_regex(
    expected_exception,
    expected_regex,
    extras: Incomplete | None = ...,
    *args,
    **kwargs,
): ...
def assert_true(expr, msg, extras: Incomplete | None = ...) -> None: ...
def assert_false(expr, msg, extras: Incomplete | None = ...) -> None: ...
def skip(reason, extras: Incomplete | None = ...) -> None: ...
def skip_if(expr, reason, extras: Incomplete | None = ...) -> None: ...
def abort_class(reason, extras: Incomplete | None = ...) -> None: ...
def abort_class_if(expr, reason, extras: Incomplete | None = ...) -> None: ...
def abort_all(reason, extras: Incomplete | None = ...) -> None: ...
def abort_all_if(expr, reason, extras: Incomplete | None = ...) -> None: ...
def fail(msg, extras: Incomplete | None = ...) -> None: ...
def explicit_pass(msg, extras: Incomplete | None = ...) -> None: ...

class _AssertRaisesContext:
    expected: Incomplete
    failureException: Incomplete
    expected_regexp: Incomplete
    extras: Incomplete
    def __init__(
        self,
        expected,
        expected_regexp: Incomplete | None = ...,
        extras: Incomplete | None = ...,
    ) -> None: ...
    def __enter__(self): ...
    exception: Incomplete
    def __exit__(self, exc_type, exc_value, tb): ...
