from _typeshed import Incomplete
from mobly import controller_manager as controller_manager
from mobly import expects as expects
from mobly import records as records
from mobly import runtime_test_info as runtime_test_info
from mobly import signals as signals
from mobly import utils as utils

TEST_CASE_TOKEN: str
RESULT_LINE_TEMPLATE: Incomplete
TEST_STAGE_BEGIN_LOG_TEMPLATE: str
TEST_STAGE_END_LOG_TEMPLATE: str
STAGE_NAME_PRE_RUN: str
STAGE_NAME_SETUP_GENERATED_TESTS: str
STAGE_NAME_SETUP_CLASS: str
STAGE_NAME_SETUP_TEST: str
STAGE_NAME_TEARDOWN_TEST: str
STAGE_NAME_TEARDOWN_CLASS: str
STAGE_NAME_CLEAN_UP: str
ATTR_REPEAT_CNT: str
ATTR_MAX_RETRY_CNT: str
ATTR_MAX_CONSEC_ERROR: str

class Error(Exception): ...

def repeat(count, max_consecutive_error: Incomplete | None = ...): ...
def retry(max_count): ...

class BaseTestClass:
    TAG: Incomplete
    tests: Incomplete
    root_output_path: Incomplete
    log_path: Incomplete
    test_bed_name: Incomplete
    testbed_name: Incomplete
    user_params: Incomplete
    results: Incomplete
    summary_writer: Incomplete
    controller_configs: Incomplete
    def __init__(self, configs) -> None: ...
    def unpack_userparams(
        self,
        req_param_names: Incomplete | None = ...,
        opt_param_names: Incomplete | None = ...,
        **kwargs,
    ) -> None: ...
    def register_controller(
        self, module, required: bool = ..., min_number: int = ...
    ): ...
    def pre_run(self) -> None: ...
    def setup_generated_tests(self) -> None: ...
    def setup_class(self) -> None: ...
    def teardown_class(self) -> None: ...
    def setup_test(self) -> None: ...
    def teardown_test(self) -> None: ...
    def on_fail(self, record) -> None: ...
    def on_pass(self, record) -> None: ...
    def on_skip(self, record) -> None: ...
    def record_data(self, content) -> None: ...
    current_test_info: Incomplete
    def exec_one_test(
        self, test_name, test_method, record: Incomplete | None = ...
    ): ...
    def generate_tests(
        self, test_logic, name_func, arg_sets, uid_func: Incomplete | None = ...
    ) -> None: ...
    def get_existing_test_names(self): ...
    def run(self, test_names: Incomplete | None = ...): ...
