# Copyright 2023 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/components.gni")
import("//build/dist/resource.gni")
import("//build/rust/rustc_binary.gni")
import("//build/testing/perf/test.gni")
import("//src/starnix/kernel/starnix.gni")

storage_benchmarks_target = "//src/storage/benchmarks/host:host-storage-benchmarks($target_linux_toolchain)"

resource("storage-starnix-benchmarks-bin") {
  out_dir = get_label_info(storage_benchmarks_target, "root_out_dir")
  testonly = true
  deps = [ storage_benchmarks_target ]
  sources = [ "${out_dir}/storage-benchmarks" ]
  outputs = [ "data/tests/storage-starnix-benchmarks" ]
}

rustc_binary("storage_starnix_benchmarks_runner") {
  edition = "2024"
  testonly = true
  sources = [ "src/main.rs" ]
  deps = [
    "//sdk/fidl/fuchsia.component:fuchsia.component_rust",
    "//sdk/fidl/fuchsia.power.cpu.manager:fuchsia.power.cpu.manager_rust",
    "//src/lib/fidl/rust/fidl",
    "//src/lib/fuchsia",
    "//src/lib/fuchsia-component",
    "//src/lib/trace/rust:trace",
    "//src/lib/trace/rust:trace-provider",
    "//third_party/rust_crates:anyhow",
    "//third_party/rust_crates:log",
  ]
}

fuchsia_component("storage_starnix_data_benchmark_app") {
  testonly = true
  manifest = "meta/storage_starnix_data_benchmark_app.cml"
  deps = [ ":storage-starnix-benchmarks-bin" ]
}

fuchsia_component("storage_starnix_tmp_benchmark_app") {
  testonly = true
  manifest = "meta/storage_starnix_tmp_benchmark_app.cml"
  deps = [ ":storage-starnix-benchmarks-bin" ]
}

fuchsia_test_component("storage-starnix-data-benchmarks") {
  component_name = "storage-starnix-data-benchmarks"
  manifest = "meta/storage-starnix-data-benchmarks.cml"
  deps = [ ":storage_starnix_benchmarks_runner" ]
  test_type = "storage"
}

fuchsia_test_component("storage-starnix-tmp-benchmarks") {
  component_name = "storage-starnix-tmp-benchmarks"
  manifest = "meta/storage-starnix-tmp-benchmarks.cml"
  deps = [ ":storage_starnix_benchmarks_runner" ]
  test_type = "storage"
}

fuchsia_test_package("storage-starnix-benchmarks") {
  test_components = [
    ":storage-starnix-data-benchmarks",
    ":storage-starnix-tmp-benchmarks",
  ]
  deps = [
    ":storage_starnix_data_benchmark_app",
    ":storage_starnix_tmp_benchmark_app",
    "//src/starnix/containers/debian:container_resources",
  ]
  subpackages = [
    "//src/starnix/kernel:starnix_kernel_package",
    "//src/starnix/containers/debian:debian_package",
  ]
  test_specs = {
    environments = []

    package_resolution_timeout_secs = 660
  }
}

fuchsia_component_perf_test("storage_starnix_data_benchmarks") {
  package = ":storage-starnix-benchmarks"
  component_name = "storage-starnix-data-benchmarks"
  expected_metric_names_filepath = "//src/tests/end_to_end/perf/expected_metric_names/fuchsia.storage.starnix_data.txt"
  use_component_builtin_args = true
  test_type = "storage"
}

fuchsia_component_perf_test("storage_starnix_tmp_benchmarks") {
  package = ":storage-starnix-benchmarks"
  component_name = "storage-starnix-tmp-benchmarks"
  expected_metric_names_filepath = "//src/tests/end_to_end/perf/expected_metric_names/fuchsia.storage.starnix_tmp.txt"
  use_component_builtin_args = true
  test_type = "storage"
}

group("benchmark-packages") {
  testonly = true
  deps = [ ":storage-starnix-benchmarks" ]
}

group("benchmarks") {
  testonly = true
  deps = []
  if (!is_asan && host_os == "linux") {
    deps += [
      ":storage_starnix_data_benchmarks",
      ":storage_starnix_tmp_benchmarks",
    ]
  }
}
