// Copyright 2025 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

use std::collections::HashSet;
use std::io::{BufWriter, Write};
use std::path::Path;
use std::{env, fs};
use syn;

struct KgslStruct {
    name: String,
    fields: Vec<String>,
    arch_independent: bool,
}

fn parse(input: &Path) -> anyhow::Result<Vec<KgslStruct>> {
    let contents = fs::read_to_string(&input)?;
    let ast = syn::parse_file(&contents)?;
    let mut structs = Vec::new();
    let arch_dependent_typenames = HashSet::from(["uaddr", "c_ulong", "__kernel_size_t"]);
    for item in ast.items {
        let syn::Item::Struct(uapi_struct) = item else { continue };
        let name = uapi_struct.ident.to_string();
        if !name.starts_with("kgsl_") {
            continue;
        }
        let fields: Vec<String> = uapi_struct
            .fields
            .iter()
            .map(|field| field.ident.as_ref().expect("struct field has name").to_string())
            .filter(|name| !name.starts_with("__bindgen") && !name.starts_with("__pad"))
            .collect();
        let mut has_arch_dependent_fields = false;
        let mut has_uref_fields = false;
        for field in uapi_struct.fields {
            let syn::Type::Path(ty) = &field.ty else { continue };
            let typename = ty.path.segments.last().expect("path is non-empty").ident.to_string();
            if arch_dependent_typenames.contains(typename.as_str()) || typename.starts_with("kgsl_")
            {
                has_arch_dependent_fields = true;
            }
            if typename == "uref" {
                has_uref_fields = true;
            }
        }
        if !has_uref_fields {
            // Structs with uref fields are unsupported.
            structs.push(KgslStruct { name, fields, arch_independent: !has_arch_dependent_fields });
        }
    }

    Ok(structs)
}

fn generate(output: &Path, structs: Vec<KgslStruct>) -> anyhow::Result<()> {
    let file = fs::File::create(output)?;
    let mut writer = BufWriter::new(file);
    writeln!(
        writer,
        "\
// Copyright 2025 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// WARNING - This file is generated by //src/starnix/modules/kgsl/uapi_manual
// Do not modify this file manually. Instead, update the script and rebuild."
    )?;
    for s in structs {
        if s.arch_independent {
            writeln!(
                writer,
                "
#[rustfmt::skip]
impl From<crate::{0}> for crate::arch32::{0} {{
    fn from(f: crate::{0}) -> Self {{
        zerocopy::transmute!(f)
    }}
}}

#[rustfmt::skip]
impl From<crate::arch32::{0}> for crate::{0} {{
    fn from(f: crate::arch32::{0}) -> Self {{
        zerocopy::transmute!(f)
    }}
}}",
                s.name
            )?;
        } else {
            writeln!(
                writer,
                "
#[rustfmt::skip]
crate::arch_translate_data! {{
    BidiFrom<{}> {{",
                s.name
            )?;
            for field in &s.fields {
                writeln!(writer, "        {},", field)?;
            }
            writeln!(writer, "    }}\n}}")?;
        }
    }
    Ok(())
}

fn main() -> anyhow::Result<()> {
    let args: Vec<String> = env::args().collect();
    if args.len() != 3 {
        anyhow::bail!(
            "Usage: {} INPUT OUTPUT",
            env::current_exe()
                .expect("exe path set")
                .file_name()
                .expect("exe has filename")
                .to_string_lossy()
        );
    }
    let structs = parse(Path::new(&args[1]))?;
    generate(Path::new(&args[2]), structs)?;
    Ok(())
}
