// Copyright 2025 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

use std::collections::{HashMap, HashSet};
use std::io::{BufWriter, Write};
use std::path::Path;
use std::{env, fs};
use syn;

struct KgslField {
    name: String,
    typename: String,
    inner_typename: Option<String>,
}

struct KgslStruct {
    name: String,
    fields: Vec<KgslField>,
    arch_independent: bool,
    has_uref_fields: bool,
    has_arch_dependent_urefs: bool,
}

fn parse(input: &Path) -> anyhow::Result<Vec<KgslStruct>> {
    let contents = fs::read_to_string(&input)?;
    let ast = syn::parse_file(&contents)?;
    let mut structs = Vec::new();
    let arch_dependent_typenames = HashSet::from(["uaddr", "c_ulong", "__kernel_size_t", "uref"]);
    for item in ast.items {
        let syn::Item::Struct(uapi_struct) = item else { continue };
        let name = uapi_struct.ident.to_string();
        if !name.starts_with("kgsl_") {
            continue;
        }
        let mut fields = Vec::new();
        let mut has_arch_dependent_fields = false;
        let mut has_uref_fields = false;
        for field in uapi_struct.fields {
            let name = field.ident.as_ref().expect("struct field has name").to_string();
            if name.starts_with("__bindgen") || name.starts_with("__pad") {
                continue;
            }
            let syn::Type::Path(ty) = &field.ty else { continue };
            let seg = ty.path.segments.last().expect("path is non-empty");
            let typename = seg.ident.to_string();

            let inner_typename = if let syn::PathArguments::AngleBracketed(args) = &seg.arguments
                && let Some(syn::GenericArgument::Type(syn::Type::Path(inner_ty))) =
                    args.args.first()
            {
                Some(inner_ty.path.segments.last().unwrap().ident.to_string())
            } else {
                None
            };

            if arch_dependent_typenames.contains(typename.as_str()) || typename.starts_with("kgsl_")
            {
                has_arch_dependent_fields = true;
            }
            if typename == "uref" {
                has_uref_fields = true;
            }
            fields.push(KgslField { name, typename, inner_typename });
        }
        structs.push(KgslStruct {
            name,
            fields,
            arch_independent: !has_arch_dependent_fields,
            has_uref_fields,
            has_arch_dependent_urefs: false,
        });
    }

    // Validate inner types of urefs
    let struct_map: HashMap<String, &KgslStruct> =
        structs.iter().map(|s| (s.name.clone(), s)).collect();
    let mut manual_conversion_structs = HashSet::new();

    for s in &structs {
        for f in &s.fields {
            if f.typename == "uref" {
                if let Some(inner) = &f.inner_typename {
                    if arch_dependent_typenames.contains(inner.as_str()) {
                        // e.g. uref<uaddr>
                        manual_conversion_structs.insert(s.name.clone());
                    }
                    if let Some(target_struct) = struct_map.get(inner) {
                        if !target_struct.arch_independent {
                            // e.g. uref<kgsl_ibdesc>
                            manual_conversion_structs.insert(s.name.clone());
                        }
                    }
                }
            }
        }
    }

    // Update flags
    for s in &mut structs {
        if manual_conversion_structs.contains(&s.name) {
            s.has_arch_dependent_urefs = true;
        }
    }

    Ok(structs)
}

fn generate(output: &Path, structs: Vec<KgslStruct>) -> anyhow::Result<()> {
    let file = fs::File::create(output)?;
    let mut writer = BufWriter::new(file);
    writeln!(
        writer,
        "\
// Copyright 2025 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// WARNING - This file is generated by //src/starnix/modules/kgsl/uapi_manual
// Do not modify this file manually. Instead, update the script and rebuild."
    )?;
    for s in structs {
        if s.has_arch_dependent_urefs {
            writeln!(
                writer,
                "\n// {} contains user references to arch-dependent types and must be translated manually.",
                s.name
            )?;
            continue;
        }
        if s.arch_independent {
            writeln!(
                writer,
                "
#[rustfmt::skip]
impl From<crate::{0}> for crate::arch32::{0} {{
    fn from(f: crate::{0}) -> Self {{
        zerocopy::transmute!(f)
    }}
}}

#[rustfmt::skip]
impl From<crate::arch32::{0}> for crate::{0} {{
    fn from(f: crate::arch32::{0}) -> Self {{
        zerocopy::transmute!(f)
    }}
}}",
                s.name
            )?;
        } else if s.has_uref_fields {
            writeln!(
                writer,
                "
#[rustfmt::skip]
impl TryFrom<crate::{0}> for crate::arch32::{0} {{
    type Error = ();
    fn try_from(f: crate::{0}) -> Result<Self, ()> {{
        Ok(Self {{",
                s.name
            )?;
            for field in &s.fields {
                if field.typename == "uref" {
                    writeln!(
                        writer,
                        "            {0}: crate::uaddr32::try_from(f.{0}.addr).map_err(|_| ())?.into(),",
                        field.name
                    )?;
                } else {
                    writeln!(writer, "            {}: f.{}.into(),", field.name, field.name)?;
                }
            }
            writeln!(writer, "            ..Default::default()\n        }})\n    }}\n}}")?;

            writeln!(
                writer,
                "
#[rustfmt::skip]
impl From<crate::arch32::{0}> for crate::{0} {{
    fn from(f: crate::arch32::{0}) -> Self {{
        Self {{",
                s.name
            )?;
            for field in &s.fields {
                if field.typename == "uref" {
                    writeln!(writer, "            {0}: f.{0}.addr.into(),", field.name)?;
                } else {
                    writeln!(writer, "            {}: f.{}.into(),", field.name, field.name)?;
                }
            }
            writeln!(writer, "            ..Default::default()\n        }}\n    }}\n}}")?;
        } else {
            writeln!(
                writer,
                "
#[rustfmt::skip]
crate::arch_translate_data! {{
    BidiFrom<{0}> {{",
                s.name
            )?;
            for field in &s.fields {
                writeln!(writer, "        {},", field.name)?;
            }
            writeln!(writer, "    }}\n}}")?;
        }
    }

    Ok(())
}

fn main() -> anyhow::Result<()> {
    let args: Vec<String> = env::args().collect();
    if args.len() != 3 {
        anyhow::bail!(
            "Usage: {} INPUT OUTPUT",
            env::current_exe()
                .expect("exe path set")
                .file_name()
                .expect("exe has filename")
                .to_string_lossy()
        );
    }
    let structs = parse(Path::new(&args[1]))?;
    generate(Path::new(&args[2]), structs)?;
    Ok(())
}
