// Copyright 2016 The Fuchsia Authors. All rights reserved.
//
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include <inttypes.h>
#include <lib/maybe-standalone-test/maybe-standalone.h>
#include <lib/zx/time.h>
#include <lib/zx/vmar.h>
#include <lib/zx/vmo.h>
#include <zircon/syscalls.h>

#include <zxtest/zxtest.h>

namespace {

// Calculation of elapsed time using ticks.
TEST(TicksTest, ElapsedTimeUsingTicks) {
  zx::ticks ticks_per_second = zx::ticks::per_second();
  ASSERT_GT(ticks_per_second, zx::ticks(0), "Invalid ticks per second");

  zx::ticks start = zx::ticks::now();
  zx::ticks end = zx::ticks::now();
  ASSERT_GE(end, start, "Ticks went backwards");

  double seconds =
      static_cast<double>((end - start).get()) / static_cast<double>(ticks_per_second.get());
  ASSERT_GE(seconds, 0, "Time went backwards");
}

// This is a regression test generated by Gemini.  See https://fxbug.dev/515184484
TEST(TicksTest, TimeValuesPaddingLeak) {
  zx::unowned_vmo time_values_vmo = maybe_standalone::GetVmo("time_values");
  if (!time_values_vmo->is_valid()) {
    // Skip the test if the VMO is not exposed on this platform or configuration.
    ZXTEST_SKIP("time_values VMO not available on this platform");
  }

  uint64_t size = 0;
  ASSERT_OK(time_values_vmo->get_size(&size));

  uintptr_t addr;
  ASSERT_OK(zx::vmar::root_self()->map(ZX_VM_PERM_READ, 0, *time_values_vmo, 0, size, &addr));

  const uint8_t* ptr = reinterpret_cast<const uint8_t*>(addr);

  // TimeValues structure resides at the start of the time_values VMO. Based on
  // its ABI definition
  // (zircon/kernel/lib/fasttime/include/lib/fasttime/internal/abi.h), the
  // fields occupy 43 bytes, and the structure is padded to a size of 48 bytes.
  //
  // Offsets 43 to 47 inclusive represent compiler-inserted padding. These 5
  // bytes must be explicitly initialized to 0 by the kernel to prevent stack
  // information leak.
  for (size_t i = 43; i < 48; ++i) {
    EXPECT_EQ(0u, ptr[i], "Padding byte at offset %zu contains garbage!", i);
  }

  ASSERT_OK(zx::vmar::root_self()->unmap(addr, size));
}

}  // namespace
