# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/host.gni")
import("//build/python/python_binary.gni")
import("//build/python/python_host_test.gni")

perf_analyze_sources = [
  "binder.py",
  "cpu.py",
  "plugins.py",
  "query.py",
  "result_formatter.py",
]

python_binary("perf_analyze_bin") {
  main_source = "perf_analyze.py"
  sources = perf_analyze_sources
  deps = [ "//src/performance/lib/tp_shell" ]
  output_name = "perf-analyze.pyz"
}

# Rename the resulting .pyz for the host tool
copy("copy_perf_analyze") {
  deps = [ ":perf_analyze_bin" ]
  sources = [ "${target_out_dir}/perf-analyze.pyz" ]
  outputs = [ "${root_out_dir}/perf-analyze" ]
}

install_host_tools("perf-analyze") {
  deps = [ ":copy_perf_analyze" ]
  outputs = [ "perf-analyze" ]
}

if (is_host) {
  python_host_test("perf_analyze_test") {
    main_source = "perf_analyze_test.py"
    sources = [ "perf_analyze.py" ] + perf_analyze_sources
    deps = [ "//src/performance/lib/tp_shell" ]
    data_sources = [
      "test-data/sample_fxt.fxt",
      "test-data/sample_queries.json",
    ]
    data_package_name = "test_data"
  }

  python_host_test("result_formatter_test") {
    main_source = "result_formatter_test.py"
    sources = [
      "plugins.py",
      "result_formatter.py",
    ]
  }

  python_host_test("binder_test") {
    main_source = "binder_test.py"
    sources = [
      "binder.py",
      "plugins.py",
      "result_formatter.py",
    ]
    deps = [ "//src/performance/lib/tp_shell" ]
  }

  python_host_test("cpu_test") {
    main_source = "cpu_test.py"
    sources = [
      "cpu.py",
      "plugins.py",
    ]
    deps = [ "//src/performance/lib/tp_shell" ]
  }

  python_host_test("plugins_test") {
    main_source = "plugins_test.py"
    sources = [ "plugins.py" ]
  }
} else {
  group("binder_test") {
    testonly = true
    public_deps = [ ":binder_test($host_toolchain)" ]
  }
  group("cpu_test") {
    testonly = true
    public_deps = [ ":cpu_test($host_toolchain)" ]
  }
  group("perf_analyze_test") {
    testonly = true
    public_deps = [ ":perf_analyze_test($host_toolchain)" ]
  }
  group("plugins_test") {
    testonly = true
    public_deps = [ ":plugins_test($host_toolchain)" ]
  }
  group("result_formatter_test") {
    testonly = true
    public_deps = [ ":result_formatter_test($host_toolchain)" ]
  }
}

group("tests") {
  testonly = true
  deps = [
    ":binder_test",
    ":cpu_test",
    ":perf_analyze_test",
    ":plugins_test",
    ":result_formatter_test",
  ]
}
