# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/test.gni")
import("//build/testing/bootfs_test.gni")

test("devcoordinator-namespace") {
  output_name = "devcoordinator-namespace-test"
  sources = [ "namespace_test.cc" ]
  deps = [
    "//zircon/system/ulib/fbl",
    "//zircon/system/ulib/zxtest",
  ]
}

bootfs_test("devcoordinator-namespace-bootfs-test") {
  name = "devcoordinator-namespace-test"
  deps = [ ":devcoordinator-namespace" ]
}
