# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bind/bind.gni")
import("//build/drivers.gni")

fuchsia_driver_dml("fake-board-dml") {
  dml = "meta/fake-board.dml"
  driver_name = "fake-board"
}

driver_bind_rules("fake-board-bind") {
  bind_output = "fake-board.bindbc"
  dml_label = ":fake-board-dml"
  deps = [
    "//src/devices/bind/fuchsia",
    "//src/devices/bind/fuchsia.test.platform",
  ]
}

fuchsia_cc_driver("fake-board-driver") {
  output_name = "fake-board"
  sources = [
    "fake-board.cc",
    "fake-board.h",
  ]
  deps = [
    ":fake-board-bind",
    "//sdk/fidl/fuchsia.hardware.platform.bus:fuchsia.hardware.platform.bus_cpp",
    "//sdk/lib/driver/component/cpp",
    "//sdk/lib/driver/devicetree/manager",
    "//sdk/lib/driver/devicetree/visitors:load-visitors",
    "//sdk/lib/driver/logging/cpp",
    "//src/devices/lib/driver:driver_runtime",
  ]
}

fuchsia_driver_component("fake-board-component") {
  component_name = "fake-board"
  dml_label = ":fake-board-dml"
  deps = [ ":fake-board-driver" ]
  info = "meta/fake-board-info.json"
}
