# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//src/testing/trf_codegen/trf_test.gni")

if (is_fuchsia) {
  trf_test("reverser_trf_test") {
    is_ctf = true
    source = "src/reverser_trf_test.rs"
    mocks = [ "src/mocks.rs" ]
    cut = [ "//examples/components/reverser" ]
    deps = [
      "//examples/components/reverser/fidl:fuchsia.examples.reverser_rust",
      "//third_party/rust_crates:anyhow",
    ]
  }
}
