# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(is_fuchsia, "These targets are only compiled in the fuchsia toolchain.")

import("//build/components.gni")
import("//build/rust/rustc_test.gni")

rustc_test("bin") {
  name = "reverser_integration_test_rust"
  edition = "2024"

  deps = [
    "//examples/components/reverser/fidl:fuchsia.examples.reverser_rust",
    "//src/lib/fuchsia",
    "//src/lib/fuchsia-component-test",
    "//third_party/rust_crates:anyhow",
  ]

  sources = [ "src/lib.rs" ]
}

fuchsia_test_component("reverser_integration_test_component") {
  component_name = "reverser_integration_test"
  manifest = "meta/reverser_integration_test.cml"
  deps = [ ":bin" ]
}

fuchsia_test_package("reverser_integration_test") {
  test_components = [ ":reverser_integration_test_component" ]
  deps = [ "//examples/components/reverser:reverser_component" ]
}
