// Copyright 2025 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "load-tests.h"

namespace ld::testing {

template <class Fixture>
using LdLoadLibcTests = Fixture;

// The libc-using tests don't run in-process; so TestTypes<>, not LoadTypes.
TYPED_TEST_SUITE(LdLoadLibcTests, TestTypes<>);

namespace {

constexpr std::string_view kLibcSoname = "libnew-libc.so";

// This is just running an empty main() function using the vanilla system libc.
// It's really just testing that the test harness itself launches a PT_INTERP
// executable consistent with what the real system program loader does, for
// both the ELF loading and the process bootstrap protocol.
TYPED_TEST(LdLoadLibcTests, LibcNoopTest) {
  if constexpr (!TestFixture::kRunsLdStartup) {
    GTEST_SKIP() << "legacy libc not compatible with remote dynamic linking";
  }

  ASSERT_NO_FATAL_FAILURE(this->Init());

  // The shadow-based sanitizer builds of the system libc rely on the legacy
  // program loader behavior of reserving the low half of the address space to
  // ensure the PT_INTERP and vDSO can't land there.
  ASSERT_NO_FATAL_FAILURE(this->LegacyAddressSpaceReservation());

  // This file is generated by the build with the right list of DT_NEEDED
  // for the system libc.  The legacy libc is folded into the dynamic linker,
  // and the vDSO doesn't need to be requested; so the list is empty
  // except for sanitizer builds of the test case.
  this->Needed(std::initializer_list<std::string_view>{
#include "libc-noop-test-needed.inc"
  });

  ASSERT_NO_FATAL_FAILURE(this->Load("libc-noop-test"));

  EXPECT_EQ(this->Run(), 0);

  this->ExpectLog("");
}

TYPED_TEST(LdLoadLibcTests, LibcStartMain) {
  ASSERT_NO_FATAL_FAILURE(this->Init());

  ASSERT_NO_FATAL_FAILURE(this->Needed({kLibcSoname}));
  ASSERT_NO_FATAL_FAILURE(this->Load("libc-start-main"));

  EXPECT_EQ(this->Run(), 0);

  this->ExpectLog("");
}

}  // namespace
}  // namespace ld::testing
