# Copyright 2019 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/config/current_target_tuple.gni")
import("//build/config/sysroot.gni")
import("//build/cpp/library_headers.gni")
import("//build/rust/rustc_library.gni")
import("//zircon/kernel/kernel_bindgen_crate.gni")
import("//zircon/kernel/params.gni")

source_set("counters") {
  visibility = [
    "//src/zircon/bin/kcounter:*",
    "//src/zircon/tests/kcounter:*",
    "//zircon/kernel/*",
    "//zircon/system/ulib/kcounter/*",
  ]

  public_deps = [ ":headers" ]

  if (is_kernel) {
    sources = [ "counters.cc" ]
    deps = [
      "//zircon/kernel/lib/init",
      "//zircon/kernel/lib/special-sections",
    ]
  }
}

rustc_library("counters-rs") {
  edition = "2024"
  sources = [ "src/lib.rs" ]
  deps = [
    ":counters",
    ":counters-bindings",
    "//src/lib/zr",
  ]
  rustenv = [ "SMP_MAX_CPUS=${smp_max_cpus}" ]

  # TODO(https://fxbug.dev/548748442): remove when all fixed in the code
  if (is_kernel) {
    configs += [ "//zircon/kernel/switch:allow-unnecessary-cast" ]
  }
}

library_headers("headers") {
  headers = [
    "lib/counters.h",
    "lib/counter-vmo-abi.h",
  ]

  public_deps = [
    # <lib/counters.h> has #include <lib/special-sections/special-sections.h>.
    "//zircon/kernel/lib/special-sections:headers",
  ]

  if (is_kernel) {
    public_deps += [ "//zircon/kernel/lib/libc:headers" ]
  }
}

group("tests") {
  testonly = true
  deps = [
    ":counters-bindings",
    ":counters-rs",
  ]
}

group("kernel-tests") {
  testonly = true
}

group("phys-tests") {
  testonly = true
}

group("boot_tests") {
  testonly = true
}

kernel_bindgen_crate("counters-bindings") {
  headers = [ "bindgen.h" ]
  cpp = true

  non_rust_deps = [ ":headers" ]

  type_allowlist = [ "counters::.*" ]

  notice_year = 2026

  raw_lines = [ "#![no_std]" ]

  expect_lints = [
    "clippy::missing_safety_doc",
    "non_camel_case_types",
    "non_upper_case_globals",
  ]
}
