# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/host.gni")
import("//build/python/python_host_test.gni")
import("//build/python/python_library.gni")

group("tests") {
  testonly = true
  public_deps = [ ":mobly_logger_extension_test($host_toolchain)" ]
}

if (is_host) {
  python_library("mobly_logger_extension") {
    sources = [ "__init__.py" ]
    library_deps = [
      "//scripts/lib/logging_utils",
      "//third_party/mobly:mobly_no_testonly",
    ]
  }

  python_host_test("mobly_logger_extension_test") {
    main_source = "tests/mobly_logger_extension_test.py"
    sources = [ "tests/mobly_logger_extension_test.py" ]
    libraries = [
      ":mobly_logger_extension",
      "//scripts/lib/logging_utils",
      "//third_party/mobly",
    ]
  }
}
