# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")
load("//build/bazel/rules/host:defs.bzl", "go_binary_host_tool")
load("//build/bazel/rules/host_tests:host_go_test.bzl", "host_go_test")
load("//build/bazel/rules/host_tests:host_test_data.bzl", "host_test_data_files")

package(default_applicable_licenses = ["//:license"])

go_library(
    name = "gopkg",
    srcs = [
        "main.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/sdk/ctf/plasa/plasa_test_coverage_report",
    target_compatible_with = HOST_CONSTRAINTS,
    deps = [
        "//sdk/ctf/plasa/model:gopkg",
        "//third_party/golibs:github.com/google/go-cmp/cmp",
        "//third_party/golibs:gopkg.in/yaml.v2",
        "//tools/fidl/lib/summarize:gopkg",
    ],
)

go_binary_host_tool(
    name = "plasa_test_coverage_report",
    embed = [":gopkg"],
    target_compatible_with = HOST_CONSTRAINTS,
)

host_test_data_files(
    name = "plasa_test_coverage_report_testdata",
    srcs = [
        "testdata/fragment-fidl.plasa.json",
        "testdata/fragment-vdso.plasa.json",
        "testdata/fragment1.plasa.json",
        "testdata/fragment2.plasa.json",
        "testdata/plasa.manifest.json",
    ],
    dest_dir = "testdata",
)

host_go_test(
    name = "plasa_test_coverage_report_test",
    srcs = ["main_test.go"],
    embed = [":gopkg"],
    target_compatible_with = HOST_CONSTRAINTS,
    test_args = [
        "-test_data_dir=testdata",
        "-fragment-prefix=testdata",
    ],
    test_data = [":plasa_test_coverage_report_testdata"],
    visibility = ["//sdk:__pkg__"],
    deps = [
        "//third_party/golibs:github.com/google/go-cmp/cmp",
    ],
)
