# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/python/python_host_test.gni")
import("//build/python/python_library.gni")

python_library("zero_function") {
  testonly = true
  library_name = "zero_function"
  sources = [
    "__init__.py",
    "usbtest_controller.py",
    "zero_function.py",
  ]
  library_deps = [
    "//src/testing/end_to_end/honeydew",
    "//src/testing/end_to_end/mobly_base_tests/fuchsia_base_test",
    "//src/tests/end_to_end/usb/lib:usb_lib",
    "//src/tests/end_to_end/usb/lib/testusb",
  ]
}

if (is_host) {
  python_host_test("zero_function_lib_test") {
    main_source = "zero_function_test.py"
    libraries = [
      ":zero_function",
      "//src/testing/end_to_end/honeydew",
      "//src/testing/end_to_end/mobly_base_tests/fuchsia_base_test",
      "//src/tests/end_to_end/usb/lib:usb_lib",
      "//src/tests/end_to_end/usb/lib/testusb:testusb",
      "//third_party/mobly",
    ]
    main_callable = "unittest.main"
    extra_args = [ "-v" ]
  }
}

group("tests") {
  testonly = true
  public_deps = [ ":zero_function_lib_test($host_toolchain)" ]
}
