# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")
load("//build/bazel/rules/host_tests:host_go_test.bzl", "host_go_test")

package(default_applicable_licenses = ["//:license"])

go_library(
    name = "parser",
    srcs = [
        "generators.go",
        "parser.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/fidl/gidl/lib/parser",
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = [
        "//tools/fidl/gidl:__subpackages__",
    ],
    deps = [
        "//third_party/golibs:golang.org/x/exp/slices",
        "//tools/fidl/gidl/lib/ir",
        "//tools/fidl/lib/fidlgen",
    ],
)

host_go_test(
    name = "gidl_parser_tests",
    srcs = ["parser_test.go"],
    embed = [":parser"],
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//tools:__pkg__"],
    deps = ["//third_party/golibs:github.com/google/go-cmp/cmp"],
)
