# Copyright 2019 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/cpp/library_headers.gni")
import("//zircon/kernel/kernel_rust_crate.gni")
import("//zircon/kernel/kernel_rust_mod.gni")

library_headers("headers") {
  headers = [ "lib/pow2_range_allocator.h" ]
}

static_library("pow2_range_allocator") {
  public_deps = [ ":headers" ]

  sources = [ "pow2_range_allocator.cc" ]
}

kernel_rust_crate("pow2-range-allocator-rs") {
  crate_name = "pow2_range_allocator"
  sources = [ "src/lib.rs" ]
  deps = [
    "//sdk/rust/zx-status",
    "//src/lib/kalloc",
    "//src/lib/ksync",
    "//third_party/rust_crates:pin-init",
    "//zircon/kernel/lib/debug",
    "//zircon/system/ulib/fbl/rust:fbl",
  ]
}

kernel_rust_mod("pow2_range_allocator_tests") {
  testonly = true
  source_root = "tests/kernel.rs"
  sources = [ "tests/kernel.rs" ]
  deps = [ ":pow2-range-allocator-rs" ]
  test_deps = [
    "//sdk/rust/zx-status",
    "//third_party/rust_crates:pin-init",
    "//zircon/kernel/lib/unittest:unittest-rs",
  ]
}

group("tests") {
  testonly = true
}

source_set("kernel-tests") {
  testonly = true
  sources = [ "pow2_range_allocator_tests.cc" ]
  deps = [
    ":pow2_range_allocator",
    ":pow2_range_allocator_tests",
    "//zircon/kernel/lib/unittest",
  ]
}

group("phys-tests") {
  testonly = true
}

group("boot_tests") {
  testonly = true
}
