# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//zircon/kernel/kernel_rust_mod.gni")

kernel_rust_mod("zircon") {
  output_name = "acpi_lite_zircon"

  source_root = "src/mod.rs"
  sources = [ "src/mod.rs" ]

  deps = [
    "//sdk/rust/zx-status",
    "//src/lib/kalloc",
    "//src/lib/ksync",
    "//src/lib/zr",
    "//third_party/rust_crates:pin-init",
    "//zircon/kernel/lib/acpi_lite/rust:acpi_lite",
    "//zircon/kernel/lib/page:page-rs",
    "//zircon/system/ulib/fbl/rust:fbl",
  ]

  test_deps = [ "//zircon/kernel/lib/unittest:unittest-rs" ]
}
