# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
[workspace]
members = [
  "sapphire-async",
  "sapphire-collections",
  "sapphire-common",
  "sapphire-emboss",
  "sapphire-gatt",
  "sapphire-hci",
  "sapphire-host",
  "sapphire-peer-cache",
  "sapphire-rpc-macro",
  "sapphire-sync",
]
resolver = "3"

