# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""Device-agnostic capability strings.

For a list of available OpenWrt UCI capabilities, refer to:
https://openwrt.org/docs/guide-user/network/wifi/basic#ht_high_throughput_capabilities
"""

from dataclasses import dataclass

# 802.11n (HT) capabilities
N_CAPABILITY_LDPC = "LDPC"
N_CAPABILITY_GREENFIELD = "GF"
N_CAPABILITY_SHORT_GI_20 = "SHORT-GI-20"
N_CAPABILITY_SHORT_GI_40 = "SHORT-GI-40"
N_CAPABILITY_TX_STBC = "TX-STBC"
N_CAPABILITY_RX_STBC1 = "RX-STBC1"
N_CAPABILITY_RX_STBC12 = "RX-STBC12"
N_CAPABILITY_RX_STBC123 = "RX-STBC123"
N_CAPABILITY_MAX_AMSDU_7935 = "MAX-AMSDU-7935"
N_CAPABILITY_DSSS_CCK_40 = "DSSS_CCK-40"
N_CAPABILITY_HT40_PLUS = "HT40+"
N_CAPABILITY_HT20 = "HT20"

# TODO(b/508107385): Remove the legacy/unsupported capabilities.
N_CAPABILITY_40_INTOLERANT = "40-INTOLERANT"
N_CAPABILITY_SMPS_STATIC = "SMPS-STATIC"

# 802.11ac (VHT) capabilities
AC_CAPABILITY_MAX_MPDU_7991 = "MAX-MPDU-7991"
AC_CAPABILITY_MAX_MPDU_11454 = "MAX-MPDU-11454"
AC_CAPABILITY_RXLDPC = "RXLDPC"
AC_CAPABILITY_SHORT_GI_80 = "SHORT-GI-80"
AC_CAPABILITY_SHORT_GI_160 = "SHORT-GI-160"
AC_CAPABILITY_TX_STBC_2BY1 = "TX-STBC-2BY1"
AC_CAPABILITY_SU_BEAMFORMER = "SU-BEAMFORMER"
AC_CAPABILITY_SU_BEAMFORMEE = "SU-BEAMFORMEE"
AC_CAPABILITY_MU_BEAMFORMER = "MU-BEAMFORMER"
AC_CAPABILITY_MU_BEAMFORMEE = "MU-BEAMFORMEE"
AC_CAPABILITY_VHT_TXOP_PS = "VHT-TXOP-PS"
AC_CAPABILITY_HTC_VHT = "HTC-VHT"
AC_CAPABILITY_RX_STBC_1 = "RX-STBC-1"
AC_CAPABILITY_RX_STBC_12 = "RX-STBC-12"
AC_CAPABILITY_RX_STBC_123 = "RX-STBC-123"
AC_CAPABILITY_RX_STBC_1234 = "RX-STBC-1234"
AC_CAPABILITY_MAX_A_MPDU_LEN_EXP0 = "MAX-A-MPDU-LEN-EXP0"
AC_CAPABILITY_MAX_A_MPDU_LEN_EXP1 = "MAX-A-MPDU-LEN-EXP1"
AC_CAPABILITY_MAX_A_MPDU_LEN_EXP2 = "MAX-A-MPDU-LEN-EXP2"
AC_CAPABILITY_MAX_A_MPDU_LEN_EXP3 = "MAX-A-MPDU-LEN-EXP3"
AC_CAPABILITY_MAX_A_MPDU_LEN_EXP4 = "MAX-A-MPDU-LEN-EXP4"
AC_CAPABILITY_MAX_A_MPDU_LEN_EXP5 = "MAX-A-MPDU-LEN-EXP5"
AC_CAPABILITY_MAX_A_MPDU_LEN_EXP6 = "MAX-A-MPDU-LEN-EXP6"
AC_CAPABILITY_MAX_A_MPDU_LEN_EXP7 = "MAX-A-MPDU-LEN-EXP7"
AC_CAPABILITY_VHT_LINK_ADAPT0 = "VHT-LINK-ADAPT0"
AC_CAPABILITY_VHT_LINK_ADAPT1 = "VHT-LINK-ADAPT1"
AC_CAPABILITY_VHT_LINK_ADAPT2 = "VHT-LINK-ADAPT2"
AC_CAPABILITY_VHT_LINK_ADAPT3 = "VHT-LINK-ADAPT3"
AC_CAPABILITY_VHT160 = "VHT160"
AC_CAPABILITY_VHT160_80PLUS80 = "VHT160-80PLUS80"
AC_CAPABILITY_RX_ANTENNA_PATTERN = "RX-ANTENNA-PATTERN"
AC_CAPABILITY_TX_ANTENNA_PATTERN = "TX-ANTENNA-PATTERN"

# Define UCI Option Name Constants
UCI_OPT_LDPC = "ldpc"
UCI_OPT_GREENFIELD = "greenfield"
UCI_OPT_SHORT_GI_20 = "short_gi_20"
UCI_OPT_SHORT_GI_40 = "short_gi_40"
UCI_OPT_TX_STBC = "tx_stbc"
UCI_OPT_RX_STBC = "rx_stbc"
UCI_OPT_MAX_AMSDU = "max_amsdu"
UCI_OPT_DSSS_CCK_40 = "dsss_cck_40"
UCI_OPT_HT40_PLUS = "ht40_plus"
UCI_OPT_HT20 = "ht20"
UCI_OPT_VHT_MAX_MPDU = "vht_max_mpdu"
UCI_OPT_RXLDPC = "rxldpc"
UCI_OPT_SHORT_GI_80 = "short_gi_80"
UCI_OPT_SHORT_GI_160 = "short_gi_160"
UCI_OPT_TX_STBC_2BY1 = "tx_stbc_2by1"
UCI_OPT_SU_BEAMFORMER = "su_beamformer"
UCI_OPT_SU_BEAMFORMEE = "su_beamformee"
UCI_OPT_MU_BEAMFORMER = "mu_beamformer"
UCI_OPT_MU_BEAMFORMEE = "mu_beamformee"
UCI_OPT_VHT_TXOP_PS = "vht_txop_ps"
UCI_OPT_HTC_VHT = "htc_vht"
UCI_OPT_MAX_A_MPDU_LEN_EXP = "max_a_mpdu_len_exp"
UCI_OPT_VHT_LINK_ADAPT = "vht_link_adapt"
UCI_OPT_VHT160 = "vht160"
UCI_OPT_RXANTENNA = "rxantenna"
UCI_OPT_TXANTENNA = "txantenna"


@dataclass
class OpenWrtCapInfo:
    uci_option: str
    value: int


# Define the default state for every OpenWrt option.
# None means do not set a default value (do not auto-disable).
UCI_OPTION_DEFAULTS = {
    UCI_OPT_LDPC: 0,
    UCI_OPT_GREENFIELD: 0,
    UCI_OPT_SHORT_GI_20: 0,
    UCI_OPT_SHORT_GI_40: 0,
    UCI_OPT_TX_STBC: 0,
    UCI_OPT_RX_STBC: 0,
    UCI_OPT_MAX_AMSDU: 0,
    UCI_OPT_DSSS_CCK_40: 0,
    UCI_OPT_HT40_PLUS: 0,
    UCI_OPT_HT20: 0,
    UCI_OPT_VHT_MAX_MPDU: None,
    UCI_OPT_RXLDPC: 0,
    UCI_OPT_SHORT_GI_80: 0,
    UCI_OPT_SHORT_GI_160: 0,
    UCI_OPT_TX_STBC_2BY1: 0,
    UCI_OPT_SU_BEAMFORMER: 0,
    UCI_OPT_SU_BEAMFORMEE: 0,
    UCI_OPT_MU_BEAMFORMER: 0,
    UCI_OPT_MU_BEAMFORMEE: 0,
    UCI_OPT_VHT_TXOP_PS: 0,
    UCI_OPT_HTC_VHT: 0,
    UCI_OPT_MAX_A_MPDU_LEN_EXP: None,
    UCI_OPT_VHT_LINK_ADAPT: None,
    UCI_OPT_VHT160: 0,
    UCI_OPT_RXANTENNA: 0,
    UCI_OPT_TXANTENNA: 0,
}

# Define the mapping at module level to avoid recreation on every call.
_CAPABILITY_MAPPING = {
    N_CAPABILITY_LDPC: OpenWrtCapInfo(UCI_OPT_LDPC, 1),
    N_CAPABILITY_GREENFIELD: OpenWrtCapInfo(UCI_OPT_GREENFIELD, 1),
    N_CAPABILITY_SHORT_GI_20: OpenWrtCapInfo(UCI_OPT_SHORT_GI_20, 1),
    N_CAPABILITY_SHORT_GI_40: OpenWrtCapInfo(UCI_OPT_SHORT_GI_40, 1),
    N_CAPABILITY_TX_STBC: OpenWrtCapInfo(UCI_OPT_TX_STBC, 1),
    N_CAPABILITY_RX_STBC1: OpenWrtCapInfo(UCI_OPT_RX_STBC, 1),
    N_CAPABILITY_RX_STBC12: OpenWrtCapInfo(UCI_OPT_RX_STBC, 2),
    N_CAPABILITY_RX_STBC123: OpenWrtCapInfo(UCI_OPT_RX_STBC, 3),
    N_CAPABILITY_MAX_AMSDU_7935: OpenWrtCapInfo(UCI_OPT_MAX_AMSDU, 1),
    N_CAPABILITY_DSSS_CCK_40: OpenWrtCapInfo(UCI_OPT_DSSS_CCK_40, 1),
    N_CAPABILITY_HT40_PLUS: OpenWrtCapInfo(UCI_OPT_HT40_PLUS, 1),
    N_CAPABILITY_HT20: OpenWrtCapInfo(UCI_OPT_HT20, 1),
    AC_CAPABILITY_MAX_MPDU_7991: OpenWrtCapInfo(UCI_OPT_VHT_MAX_MPDU, 7991),
    AC_CAPABILITY_MAX_MPDU_11454: OpenWrtCapInfo(UCI_OPT_VHT_MAX_MPDU, 11454),
    AC_CAPABILITY_RXLDPC: OpenWrtCapInfo(UCI_OPT_RXLDPC, 1),
    AC_CAPABILITY_SHORT_GI_80: OpenWrtCapInfo(UCI_OPT_SHORT_GI_80, 1),
    AC_CAPABILITY_SHORT_GI_160: OpenWrtCapInfo(UCI_OPT_SHORT_GI_160, 1),
    AC_CAPABILITY_TX_STBC_2BY1: OpenWrtCapInfo(UCI_OPT_TX_STBC_2BY1, 1),
    AC_CAPABILITY_SU_BEAMFORMER: OpenWrtCapInfo(UCI_OPT_SU_BEAMFORMER, 1),
    AC_CAPABILITY_SU_BEAMFORMEE: OpenWrtCapInfo(UCI_OPT_SU_BEAMFORMEE, 1),
    AC_CAPABILITY_MU_BEAMFORMER: OpenWrtCapInfo(UCI_OPT_MU_BEAMFORMER, 1),
    AC_CAPABILITY_MU_BEAMFORMEE: OpenWrtCapInfo(UCI_OPT_MU_BEAMFORMEE, 1),
    AC_CAPABILITY_VHT_TXOP_PS: OpenWrtCapInfo(UCI_OPT_VHT_TXOP_PS, 1),
    AC_CAPABILITY_HTC_VHT: OpenWrtCapInfo(UCI_OPT_HTC_VHT, 1),
    AC_CAPABILITY_RX_STBC_1: OpenWrtCapInfo(UCI_OPT_RX_STBC, 1),
    AC_CAPABILITY_RX_STBC_12: OpenWrtCapInfo(UCI_OPT_RX_STBC, 2),
    AC_CAPABILITY_RX_STBC_123: OpenWrtCapInfo(UCI_OPT_RX_STBC, 3),
    AC_CAPABILITY_RX_STBC_1234: OpenWrtCapInfo(UCI_OPT_RX_STBC, 4),
    AC_CAPABILITY_MAX_A_MPDU_LEN_EXP0: OpenWrtCapInfo(
        UCI_OPT_MAX_A_MPDU_LEN_EXP, 0
    ),
    AC_CAPABILITY_MAX_A_MPDU_LEN_EXP1: OpenWrtCapInfo(
        UCI_OPT_MAX_A_MPDU_LEN_EXP, 1
    ),
    AC_CAPABILITY_MAX_A_MPDU_LEN_EXP2: OpenWrtCapInfo(
        UCI_OPT_MAX_A_MPDU_LEN_EXP, 2
    ),
    AC_CAPABILITY_MAX_A_MPDU_LEN_EXP3: OpenWrtCapInfo(
        UCI_OPT_MAX_A_MPDU_LEN_EXP, 3
    ),
    AC_CAPABILITY_MAX_A_MPDU_LEN_EXP4: OpenWrtCapInfo(
        UCI_OPT_MAX_A_MPDU_LEN_EXP, 4
    ),
    AC_CAPABILITY_MAX_A_MPDU_LEN_EXP5: OpenWrtCapInfo(
        UCI_OPT_MAX_A_MPDU_LEN_EXP, 5
    ),
    AC_CAPABILITY_MAX_A_MPDU_LEN_EXP6: OpenWrtCapInfo(
        UCI_OPT_MAX_A_MPDU_LEN_EXP, 6
    ),
    AC_CAPABILITY_MAX_A_MPDU_LEN_EXP7: OpenWrtCapInfo(
        UCI_OPT_MAX_A_MPDU_LEN_EXP, 7
    ),
    AC_CAPABILITY_VHT_LINK_ADAPT0: OpenWrtCapInfo(UCI_OPT_VHT_LINK_ADAPT, 0),
    AC_CAPABILITY_VHT_LINK_ADAPT1: OpenWrtCapInfo(UCI_OPT_VHT_LINK_ADAPT, 1),
    AC_CAPABILITY_VHT_LINK_ADAPT2: OpenWrtCapInfo(UCI_OPT_VHT_LINK_ADAPT, 2),
    AC_CAPABILITY_VHT_LINK_ADAPT3: OpenWrtCapInfo(UCI_OPT_VHT_LINK_ADAPT, 3),
    AC_CAPABILITY_VHT160: OpenWrtCapInfo(UCI_OPT_VHT160, 1),
    AC_CAPABILITY_VHT160_80PLUS80: OpenWrtCapInfo(UCI_OPT_VHT160, 2),
    AC_CAPABILITY_RX_ANTENNA_PATTERN: OpenWrtCapInfo(UCI_OPT_RXANTENNA, 1),
    AC_CAPABILITY_TX_ANTENNA_PATTERN: OpenWrtCapInfo(UCI_OPT_TXANTENNA, 1),
}


def to_openwrt_capability(cap: str) -> OpenWrtCapInfo:
    """Maps a generic capability string to its OpenWrt UCI option name and value."""
    if cap not in _CAPABILITY_MAPPING:
        raise ValueError(f"Unknown capability: {cap}")
    return _CAPABILITY_MAPPING[cap]
