# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/python/python_library.gni")

python_library("proto") {
  source_root = "."
  sources = [
    "__init__.py",
    "build_artifacts_pb2.py",
    "context_pb2.py",
    "static_pb2.py",
  ]
  deps = [ "//prebuilt/third_party/protobuf-py3" ]
}
