# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# type: ignore

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: set_artifacts.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'set_artifacts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13set_artifacts.proto\x12\x04\x66int\"\xc2\x02\n\x0cSetArtifacts\x12\x17\n\x0f\x66\x61ilure_summary\x18\x01 \x01(\t\x12\x15\n\rgn_trace_path\x18\x02 \x01(\t\x12\x12\n\nskip_build\x18\x03 \x01(\x08\x12-\n\x08metadata\x18\x04 \x01(\x0b\x32\x1b.fint.SetArtifacts.Metadata\x12\x12\n\nenable_rbe\x18\x05 \x01(\x08\x12\x1b\n\x13\x62uild_event_service\x18\x06 \x01(\t\x12!\n\x19\x62uild_event_service_ninja\x18\x07 \x01(\t\x1ak\n\x08Metadata\x12\r\n\x05\x62oard\x18\x01 \x01(\t\x12\x18\n\x10\x63ompilation_mode\x18\x02 \x01(\t\x12\x0f\n\x07product\x18\x03 \x01(\t\x12\x13\n\x0btarget_arch\x18\x04 \x01(\t\x12\x10\n\x08variants\x18\x05 \x03(\tB5Z3go.fuchsia.dev/fuchsia/tools/integration/fint/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'set_artifacts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3go.fuchsia.dev/fuchsia/tools/integration/fint/proto'
  _globals['_SETARTIFACTS']._serialized_start=30
  _globals['_SETARTIFACTS']._serialized_end=352
  _globals['_SETARTIFACTS_METADATA']._serialized_start=245
  _globals['_SETARTIFACTS_METADATA']._serialized_end=352
# @@protoc_insertion_point(module_scope)
