# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(
    default_applicable_licenses = ["//:license"],
)

# compat_info is used cross toolchain
rustc_library(
    name = "lib",
    srcs = ["src/lib.rs"],
    crate_name = "compat_info",
    edition = "2024",
    visibility = ["//src/developer:__subpackages__"],
    with_host_unit_tests = True,
    deps = [
        "//sdk/fidl/fuchsia.developer.remotecontrol:fuchsia.developer.remotecontrol_rust",
        "//src/lib/versioning/version-history/rust",
        "//third_party/rust_crates/vendor:schemars",
        "//third_party/rust_crates/vendor:serde",
        "//third_party/rust_crates/vendor:serde_json",
    ],
)
