#!/bin/bash
# Copyright 2025 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Wait for the piped-in "led launch" to finish. Afterwards, produce an exit
# status that corresponds to that of the run, and print the cas digest.
set -e
set -o pipefail
readonly BBID="$(jq -r .buildbucket.build_id)"
readonly STATUS="$(bb collect -fields status -json $BBID | jq -r .status)"
[[ "$STATUS" = "SUCCESS" ]] || exit 125
bb collect -p -json $BBID | jq -r .output.properties.isolated
