#!/bin/bash
# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

readonly COG_BASE_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/../..")"
readonly CARTFS_FUCHSIA_DIR="$(readlink -f "${COG_BASE_DIR}/cartfs-dir/fuchsia")"

set -e

if [[ ! -e "${CARTFS_FUCHSIA_DIR}" ]]; then
  echo "Error: unable to find the cartfs symlink. Run the setup script to fix this."
  exit 1
fi

# We need to run this here to make sure that the PATH is updated with the
# prebuilts in the CartFS. If we do not do this then we will pick up the wrong
# hermetic-env.
source "${CARTFS_FUCHSIA_DIR}/scripts/fx-env.sh" && fx-update-path
(
  cd "${CARTFS_FUCHSIA_DIR}"/vendor/google
  "${CARTFS_FUCHSIA_DIR}/.jiri_root/bin/ffx" "$@"
)
