# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")
load("//build/bazel/platforms:constraints.bzl", "HOST_OS_CONSTRAINTS")
load("//build/bazel/rules/host:defs.bzl", "go_binary_host_tool")
load("//build/bazel/rules/host_tests:host_go_test.bzl", "host_go_test")

package(default_applicable_licenses = ["//:license"])

go_library(
    name = "proto_lib",
    srcs = [
        "proto/params.pb.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/integration/testsharder/proto",
    target_compatible_with = HOST_OS_CONSTRAINTS,
    visibility = ["//:__subpackages__"],
    deps = [
        "//third_party/golibs:google.golang.org/protobuf/proto",
        "//third_party/golibs:google.golang.org/protobuf/reflect/protoreflect",
        "//third_party/golibs:google.golang.org/protobuf/runtime/protoimpl",
        "//third_party/golibs:google.golang.org/protobuf/types/known/durationpb",
    ],
)

go_library(
    name = "testsharder_lib",
    srcs = [
        "builder_deps.go",
        "doc.go",
        "durations.go",
        "emu_versions.go",
        "ffx_deps.go",
        "images.go",
        "postprocess.go",
        "preprocess.go",
        "shard.go",
        "task_requests.go",
        "test.go",
        "test_modifier.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/integration/testsharder",
    target_compatible_with = HOST_OS_CONSTRAINTS,
    visibility = ["//:__subpackages__"],
    deps = [
        ":metadata",
        ":proto_lib",
        "//third_party/golibs:golang.org/x/exp/maps",
        "//third_party/golibs:golang.org/x/exp/slices",
        "//tools/botanist:targets",
        "//tools/build",
        "//tools/integration/fint:proto_lib",
        "//tools/lib/color",
        "//tools/lib/ffxutil",
        "//tools/lib/flagmisc",
        "//tools/lib/hostplatform",
        "//tools/lib/jsonutil",
        "//tools/lib/logger",
        "//tools/metadata:proto_lib",
        "//tools/testing/runtests",
    ],
)

go_library(
    name = "metadata",
    srcs = [
        "metadata/metadata.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/integration/testsharder/metadata",
    target_compatible_with = HOST_OS_CONSTRAINTS,
    visibility = ["//:__subpackages__"],
    deps = [
        "//third_party/golibs:google.golang.org/protobuf/encoding/prototext",
        "//tools/build",
        "//tools/metadata:proto_lib",
    ],
)

go_library(
    name = "main",
    srcs = [
        "cmd/main.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/integration/testsharder/main",
    target_compatible_with = HOST_OS_CONSTRAINTS,
    visibility = ["//:__subpackages__"],
    deps = [
        ":metadata",
        ":proto_lib",
        ":testsharder_lib",
        "//third_party/golibs:golang.org/x/exp/slices",
        "//third_party/golibs:google.golang.org/protobuf/encoding/prototext",
        "//tools/build",
        "//tools/lib/color",
        "//tools/lib/flagmisc",
        "//tools/lib/hostplatform",
        "//tools/lib/logger",
    ],
)

# @bazel2gn:skip
go_binary_host_tool(
    name = "testsharder",
    embed = [":main"],
    target_compatible_with = HOST_CONSTRAINTS,
)

host_go_test(
    name = "testsharder_lib_tests",
    srcs = [
        "durations_test.go",
        "ffx_deps_test.go",
        "images_test.go",
        "postprocess_test.go",
        "preprocess_test.go",
        "shard_test.go",
        "task_requests_test.go",
        "test_modifier_test.go",
    ],
    embed = [":testsharder_lib"],
    deps = [
        "//third_party/golibs:github.com/google/go-cmp/cmp",
        "//third_party/golibs:github.com/google/go-cmp/cmp/cmpopts",
    ],
)

host_go_test(
    name = "testsharder_metadata_tests",
    srcs = [
        "metadata/metadata_test.go",
    ],
    embed = [":metadata"],
    deps = [
        "//third_party/golibs:github.com/google/go-cmp/cmp",
    ],
)
