# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")
load("//build/bazel/rules/host_tests:host_go_test.bzl", "host_go_test")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

genrule(
    name = "copy_agents_txt",
    srcs = ["//tools/devshell/lib:agents.txt"],
    outs = ["agents.txt"],
    cmd = "cp $< $@",
)

go_library(
    name = "agents",
    srcs = [
        "agents.go",
    ],
    embedsrcs = [
        ":copy_agents_txt",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/lib/agents",
)

host_go_test(
    name = "agents_tests",
    srcs = [
        "agents_test.go",
    ],
    embed = [
        ":agents",
    ],
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//tools:__pkg__"],
)
