# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bazel/bazel_host_tool.gni")
import("//build/rust/rustc_test.gni")

assert(is_host, "bazel_host_tool() can only be called in a host toolchain.")

bazel_host_tool("list_test_expectations") {
  bazel_target = ":list_test_expectations"
  bazel_output_path = "{{BAZEL_TARGET_OUT_DIR}}/list_test_expectations"
  install_host_tool = true
}

rustc_test("bin_test") {
  edition = "2024"
  name = "list_test_expectations_bin_test"
  source_root = "src/main.rs"
  sources = [ "src/main.rs" ]
  deps = [
    "//src/lib/testing/expectation/expectations_matcher",
    "//src/lib/testing/expectation/ser",
    "//third_party/rust_crates:anyhow",
    "//third_party/rust_crates:argh",
    "//third_party/rust_crates:glob",
    "//third_party/rust_crates:serde_json5",
  ]
  configs += [ "//build/config/rust/lints:deny_unused_results" ]
}

group("tests") {
  testonly = true
  deps = [ ":bin_test" ]
}
