# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bazel/bazel_host_tool.gni")

assert(is_host, "bazel_host_tool() can only be called in a host toolchain.")

bazel_host_tool("go_test_parser") {
  bazel_target = ":go_test_parser"
  bazel_output_path = "{{BAZEL_TARGET_OUT_DIR}}/go_test_parser_/go_test_parser"
}
