# Copyright 2019 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/cpp/library_headers.gni")
import("//build/rust/rustc_bindgen.gni")
import("//build/zircon/zircon_cpu.gni")
import("//zircon/kernel/kernel_bindgen_crate.gni")
import("//zircon/kernel/kernel_rust_mod.gni")
import("//zircon/kernel/params.gni")

source_set("vm") {
  public_deps = [ ":headers" ]

  sources = [
    "anonymous_page_request.cc",
    "arch_vm_aspace_ffi.cc",
    "attribution_ffi.cc",
    "compression.cc",
    "compressor.cc",
    "continuous_attribution_tracker.cc",
    "debug_compressor.cc",
    "discardable_vmo_tracker.cc",
    "evictor.cc",
    "kstack.cc",
    "lz4_compressor.cc",
    "mem_command.cc",
    "memory_stats.cc",
    "page.cc",
    "page_ffi.cc",
    "page_queues.cc",
    "page_queues_ffi.cc",
    "page_source.cc",
    "page_source_ffi.cc",
    "page_state.cc",
    "physical_page_borrowing_config.cc",
    "physical_page_borrowing_config_ffi.cc",
    "physical_page_provider.cc",
    "physmap_ffi.cc",
    "pinned_vm_object.cc",
    "pmm.cc",
    "pmm_arena.cc",
    "pmm_checker.cc",
    "pmm_ffi.cc",
    "pmm_node.cc",
    "ppb_command.cc",
    "scanner.cc",
    "scanner_ffi.cc",
    "slot_page_storage.cc",
    "stream_size_manager.cc",
    "vm.cc",
    "vm_address_region.cc",
    "vm_address_region_or_mapping.cc",
    "vm_aspace.cc",
    "vm_cow_pages.cc",
    "vm_cow_pages_ffi.cc",
    "vm_mapping.cc",
    "vm_object.cc",
    "vm_object_ffi.cc",
    "vm_object_paged.cc",
    "vm_object_paged_ffi.cc",
    "vm_object_physical.cc",
    "vm_page_list.cc",
    "vmm.cc",
  ]
  deps = [
    ":vm-rs",
    "//src/lib/zbitl",
    "//third_party/lz4",
    "//zircon/kernel/lib/arch",
    "//zircon/kernel/lib/boot-options",
    "//zircon/kernel/lib/btree",
    "//zircon/kernel/lib/console",
    "//zircon/kernel/lib/counters",
    "//zircon/kernel/lib/dump",
    "//zircon/kernel/lib/fbl",
    "//zircon/kernel/lib/heap/cmpctmalloc:headers",
    "//zircon/kernel/lib/init",
    "//zircon/kernel/lib/ktl",
    "//zircon/kernel/lib/ktrace",
    "//zircon/kernel/lib/page",
    "//zircon/kernel/lib/page_cache",
    "//zircon/kernel/lib/thread-stack",
    "//zircon/kernel/lib/user_copy",
    "//zircon/kernel/lib/userabi",
    "//zircon/kernel/phys:handoff",
    "//zircon/kernel/phys:zircon-abi-spec",
    "//zircon/kernel/phys/lib/memalloc:range",
    "//zircon/system/ulib/affine",
    "//zircon/system/ulib/ffl",
    "//zircon/system/ulib/lazy_init",
    "//zircon/system/ulib/pretty",
  ]

  defines = [
    "LZ4_STATIC_LINKING_ONLY",
    "LZ4_STATIC_LINKING_ONLY_DISABLE_MEMORY_ALLOCATION",
  ]

  # GCC figures out some cases where we have a global variable that's used as a
  # RefPtr and so appears like it might be passed to delete.  We always leak
  # the reference so it will never actually be called, but the compiler can't
  # figure that out statically so we must disable its warning.
  configs += [ ":suppress-nonheap-warning" ]
}

config("bindgen_common_config") {
  cflags = [ "-ffreestanding" ]
  defines = [
    "SMP_MAX_CPUS=$smp_max_cpus",
    "_KERNEL",
    "LK",
    "ZIRCON_TOOLCHAIN",
  ]
  include_dirs = [
    "//zircon/kernel/include",
    "//zircon/kernel/arch/$zircon_cpu/include",
    "//zircon/system/ulib/page_tables/include",
  ]
  if (current_cpu == "x64") {
    include_dirs += [ "//zircon/kernel/arch/x86/page_tables/include" ]
  }
}

group("bindgen_common_deps") {
  public_configs = [
    ":bindgen_common_config",
    "//build/config/fuchsia:compiler_fuchsia_api_level",
  ]
  public_deps = [
    ":headers",
    "//src/performance/lib/fxt:headers",
    "//zircon/kernel/lib/backtrace:headers",
    "//zircon/kernel/lib/fbl:headers",
    "//zircon/kernel/lib/heap:headers",
    "//zircon/kernel/lib/libc:headers",
    "//zircon/kernel/lib/lockup_detector:headers",
    "//zircon/kernel/lib/mmu_rcu:headers",
    "//zircon/kernel/lib/page-map:headers",
    "//zircon/kernel/lib/percpu_writer:headers",
    "//zircon/kernel/lib/power-management:headers",
    "//zircon/kernel/lib/sched:headers",
    "//zircon/kernel/lib/spsc_buffer:headers",
    "//zircon/kernel/lib/stall:headers",
    "//zircon/kernel/lib/wake-vector:headers",
    "//zircon/kernel/object:headers",
    "//zircon/system/ulib/page_tables:headers",
  ]
}

kernel_bindgen_crate("scanner-bindings") {
  visibility = [ ":*" ]
  headers = [ "include/vm/scanner_ffi.h" ]
  non_rust_deps = [ ":headers" ]
  output_name = "scanner_bindings.rs"
  cpp = true

  edition = "2024"
  notice_year = 2026
  function_allowlist = [
    "cpp_scanner_push_disable_count",
    "cpp_scanner_pop_disable_count",
  ]

  raw_lines = [ "#![no_std]" ]
  expect_lints = []
}

kernel_bindgen_crate("physical-page-borrowing-config-bindings") {
  visibility = [ ":*" ]
  headers = [ "include/vm/physical_page_borrowing_config_ffi.h" ]
  non_rust_deps = [ ":bindgen_common_deps" ]
  output_name = "physical_page_borrowing_config_bindings.rs"
  cpp = true

  edition = "2024"
  notice_year = 2026
  function_allowlist = [ "cpp_set_loaning_enabled" ]

  raw_lines = [ "#![no_std]" ]
  expect_lints = []
}

library_headers("headers") {
  headers = []

  public_deps = [
    # <vm/page.h> has #include <vm/phys/arena.h>.
    "phys:headers",

    # <vm/vm_page_list.h> has #include <ktl/unique_ptr.h>.
    "//zircon/kernel/lib/ktl:headers",

    # <vm/vm_object.h> has #include <fbl/name.h>.
    "//zircon/kernel/lib/fbl:headers",

    # <vm/vm_object.h> has #include <lib/user_copy/user_ptr.h>.
    "//zircon/kernel/lib/user_copy:headers",

    # <vm/vm_aspace.h> has #include <lib/crypto/prng.h>
    "//zircon/kernel/lib/crypto:headers",

    # Many headers naturally have #include <lib/page/size.h>
    "//zircon/kernel/lib/page:headers",

    # <vm/vm_object.h> has #include <ffl/fixed.h>
    "//zircon/system/ulib/ffl:headers",

    # "pmm_arena.h" has #include <lib/zx/result.h>.
    "//zircon/system/ulib/zx:headers",

    # <vm/pmm_checker.h> has #include <lib/boot-options/boot-options.h>.
    "//zircon/kernel/lib/boot-options:headers",
    "//zircon/kernel/lib/btree:headers",
  ]

  public_configs = [
    # <vm/physical_page_provider.h> has #include <object/port_dispatcher.h>.
    # But this is a circular dependency, so we can't use its :headers in deps.
    "//zircon/kernel/object:headers.config",
  ]
}

kernel_bindgen_crate("vm-constants-rs") {
  headers = [ "include/vm/vm_constants.h" ]
  cpp = true

  non_rust_deps = [ ":headers" ]

  if (enable_lock_dep) {
    additional_clang_flags = [ "-DWITH_LOCK_DEP=1" ]
  }

  notice_year = 2026
  var_allowlist = [
    "kVmObjectPhysicalState.*",
    "kVmCachePolicyMask",
  ]

  expect_lints = [ "non_upper_case_globals" ]

  raw_lines = [ "#![no_std]" ]
}

kernel_bindgen_crate("physmap-bindings") {
  visibility = [ ":*" ]
  headers = [ "include/vm/physmap_ffi.h" ]
  non_rust_deps = [ ":bindgen_common_deps" ]
  output_name = "physmap_bindings.rs"
  cpp = true

  notice_year = 2026
  function_allowlist = [ "cpp_paddr_to_physmap" ]
  type_blocklist = [
    "zx_paddr_t",
    "zx_vaddr_t",
  ]
  additional_bindgen_flags = [ "--no-recursive-allowlist" ]
  deps = [ "//sdk/rust/zx-types" ]

  edition = "2024"

  raw_lines = [
    "#![no_std]",
    "pub use zx_types::{zx_paddr_t, zx_vaddr_t};",
  ]
}

kernel_bindgen_crate("pmm-bindings") {
  visibility = [ ":*" ]
  headers = [ "include/vm/pmm_ffi.h" ]
  non_rust_deps = [ ":bindgen_common_deps" ]
  output_name = "pmm_bindings.rs"
  cpp = true

  notice_year = 2026
  function_allowlist = [
    "cpp_pmm_page_queues",
    "cpp_pmm_alloc_page",
    "cpp_pmm_free_page",
    "cpp_paddr_to_vm_page",
  ]
  type_allowlist = [ "PmmOptDelayReuse" ]
  type_blocklist = [
    "PageQueues",
    "vm_page_t",
    "zx_paddr_t",
    "zx_status_t",
  ]
  additional_bindgen_flags = [
    "--no-recursive-allowlist",
    "--rustified-enum=PmmOptDelayReuse",
  ]
  deps = [
    ":page-bindings",
    ":page-queues-bindings",
    "//sdk/rust/zx-types",
  ]
  var_allowlist = [ "PMM_ALLOC_FLAG_.*" ]
  edition = "2024"
  raw_lines = [
    "#![no_std]",
    "use page_bindings::vm_page_t;",
    "use page_queues_bindings::PageQueues;",
    "pub use zx_types::{zx_paddr_t, zx_status_t};",
  ]
  expect_lints = []
}

kernel_bindgen_crate("page-queues-bindings") {
  visibility = [ ":*" ]
  headers = [ "include/vm/page_queues_ffi.h" ]
  non_rust_deps = [ ":bindgen_common_deps" ]
  output_name = "page_queues_bindings.rs"
  cpp = true

  edition = "2024"
  notice_year = 2026
  function_allowlist = [
    "cpp_page_queues_debug_page_is_wired",
    "cpp_page_queues_debug_page_is_any_anonymous",
    "cpp_page_queues_debug_page_is_reclaim",
    "cpp_page_queues_rotate_reclaim_queues",
  ]
  type_allowlist = [
    "AgeReason",
    "LruAction",
    "PageQueues",
  ]
  type_blocklist = [
    "fbl_RefPtr",
    "vm_page_t",
    "zx_paddr_t",
    "zx_status_t",
    "PageQueues_VmoBacklink",
    "PageQueues_ReclaimCounts",
    "PageQueues_Counts",
    "PageQueues_ActiveInactiveCounts",
  ]
  var_allowlist = [ "PageQueues_k.*" ]
  opaque_types = [ "PageQueues" ]
  rustified_enum = [
    "PageQueues_AgeReason",
    "PageQueues_LruAction",
  ]
  function_blocklist = [ "PageQueues_.*" ]
  additional_bindgen_flags = [ "--no-recursive-allowlist" ]
  deps = [
    ":page-bindings",
    "//sdk/rust/zx-types",
  ]
  raw_lines = [
    "#![no_std]",
    "use page_bindings::vm_page_t;",
    "pub use zx_types::zx_duration_mono_t;",
    "pub use zx_types::zx_paddr_t;",
  ]
  expect_lints = [
    "non_camel_case_types",
    "non_upper_case_globals",
  ]
}

kernel_bindgen_crate("page-bindings") {
  visibility = [ ":*" ]
  headers = [ "include/vm/page_ffi.h" ]
  non_rust_deps = [ ":bindgen_common_deps" ]
  output_name = "page_bindings.rs"
  cpp = true

  edition = "2024"
  notice_year = 2026
  var_allowlist = [
    "VM_PAGE_OBJECT_DIRTY_STATES_MASK",
    "VM_PAGE_OBJECT_DIRTY_STATE_BITS",
    "VM_PAGE_OBJECT_MAX_DIRTY_STATES",
    "VM_PAGE_OBJECT_MAX_PIN_COUNT",
    "VM_PAGE_OBJECT_PIN_COUNT_BITS",
  ]
  function_allowlist = [
    "cpp_get_count",
    "cpp_add_to_initial_count",
    "cpp_vm_page_is_loan_cancelled",
    "cpp_vm_page_is_loaned",
    "cpp_vm_page_set_is_loaned",
    "cpp_vm_page_clear_is_loaned",
    "cpp_vm_page_set_is_loan_cancelled",
    "cpp_vm_page_clear_is_loan_cancelled",
    "cpp_vm_page_dump",
    "cpp_vm_page_paddr",
    "cpp_vm_page_state",
    "cpp_vm_page_set_state",
    "cpp_vm_page_object_get_object",
    "cpp_vm_page_object_get_page_offset",
  ]
  type_allowlist = [
    "vm_page_t",
    "vm_page_state",
  ]
  opaque_types = [ "vm_page_t" ]
  rustified_enum = [ "vm_page_state" ]
  function_blocklist = [
    "vm_page_get_count",
    "vm_page_add_to_initial_count",
    "vm_page_dump",
  ]
  additional_bindgen_flags = [
    "--with-derive-custom-enum=vm_page_state=Ord",
    "--with-derive-custom-enum=vm_page_state=PartialOrd",
    "--no-recursive-allowlist",
  ]
  raw_lines = [
    "#![no_std]",
    "pub use zx_types::zx_paddr_t as paddr_t;",
  ]
  expect_lints = [ "non_camel_case_types" ]
  deps = [ "//sdk/rust/zx-types" ]
}

kernel_bindgen_crate("vm-fault-bindings") {
  visibility = [ ":*" ]
  headers = [ "include/vm/fault.h" ]
  non_rust_deps = [ ":bindgen_common_deps" ]
  output_name = "vm_fault_bindings.rs"
  cpp = true

  notice_year = 2026
  var_allowlist = [ "VMM_PF_FLAG_.*" ]

  edition = "2024"
  raw_lines = [ "#![no_std]" ]
  expect_lints = [ "non_camel_case_types" ]
}

kernel_bindgen_crate("vm-aspace-bindings") {
  visibility = [ ":*" ]
  headers = [ "include/vm/vm_aspace.h" ]
  non_rust_deps = [ ":bindgen_common_deps" ]
  output_name = "vm_aspace_bindings.rs"
  cpp = true

  notice_year = 2026
  var_allowlist = [ "VmAspace_VMM_FLAG_.*" ]

  edition = "2024"
  raw_lines = [ "#![no_std]" ]
  expect_lints = [
    "non_camel_case_types",
    "non_upper_case_globals",
  ]
}

kernel_bindgen_crate("vm-address-region-bindings") {
  visibility = [ ":*" ]
  headers = [ "include/vm/vm_address_region.h" ]
  non_rust_deps = [ ":bindgen_common_deps" ]
  output_name = "vm_address_region_bindings.rs"
  cpp = true

  notice_year = 2026
  var_allowlist = [
    "VMAR_FLAG_.*",
    "VMAR_CAN_RWX_FLAGS",
  ]
  type_allowlist = [
    "ActivateInsertRegions",
    "DestroyRemoveFromParent",
    "DestroyUnmap",
    "MemoryPriority",
    "Mergeable",
    "RangeOpType",
    "UnmapOptions",
    "VmAddressRegion",
    "VmAddressRegionOpChildren",
    "VmAddressRegionOrMapping",
    "VmMapping",
  ]
  type_blocklist = [
    "arch_mmu_flags_t",
    "fbl_RefPtr",
    "vaddr_t",
    "VmAddressRegion_AttributionCounts",
    "VmAddressRegion_MapResult",
    "VmMapping_AttributionCounts",
    "VmMapping_CurrentlyFaulting",
    "VmMapping_FlagsRange",
  ]
  opaque_types = [
    "VmAddressRegion",
    "VmAddressRegionOrMapping",
    "VmMapping",
  ]
  rustified_enum = [
    "VmAddressRegionOpChildren",
    "VmAddressRegionOrMapping_MemoryPriority",
    "VmAddressRegion_RangeOpType",
    "VmMapping_ActivateInsertRegions",
    "VmMapping_DestroyRemoveFromParent",
    "VmMapping_DestroyUnmap",
    "VmMapping_Mergeable",
    "VmMapping_UnmapOptions",
  ]
  function_blocklist = [
    "VmAddressRegion_.*",
    "VmAddressRegionOrMapping_.*",
    "VmMapping_.*",
  ]
  additional_bindgen_flags = [ "--no-recursive-allowlist" ]

  edition = "2024"
  raw_lines = [ "#![no_std]" ]
  expect_lints = [
    "non_camel_case_types",
    "non_upper_case_globals",
  ]
}

kernel_bindgen_crate("attribution-bindings") {
  visibility = [ ":*" ]
  headers = [ "include/vm/attribution_ffi.h" ]
  non_rust_deps = [ ":bindgen_common_deps" ]
  output_name = "attribution_bindings.rs"
  cpp = true

  edition = "2024"
  notice_year = 2026
  function_allowlist = [ "cpp_attribution_counts_zero" ]
  type_allowlist = [
    "vm::AttributionCounts",
    "vm::FractionalBytes",
  ]
  additional_bindgen_flags = [
    "--opaque-type=vm::FractionalBytes",
    "--with-derive-partialeq",
    "--with-derive-eq",
    "--no-recursive-allowlist",
  ]
  raw_lines = [ "#![no_std]" ]
  expect_lints = [ "non_camel_case_types" ]
}

kernel_bindgen_crate("page-source-bindings") {
  visibility = [ ":*" ]
  headers = [ "include/vm/page_source_ffi.h" ]
  non_rust_deps = [ ":bindgen_common_deps" ]
  output_name = "page_source_bindings.rs"
  cpp = true

  edition = "2024"
  notice_year = 2026
  function_allowlist = [
    "cpp_multi_page_request_construct",
    "cpp_multi_page_request_destroy",
    "cpp_multi_page_request_cancel_requests",
  ]
  type_allowlist = [ "MultiPageRequest" ]
  additional_bindgen_flags = [
    "--opaque-type=MultiPageRequest",
    "--no-recursive-allowlist",
    "--blocklist-function=MultiPageRequest_.*",
  ]
  raw_lines = [ "#![no_std]" ]
}

kernel_bindgen_crate("vm-object-bindings") {
  visibility = [ ":*" ]
  headers = [ "include/vm/vm_object_ffi.h" ]
  non_rust_deps = [ ":bindgen_common_deps" ]
  output_name = "vm_object_bindings.rs"
  cpp = true

  edition = "2024"
  notice_year = 2026
  function_allowlist = [
    "cpp_vm_object_commit_range",
    "cpp_vm_object_decommit_range",
    "cpp_vm_object_commit_range_pinned",
    "cpp_vm_object_free",
    "cpp_vm_object_get_ref_counted",
    "cpp_vm_object_is_resizable",
    "cpp_vm_object_is_contiguous",
    "cpp_vm_object_resize",
    "cpp_vm_object_set_name",
    "cpp_vm_object_size",
    "cpp_vm_object_unpin",
    "cpp_vm_object_write",
    "cpp_vm_object_hint_range",
    "cpp_vm_object_get_mapping_cache_policy",
    "cpp_vm_object_create_clone",
    "cpp_vm_object_get_page_blocking",
    "cpp_vm_object_set_user_id",
    "cpp_vm_object_user_id",
    "cpp_vm_object_parent_user_id",
    "cpp_vm_object_lookup",
    "cpp_vm_object_get_page",
    "cpp_vm_object_get_attributed_memory",
    "cpp_vm_object_read",
    "cpp_vm_object_zero_range",
  ]
  type_allowlist = [
    "EvictionHint",
    "Resizability",
    "SnapshotType",
    "SupplyOptions",
    "VmObject",
    "VmObjectReadWriteOptions",
    "cpp_vm_object_lookup_fn",
  ]
  type_blocklist = [
    "AttributionCounts",
    "MultiPageRequest",
    "paddr_t",
    "vm_page_t",
    "zx_status_t",
    "VmObject_AttributionCounts",
    "VmObject_ChildObserverLock",
    "VmObject_ChildType",
    "VmObject_CacheOpType",
    "VmObject_DirtyRangeEnumerateFunction",
    "VmObject_GlobalList",
    "VmObject_LookupFunction",
    "VmObject_MappingKey",
    "VmObject_MappingTree",
    "VmObject_OnWriteBytesTransferredCallback",
    "VmObject_RangeChangeOp",
  ]
  opaque_types = [ "VmObject" ]
  rustified_enum = [
    "Resizability",
    "SnapshotType",
    "SupplyOptions",
    "VmObjectReadWriteOptions",
    "VmObject_EvictionHint",
  ]
  function_blocklist = [ "VmObject_.*" ]
  additional_bindgen_flags = [ "--no-recursive-allowlist" ]
  var_allowlist = [ "VmObject_MAX_SIZE" ]
  deps = [
    ":attribution-bindings",
    ":page-bindings",
    ":page-source-bindings",
    "//sdk/rust/zx-types",
  ]
  raw_lines = [
    "#![no_std]",
    "use attribution_bindings::vm_AttributionCounts;",
    "use page_bindings::vm_page_t;",
    "use page_source_bindings::MultiPageRequest;",
    "use zx_types::zx_paddr_t as paddr_t;",
    "use zx_types::zx_status_t;",
  ]
  expect_lints = [
    "non_camel_case_types",
    "non_upper_case_globals",
  ]
}

kernel_bindgen_crate("vm-object-paged-bindings") {
  visibility = [ ":*" ]
  headers = [ "include/vm/vm_object_paged_ffi.h" ]
  non_rust_deps = [ ":bindgen_common_deps" ]
  output_name = "vm_object_paged_bindings.rs"
  cpp = true

  edition = "2024"
  notice_year = 2026
  function_allowlist = [
    "cpp_vm_object_as_vm_object_paged",
    "cpp_vm_object_paged_as_vm_object",
    "cpp_vm_object_paged_create",
    "cpp_vm_object_paged_create_contiguous",
    "cpp_vm_object_paged_debug_get_cow_pages",
    "cpp_vm_object_paged_debug_get_page",
  ]
  type_allowlist = [ "VmObjectPaged" ]
  type_blocklist = [
    "VmCowPages",
    "VmObject",
    "vm_page_t",
    "zx_status_t",
  ]
  var_allowlist = [
    "VmObjectPaged_kAlwaysPinned",
    "VmObjectPaged_kCanBlockOnPageRequests",
    "VmObjectPaged_kContiguous",
    "VmObjectPaged_kDiscardable",
    "VmObjectPaged_kReference",
    "VmObjectPaged_kResizable",
    "VmObjectPaged_kSlice",
  ]
  opaque_types = [ "VmObjectPaged" ]
  function_blocklist = [ "VmObjectPaged_.*" ]
  additional_bindgen_flags = [ "--no-recursive-allowlist" ]
  expect_lints = [
    "non_camel_case_types",
    "non_upper_case_globals",
  ]
  deps = [
    ":page-bindings",
    ":vm-cow-pages-bindings",
    ":vm-object-bindings",
    "//sdk/rust/zx-types",
  ]

  raw_lines = [
    "#![no_std]",
    "use page_bindings::vm_page_t;",
    "use vm_cow_pages_bindings::VmCowPages;",
    "use vm_object_bindings::VmObject;",
    "use zx_types::zx_status_t;",
  ]
}

kernel_bindgen_crate("vm-cow-pages-bindings") {
  visibility = [ ":*" ]
  headers = [ "include/vm/vm_cow_pages_ffi.h" ]
  non_rust_deps = [ ":bindgen_common_deps" ]
  output_name = "vm_cow_pages_bindings.rs"
  cpp = true

  notice_year = 2026
  function_allowlist = [
    "cpp_vm_cow_pages_free",
    "cpp_vm_cow_pages_get_ref_counted",
    "cpp_vm_cow_pages_initialize_page_cache",
    "cpp_vm_cow_pages_replace_page_with_loaned",
    "cpp_vm_cow_pages_should_delay_reuse_on_free",
    "cpp_vm_cow_pages_debug_get_parent",
    "cpp_vm_cow_pages_dedup_zero_page",
  ]
  type_allowlist = [
    "DirtyState",
    "EvictionAction",
    "PageSourceType",
    "VmCowPages",
    "VmCowPagesOptions",
    "VmCowReclaimFailure",
  ]
  type_blocklist = [
    "PmmOptDelayReuse",
    "vm_page_t",
    "zx_status_t",
    "VmCowPages_AddPageTransaction",
    "VmCowPages_AttributionCounts",
    "VmCowPages_CanOverwriteSlot",
    "VmCowPages_DirtyRangeEnumerateFunction",
    "VmCowPages_DiscardablePageCounts",
    "VmCowPages_LockedPtr",
    "VmCowPages_LockedRefPtr",
    "VmCowPages_LookupReadableFunction",
    "VmCowPages_PageLookup",
    "VmCowPages_ParentAndRange",
    "VmCowPages_RangeChangeOp",
  ]
  var_allowlist = [ "VmCowPagesOptions_.*" ]
  opaque_types = [ "VmCowPages" ]
  rustified_enum = [
    "PageSourceType",
    "VmCowPages_DirtyState",
    "VmCowPages_EvictionAction",
    "VmCowReclaimFailure",
  ]
  function_blocklist = [ "VmCowPages_.*" ]
  additional_bindgen_flags = [ "--no-recursive-allowlist" ]
  expect_lints = [
    "non_camel_case_types",
    "non_upper_case_globals",
  ]

  edition = "2024"

  deps = [
    ":page-bindings",
    ":pmm-bindings",
    "//sdk/rust/zx-types",
  ]

  raw_lines = [
    "#![no_std]",
    "use page_bindings::vm_page_t;",
    "use pmm_bindings::PmmOptDelayReuse;",
    "use zx_types::zx_status_t;",
  ]
}

kernel_rust_mod("vm-rs") {
  output_name = "vm"
  source_root = "mod.rs"
  sources = [
    "arch_vm_aspace.rs",
    "attribution.rs",
    "fault.rs",
    "mod.rs",
    "page.rs",
    "page_queues.rs",
    "page_source.rs",
    "page_state.rs",
    "physical_page_borrowing_config.rs",
    "physmap.rs",
    "pinned_vm_object.rs",
    "pmm.rs",
    "scanner.rs",
    "vm.rs",
    "vm_address_region.rs",
    "vm_aspace.rs",
    "vm_cow_pages.rs",
    "vm_mapping.rs",
    "vm_object.rs",
    "vm_object_paged.rs",
    "vm_object_physical.rs",
  ]

  deps = [
    ":attribution-bindings",
    ":page-bindings",
    ":page-queues-bindings",
    ":page-source-bindings",
    ":physical-page-borrowing-config-bindings",
    ":physmap-bindings",
    ":pmm-bindings",
    ":scanner-bindings",
    ":vm-address-region-bindings",
    ":vm-aspace-bindings",
    ":vm-constants-rs",
    ":vm-cow-pages-bindings",
    ":vm-fault-bindings",
    ":vm-object-bindings",
    ":vm-object-paged-bindings",
    "//sdk/rust/zx-status",
    "//src/lib/kalloc",
    "//src/lib/kprint",
    "//src/lib/ksync",
    "//src/lib/zr",
    "//third_party/rust_crates:pin-init",
    "//zircon/kernel/lib/init:init_rust",
    "//zircon/kernel/lib/page:page-rs",
    "//zircon/kernel/switch:allow_dead_code",
    "//zircon/system/ulib/fbl/rust:fbl",
  ]
}

kernel_bindgen_crate("test-helper-bindings") {
  visibility = [ ":*" ]
  headers = [ "unittests/test_helper_ffi.h" ]
  non_rust_deps = [ ":bindgen_common_deps" ]
  output_name = "test_helper_bindings.rs"
  cpp = true

  edition = "2024"
  notice_year = 2026
  function_allowlist = [
    "cpp_make_committed_pager_vmo",
    "cpp_make_partially_committed_pager_vmo",
    "cpp_make_private_attribution_counts",
    "cpp_verify_private_attribution_counts",
    "cpp_verify_continuous_attribution_bytes",
  ]
  type_blocklist = [
    "AttributionCounts",
    "VmObject",
    "VmObjectPaged",
    "vm_page_t",
    "zx_status_t",
  ]

  additional_bindgen_flags = [ "--no-recursive-allowlist" ]

  raw_lines = [
    "#![no_std]",
    "use attribution_bindings::vm_AttributionCounts;",
    "use page_bindings::vm_page_t;",
    "use vm_object_bindings::VmObject;",
    "use vm_object_paged_bindings::VmObjectPaged;",
    "use zx_types::zx_status_t;",
  ]
  deps = [
    ":attribution-bindings",
    ":page-bindings",
    ":vm-object-bindings",
    ":vm-object-paged-bindings",
    "//sdk/rust/zx-types",
  ]
}

kernel_rust_mod("vm-rs-unittests") {
  output_name = "vm_unittests"
  testonly = true
  visibility = [ ":*" ]
  source_root = "unittests/mod.rs"
  sources = [
    "unittests/test_helper.rs",
    "unittests/vmo_unittest.rs",
  ]
  deps = [
    ":test-helper-bindings",
    "//sdk/rust/zx-types",
    "//zircon/kernel/lib/debug",
    "//zircon/system/ulib/fbl/rust:fbl",
  ]
  test_deps = [ "//zircon/kernel/lib/unittest:unittest-rs" ]
}

config("suppress-nonheap-warning") {
  visibility = [ ":*" ]
  if (is_gcc) {
    cflags = [ "-Wno-free-nonheap-object" ]
  }
}

source_set("tests") {
  testonly = true
  sources = [
    "unittests/aspace_unittest.cc",
    "unittests/compression_unittest.cc",
    "unittests/continuous_attribution_unittest.cc",
    "unittests/evictor_unittest.cc",
    "unittests/page_queues_unittest.cc",
    "unittests/pmm_unittest.cc",
    "unittests/slab_unittest.cc",
    "unittests/test_helper.cc",
    "unittests/test_helper_ffi.cc",
    "unittests/vmo_unittest.cc",
    "unittests/vmpl_unittest.cc",
  ]
  deps = [
    ":vm-rs-unittests",
    "//third_party/lz4",
    "//zircon/kernel/lib/page",
    "//zircon/kernel/lib/unittest",
  ]
}

group("kernel-tests") {
  testonly = true
  deps = [ ":tests" ]
}
