# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

group("drivers") {
  testonly = true
  deps = [
    ":bazel_driver_packages",
    "bind/bindlib_codegen",
    "config:drivers",
    "driver_test_realm/sample_driver",
    "interrupt_handling/rust:package",
    "metadata:drivers",
    "power:drivers",
    "simple/dfv1:pkg",
    "simple/rust:pkg",
    "skeleton:pkg",
    "transport",
  ]
}

group("hermetic_tests") {
  testonly = true
  deps = [
    "driver_test_realm:hermetic_tests",
    "metadata:hermetic_tests",
    "power:hermetic_tests",
    "simple/rust:hermetic_tests",
    "transport:hermetic_tests",
  ]
}

# Drivers built by ':bazel_drivers'
group("bazel_driver_packages") {
  testonly = true
  visibility = [ ":drivers" ]
  deps = [
    "//examples/drivers/simple/dfv2:pkg",
    "//examples/drivers/template:pkg",
    "//examples/drivers/transport:driver_transport_child_pkg",
    "//examples/drivers/transport:driver_transport_parent_pkg",
  ]
}
