# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load(
    "@rules_fuchsia//fuchsia:assembly.bzl",
    "fuchsia_board_configuration",
    "fuchsia_product",
    "fuchsia_product_bundle",
)

# This test uses the non-sdk version of the product_configuration rule
# so that the generated example AIB can be used.
load(
    "//build/bazel/rules/assembly:product_configuration.bzl",
    "product_configuration",
)

package(
    default_applicable_licenses = ["//:license"],
)

fuchsia_board_configuration(
    name = "board_config",
    board_name = "test",
    partitions_configuration = "//build/bazel/assembly/partitions_configurations:default",
    version = "fake_version",
)

product_configuration(
    name = "product_config",
    enable_example_aib = True,
    product_config_json = {
        "platform": {
            "build_type": "user",
            "feature_set_level": "utility",
            "example_config": {
                "include_example_aib": True,
            },
        },
    },
)

fuchsia_product(
    name = "main_image",
    board_config = ":board_config",
    platform_artifacts = "//build/bazel/assembly/assembly_input_bundles:platform_user",
    product_config = ":product_config",
)

fuchsia_product_bundle(
    name = "product_bundle",
    testonly = True,
    main = ":main_image",
    product_bundle_name = "scrutiny-structured-config-test",
    repository_keys = "//src/sys/pkg/repositories/devhost/keys:keys",
    update_epoch = "1",
)
