# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")
load("//build/bazel/rules/host:defs.bzl", "go_binary_host_tool")
load("//build/bazel/rules/host_tests:host_go_test.bzl", "host_go_test")

package(default_applicable_licenses = ["//:license"])

go_library(
    name = "main",
    srcs = [
        "cmd/batch_runner.go",
        "cmd/main.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/debug/generate_breakpad/cmd",
    target_compatible_with = HOST_CONSTRAINTS,
    deps = [
        "//tools/debug/elflib",
        "//tools/lib/color",
        "//tools/lib/logger",
        "//tools/lib/osmisc",
        "//tools/lib/subprocess",
    ],
)

go_binary_host_tool(
    name = "generate_breakpad",
    embed = [":main"],
    target_compatible_with = HOST_CONSTRAINTS,
)

host_go_test(
    name = "generate_breakpad_tests",
    srcs = [
        "cmd/batch_runner_test.go",
    ],
    embed = [":main"],
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//tools:__pkg__"],
    deps = [
        "//tools/lib/subprocess",
    ],
)
