# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")
load("//build/bazel/rules/host:defs.bzl", "go_binary_host_tool")
load("//build/bazel/rules/host_tests:host_go_test.bzl", "host_go_test")

package(default_applicable_licenses = ["//:license"])

go_library(
    name = "clippy_reporter_lib",
    srcs = [
        "main.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/staticanalysis/clippy-reporter",
    target_compatible_with = HOST_CONSTRAINTS,
    deps = [
        "//third_party/golibs:golang.org/x/exp/maps",
        "//tools/build",
        "//tools/lib/jsonutil",
        "//tools/lib/logger",
        "//tools/staticanalysis",
    ],
)

go_binary_host_tool(
    name = "clippy-reporter",
    embed = [":clippy_reporter_lib"],
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//visibility:public"],
)

host_go_test(
    name = "clippy_reporter_tests",
    srcs = [
        "main_test.go",
    ],
    embed = [":clippy_reporter_lib"],
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//tools:__pkg__"],
    deps = [
        "//third_party/golibs:github.com/google/go-cmp/cmp",
        "//third_party/golibs:github.com/google/go-cmp/cmp/cmpopts",
        "//tools/build",
        "//tools/staticanalysis",
    ],
)
