import abc

from _typeshed import Incomplete
from mobly.controllers.android_device_lib import (
    callback_handler as callback_handler,
)
from mobly.snippet import errors as errors

UNKNOWN_UID: int
Error = errors.Error
AppStartError = errors.ServerStartError
AppRestoreConnectionError = errors.ServerRestoreConnectionError
ApiError = errors.ApiError
ProtocolError = errors.ProtocolError

class JsonRpcCommand:
    INIT: str
    CONTINUE: str

class JsonRpcClientBase(abc.ABC):
    host_port: Incomplete
    device_port: Incomplete
    app_name: Incomplete
    log: Incomplete
    uid: Incomplete
    verbose_logging: bool
    def __init__(self, app_name, ad) -> None: ...
    def __del__(self) -> None: ...
    def start_app_and_connect(self) -> None: ...
    def stop_app(self) -> None: ...
    def restore_app_connection(self, port: Incomplete | None = ...) -> None: ...
    def connect(self, uid=..., cmd=...) -> None: ...
    def disconnect(self) -> None: ...
    def close_socket_connection(self) -> None: ...
    def clear_host_port(self) -> None: ...
    def disable_hidden_api_blacklist(self) -> None: ...
    def __getattr__(self, name): ...
    def set_snippet_client_verbose_logging(self, verbose) -> None: ...
