# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")
load("//build/bazel/rules/host_tests:host_go_test.bzl", "host_go_test")
load("//build/bazel/rules/host_tests:host_test_data.bzl", "host_test_data_files")

package(default_applicable_licenses = ["//:license"])

go_library(
    name = "mixer",
    srcs = [
        "mixer.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/fidl/gidl/lib/mixer",
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = [
        "//tools/fidl/gidl:__subpackages__",
    ],
    deps = [
        "//tools/fidl/gidl/lib/ir",
        "//tools/fidl/lib/fidlgen",
    ],
)

host_test_data_files(
    name = "mixer_testdata",
    testonly = True,
    srcs = ["//tools/fidl/gidl/lib/mixer/testdata:test.mixer"],
    dest_dir = "testdata",
)

host_go_test(
    name = "gidl_mixer_tests",
    srcs = ["mixer_test.go"],
    embed = [":mixer"],
    target_compatible_with = HOST_CONSTRAINTS,
    test_args = ["-test_data_dir=testdata"],
    test_data = [":mixer_testdata"],
    visibility = ["//tools:__pkg__"],
)
