#!/bin/bash
# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Build
### Remove the published repsitory in amber-files/ and perform a full build.
### If the build was successfully completed before, this boils down to merely publish the build
### artifacts of the completed build to the repository.

set -e

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
fx-config-read

rm -rf "${FUCHSIA_BUILD_DIR}"/amber-files/keys "${FUCHSIA_BUILD_DIR}"/amber-files/repository
fx-command-run build
