# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "bitflags-serde-legacy",
    srcs = ["src/lib.rs"],
    crate_name = "bitflags_serde_legacy",
    edition = "2024",
    test_deps = [
        "//third_party/rust_crates/vendor:bitflags",
        "//third_party/rust_crates/vendor:ciborium",
        "//third_party/rust_crates/vendor:serde",
        "//third_party/rust_crates/vendor:serde_json",
    ],
    visibility = [
        "//src/settings/display:__pkg__",
        "//src/settings/input:__pkg__",
        "//src/settings/setup:__pkg__",
        "//src/sys/lib/bitflags-serde-legacy:__pkg__",
        "//src/sys/lib/cm_rust:__pkg__",
        "//visibility:private",
    ],
    with_unit_tests = True,
)
