# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "injectable-time",
    srcs = [
        "src/injectable_time.rs",
        "src/lib.rs",
    ],
    crate_name = "injectable_time",
    edition = "2024",
    visibility = ["//:__subpackages__"],
    with_unit_tests = True,
    deps = [
        "//src/lib/fuchsia-sync",
        "//third_party/rust_crates/vendor:chrono",
    ] + select({
        "@platforms//os:fuchsia": [
            "//sdk/rust/zx",
        ],
        "//conditions:default": [],
    }),
)
