# Copyright 2024 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/cpp/library_headers.gni")
import("//zircon/kernel/kernel_rust_mod.gni")

library_headers("headers") {
  headers = [
    "dev/power/moonflower/init.h",
    "dev/power/moonflower/moonflower_ffi.h",
  ]
}

kernel_rust_mod("moonflower-rs") {
  output_name = "power_moonflower"
  source_root = "moonflower.rs"
  sources = [ "moonflower.rs" ]
  deps = [
    "//sdk/rust/zx-status",
    "//src/lib/regio",
    "//zircon/kernel/lib/debug",
  ]
  test_deps = [ "//zircon/kernel/lib/unittest:unittest-rs" ]
}

source_set("moonflower") {
  sources = [ "moonflower_ffi.cc" ]
  public_deps = [ ":headers" ]
  deps = [
    ":moonflower-rs",
    "//zircon/kernel/dev/pdev/power",
    "//zircon/kernel/dev/psci",
    "//zircon/kernel/lib/arch",
    "//zircon/kernel/lib/counters",
    "//zircon/kernel/lib/debuglog",
    "//zircon/kernel/lib/init",
    "//zircon/kernel/lib/power-management",
    "//zircon/kernel/phys:handoff",
    "//zircon/system/ulib/ddk-platform-defs",
  ]
}
