# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/fidl/fidl.gni")

visibility = [ "//src/developer/forensics/*" ]

fidl("fuchsia.feedback.internal") {
  sources = [ "system_log_recorder.fidl" ]

  public_deps = [ "//zircon/vdso/zx" ]
}
