# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "cm_types",
    srcs = ["src/lib.rs"],
    crate_name = "cm_types",
    edition = "2024",
    test_deps = [
        "//third_party/rust_crates/vendor:assert_matches",
        "//third_party/rust_crates/vendor:serde_json",
    ],
    visibility = ["//:__subpackages__"],
    with_unit_tests = True,
    deps = [
        "//sdk/fidl/fuchsia.component.decl:fuchsia.component.decl_rust",
        "//sdk/fidl/fuchsia.io:fuchsia.io_rust",
        "//src/lib/fidl/rust/fidl",
        "//src/storage/lib/vfs/rust/name",
        "//third_party/rust_crates/vendor:flyweights",
        "//third_party/rust_crates/vendor:serde",
        "//third_party/rust_crates/vendor:thiserror",
        "//third_party/rust_crates/vendor:url",
    ] + select({
        "@platforms//os:fuchsia": [
            "//src/lib/fuchsia-runtime",
        ],
        "//conditions:default": [],
    }),
)
