from _typeshed import Incomplete
from mobly import utils as utils

ADB: str
ADB_PORT_LOCK: Incomplete
ADB_ROOT_RETRY_ATTMEPTS: int
ADB_ROOT_RETRY_ATTEMPT_INTERVAL_SEC: int
DEFAULT_INSTRUMENTATION_RUNNER: str
DEFAULT_GETPROP_TIMEOUT_SEC: int
DEFAULT_GETPROPS_ATTEMPTS: int
DEFAULT_GETPROPS_RETRY_SLEEP_SEC: int
PATTERN_ADB_CONNECT_SUCCESS: Incomplete

class Error(Exception): ...

class AdbError(Error):
    cmd: Incomplete
    stdout: Incomplete
    stderr: Incomplete
    ret_code: Incomplete
    serial: Incomplete
    def __init__(
        self, cmd, stdout, stderr, ret_code, serial: str = ...
    ) -> None: ...

class AdbTimeoutError(Error):
    cmd: Incomplete
    timeout: Incomplete
    serial: Incomplete
    def __init__(self, cmd, timeout, serial: str = ...) -> None: ...

def is_adb_available(): ...
def list_occupied_adb_ports(): ...

class AdbProxy:
    serial: Incomplete
    def __init__(self, serial: str = ...) -> None: ...
    @property
    def current_user_id(self) -> int: ...
    def connect(self, address) -> bytes: ...
    def getprop(self, prop_name): ...
    def getprops(self, prop_names): ...
    def has_shell_command(self, command) -> bool: ...
    def forward(
        self, args: Incomplete | None = ..., shell: bool = ...
    ) -> bytes: ...
    def instrument(
        self,
        package,
        options: Incomplete | None = ...,
        runner: Incomplete | None = ...,
        handler: Incomplete | None = ...,
    ) -> bytes: ...
    def root(self) -> bytes: ...
    def __getattr__(self, name): ...
