from _typeshed import Incomplete

class EventDispatcherError(Exception): ...
class IllegalStateError(EventDispatcherError): ...
class DuplicateError(EventDispatcherError): ...

class EventDispatcher:
    DEFAULT_TIMEOUT: int
    started: bool
    executor: Incomplete
    poller: Incomplete
    event_dict: Incomplete
    handlers: Incomplete
    lock: Incomplete
    def __init__(self, sl4a) -> None: ...
    def poll_events(self) -> None: ...
    def register_handler(self, handler, event_name, args) -> None: ...
    def start(self) -> None: ...
    def clean_up(self) -> None: ...
    def pop_event(self, event_name, timeout=...): ...
    def wait_for_event(
        self, event_name, predicate, timeout=..., *args, **kwargs
    ): ...
    def pop_events(self, regex_pattern, timeout): ...
    def get_event_q(self, event_name): ...
    def handle_subscribed_event(self, event_obj, event_name) -> None: ...
    def handle_event(
        self,
        event_handler,
        event_name,
        user_args,
        event_timeout: Incomplete | None = ...,
        cond: Incomplete | None = ...,
        cond_timeout: Incomplete | None = ...,
    ): ...
    def pop_all(self, event_name): ...
    def clear_events(self, event_name) -> None: ...
    def clear_all_events(self) -> None: ...
