from _typeshed import Incomplete

def exe_cmd(*cmds): ...

class FastbootProxy:
    serial: Incomplete
    fastboot_str: Incomplete
    def __init__(self, serial: str = ...) -> None: ...
    def args(self, *args): ...
    def __getattr__(self, name): ...
