from _typeshed import Incomplete
from mobly.controllers import android_device as android_device

class Error(Exception): ...

class JsonRpcShellBase:
    def load_device(self, serial: Incomplete | None = ...) -> None: ...
    def start_console(self) -> None: ...
    def main(self, serial: Incomplete | None = ...) -> None: ...
