from _typeshed import Incomplete
from mobly import expects as expects
from mobly.controllers.android_device_lib import errors as errors
from mobly.controllers.android_device_lib.services import (
    base_service as base_service,
)

class Error(errors.DeviceError): ...

class ServiceManager:
    def __init__(self, device) -> None: ...
    def has_service_by_name(self, name): ...
    @property
    def is_any_alive(self): ...
    def register(
        self,
        alias,
        service_class,
        configs: Incomplete | None = ...,
        start_service: bool = ...,
    ) -> None: ...
    def unregister(self, alias) -> None: ...
    def for_each(self, func) -> None: ...
    def list_live_services(self): ...
    def create_output_excerpts_all(self, test_info): ...
    def unregister_all(self) -> None: ...
    def start_all(self) -> None: ...
    def start_services(self, service_alises) -> None: ...
    def stop_all(self) -> None: ...
    def pause_all(self) -> None: ...
    def resume_all(self) -> None: ...
    def resume_services(self, service_alises) -> None: ...
    def __getattr__(self, name): ...
