import enum

from _typeshed import Incomplete
from mobly import utils as utils
from mobly.controllers.android_device_lib import adb as adb
from mobly.controllers.android_device_lib import (
    callback_handler_v2 as callback_handler_v2,
)
from mobly.snippet import client_base as client_base
from mobly.snippet import errors as errors

UNKNOWN_UID: int

class ConnectionHandshakeCommand(enum.Enum):
    INIT: str
    CONTINUE: str

class SnippetClientV2(client_base.ClientBase):
    host_port: Incomplete
    device_port: Incomplete
    uid: Incomplete
    def __init__(self, package, ad) -> None: ...
    @property
    def user_id(self): ...
    @property
    def is_alive(self): ...
    def before_starting_server(self) -> None: ...
    def start_server(self) -> None: ...
    def make_connection(self) -> None: ...
    def create_socket_connection(self) -> None: ...
    def send_handshake_request(self, uid=..., cmd=...) -> None: ...
    def check_server_proc_running(self) -> None: ...
    def send_rpc_request(self, request): ...
    def handle_callback(self, callback_id, ret_value, rpc_func_name): ...
    def make_connection_with_forwarded_port(
        self, host_port, device_port, uid=..., cmd=...
    ) -> None: ...
    def stop(self) -> None: ...
    def close_connection(self) -> None: ...
    def restore_server_connection(
        self, port: Incomplete | None = ...
    ) -> None: ...
    def help(self, print_output: bool = ...): ...
