# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/components.gni")
import("//build/rust/rustc_test.gni")

# Defines a SPI system test package.
#
# Parameters
#
#   bus_addresses (required)
#     [list of strings] The addresses of the SPI buses to target.
#
#   min_expected_throughput_bytes_per_second (required)
#     [list of ints] The minimum expected SPI throughput for each bus in bytes per second. These
#     values should come with a comment explaining where they came from or how they were chosen.
#     Must match the length of bus_addresses.
#
#   max_expected_latency_nanoseconds (required)
#     [list of ints] The maximum expected SPI latency for each bus in nanoseconds. These values
#     should come with a comment explaining where they came from or how they were chosen.
#     Must match the length of bus_addresses.
#
#   test_specs (required)
#     [scope] Test specifications.
#
template("spi_system_test") {
  assert(defined(invoker.bus_addresses), "bus_addresses must be defined")
  assert(defined(invoker.min_expected_throughput_bytes_per_second),
         "min_expected_throughput_bytes_per_second must be defined")
  assert(defined(invoker.max_expected_latency_nanoseconds),
         "max_expected_latency_nanoseconds must be defined")
  assert(defined(invoker.test_specs), "test_specs must be defined")

  _manifest_target = "${target_name}_manifest"
  _config_lib_target = "${target_name}_config_lib"
  _bin_target = "${target_name}_bin"
  _component_target = "${target_name}_component"
  _config_values_target = "${target_name}_config_values"
  _package_target = target_name

  fuchsia_component_manifest(_manifest_target) {
    testonly = true
    manifest =
        "//src/devices/spi/tests/spi-system-test/meta/spi-system-test.cml"
  }

  fuchsia_structured_config_rust_lib(_config_lib_target) {
    testonly = true
    cm_label = ":$_manifest_target"
    name = "spi_system_test_config"
  }

  rustc_test(_bin_target) {
    output_name = "spi_system_test"
    edition = "2024"
    source_root = "//src/devices/spi/tests/spi-system-test/src/lib.rs"
    sources = [ "//src/devices/spi/tests/spi-system-test/src/lib.rs" ]
    deps = [
      ":$_config_lib_target",
      "//sdk/fidl/fuchsia.driver.framework:fuchsia.driver.framework_rust",
      "//sdk/fidl/fuchsia.driver.token:fuchsia.driver.token_rust",
      "//sdk/fidl/fuchsia.hardware.sharedmemory:fuchsia.hardware.sharedmemory_rust",
      "//sdk/fidl/fuchsia.hardware.spi:fuchsia.hardware.spi_rust",
      "//sdk/fidl/fuchsia.mem:fuchsia.mem_rust",
      "//sdk/rust/zx",
      "//src/lib/fidl/rust/fidl",
      "//src/lib/fuchsia",
      "//src/lib/fuchsia-component",
      "//src/lib/fuchsia-fs",
      "//third_party/rust_crates:anyhow",
      "//third_party/rust_crates:futures",
      "//third_party/rust_crates:rand",
    ]
  }

  fuchsia_test_component(_component_target) {
    cm_label = ":$_manifest_target"
    deps = [ ":$_bin_target" ]
    test_type = "driver_system"
  }

  fuchsia_structured_config_values(_config_values_target) {
    testonly = true
    cm_label = ":$_manifest_target"
    values = {
      bus_addresses = invoker.bus_addresses
      min_expected_throughput_bytes_per_second =
          invoker.min_expected_throughput_bytes_per_second
      max_expected_latency_nanoseconds =
          invoker.max_expected_latency_nanoseconds
    }
  }

  fuchsia_test_package(_package_target) {
    test_components = [ ":$_component_target" ]
    deps = [ ":$_config_values_target" ]
    test_specs = invoker.test_specs
  }
}
