#!/bin/bash
# Copyright 2025 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Developer Tools
###  generates a .watchmanconfig file for use with jj
## This command is based off the .gitignore file and generates a .watchmanconfig
## file suitable for use with the `jj` vcs software.

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?
fx-config-read

cat > "${FUCHSIA_DIR}/.watchmanconfig" <<EOT
{
  "ignore_dirs": [
    "out",
    "bazel-bin",
    "bazel-out",
    "bazel-repos",
    "bazel-workspace",
    "vendor",
    "tmp",
    ".jiri",
    ".jiri_root",
    "local",
    "prebuilt",
    "test_data",
    "integration"
  ]
}
EOT
