#!/bin/bash
# Copyright 2025 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Run, inspect and debug
### Provides a shortcut to the prebuilt Clang / LLVM tools

## usage: fx llvm [tool] [args...]
##
##    -h|--help     Shows this help and lists all available Clang / LLVM tools

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/toolchain.sh || exit $?

readonly -a TOOLCHAIN_PREFIXES=("" "llvm-")
readonly -a TOOLCHAIN_PATHS=("${PREBUILT_CLANG_DIR}/bin")

exec_toolchain_tool "$@"
