# Copyright 2021 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/host.gni")

if (current_toolchain == default_toolchain) {
  gn_project_json_file = "${root_build_dir}/project.json"

  # An action that pretends to create gn_desc.json. Dependents will be
  # re-run when this file is regenerated, which will happen when the regenerator
  # is invoked.
  action("gn_project_json") {
    script = "//build/scripts/no_op.sh"
    outputs = [ gn_project_json_file ]
    args = rebase_path(outputs, root_build_dir)
  }
}

if (is_host) {
  # The default target adds the tool and the generation of the `gn_desc.json`
  # file to the build graph.
  group("gn_desc") {
    testonly = true
    deps = [
      ":gn_project_json($default_toolchain)",
      ":install_gn_desc($host_toolchain)",
    ]
  }

  # This makes the binary available to fx. It also lists the gn_desc.json target
  # as a dependency so that if the tool is installed, then `gn desc` is always
  # run and a file available for it to use.
  install_host_tools("install_gn_desc") {
    testonly = true
    deps = [
      ":gn_project_json($default_toolchain)",
      "bin:gn_desc",
    ]
    outputs = [ "gn_desc" ]
  }

  # All the tests.
  group("host_tests") {
    testonly = true
    deps = [
      "bin:tests",
      "gn_graph:tests",
      "gn_json:tests",
      "tests",
    ]
  }
}
