# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bazel/bazel_inputs.gni")
import("//build/rust/rustc_binary.gni")

if (is_host) {
  rustc_binary("bin") {
    edition = "2024"
    output_name = "dmlc"
    source_root = "src/main.rs"
    with_unit_tests = true
    sources = [
      "src/bind_generator.rs",
      "src/board_compiler.rs",
      "src/cml_generator.rs",
      "src/cpp_generator.rs",
      "src/driver_compiler.rs",
      "src/main.rs",
      "src/parser.rs",
      "src/rust_generator.rs",
      "src/workarounds.rs",
    ]
    deps = [
      "//sdk/fidl/fuchsia.driver.metadata:fuchsia.driver.metadata_rust",
      "//src/devices/board/lib/dml-config",
      "//src/lib/fidl/rust/fidl",
      "//third_party/rust_crates:anyhow",
      "//third_party/rust_crates:argh",
      "//third_party/rust_crates:chrono",
      "//third_party/rust_crates:serde",
      "//third_party/rust_crates:serde_json",
      "//third_party/rust_crates:serde_json5",
    ]
  }

  rustc_binary("decode_config") {
    edition = "2024"
    source_root = "src/decode_config.rs"
    sources = [ "src/decode_config.rs" ]
    deps = [
      "//sdk/fidl/fuchsia.driver.metadata:fuchsia.driver.metadata_rust",
      "//src/devices/board/lib/dml-config",
      "//src/lib/fidl/rust/fidl",
      "//third_party/rust_crates:anyhow",
    ]
  }

  bazel_input_file("bazel_input") {
    generator = ":bin"
    outputs = [ "${root_out_dir}/dmlc" ]
    gn_targets_name = "dmlc"
  }
} else {
  group("bazel_input") {
    public_deps = [ ":bazel_input($host_toolchain)" ]
  }
}

group("dmlc") {
  deps = [
    ":bin($host_toolchain)",
    ":decode_config($host_toolchain)",
  ]
}

group("tests") {
  testonly = true
  deps = [ ":bin_test($host_toolchain)" ]
}
