# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
[build]
target = ["x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "thumbv7em-none-eabihf"]

# A bit awkward but when we run the build manually with cargo, we need to have it fetch dependencies
# normally from crates.io or we will have too many issues trying to coexist with Fuchsia
#
# Actual Fuchsia builds will still use vendored dependencies only since it won't run any cargo commands
#
# This is only used for verifying that our project is actually no_std-compatible
[source.crates-io]
replace-with = "bypassed-crates-io"

[source.bypassed-crates-io]
registry = "https://github.com/rust-lang/crates.io-index?unique=1"
