# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# A forwarding target to the Bazel-built undercoat host tool for infra/builders
# that request "//tools/fuzz".
group("fuzz") {
  deps = [ "//build/bazel/host:bazel_root_host_tools.undercoat.host_tool($host_toolchain)" ]
}
