# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bazel/bazel_host_tool.gni")

if (is_host) {
  bazel_host_tool("undercoat") {
    bazel_target = ":undercoat"
    bazel_output_path = "{{BAZEL_TARGET_OUT_DIR}}/undercoat_/undercoat"
    install_host_tool = true
  }
}

# A forwarding target to the Bazel-built undercoat host tool for infra/builders
# that request "//tools/fuzz".
group("fuzz") {
  deps = [ ":undercoat($host_toolchain)" ]
}
