# Copyright 2019 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/cpp/library_headers.gni")
import("//zircon/kernel/kernel_rust_mod.gni")

library_headers("headers") {
  headers = [ "pdev/interrupt.h" ]

  public_deps = [
    # <pdev/interrupt.h> has #include <dev/interrupt.h>.
    "//zircon/kernel/dev/interrupt:headers",
  ]
}

kernel_rust_mod("interrupt-rs") {
  output_name = "pdev_interrupt"
  source_root = "interrupt.rs"
  sources = [
    "console.rs",
    "interrupt.rs",
  ]
  deps = [
    "//sdk/rust/zx-status",
    "//src/lib/ksync",
    "//third_party/rust_crates:pin-init",
    "//zircon/kernel/dev/interrupt:dev_interrupt",
    "//zircon/kernel/lib/debug",
  ]
  test_deps = [ "//zircon/kernel/lib/unittest:unittest-rs" ]
}

source_set("interrupt") {
  public_deps = [ ":headers" ]
  deps = [ ":interrupt-rs" ]
}
