# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bind/bind.gni")
import("//build/components.gni")
import("//build/drivers.gni")

fuchsia_driver_dml("uart-dml") {
  dml = "meta/uart.dml"
  driver_name = "uart"
  golden_cml = "meta/uart.cml"
  golden_bind = "meta/uart.bind"
}

driver_bind_rules("bt_transport_uart_rust_bind") {
  dml_label = ":uart-dml"
  bind_output = "bt-transport-uart-rust.bindbc"
  tests = "meta/bind_tests.json"
  deps = [
    "//src/devices/bind/fuchsia",
    "//src/devices/bind/fuchsia.serial",
  ]
}

fuchsia_component_manifest("bt-transport-uart-rust-manifest") {
  component_name = "bt-transport-uart-rust"
  manifest = "meta/uart.cml"
}

fuchsia_structured_config_rust_lib("bt-transport-uart-rust-config") {
  cm_label = ":bt-transport-uart-rust-manifest"
}

fuchsia_rust_driver("bt-transport-uart-rust-driver") {
  edition = "2024"
  with_unit_tests = true
  output_name = "bt-transport-uart-rust"

  configs += [ "//build/config/rust/lints:clippy_warn_all" ]

  sources = [ "src/lib.rs" ]

  deps = [
    ":bt-transport-uart-rust-config",
    "//sdk/lib/driver/component/rust",
    "//src/lib/fuchsia-async",
    "//third_party/rust_crates:log",
  ]

  test_deps = [ "//src/lib/fuchsia" ]
}

fuchsia_driver_component("bt-transport-uart-rust") {
  cm_label = ":bt-transport-uart-rust-manifest"
  info = "meta/bt-transport-uart-info.json"
  deps = [
    ":bt-transport-uart-rust-driver",
    ":bt_transport_uart_rust_bind",
  ]
}

fuchsia_driver_package("uart-rust") {
  package_name = "bt-transport-uart-rust"
  driver_components = [ ":bt-transport-uart-rust" ]
}

fuchsia_unittest_package("bt-transport-uart-rust-tests") {
  deps = [ ":bt-transport-uart-rust-driver_test" ]
}

group("tests") {
  testonly = true
  deps = [
    ":bt-transport-uart-rust-tests",
    ":bt_transport_uart_rust_bind_test",
  ]
}
