# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

visibility(["//build/bazel/rules/idk/private"])

"""Lists of FIDL libraries in each category.

For information on categories, see
https://fuchsia.dev/fuchsia-src/contribute/sdk/categories.
"""

# Stable FIDL libraries in the partner category.
# All are included in the IDK.
# LINT.IfChange(partner_libraries)
PARTNER_IDK_STABLE_FIDL_LIBRARY_ATOMS_LIST = [
    # buildifier: keep sorted
    "//sdk/fidl/fuchsia.accessibility.gesture:fuchsia.accessibility.gesture_idk",
    "//sdk/fidl/fuchsia.accessibility.semantics:fuchsia.accessibility.semantics_idk",
    "//sdk/fidl/fuchsia.accessibility.tts:fuchsia.accessibility.tts_idk",
    "//sdk/fidl/fuchsia.accessibility.virtualkeyboard:fuchsia.accessibility.virtualkeyboard_idk",
    "//sdk/fidl/fuchsia.audio.effects:fuchsia.audio.effects_idk",
    "//sdk/fidl/fuchsia.auth:fuchsia.auth_idk",
    "//sdk/fidl/fuchsia.auth.oldtokens:fuchsia.auth.oldtokens_idk",
    "//sdk/fidl/fuchsia.bluetooth.a2dp:fuchsia.bluetooth.a2dp_idk",
    "//sdk/fidl/fuchsia.bluetooth.bredr:fuchsia.bluetooth.bredr_idk",
    "//sdk/fidl/fuchsia.bluetooth.fastpair:fuchsia.bluetooth.fastpair_idk",
    "//sdk/fidl/fuchsia.bluetooth:fuchsia.bluetooth_idk",
    "//sdk/fidl/fuchsia.bluetooth.gatt:fuchsia.bluetooth.gatt_idk",
    "//sdk/fidl/fuchsia.bluetooth.gatt2:fuchsia.bluetooth.gatt2_idk",
    "//sdk/fidl/fuchsia.bluetooth.hfp:fuchsia.bluetooth.hfp_idk",
    "//sdk/fidl/fuchsia.bluetooth.host:fuchsia.bluetooth.host_idk",
    "//sdk/fidl/fuchsia.bluetooth.le:fuchsia.bluetooth.le_idk",
    "//sdk/fidl/fuchsia.bluetooth.sys:fuchsia.bluetooth.sys_idk",
    "//sdk/fidl/fuchsia.bluetooth.test:fuchsia.bluetooth.test_idk",
    "//sdk/fidl/fuchsia.buildinfo:fuchsia.buildinfo_idk",
    "//sdk/fidl/fuchsia.buildinfo.test:fuchsia.buildinfo.test_idk",
    "//sdk/fidl/fuchsia.camera:fuchsia.camera_idk",
    "//sdk/fidl/fuchsia.camera2:fuchsia.camera2_idk",
    "//sdk/fidl/fuchsia.camera2.hal:fuchsia.camera2.hal_idk",
    "//sdk/fidl/fuchsia.camera3:fuchsia.camera3_idk",
    "//sdk/fidl/fuchsia.castauth:fuchsia.castauth_idk",
    "//sdk/fidl/fuchsia.castconfig:fuchsia.castconfig_idk",
    "//sdk/fidl/fuchsia.castremotecontrol:fuchsia.castremotecontrol_idk",
    "//sdk/fidl/fuchsia.castsetup:fuchsia.castsetup_idk",
    "//sdk/fidl/fuchsia.castsysteminfo:fuchsia.castsysteminfo_idk",
    "//sdk/fidl/fuchsia.castwindow:fuchsia.castwindow_idk",
    "//sdk/fidl/fuchsia.component.decl:fuchsia.component.decl_idk",
    "//sdk/fidl/fuchsia.component:fuchsia.component_idk",
    "//sdk/fidl/fuchsia.component.resolution:fuchsia.component.resolution_idk",
    "//sdk/fidl/fuchsia.component.runner:fuchsia.component.runner_idk",
    "//sdk/fidl/fuchsia.component.runtime:fuchsia.component.runtime_idk",
    "//sdk/fidl/fuchsia.component.sandbox:fuchsia.component.sandbox_idk",
    "//sdk/fidl/fuchsia.component.test:fuchsia.component.test_idk",
    "//sdk/fidl/fuchsia.data:fuchsia.data_idk",
    "//sdk/fidl/fuchsia.debugdata:fuchsia.debugdata_idk",
    "//sdk/fidl/fuchsia.developer.tiles:fuchsia.developer.tiles_idk",
    "//sdk/fidl/fuchsia.device.fs:fuchsia.device.fs_idk",
    "//sdk/fidl/fuchsia.diagnostics:fuchsia.diagnostics_idk",
    "//sdk/fidl/fuchsia.diagnostics.system:fuchsia.diagnostics.system_idk",
    "//sdk/fidl/fuchsia.diagnostics.types:fuchsia.diagnostics.types_idk",
    "//sdk/fidl/fuchsia.driver.development:fuchsia.driver.development_idk",
    "//sdk/fidl/fuchsia.driver.framework:fuchsia.driver.framework_idk",
    "//sdk/fidl/fuchsia.driver.registrar:fuchsia.driver.registrar_idk",
    "//sdk/fidl/fuchsia.driver.test:fuchsia.driver.test_idk",
    "//sdk/fidl/fuchsia.element:fuchsia.element_idk",
    "//sdk/fidl/fuchsia.factory:fuchsia.factory_idk",
    "//sdk/fidl/fuchsia.factory.wlan:fuchsia.factory.wlan_idk",
    "//sdk/fidl/fuchsia.feedback:fuchsia.feedback_idk",
    "//sdk/fidl/fuchsia.fonts:fuchsia.fonts_idk",
    "//sdk/fidl/fuchsia.gpu.agis:fuchsia.gpu.agis_idk",
    "//sdk/fidl/fuchsia.gpu.magma:fuchsia.gpu.magma_idk",
    "//sdk/fidl/fuchsia.hardware.adc:fuchsia.hardware.adc_idk",
    "//sdk/fidl/fuchsia.hardware.audio:fuchsia.hardware.audio_idk",
    "//sdk/fidl/fuchsia.hardware.audio.signalprocessing:fuchsia.hardware.audio.signalprocessing_idk",
    "//sdk/fidl/fuchsia.hardware.bluetooth:fuchsia.hardware.bluetooth_idk",
    "//sdk/fidl/fuchsia.hardware.clock:fuchsia.hardware.clock_idk",
    "//sdk/fidl/fuchsia.hardware.clockimpl:fuchsia.hardware.clockimpl_idk",
    "//sdk/fidl/fuchsia.hardware.gpio:fuchsia.hardware.gpio_idk",
    "//sdk/fidl/fuchsia.hardware.i2c:fuchsia.hardware.i2c_idk",
    "//sdk/fidl/fuchsia.hardware.light:fuchsia.hardware.light_idk",
    "//sdk/fidl/fuchsia.hardware.network:fuchsia.hardware.network_idk",
    "//sdk/fidl/fuchsia.hardware.pci:fuchsia.hardware.pci_idk",
    "//sdk/fidl/fuchsia.hardware.pin:fuchsia.hardware.pin_idk",
    "//sdk/fidl/fuchsia.hardware.pinimpl:fuchsia.hardware.pinimpl_idk",
    "//sdk/fidl/fuchsia.hardware.platform.device:fuchsia.hardware.platform.device_idk",
    "//sdk/fidl/fuchsia.hardware.power.sensor:fuchsia.hardware.power.sensor_idk",
    "//sdk/fidl/fuchsia.hardware.power.statecontrol:fuchsia.hardware.power.statecontrol_idk",
    "//sdk/fidl/fuchsia.hardware.radar:fuchsia.hardware.radar_idk",
    "//sdk/fidl/fuchsia.hardware.rtc:fuchsia.hardware.rtc_idk",
    "//sdk/fidl/fuchsia.hardware.temperature:fuchsia.hardware.temperature_idk",
    "//sdk/fidl/fuchsia.hwinfo:fuchsia.hwinfo_idk",
    "//sdk/fidl/fuchsia.images:fuchsia.images_idk",
    "//sdk/fidl/fuchsia.images2:fuchsia.images2_idk",
    "//sdk/fidl/fuchsia.input:fuchsia.input_idk",
    "//sdk/fidl/fuchsia.input.report:fuchsia.input.report_idk",
    "//sdk/fidl/fuchsia.input.virtualkeyboard:fuchsia.input.virtualkeyboard_idk",
    "//sdk/fidl/fuchsia.inspect:fuchsia.inspect_idk",
    "//sdk/fidl/fuchsia.intl:fuchsia.intl_idk",
    "//sdk/fidl/fuchsia.io:fuchsia.io_idk",
    "//sdk/fidl/fuchsia.kernel:fuchsia.kernel_idk",
    "//sdk/fidl/fuchsia.ldsvc:fuchsia.ldsvc_idk",
    "//sdk/fidl/fuchsia.legacymetrics:fuchsia.legacymetrics_idk",
    "//sdk/fidl/fuchsia.lightsensor:fuchsia.lightsensor_idk",
    "//sdk/fidl/fuchsia.location:fuchsia.location_idk",
    "//sdk/fidl/fuchsia.location.namedplace:fuchsia.location.namedplace_idk",
    "//sdk/fidl/fuchsia.location.position:fuchsia.location.position_idk",
    "//sdk/fidl/fuchsia.location.sensor:fuchsia.location.sensor_idk",
    "//sdk/fidl/fuchsia.logger:fuchsia.logger_idk",
    "//sdk/fidl/fuchsia.lowpan.bootstrap:fuchsia.lowpan.bootstrap_idk",
    "//sdk/fidl/fuchsia.lowpan.device:fuchsia.lowpan.device_idk",
    "//sdk/fidl/fuchsia.lowpan:fuchsia.lowpan_idk",
    "//sdk/fidl/fuchsia.lowpan.thread:fuchsia.lowpan.thread_idk",
    "//sdk/fidl/fuchsia.math:fuchsia.math_idk",
    "//sdk/fidl/fuchsia.media.audio:fuchsia.media.audio_idk",
    "//sdk/fidl/fuchsia.media.drm:fuchsia.media.drm_idk",
    "//sdk/fidl/fuchsia.media:fuchsia.media_idk",
    "//sdk/fidl/fuchsia.media.playback:fuchsia.media.playback_idk",
    "//sdk/fidl/fuchsia.media.sessions2:fuchsia.media.sessions2_idk",
    "//sdk/fidl/fuchsia.media.sounds:fuchsia.media.sounds_idk",
    "//sdk/fidl/fuchsia.media.target:fuchsia.media.target_idk",
    "//sdk/fidl/fuchsia.mediacodec:fuchsia.mediacodec_idk",
    "//sdk/fidl/fuchsia.mediastreams:fuchsia.mediastreams_idk",
    "//sdk/fidl/fuchsia.mem:fuchsia.mem_idk",
    "//sdk/fidl/fuchsia.memorypressure:fuchsia.memorypressure_idk",
    "//sdk/fidl/fuchsia.metrics:fuchsia.metrics_idk",
    "//sdk/fidl/fuchsia.migration:fuchsia.migration_idk",
    "//sdk/fidl/fuchsia.net:fuchsia.net_idk",
    "//sdk/fidl/fuchsia.net.http:fuchsia.net.http_idk",
    "//sdk/fidl/fuchsia.net.interfaces:fuchsia.net.interfaces_idk",
    "//sdk/fidl/fuchsia.net.mdns:fuchsia.net.mdns_idk",
    "//sdk/fidl/fuchsia.net.reachability:fuchsia.net.reachability_idk",
    "//sdk/fidl/fuchsia.net.routes:fuchsia.net.routes_idk",
    "//sdk/fidl/fuchsia.net.stackmigrationdeprecated:fuchsia.net.stackmigrationdeprecated_idk",
    "//sdk/fidl/fuchsia.pkg.resolution:fuchsia.pkg.resolution_idk",
    "//sdk/fidl/fuchsia.power.clientlevel:fuchsia.power.clientlevel_idk",
    "//sdk/fidl/fuchsia.power:fuchsia.power_idk",
    "//sdk/fidl/fuchsia.power.profile:fuchsia.power.profile_idk",
    "//sdk/fidl/fuchsia.power.system:fuchsia.power.system_idk",
    "//sdk/fidl/fuchsia.power.systemmode:fuchsia.power.systemmode_idk",
    "//sdk/fidl/fuchsia.process:fuchsia.process_idk",
    "//sdk/fidl/fuchsia.process.lifecycle:fuchsia.process.lifecycle_idk",
    "//sdk/fidl/fuchsia.recovery:fuchsia.recovery_idk",
    "//sdk/fidl/fuchsia.recovery.ui:fuchsia.recovery.ui_idk",
    "//sdk/fidl/fuchsia.scenic.scheduling:fuchsia.scenic.scheduling_idk",
    "//sdk/fidl/fuchsia.scheduler:fuchsia.scheduler_idk",
    "//sdk/fidl/fuchsia.session:fuchsia.session_idk",
    "//sdk/fidl/fuchsia.settings:fuchsia.settings_idk",
    "//sdk/fidl/fuchsia.settings.policy:fuchsia.settings.policy_idk",
    "//sdk/fidl/fuchsia.storage.blobfs:fuchsia.storage.blobfs_idk",
    "//sdk/fidl/fuchsia.storage.ftl:fuchsia.storage.ftl_idk",
    "//sdk/fidl/fuchsia.sysinfo:fuchsia.sysinfo_idk",
    "//sdk/fidl/fuchsia.sysmem:fuchsia.sysmem_idk",
    "//sdk/fidl/fuchsia.sysmem2:fuchsia.sysmem2_idk",
    "//sdk/fidl/fuchsia.test:fuchsia.test_idk",
    "//sdk/fidl/fuchsia.thermal:fuchsia.thermal_idk",
    "//sdk/fidl/fuchsia.time.alarms:fuchsia.time.alarms_idk",
    "//sdk/fidl/fuchsia.tracing.controller:fuchsia.tracing.controller_idk",
    "//sdk/fidl/fuchsia.tracing:fuchsia.tracing_idk",
    "//sdk/fidl/fuchsia.tracing.perfetto:fuchsia.tracing.perfetto_idk",
    "//sdk/fidl/fuchsia.tracing.provider:fuchsia.tracing.provider_idk",
    "//sdk/fidl/fuchsia.ui.activity.control:fuchsia.ui.activity.control_idk",
    "//sdk/fidl/fuchsia.ui.activity:fuchsia.ui.activity_idk",
    "//sdk/fidl/fuchsia.ui.app:fuchsia.ui.app_idk",
    "//sdk/fidl/fuchsia.ui.brightness:fuchsia.ui.brightness_idk",
    "//sdk/fidl/fuchsia.ui.composition:fuchsia.ui.composition_idk",
    "//sdk/fidl/fuchsia.ui.display.singleton:fuchsia.ui.display.singleton_idk",
    "//sdk/fidl/fuchsia.ui.gfx:fuchsia.ui.gfx_idk",
    "//sdk/fidl/fuchsia.ui.input:fuchsia.ui.input_idk",
    "//sdk/fidl/fuchsia.ui.input3:fuchsia.ui.input3_idk",
    "//sdk/fidl/fuchsia.ui.observation.geometry:fuchsia.ui.observation.geometry_idk",
    "//sdk/fidl/fuchsia.ui.pointer:fuchsia.ui.pointer_idk",
    "//sdk/fidl/fuchsia.ui.pointerinjector:fuchsia.ui.pointerinjector_idk",
    "//sdk/fidl/fuchsia.ui.policy:fuchsia.ui.policy_idk",
    "//sdk/fidl/fuchsia.ui.scenic:fuchsia.ui.scenic_idk",
    "//sdk/fidl/fuchsia.ui.test.input:fuchsia.ui.test.input_idk",
    "//sdk/fidl/fuchsia.ui.test.scene:fuchsia.ui.test.scene_idk",
    "//sdk/fidl/fuchsia.ui.types:fuchsia.ui.types_idk",
    "//sdk/fidl/fuchsia.ui.views:fuchsia.ui.views_idk",
    "//sdk/fidl/fuchsia.ultrasound:fuchsia.ultrasound_idk",
    "//sdk/fidl/fuchsia.unknown:fuchsia.unknown_idk",
    "//sdk/fidl/fuchsia.update.channel:fuchsia.update.channel_idk",
    "//sdk/fidl/fuchsia.update.channelcontrol:fuchsia.update.channelcontrol_idk",
    "//sdk/fidl/fuchsia.update.config:fuchsia.update.config_idk",
    "//sdk/fidl/fuchsia.update:fuchsia.update_idk",
    "//sdk/fidl/fuchsia.url:fuchsia.url_idk",
    "//sdk/fidl/fuchsia.version:fuchsia.version_idk",
    "//sdk/fidl/fuchsia.weave:fuchsia.weave_idk",
    "//sdk/fidl/fuchsia.web:fuchsia.web_idk",
    "//sdk/fidl/fuchsia.wlan.common:fuchsia.wlan.common_idk",
    "//sdk/fidl/fuchsia.wlan.driver:fuchsia.wlan.driver_idk",
    "//sdk/fidl/fuchsia.wlan.ieee80211:fuchsia.wlan.ieee80211_idk",
    "//sdk/fidl/fuchsia.wlan.phyimpl:fuchsia.wlan.phyimpl_idk",
    "//sdk/fidl/fuchsia.wlan.policy:fuchsia.wlan.policy_idk",
    "//sdk/fidl/fuchsia.wlan.product.deprecatedclient:fuchsia.wlan.product.deprecatedclient_idk",
    "//sdk/fidl/fuchsia.wlan.product.deprecatedconfiguration:fuchsia.wlan.product.deprecatedconfiguration_idk",
    "//sdk/fidl/fuchsia.wlan.softmac:fuchsia.wlan.softmac_idk",
    "//zircon/vdso/zx:zx_idk",
]

# Unstable FIDL libraries in the partner category.
# All are included in the IDK.
PARTNER_IDK_UNSTABLE_FIDL_LIBRARY_ATOMS_LIST = [
    # buildifier: keep sorted
    "//sdk/fidl/fuchsia.boot.metadata:fuchsia.boot.metadata_idk",
    "//sdk/fidl/fuchsia.buttons:fuchsia.buttons_idk",
    "//sdk/fidl/fuchsia.driver.metadata:fuchsia.driver.metadata_idk",
    "//sdk/fidl/fuchsia.driver.token:fuchsia.driver.token_idk",
    "//sdk/fidl/fuchsia.hardware.adcimpl:fuchsia.hardware.adcimpl_idk",
    "//sdk/fidl/fuchsia.hardware.amlogic.metadata:fuchsia.hardware.amlogic.metadata_idk",
    "//sdk/fidl/fuchsia.hardware.block.volume:fuchsia.hardware.block.volume_idk",
    "//sdk/fidl/fuchsia.hardware.cpu.ctrl:fuchsia.hardware.cpu.ctrl_idk",
    "//sdk/fidl/fuchsia.hardware.gnss:fuchsia.hardware.gnss_idk",
    "//sdk/fidl/fuchsia.hardware.google.nanohub:fuchsia.hardware.google.nanohub_idk",
    "//sdk/fidl/fuchsia.hardware.haptics:fuchsia.hardware.haptics_idk",
    "//sdk/fidl/fuchsia.hardware.hrtimer:fuchsia.hardware.hrtimer_idk",
    "//sdk/fidl/fuchsia.hardware.i2c.businfo:fuchsia.hardware.i2c.businfo_idk",
    "//sdk/fidl/fuchsia.hardware.i2cimpl:fuchsia.hardware.i2cimpl_idk",
    "//sdk/fidl/fuchsia.hardware.inlineencryption:fuchsia.hardware.inlineencryption_idk",
    "//sdk/fidl/fuchsia.hardware.interconnect:fuchsia.hardware.interconnect_idk",
    "//sdk/fidl/fuchsia.hardware.mailbox:fuchsia.hardware.mailbox_idk",
    "//sdk/fidl/fuchsia.hardware.mediacodec:fuchsia.hardware.mediacodec_idk",
    "//sdk/fidl/fuchsia.hardware.network.driver:fuchsia.hardware.network.driver_idk",
    "//sdk/fidl/fuchsia.hardware.nfc:fuchsia.hardware.nfc_idk",
    "//sdk/fidl/fuchsia.hardware.platform.bus:fuchsia.hardware.platform.bus_idk",
    "//sdk/fidl/fuchsia.hardware.power.battery:fuchsia.hardware.power.battery_idk",
    "//sdk/fidl/fuchsia.hardware.power.charger:fuchsia.hardware.power.charger_idk",
    "//sdk/fidl/fuchsia.hardware.power:fuchsia.hardware.power_idk",
    "//sdk/fidl/fuchsia.hardware.power.source:fuchsia.hardware.power.source_idk",
    "//sdk/fidl/fuchsia.hardware.power.suspend:fuchsia.hardware.power.suspend_idk",
    "//sdk/fidl/fuchsia.hardware.power.usb:fuchsia.hardware.power.usb_idk",
    "//sdk/fidl/fuchsia.hardware.powerdomain:fuchsia.hardware.powerdomain_idk",
    "//sdk/fidl/fuchsia.hardware.qualcomm.fastrpc:fuchsia.hardware.qualcomm.fastrpc_idk",
    "//sdk/fidl/fuchsia.hardware.qualcomm.router:fuchsia.hardware.qualcomm.router_idk",
    "//sdk/fidl/fuchsia.hardware.registers:fuchsia.hardware.registers_idk",
    "//sdk/fidl/fuchsia.hardware.reset:fuchsia.hardware.reset_idk",
    "//sdk/fidl/fuchsia.hardware.sdhci:fuchsia.hardware.sdhci_idk",
    "//sdk/fidl/fuchsia.hardware.sdio:fuchsia.hardware.sdio_idk",
    "//sdk/fidl/fuchsia.hardware.sdmmc:fuchsia.hardware.sdmmc_idk",
    "//sdk/fidl/fuchsia.hardware.serial:fuchsia.hardware.serial_idk",
    "//sdk/fidl/fuchsia.hardware.serialimpl:fuchsia.hardware.serialimpl_idk",
    "//sdk/fidl/fuchsia.hardware.sharedmemory:fuchsia.hardware.sharedmemory_idk",
    "//sdk/fidl/fuchsia.hardware.spi.businfo:fuchsia.hardware.spi.businfo_idk",
    "//sdk/fidl/fuchsia.hardware.spi:fuchsia.hardware.spi_idk",
    "//sdk/fidl/fuchsia.hardware.spiimpl:fuchsia.hardware.spiimpl_idk",
    "//sdk/fidl/fuchsia.hardware.spmi:fuchsia.hardware.spmi_idk",
    "//sdk/fidl/fuchsia.hardware.trippoint:fuchsia.hardware.trippoint_idk",
    "//sdk/fidl/fuchsia.hardware.ufs.phy:fuchsia.hardware.ufs.phy_idk",
    "//sdk/fidl/fuchsia.hardware.usb.dci:fuchsia.hardware.usb.dci_idk",
    "//sdk/fidl/fuchsia.hardware.usb.descriptor:fuchsia.hardware.usb.descriptor_idk",
    "//sdk/fidl/fuchsia.hardware.usb.endpoint:fuchsia.hardware.usb.endpoint_idk",
    "//sdk/fidl/fuchsia.hardware.usb.phy:fuchsia.hardware.usb.phy_idk",
    "//sdk/fidl/fuchsia.hardware.usb.policy:fuchsia.hardware.usb.policy_idk",
    "//sdk/fidl/fuchsia.hardware.usb.request:fuchsia.hardware.usb.request_idk",
    "//sdk/fidl/fuchsia.hardware.uwb:fuchsia.hardware.uwb_idk",
    "//sdk/fidl/fuchsia.hardware.vreg:fuchsia.hardware.vreg_idk",
    "//sdk/fidl/fuchsia.location.gnss.types:fuchsia.location.gnss.types_idk",
    "//sdk/fidl/fuchsia.net.matchers:fuchsia.net.matchers_idk",
    "//sdk/fidl/fuchsia.power.broker:fuchsia.power.broker_idk",
    "//sdk/fidl/fuchsia.power.observability:fuchsia.power.observability_idk",
    "//sdk/fidl/fuchsia.storage.block:fuchsia.storage.block_idk",
    "//sdk/fidl/fuchsia.system.state:fuchsia.system.state_idk",
    "//sdk/fidl/fuchsia.usb.policy:fuchsia.usb.policy_idk",
    "//sdk/fidl/fuchsia.wlan.fullmac:fuchsia.wlan.fullmac_idk",
    "//sdk/fidl/fuchsia.wlan.stats:fuchsia.wlan.stats_idk",
]
# LINT.ThenChange(BUILD.gn:partner_libraries)

# FIDL libraries in the prebuilt category. All are stable.
# None are included in the IDK, but they may be used by prebuilt libraries in the IDK.
# LINT.IfChange(prebuilt_libraries)
PREBUILT_FIDL_LIBRARY_ATOMS_LIST = [
    # buildifier: keep sorted
    "//sdk/fidl/fuchsia.device:fuchsia.device_idk",
    "//sdk/fidl/fuchsia.fs:fuchsia.fs_idk",
    "//sdk/fidl/fuchsia.hardware.pty:fuchsia.hardware.pty_idk",
    "//sdk/fidl/fuchsia.memory.sampler:fuchsia.memory.sampler_idk",
    "//sdk/fidl/fuchsia.net.name:fuchsia.net.name_idk",
    "//sdk/fidl/fuchsia.net.resources:fuchsia.net.resources_idk",
    "//sdk/fidl/fuchsia.net.tcp:fuchsia.net.tcp_idk",
    "//sdk/fidl/fuchsia.posix:fuchsia.posix_idk",
    "//sdk/fidl/fuchsia.posix.socket:fuchsia.posix.socket_idk",
    "//sdk/fidl/fuchsia.posix.socket.packet:fuchsia.posix.socket.packet_idk",
    "//sdk/fidl/fuchsia.posix.socket.raw:fuchsia.posix.socket.raw_idk",
    "//sdk/fidl/fuchsia.vulkan.loader:fuchsia.vulkan.loader_idk",
]
# LINT.ThenChange(BUILD.gn:prebuilt_libraries)

# FIDL libraries in the host tool category. All are stable.
# None are included in the IDK, but they may be used by host tools in the IDK.
# LINT.IfChange(host_tool_libraries)
HOST_TOOL_FIDL_LIBRARY_ATOMS_LIST = [
    # buildifier: keep sorted
    "//sdk/fidl/fuchsia.dash:fuchsia.dash_idk",
    "//sdk/fidl/fuchsia.debugger:fuchsia.debugger_idk",
    "//sdk/fidl/fuchsia.developer.console:fuchsia.developer.console_idk",
    "//sdk/fidl/fuchsia.developer.ffxdaemonlifecycle:fuchsia.developer.ffxdaemonlifecycle_idk",
    "//sdk/fidl/fuchsia.developer.remotecontrol:fuchsia.developer.remotecontrol_idk",
    "//sdk/fidl/fuchsia.diagnostics.host:fuchsia.diagnostics.host_idk",
    "//sdk/fidl/fuchsia.fdomain:fuchsia.fdomain_idk",
    "//sdk/fidl/fuchsia.memory.debug:fuchsia.memory.debug_idk",
    "//sdk/fidl/fuchsia.memory.heapdump.client:fuchsia.memory.heapdump.client_idk",
    "//sdk/fidl/fuchsia.memory.inspection:fuchsia.memory.inspection_idk",
    "//sdk/fidl/fuchsia.overnet.protocol:fuchsia.overnet.protocol_idk",
    "//sdk/fidl/fuchsia.pkg.garbagecollector:fuchsia.pkg.garbagecollector_idk",
    "//sdk/fidl/fuchsia.power.metrics:fuchsia.power.metrics_idk",
    "//sdk/fidl/fuchsia.starnix.container:fuchsia.starnix.container_idk",
    "//sdk/fidl/fuchsia.sys2:fuchsia.sys2_idk",
    "//sdk/fidl/fuchsia.test.manager:fuchsia.test.manager_idk",
]
# LINT.ThenChange(BUILD.gn:host_tool_libraries)

# FIDL libraries in the compat test category. All are stable.
# None are included in the IDK, and they may not be used by anything in the IDK.
# LINT.IfChange(compat_test_libraries)
COMPAT_TEST_FIDL_LIBRARY_ATOMS_LIST = [
    # buildifier: keep sorted
    "//examples/fidl/fuchsia.examples:fuchsia.examples_idk",
    "//sdk/fidl/fuchsia.testing.harness:fuchsia.testing.harness_idk",
    "//sdk/fidl/fuchsia.ui.focus:fuchsia.ui.focus_idk",
    "//sdk/fidl/fuchsia.ui.observation.scope:fuchsia.ui.observation.scope_idk",
    "//sdk/fidl/fuchsia.ui.observation.test:fuchsia.ui.observation.test_idk",
    "//sdk/fidl/fuchsia.ui.pointer.augment:fuchsia.ui.pointer.augment_idk",
    "//sdk/fidl/fuchsia.ui.test.conformance:fuchsia.ui.test.conformance_idk",
    "//sdk/fidl/fuchsia.ui.test.context:fuchsia.ui.test.context_idk",
]
# LINT.ThenChange(BUILD.gn:compat_test_libraries)
