# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//:build/rust/fidl_rust_next.bzl", "fidl_rust_next_allowlist")
load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "fidl_next_bind_internal",
    srcs = [
        "src/client.rs",
        "src/decoded.rs",
        "src/endpoint.rs",
        "src/error.rs",
        "src/executor.rs",
        "src/fuchsia_async.rs",
        "src/future/mod.rs",
        "src/future/send.rs",
        "src/future/two_way.rs",
        "src/lib.rs",
        "src/protocol.rs",
        "src/server.rs",
        "src/service.rs",
    ] + select({
        "@platforms//os:fuchsia": [
            "src/fuchsia.rs",
        ],
        "//conditions:default": [],
    }),
    crate_features = [
        # Enables support for fuchsia-async.
        # This feature _should_ be named `fuchsia_async`, but our cargo manifest
        # generator doesn't support features with the same name as mandatory
        # dependencies.
        "fasync",
    ] + select({
        "@platforms//os:fuchsia": ["fuchsia"],
        "//conditions:default": [],
    }),
    crate_name = "fidl_next_bind",
    edition = "2024",
    with_unit_tests = True,
    deps = [
        "//src/lib/fidl/rust_next/fidl_next_codec",
        "//src/lib/fidl/rust_next/fidl_next_protocol",
        "//src/lib/fuchsia-async",
        "//third_party/rust_crates/vendor:pin-project",
        "//third_party/rust_crates/vendor:thiserror",
    ] + select({
        "@platforms//os:fuchsia": [
            "//sdk/rust/zx",
        ],
        "//conditions:default": [],
    }),
)

alias(
    name = "fidl_next_bind",
    actual = ":fidl_next_bind_internal",
    visibility = fidl_rust_next_allowlist,
)
