# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/cc:fx_cc_library.bzl", "fx_cc_library")

package(default_applicable_licenses = ["//:license"])

fx_cc_library(
    name = "elflib",
    srcs = ["elflib.cc"],
    hdrs = ["elflib.h"],
    public_configs = ["//src/lib/llvm:LLVMHeader_config"],
    visibility = ["//visibility:public"],
    deps = [
        "//zircon/system/public",
        "//zircon/system/ulib/fbl",
        "@prebuilt_llvm//:llvm_includes",
    ],  # @bazel2gn:raw_overwrite:[ "//zircon/system/public", "//zircon/system/ulib/fbl" ]
)
