## require is_lto=false
## require optimize=none

[zxdb] run-component fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/async_rust_multithreaded.cm
Launched Process 1 state=Running koid=?? name=async_rust_multithreaded.cm component=async_rust_multithreaded.cm
🛑

# Only the thread that executes the panic! will be stopped when we catch the exception, so
# explicitly pause to make sure all threads are suspended.
[zxdb] pause
🛑

# TODO(https://fxbug.dev/292107156): Use local unwinding once we can download symbols in E2E tests.
[zxdb] thread * frame --force-remote-unwind
▶ 0

# There are three threads. The "initial-thread" on all processes, plus the two specified to the
# fasync::run annotation to main.
[zxdb] t 1 abt
## allow-out-of-order-output
Task(id = ??)
└─ async_rust_multithreaded::main::func • async_rust_multithreaded.rs:??
   └─ fuchsia_async::runtime::fuchsia::timer::Timer
Scope("scope")
└─ Task(id = ??)
   └─ async_rust_multithreaded::foo (Unresumed) • async_rust_multithreaded.rs:??
└─ Scope("child")
   └─ Task(id = ??)
      └─ async_rust_multithreaded::foo (Unresumed) • async_rust_multithreaded.rs:??

[zxdb] t 2 abt
## allow-out-of-order-output
Task(id = ??)
└─ async_rust_multithreaded::main::func • async_rust_multithreaded.rs:??
   └─ fuchsia_async::runtime::fuchsia::timer::Timer
Scope("scope")
└─ Task(id = ??)
   └─ async_rust_multithreaded::foo (Unresumed) • async_rust_multithreaded.rs:??
└─ Scope("child")
   └─ Task(id = ??)
      └─ async_rust_multithreaded::foo (Unresumed) • async_rust_multithreaded.rs:??

[zxdb] t 3 abt
## allow-out-of-order-output
Task(id = ??)
└─ async_rust_multithreaded::main::func • async_rust_multithreaded.rs:??
   └─ fuchsia_async::runtime::fuchsia::timer::Timer
Scope("scope")
└─ Task(id = ??)
   └─ async_rust_multithreaded::foo (Unresumed) • async_rust_multithreaded.rs:??
└─ Scope("child")
   └─ Task(id = ??)
      └─ async_rust_multithreaded::foo (Unresumed) • async_rust_multithreaded.rs:??

[zxdb] kill
Process 1 killed.
