## require optimize=none
[zxdb] b $main
Created Breakpoint 1 @ $main
Pending: No current matches for location. It will be matched against new
         processes and shared libraries.

[zxdb] run-component fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/cpp_functions.cm
run-component won't work for many v2 components. See "help run-component".
Launched Process 1 state=Running koid=?? name=cpp_functions.cm component=cpp_functions.cm
Breakpoint 1 now matching 1 addrs for $main
🛑 on bp 1 main() • cpp_functions.cc:??

# This will re-hit the user installed breakpoint.
[zxdb] p PrintHello()
🛑 on bp 1 main() • cpp_functions.cc:??
void

[zxdb] n
🛑 main() • cpp_functions.cc:??

# Now it stops on a generic breakpoint.
[zxdb] p NestedTwiceNoArgs()
🛑 main() • cpp_functions.cc:??
void

# The global variable should have been updated.
[zxdb] p SomeGlobal
10

# Should be at the same location as before.
[zxdb] f
▶ 0 main() • cpp_functions.cc:??

# Let the program finish.
[zxdb] c
Process 1 exited with code 0.
