# Starnix doesn't work with asan right now. LTO can cause execute_syscall to be inlined
# which breaks unwinding into user code.
## require is_asan=false
## require is_lto=false
## require is_thinlto=false
## require optimize=none
## set timeout 30

# TODO(https://fxbug.dev/42077983): attach shouldn't be necessary.
# We can use weak here to avoid loading symbols until all of the modules are mapped into memory
# which speeds up the test quite a bit.
[zxdb] attach --weak starnix_proc_exception32
Waiting for process matching "starnix_proc_exception32".

[zxdb] run-test --realm /core/testing/system-tests fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/starnix_proc_exception32.cm
Attached Process 1 state=Running koid=?? name=starnix_proc_exception32
🛑

# Zxdb can recover the first restricted frame with CFI and then the rest of the 32 bit frames with
# ArmEhAbi.
[zxdb] frame --force-remote-unwind --trust
f0() • starnix_proc_exception32.cc:?? from CFI
f1() • starnix_proc_exception32.cc:?? from ArmEhAbi
f2() • starnix_proc_exception32.cc:?? from ArmEhAbi
f3() • starnix_proc_exception32.cc:?? from ArmEhAbi
main() • starnix_proc_exception32.cc:?? from ArmEhAbi

[zxdb] kill
