## require is_lto=false
## require optimize=none
[zxdb] b $main
Created Breakpoint 1 @ $main
[zxdb] run-component fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/async_rust_multithreaded.cm
Launched Process 1 state=Running koid=?? name=async_rust_multithreaded.cm component=async_rust_multithreaded.cm
🛑
[zxdb] until foo
🛑
[zxdb] thread
## allow-out-of-order-output
Suspended           ?? initial-thread
Suspended           ?? executor_worker
▶ ?? Blocked (Exception) ?? executor_worker

[zxdb] kill
Process 1 killed.
