# proto-file: tools/metadata/proto/metadata.proto
# proto-message: Metadata
# https://fuchsia.dev/fuchsia-src/development/source_code/metadata

trackers: {
  issue_tracker: {
    # Fuchsia > Network Stack
    component_id: 1478432
  }
}
