# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load(
    "@rules_fuchsia//fuchsia:assembly.bzl",
    "fuchsia_board_configuration",
    "fuchsia_product",
    "fuchsia_product_bundle",
    "fuchsia_product_configuration",
)

package(
    default_applicable_licenses = ["//:license"],
)

fuchsia_board_configuration(
    name = "board_config",
    board_name = "test",
    partitions_configuration = "//build/bazel/assembly/partitions_configurations:default",
    version = "fake_version",
)

fuchsia_product_configuration(
    name = "assembly_config",
    product_config_json = {
        "platform": {
            "build_type": "eng",
            "feature_set_level": "utility",
        },
    },
)

fuchsia_product(
    name = "main_image",
    board_config = ":board_config",
    platform_artifacts = "//build/bazel/assembly/assembly_input_bundles:platform_eng",
    product_config = ":assembly_config",
)

fuchsia_product_bundle(
    name = "product_bundle",
    testonly = True,
    main = ":main_image",
    product_bundle_name = "scrutiny",
    repository_keys = "//src/sys/pkg/repositories/devhost/keys:keys",
    update_epoch = "1",
)
