# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/components.gni")
import("//build/rust/rustc_binary.gni")
import("//build/testing/perf/test.gni")

rustc_binary("lsm_tree_bench") {
  testonly = true
  edition = "2024"
  name = "lsm_tree_bench"
  source_root = "lsm_tree_bench.rs"
  sources = [ "lsm_tree_bench.rs" ]
  deps = [
    "//src/developer/fuchsia-criterion",
    "//src/storage/fxfs:benchmark",
    "//third_party/rust_crates:futures",
  ]
}

fuchsia_unittest_component("fxfs-lsm-tree-bench-component") {
  manifest = "meta/lsm_tree_bench.cml"
  deps = [ ":lsm_tree_bench" ]
}

fuchsia_test_package("fxfs-lsm-tree-bench") {
  test_components = [ ":fxfs-lsm-tree-bench-component" ]
}

fuchsia_component_perf_test("fxfs_lsm_tree_benchmarks") {
  package = ":fxfs-lsm-tree-bench"
  component_name = "fxfs-lsm-tree-bench-component"
  expected_metric_names_filepath = "//src/tests/end_to_end/perf/expected_metric_names/fuchsia.fxfs.lsm_tree_bench.txt"
}

group("benchmarks") {
  testonly = true
  deps = [ ":fxfs_lsm_tree_benchmarks" ]
}

group("tests") {
  testonly = true
  deps = [ ":lsm_tree_bench($host_toolchain)" ]
}
