# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# "public_checks" target is referenced by //:tefmocheck_rules_manifest.
group("public_checks") {
  metadata = {
    tefmocheck_rules = [ rebase_path("check-configs.yaml", root_build_dir) ]
  }
}
