# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")
load("//build/bazel/rules/host:defs.bzl", "go_binary_host_tool")
load("//build/bazel/rules/host_tests:host_go_test.bzl", "host_go_test")

package(default_applicable_licenses = ["//:license"])

go_library(
    name = "lib",
    srcs = [
        "cdc_ethernet_state_check.go",
        "failure_reason_check.go",
        "lib.go",
        "logprocessing.go",
        "mass_test_failure_check.go",
        "nearby_string_check.go",
        "no_tests_ran_check.go",
        "run_checks.go",
        "string_in_log_check.go",
        "swarming.go",
        "task_state_check.go",
        "types.go",
        "yaml_loader.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/testing/tefmocheck",
    target_compatible_with = HOST_CONSTRAINTS,
    deps = [
        "//third_party/golibs:golang.org/x/sync/errgroup",
        "//third_party/golibs:gopkg.in/yaml.v2",
        "//tools/build",
        "//tools/testing/runtests",
    ],
)

go_binary_host_tool(
    name = "tefmocheck",
    srcs = [
        "cmd/main.go",
    ],
    target_compatible_with = HOST_CONSTRAINTS,
    deps = [
        ":lib",
        "//tools/lib/flagmisc",
        "//tools/lib/osmisc",
    ],
)

host_go_test(
    name = "tefmocheck_lib_tests",
    srcs = [
        "cdc_ethernet_state_check_test.go",
        "failure_reason_check_test.go",
        "lib_test.go",
        "logprocessing_test.go",
        "mass_test_failure_check_test.go",
        "nearby_string_check_test.go",
        "no_tests_ran_check_test.go",
        "run_checks_test.go",
        "string_in_log_check_test.go",
        "task_state_check_test.go",
        "yaml_loader_test.go",
    ],
    embed = [":lib"],
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//tools:__pkg__"],
    deps = [
        "//third_party/golibs:github.com/google/go-cmp/cmp",
        "//third_party/golibs:github.com/google/go-cmp/cmp/cmpopts",
        "//tools/testing/runtests",
    ],
)
