# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/host.gni")

group("create") {
  deps = [
    "templates($host_toolchain)",
    "//build/bazel/host:bazel_root_host_tools.create.host_tool",
  ]
}

group("tests") {
  testonly = true
  deps = [ "goldens:tests" ]
}
