# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "operation",
    srcs = [
        "operation.cc",
        "unbuffered_operations_builder.cc",
    ],
    hdrs = [
        "operation.h",
        "operation_tree.h",
        "unbuffered_operation.h",
        "unbuffered_operations_builder.h",
    ],
    target_compatible_with = ["@platforms//os:fuchsia"],
    deps = [
        "//src/storage/lib/range",
        "//zircon/third_party/ulib/safemath",
        "@fuchsia_sdk//pkg/fdio",
        "@fuchsia_sdk//pkg/fit",
        "@fuchsia_sdk//pkg/stdcompat",
        "@fuchsia_sdk//pkg/zx",
    ],
)
