# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("operation") {
  public = [
    "operation.h",
    "operation_tree.h",
  ]
  sources = [ "operation.cc" ]
  public_deps = [
    "//sdk/lib/stdcompat",
    "//src/storage/lib/range",
    "//zircon/third_party/ulib/safemath",
  ]

  if (is_fuchsia) {
    public += [
      "unbuffered_operation.h",
      "unbuffered_operations_builder.h",
    ]
    sources += [ "unbuffered_operations_builder.cc" ]
    public_deps += [ "//zircon/system/ulib/zx" ]
    deps = [
      "//sdk/lib/fdio",
      "//sdk/lib/fit",
      "//zircon/system/ulib/zx",
    ]
  }
}

group("tests") {
  testonly = true
  deps = [ "test:tests" ]
}
