# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bazel/export_fuchsia_package_to_bazel.gni")
import("//build/components.gni")
import("//build/rust/rustc_binary.gni")

rustc_binary("fake_battery_cli_bin") {
  output_name = "fake-battery-cli"
  with_unit_tests = true
  edition = "2024"
  deps = [
    "//sdk/fidl/fuchsia.hardware.power.battery:fuchsia.hardware.power.battery_rust",
    "//sdk/fidl/fuchsia.hardware.power.source:fuchsia.hardware.power.source_rust",
    "//sdk/fidl/fuchsia.io:fuchsia.io_rust",
    "//src/lib/fuchsia",
    "//src/lib/fuchsia-component",
    "//src/lib/fuchsia-fs",
    "//src/power/testing/fake-hardware-power-control:test.hardwarepowercontrol_rust",
    "//third_party/rust_crates:anyhow",
    "//third_party/rust_crates:argh",
  ]

  sources = [ "src/main.rs" ]

  test_deps = [
    "//src/lib/fidl/rust/fidl",
    "//src/lib/fuchsia-async",
    "//third_party/rust_crates:futures",
  ]
}

# Package to be included for developer/eng builds or injected via component
# explore.
fuchsia_package("package") {
  package_name = "fake_battery_cli_pkg"
  deps = [ ":fake_battery_cli_bin" ]
}

export_fuchsia_package_to_bazel("package_for_bazel") {
  package = ":package"
}

# Run with `fx test fake-battery-cli-unittests`.
fuchsia_unittest_package("fake-battery-cli-unittests") {
  deps = [ ":fake_battery_cli_bin_test" ]
  test_specs = {
    log_settings = {
      max_severity = "ERROR"
    }
  }
}

group("tests") {
  testonly = true
  public_deps = [
    ":fake-battery-cli-unittests",
    ":package",
  ]
}
