# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load(
    "@rules_fuchsia//fuchsia:assembly.bzl",
    "fuchsia_board_configuration",
    "fuchsia_product",
    "fuchsia_product_bundle",
    "fuchsia_product_configuration",
)

package(
    default_applicable_licenses = ["//:license"],
)

fuchsia_board_configuration(
    name = "board_config",
    board_name = "test",
    filesystems = {
        "fvm": {
        },
    },
    partitions_configuration = "//build/bazel/assembly/partitions_configurations:default",
    version = "fake_version",
)

# `product_config` builds a zbi and blob.blk for consumption by the test.
fuchsia_product_configuration(
    name = "product_config",
    product_config_json = {
        "platform": {
            "build_type": "eng",
            "storage": {
                "filesystems": {
                    "volume": {
                        "fvm": {
                            "data": {
                                "data_filesystem_format": "minfs",
                            },
                            "blob": {},
                        },
                    },
                },
            },
        },
    },
)

# `product_config_recovery` builds a zbi, specifying `image_mode = "ramdisk"`
# tests the path where the blobfs exists in the zbi and is automatically
# extracted as part of the zbi, such as in recovery images.
fuchsia_product_configuration(
    name = "product_config_recovery",
    product_config_json = {
        "platform": {
            "build_type": "eng",
            "storage": {
                "filesystems": {
                    "image_mode": "ramdisk",
                    "volume": {
                        "fvm": {
                            "data": {
                                "data_filesystem_format": "minfs",
                            },
                            "blob": {},
                        },
                    },
                },
            },
        },
    },
)

fuchsia_product(
    name = "main_image",
    board_config = ":board_config",
    platform_artifacts = "//build/bazel/assembly/assembly_input_bundles:platform_eng",
    product_config = ":product_config",
)

fuchsia_product(
    name = "recovery_image",
    board_config = ":board_config",
    platform_artifacts = "//build/bazel/assembly/assembly_input_bundles:platform_eng",
    product_config = ":product_config_recovery",
)

fuchsia_product_bundle(
    name = "product_bundle",
    testonly = True,
    main = ":main_image",
    product_bundle_name = "scrutiny_ffx_integration_test",
    recovery = ":recovery_image",
)
