# Copyright 2022 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bazel/assembly/bazel_product_bundle.gni")
import("//build/rust/rustc_test.gni")
import("//build/testing/host_test_data.gni")

if (is_fuchsia) {
  bazel_product_bundle("product_bundle") {
    testonly = true
    product_bundle_name = "scrutiny_ffx_integration_test"
    bazel_product_bundle_target = ":product_bundle"
    bazel_product_image_target = ":main_image"
    bazel_product_config_target = ":product_config"
    bazel_product_config_name = "product_config"
    bazel_recovery_image_target = ":recovery_image"
    image_has_fxfs_blob = false
    image_use_vbmeta = false
    bazel_inputs_from_gn = []
  }
}

if (is_host) {
  if (has_board) {
    group("host_tests") {
      testonly = true
      deps = [ ":scrutiny_ffx_integration_test" ]
    }

    _product_bundle_out_dir =
        get_label_info(":product_bundle($target_toolchain)", "target_out_dir") +
        "/product_bundle/product_bundle"

    host_test_data("testdata") {
      deps = [ ":product_bundle($target_toolchain)" ]
      sources = [ _product_bundle_out_dir ]
    }

    # Required for the test to be able to call ffx.
    host_test_data("copy_host_tools") {
      sources = [ "${host_tools_dir}/ffx-scrutiny" ]
      deps = [ "//src/developer/ffx/plugins/scrutiny:ffx_scrutiny_tool_host_tool($host_toolchain)" ]
      outputs = [ "$target_out_dir/host_tools/{{source_file_part}}" ]
    }

    config("config") {
      ffx_path = "$target_out_dir/host_tools/ffx-scrutiny"

      rustenv = [
        "FFX_TOOL_PATH=" + rebase_path(ffx_path, root_build_dir),
        "PRODUCT_BUNDLE_PATH=" +
            rebase_path(_product_bundle_out_dir, root_build_dir),
      ]
    }

    rustc_test("scrutiny_ffx_integration_test") {
      source_root = "src/lib.rs"
      edition = "2024"
      deps = [
        ":copy_host_tools",
        ":testdata",
        "//third_party/rust_crates:tempfile",
      ]
      sources = [ "src/lib.rs" ]
      configs += [ ":config" ]

      # TODO(https://fxbug.dev/42179241): LSAN says that Scrutiny has a leak, disable this test in ASAN
      if (is_asan) {
        test_environments = []
      }
    }
  } else {
    # If there's no board, just stub out the host_tests group.
    group("host_tests") {
    }
  }
}
