# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "test_settings",
    srcs = ["test_settings.cc"],
    hdrs = ["test_settings.h"],
    deps = [
        "//sdk/lib/syslog/cpp",
        "//src/lib/fxl:cli",
    ],
    alwayslink = True,
)

cc_library(
    name = "gtest_main_no_testonly",
    srcs = ["run_all_unittests.cc"],
    implementation_deps = [
        ":test_settings",
        "//src/lib/fxl:cli",
    ],
    deps = [
        "//sdk/lib/syslog/cpp",
        "@com_google_googletest//:gtest",  # @bazel2gn:path_overwrite://third_party/googletest:gtest_no_testonly
    ],
    alwayslink = True,
)

# Generic main entry point target for GTest executables.
cc_library(
    name = "gtest_main",
    testonly = True,
    deps = [":gtest_main_no_testonly"],
)
