# Copyright 2026 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/rust/rust_auxiliary_args.gni")
import("//zircon/kernel/kernel_switchset.gni")

# This switchset exists only to do builds sufficient to run static checks.
# Thus it should include the maximal set of code (e.g. assertions) so nothing
# goes unchecked because it's disabled at compile time.
kernel_switchset("static-checks") {
  # Include all the code.
  lk_debug_level = 2
  unit_tests_enabled = true

  # TODO(https://fxbug.dev/552170802): Some Rust analyses depend on the MIR
  # that's not analyzed until after some optimizations may fold some bits away.
  # This results in checks not firing for things that happened to have been
  # simplified before checking.  So avoid any kind of optimization to maximize
  # and normalize the checking that gets done.
  optimization_mode = "none"

  # The code won't actually be used, so there's no point in enabling extra
  # compile-time variation that doesn't affect any static checks.
  exclude_variant_tags = [
    "gcc",
    "instrumented",
    "lto",
  ]

  toolchain_args = {
    # Always enable Clippy checking of rustc_library() targets in the kernel's
    # build graph.  Note this does not affect kernel_executable(), which always
    # does the Clippy checks on the kernel itself (in this switchset).
    include_clippy = true

    # There is no variant selection that will really happen in the
    # static-checks toolchain, since no terminal targets get built there.
    # TODO(https://fxbug.dev/396658029): There are some asserts associated with
    # this bug that care about this setting even when it doesn't matter.
    select_variant = []
  }
}
