# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# default_board_for_emulator points to the default board configuration for
# emulator tests.
if (current_cpu == "arm64") {
  default_board_for_emulator = "//boards/qemu-arm64"
} else if (current_cpu == "riscv64") {
  default_board_for_emulator = "//boards/riscv64"
} else {
  default_board_for_emulator = "//boards/x64"
}
