# Copyright 2025 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# The logic in BUILD.gn is too complex for bazel2gn, manually keep these
# files synchronized.
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_applicable_licenses = ["//:license"])

# LINT.IfChange
cc_library(
    name = "public",
    hdrs = [
        "zircon/analyzer.h",
        "zircon/availability.h",
        "zircon/availability_levels.inc",
        "zircon/compiler.h",
        "zircon/errors.h",
        "zircon/features.h",
        "zircon/fidl.h",
        "zircon/hw/debug/arm64.h",
        "zircon/hw/debug/x86.h",
        "zircon/limits.h",
        "zircon/processargs.h",
        "zircon/rights.h",
        "zircon/syscalls.h",
        "zircon/syscalls/debug.h",
        "zircon/syscalls/exception.h",
        "zircon/syscalls/iob.h",
        "zircon/syscalls/object.h",
        "zircon/syscalls/port.h",
        "zircon/time.h",
        "zircon/types.h",
    ],
    includes = ["."],
    visibility = ["//visibility:public"],
)

# LINT.ThenChange(BUILD.gn)
