# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")

package(default_applicable_licenses = ["//:license"])

go_library(
    name = "ir",
    srcs = [
        "error.go",
        "test_case.go",
        "util.go",
        "value.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/fidl/gidl/lib/ir",
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = [
        "//tools/fidl/gidl:__subpackages__",
    ],
    deps = [
        "//third_party/golibs:golang.org/x/exp/slices",
        "//tools/fidl/lib/fidlgen",
    ],
)
