// Copyright 2026 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

use crate::parser::{EnumDef, Schema, StructDef, Type};
use std::collections::HashSet;

pub fn generate_rust_parser(
    schemas: &[Schema],
    driver_name: &str,
    year: &str,
) -> Result<String, anyhow::Error> {
    let normalized_name = driver_name.replace("-", "_");
    let mut rs_code = String::new();

    rs_code.push_str(&format!(
        "// Copyright {year} The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// WARNING: THIS FILE IS GENERATED BY dmlc. DO NOT EDIT.

#![allow(dead_code, unused_imports, non_camel_case_types)]

use fidl_fuchsia_driver_metadata as fdr;

"
    ));

    rs_code.push_str(r#"fn find_value<'a>(dict: &'a fdr::Dictionary, key: &str) -> Option<&'a fdr::DictionaryValue> {
    dict.entries.as_ref()?.iter().find(|e| e.key == key).map(|e| &e.value)
}

fn get_bool(dict: &fdr::Dictionary, key: &str) -> Option<bool> {
    match find_value(dict, key)? {
        fdr::DictionaryValue::Boolean(b) => Some(*b),
        _ => None,
    }
}

fn get_int64(dict: &fdr::Dictionary, key: &str) -> Option<i64> {
    match find_value(dict, key)? {
        fdr::DictionaryValue::Int64(i) => Some(*i),
        _ => None,
    }
}

fn get_uint8(dict: &fdr::Dictionary, key: &str) -> Option<u8> {
    get_int64(dict, key).and_then(|i| u8::try_from(i).ok())
}

fn get_uint16(dict: &fdr::Dictionary, key: &str) -> Option<u16> {
    get_int64(dict, key).and_then(|i| u16::try_from(i).ok())
}

fn get_uint32(dict: &fdr::Dictionary, key: &str) -> Option<u32> {
    get_int64(dict, key).and_then(|i| u32::try_from(i).ok())
}

fn get_uint64(dict: &fdr::Dictionary, key: &str) -> Option<u64> {
    get_int64(dict, key).and_then(|i| u64::try_from(i).ok())
}

fn get_int8(dict: &fdr::Dictionary, key: &str) -> Option<i8> {
    get_int64(dict, key).and_then(|i| i8::try_from(i).ok())
}

fn get_int16(dict: &fdr::Dictionary, key: &str) -> Option<i16> {
    get_int64(dict, key).and_then(|i| i16::try_from(i).ok())
}

fn get_int32(dict: &fdr::Dictionary, key: &str) -> Option<i32> {
    get_int64(dict, key).and_then(|i| i32::try_from(i).ok())
}

fn get_string(dict: &fdr::Dictionary, key: &str) -> Option<String> {
    match find_value(dict, key)? {
        fdr::DictionaryValue::Str(s) => Some(s.clone()),
        _ => None,
    }
}

fn get_int64_vec(dict: &fdr::Dictionary, key: &str) -> Option<Vec<i64>> {
    match find_value(dict, key)? {
        fdr::DictionaryValue::Int64Vec(v) => Some(v.clone()),
        _ => None,
    }
}

fn get_str_vec(dict: &fdr::Dictionary, key: &str) -> Option<Vec<String>> {
    match find_value(dict, key)? {
        fdr::DictionaryValue::StrVec(v) => Some(v.clone()),
        _ => None,
    }
}

fn get_int8_vec(dict: &fdr::Dictionary, key: &str) -> Option<Vec<i8>> {
    get_int64_vec(dict, key)?.into_iter().map(|x| i8::try_from(x).ok()).collect()
}

fn get_int16_vec(dict: &fdr::Dictionary, key: &str) -> Option<Vec<i16>> {
    get_int64_vec(dict, key)?.into_iter().map(|x| i16::try_from(x).ok()).collect()
}

fn get_int32_vec(dict: &fdr::Dictionary, key: &str) -> Option<Vec<i32>> {
    get_int64_vec(dict, key)?.into_iter().map(|x| i32::try_from(x).ok()).collect()
}

fn get_uint8_vec(dict: &fdr::Dictionary, key: &str) -> Option<Vec<u8>> {
    get_int64_vec(dict, key)?.into_iter().map(|x| u8::try_from(x).ok()).collect()
}

fn get_uint16_vec(dict: &fdr::Dictionary, key: &str) -> Option<Vec<u16>> {
    get_int64_vec(dict, key)?.into_iter().map(|x| u16::try_from(x).ok()).collect()
}

fn get_uint32_vec(dict: &fdr::Dictionary, key: &str) -> Option<Vec<u32>> {
    get_int64_vec(dict, key)?.into_iter().map(|x| u32::try_from(x).ok()).collect()
}

fn get_uint64_vec(dict: &fdr::Dictionary, key: &str) -> Option<Vec<u64>> {
    get_int64_vec(dict, key)?.into_iter().map(|x| u64::try_from(x).ok()).collect()
}

fn make_key(prefix: &str, field: &str) -> String {
    if prefix.is_empty() {
        field.to_string()
    } else {
        format!("{prefix}.{field}")
    }
}

"#);

    let mut generated_enums = HashSet::new();
    let mut generated_structs = HashSet::new();

    for schema in schemas {
        // Generate Enums
        let mut sorted_enums: Vec<(&String, &EnumDef)> = schema.enums.iter().collect();
        sorted_enums.sort_by_key(|(name, _)| *name);
        for (name, enum_def) in sorted_enums {
            if !generated_enums.insert(name.clone()) {
                continue;
            }
            rs_code.push_str(&format!(
                "#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum {name} {{
"
            ));
            for (idx, variant) in enum_def.variants.iter().enumerate() {
                rs_code.push_str(&format!("    {variant} = {idx},\n"));
            }
            rs_code.push_str("}\n\n");

            rs_code.push_str(&format!("impl {name} {{\n"));
            rs_code.push_str("    pub fn from_u8(val: u8) -> Option<Self> {\n");
            rs_code.push_str("        match val {\n");
            for (idx, variant) in enum_def.variants.iter().enumerate() {
                rs_code.push_str(&format!("            {idx} => Some(Self::{variant}),\n"));
            }
            rs_code.push_str("            _ => None,\n");
            rs_code.push_str("        }\n");
            rs_code.push_str("    }\n\n");

            rs_code.push_str("    pub fn from_str(s: &str) -> Option<Self> {\n");
            rs_code.push_str("        match s {\n");
            for variant in &enum_def.variants {
                rs_code.push_str(&format!("            \"{variant}\" => Some(Self::{variant}),\n"));
            }
            rs_code.push_str("            _ => None,\n");
            rs_code.push_str("        }\n");
            rs_code.push_str("    }\n");
            rs_code.push_str("}\n\n");
        }
        // Validate struct dependencies
        for struct_def in schema.structs.values() {
            for dep in get_dependencies(struct_def) {
                if !schema.structs.contains_key(&dep) {
                    anyhow::bail!(
                        "Struct '{}' references undefined type '{}'",
                        struct_def.name,
                        dep
                    );
                }
            }
        }

        // Validate root layout dependencies
        for dep in get_dependencies(&schema.root_layout) {
            if !schema.structs.contains_key(&dep) {
                anyhow::bail!("Root layout references undefined type '{}'", dep);
            }
        }

        // Sort structs topologically by dependency
        let mut ordered_structs = Vec::new();
        let mut ordered_names = HashSet::new();
        let mut pending: Vec<&StructDef> = schema.structs.values().collect();
        pending.sort_by_key(|s| &s.name);

        while !pending.is_empty() {
            let mut progress = false;
            let mut i = 0;
            while i < pending.len() {
                let struct_def = pending[i];
                let deps = get_dependencies(struct_def);
                if deps.iter().all(|dep| ordered_names.contains(dep)) {
                    ordered_names.insert(struct_def.name.clone());
                    ordered_structs.push(struct_def);
                    pending.remove(i);
                    progress = true;
                } else {
                    i += 1;
                }
            }
            if !progress {
                anyhow::bail!("Circular dependency detected in schema structs!");
            }
        }

        // Generate Structs in dependency order
        for struct_def in ordered_structs {
            let name = &struct_def.name;
            if !generated_structs.insert(name.clone()) {
                continue;
            }
            rs_code.push_str(&format!(
                "#[derive(Debug, Clone, PartialEq, Default)]
pub struct {name} {{
"
            ));
            let mut sorted_fields = struct_def.fields.clone();
            sorted_fields.sort_by(|a, b| a.name.cmp(&b.name));
            for field in &sorted_fields {
                let rust_type = to_rust_type(&field.ty, field.optional);
                rs_code.push_str(&format!("    pub {}: {},\n", field.name, rust_type));
            }
            rs_code.push_str("}\n\n");

            rs_code.push_str(&format!("impl {name} {{\n"));
            rs_code.push_str(
                "    pub fn parse(dict: &fdr::Dictionary, prefix: &str) -> Option<Self> {\n",
            );
            rs_code.push_str("        Some(Self {\n");
            for field in &sorted_fields {
                let val_getter = get_value_getter(&field.ty, &field.name, schema)?;
                if field.optional {
                    rs_code.push_str(&format!("            {}: {},\n", field.name, val_getter));
                } else {
                    rs_code.push_str(&format!("            {}: {}?,\n", field.name, val_getter));
                }
            }
            rs_code.push_str("        })\n");
            rs_code.push_str("    }\n");
            rs_code.push_str("}\n\n");
        }

        // Root struct
        let root_class_name = schema.root_struct_name(&normalized_name, schemas.len());

        if generated_structs.insert(root_class_name.clone()) {
            rs_code.push_str(&format!(
                "#[derive(Debug, Clone, PartialEq, Default)]
pub struct {root_class_name} {{
"
            ));
            let mut sorted_root_fields = schema.root_layout.fields.clone();
            sorted_root_fields.sort_by(|a, b| a.name.cmp(&b.name));
            for field in &sorted_root_fields {
                let rust_type = to_rust_type(&field.ty, field.optional);
                rs_code.push_str(&format!("    pub {}: {},\n", field.name, rust_type));
            }
            rs_code.push_str("}\n\n");

            rs_code.push_str(&format!("impl {root_class_name} {{\n"));
            rs_code.push_str(
                "    pub fn parse(dict: &fdr::Dictionary, prefix: &str) -> Option<Self> {\n",
            );
            rs_code.push_str("        Some(Self {\n");
            for field in &sorted_root_fields {
                let val_getter = get_value_getter(&field.ty, &field.name, schema)?;
                if field.optional {
                    rs_code.push_str(&format!("            {}: {},\n", field.name, val_getter));
                } else {
                    rs_code.push_str(&format!("            {}: {}?,\n", field.name, val_getter));
                }
            }
            rs_code.push_str("        })\n");
            rs_code.push_str("    }\n\n");

            rs_code.push_str("    pub fn parse_bytes(bytes: &[u8]) -> Option<Self> {\n");
            rs_code.push_str("        let dict: fdr::Dictionary = fidl::unpersist(bytes).ok()?;\n");
            rs_code.push_str("        Self::parse(&dict, \"\")\n");
            rs_code.push_str("    }\n");
            rs_code.push_str("}\n\n");
        }
    }

    Ok(rs_code)
}

fn to_rust_type(ty: &Type, optional: bool) -> String {
    let base = match ty {
        Type::Bool => "bool".to_string(),
        Type::Uint8 => "u8".to_string(),
        Type::Uint16 => "u16".to_string(),
        Type::Uint32 => "u32".to_string(),
        Type::Uint64 => "u64".to_string(),
        Type::Int8 => "i8".to_string(),
        Type::Int16 => "i16".to_string(),
        Type::Int32 => "i32".to_string(),
        Type::Int64 => "i64".to_string(),
        Type::String => "String".to_string(),
        Type::ProviderId => "u32".to_string(),
        Type::Struct(name) => name.clone(),
        Type::Enum(name) => name.clone(),
        Type::Vector(inner) => format!("Vec<{}>", to_rust_type(inner, false)),
    };
    if optional { format!("Option<{}>", base) } else { base }
}

fn get_value_getter(ty: &Type, field_name: &str, schema: &Schema) -> Result<String, anyhow::Error> {
    let expr = match ty {
        Type::Bool => format!("get_bool(dict, &make_key(prefix, \"{field_name}\"))"),
        Type::Uint8 => format!("get_uint8(dict, &make_key(prefix, \"{field_name}\"))"),
        Type::Uint16 => format!("get_uint16(dict, &make_key(prefix, \"{field_name}\"))"),
        Type::Uint32 => format!("get_uint32(dict, &make_key(prefix, \"{field_name}\"))"),
        Type::Uint64 => format!("get_uint64(dict, &make_key(prefix, \"{field_name}\"))"),
        Type::Int8 => format!("get_int8(dict, &make_key(prefix, \"{field_name}\"))"),
        Type::Int16 => format!("get_int16(dict, &make_key(prefix, \"{field_name}\"))"),
        Type::Int32 => format!("get_int32(dict, &make_key(prefix, \"{field_name}\"))"),
        Type::Int64 => format!("get_int64(dict, &make_key(prefix, \"{field_name}\"))"),
        Type::String => format!("get_string(dict, &make_key(prefix, \"{field_name}\"))"),
        Type::ProviderId => {
            format!(
                "get_uint32(dict, &make_key(prefix, \"{}\"))",
                crate::workarounds::provider_id_key()
            )
        }
        Type::Enum(name) => {
            if !schema.enums.contains_key(name) {
                anyhow::bail!("Enum '{}' not found in schema", name);
            }
            format!(
                "get_string(dict, &make_key(prefix, \"{field_name}\")).as_deref().and_then({name}::from_str).or_else(|| get_uint8(dict, &make_key(prefix, \"{field_name}\")).and_then({name}::from_u8))"
            )
        }
        Type::Struct(name) => {
            format!("{name}::parse(dict, &make_key(prefix, \"{field_name}\"))")
        }
        Type::Vector(inner) => match &**inner {
            Type::Struct(name) => {
                if !schema.structs.contains_key(name) {
                    anyhow::bail!("Struct {} referenced in vector not found in schema", name);
                }
                format!(
                    "({{\n                let key = make_key(prefix, \"{field_name}\");\n                let count = get_uint64(dict, &format!(\"{{key}}._count\"))?;\n                let mut items = Vec::with_capacity(count as usize);\n                for i in 0..count {{\n                    let item_prefix = format!(\"{{key}}.{{i}}\");\n                    items.push({name}::parse(dict, &item_prefix)?);\n                }}\n                Some(items)\n            }})"
                )
            }
            Type::Int8 => format!("get_int8_vec(dict, &make_key(prefix, \"{field_name}\"))"),
            Type::Int16 => format!("get_int16_vec(dict, &make_key(prefix, \"{field_name}\"))"),
            Type::Int32 => format!("get_int32_vec(dict, &make_key(prefix, \"{field_name}\"))"),
            Type::Int64 => format!("get_int64_vec(dict, &make_key(prefix, \"{field_name}\"))"),
            Type::Uint8 => format!("get_uint8_vec(dict, &make_key(prefix, \"{field_name}\"))"),
            Type::Uint16 => format!("get_uint16_vec(dict, &make_key(prefix, \"{field_name}\"))"),
            Type::Uint32 => format!("get_uint32_vec(dict, &make_key(prefix, \"{field_name}\"))"),
            Type::Uint64 => format!("get_uint64_vec(dict, &make_key(prefix, \"{field_name}\"))"),
            Type::String => format!("get_str_vec(dict, &make_key(prefix, \"{field_name}\"))"),
            _ => anyhow::bail!("Unsupported vector element type for Rust generation: {:?}", inner),
        },
    };
    Ok(expr)
}

fn get_dependencies(struct_def: &StructDef) -> HashSet<String> {
    let mut deps = HashSet::new();
    for field in &struct_def.fields {
        add_deps(&field.ty, &mut deps);
    }
    deps
}

fn add_deps(ty: &Type, deps: &mut HashSet<String>) {
    match ty {
        Type::Struct(name) => {
            deps.insert(name.clone());
        }
        Type::Vector(inner) => {
            add_deps(inner, deps);
        }
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::Field;
    use std::collections::HashMap;

    fn make_schema(structs: Vec<StructDef>) -> Schema {
        let mut struct_map = HashMap::new();
        for s in structs {
            struct_map.insert(s.name.clone(), s);
        }
        Schema {
            id: "test_metadata".to_string(),
            enums: HashMap::new(),
            structs: struct_map,
            root_layout: StructDef { name: "Root".to_string(), fields: vec![] },
        }
    }

    #[test]
    fn test_topological_sort_success() {
        let struct_b = StructDef {
            name: "StructB".to_string(),
            fields: vec![Field { name: "val".to_string(), ty: Type::Uint32, optional: false }],
        };
        let struct_a = StructDef {
            name: "StructA".to_string(),
            fields: vec![Field {
                name: "b".to_string(),
                ty: Type::Struct("StructB".to_string()),
                optional: false,
            }],
        };

        let schema = make_schema(vec![struct_a, struct_b]);
        let res = generate_rust_parser(&[schema], "my_driver", "2026");
        assert!(res.is_ok());
        let code = res.unwrap();

        let idx_b = code.find("pub struct StructB {").unwrap();
        let idx_a = code.find("pub struct StructA {").unwrap();
        assert!(idx_b < idx_a, "StructB must be defined before StructA");
    }

    #[test]
    fn test_topological_sort_circular_error() {
        let struct_a = StructDef {
            name: "StructA".to_string(),
            fields: vec![Field {
                name: "b".to_string(),
                ty: Type::Struct("StructB".to_string()),
                optional: false,
            }],
        };
        let struct_b = StructDef {
            name: "StructB".to_string(),
            fields: vec![Field {
                name: "a".to_string(),
                ty: Type::Struct("StructA".to_string()),
                optional: false,
            }],
        };

        let schema = make_schema(vec![struct_a, struct_b]);
        let res = generate_rust_parser(&[schema], "my_driver", "2026");
        assert!(res.is_err());
    }

    #[test]
    fn test_generate_rust_parser_comprehensive() {
        let mut enums = HashMap::new();
        enums.insert(
            "MyEnum".to_string(),
            EnumDef {
                name: "MyEnum".to_string(),
                variants: vec!["First".to_string(), "Second".to_string()],
            },
        );

        let mut structs = HashMap::new();
        structs.insert(
            "ChildStruct".to_string(),
            StructDef {
                name: "ChildStruct".to_string(),
                fields: vec![
                    Field { name: "id".to_string(), ty: Type::Uint32, optional: false },
                    Field { name: "tag".to_string(), ty: Type::String, optional: true },
                ],
            },
        );

        let root = StructDef {
            name: "Root".to_string(),
            fields: vec![
                Field { name: "flag".to_string(), ty: Type::Bool, optional: false },
                Field {
                    name: "mode".to_string(),
                    ty: Type::Enum("MyEnum".to_string()),
                    optional: true,
                },
                Field {
                    name: "children".to_string(),
                    ty: Type::Vector(Box::new(Type::Struct("ChildStruct".to_string()))),
                    optional: false,
                },
                Field {
                    name: "numbers".to_string(),
                    ty: Type::Vector(Box::new(Type::Uint32)),
                    optional: true,
                },
            ],
        };

        let schema =
            Schema { id: "comprehensive_metadata".to_string(), enums, structs, root_layout: root };

        let res = generate_rust_parser(&[schema], "test-driver", "2026");
        assert!(res.is_ok());
        let code = res.unwrap();

        assert!(code.contains("pub enum MyEnum {"));
        assert!(code.contains("pub fn from_u8(val: u8) -> Option<Self>"));
        assert!(code.contains("pub fn from_str(s: &str) -> Option<Self>"));
        assert!(code.contains("\"First\" => Some(Self::First)"));
        assert!(code.contains("\"Second\" => Some(Self::Second)"));
        assert!(code.contains(
            "get_string(dict, &make_key(prefix, \"mode\")).as_deref().and_then(MyEnum::from_str).or_else(|| get_uint8(dict, &make_key(prefix, \"mode\")).and_then(MyEnum::from_u8))"
        ));
        assert!(code.contains("pub struct ChildStruct {"));
        assert!(code.contains("pub struct Test_driverMetadata {"));
        assert!(
            code.contains("pub fn parse(dict: &fdr::Dictionary, prefix: &str) -> Option<Self>")
        );
        assert!(code.contains("pub fn parse_bytes(bytes: &[u8]) -> Option<Self>"));
    }

    #[test]
    fn test_enum_parsing_string_and_integer_rust() {
        let mut enums = HashMap::new();
        enums.insert(
            "SpeedMode".to_string(),
            EnumDef {
                name: "SpeedMode".to_string(),
                variants: vec!["Low".to_string(), "Medium".to_string(), "High".to_string()],
            },
        );

        let root = StructDef {
            name: "DeviceConfig".to_string(),
            fields: vec![Field {
                name: "speed".to_string(),
                ty: Type::Enum("SpeedMode".to_string()),
                optional: false,
            }],
        };

        let mut structs = HashMap::new();
        structs.insert("DeviceConfig".to_string(), root.clone());

        let schema = Schema { id: "test_metadata".to_string(), enums, structs, root_layout: root };

        let res = generate_rust_parser(&[schema], "speed-driver", "2026");
        assert!(res.is_ok());
        let code = res.unwrap();

        assert!(code.contains("pub enum SpeedMode {"));
        assert!(code.contains("    Low = 0,"));
        assert!(code.contains("    Medium = 1,"));
        assert!(code.contains("    High = 2,"));

        assert!(code.contains("pub fn from_u8(val: u8) -> Option<Self>"));
        assert!(code.contains("0 => Some(Self::Low)"));
        assert!(code.contains("1 => Some(Self::Medium)"));
        assert!(code.contains("2 => Some(Self::High)"));

        assert!(code.contains("pub fn from_str(s: &str) -> Option<Self>"));
        assert!(code.contains("\"Low\" => Some(Self::Low)"));
        assert!(code.contains("\"Medium\" => Some(Self::Medium)"));
        assert!(code.contains("\"High\" => Some(Self::High)"));

        assert!(code.contains(
            "speed: get_string(dict, &make_key(prefix, \"speed\")).as_deref().and_then(SpeedMode::from_str).or_else(|| get_uint8(dict, &make_key(prefix, \"speed\")).and_then(SpeedMode::from_u8))?"
        ));
    }

    #[test]
    fn test_generate_rust_parser_multiple_schemas() {
        let schema1 = Schema {
            id: "fuchsia.hardware.powerdomain.DomainMetadata".to_string(),
            enums: HashMap::new(),
            structs: {
                let mut m = HashMap::new();
                m.insert(
                    "PowerDomain".to_string(),
                    StructDef {
                        name: "PowerDomain".to_string(),
                        fields: vec![
                            Field { name: "id".to_string(), ty: Type::Uint32, optional: false },
                            Field {
                                name: "node_id".to_string(),
                                ty: Type::Uint32,
                                optional: false,
                            },
                            Field { name: "name".to_string(), ty: Type::String, optional: true },
                        ],
                    },
                );
                m
            },
            root_layout: StructDef {
                name: "DomainMetadata".to_string(),
                fields: vec![Field {
                    name: "domains".to_string(),
                    ty: Type::Vector(Box::new(Type::Struct("PowerDomain".to_string()))),
                    optional: false,
                }],
            },
        };

        let schema2 = Schema {
            id: "fuchsia.hardware.reset.Metadata".to_string(),
            enums: HashMap::new(),
            structs: {
                let mut m = HashMap::new();
                m.insert(
                    "ResetDescriptor".to_string(),
                    StructDef {
                        name: "ResetDescriptor".to_string(),
                        fields: vec![Field {
                            name: "id".to_string(),
                            ty: Type::Uint32,
                            optional: false,
                        }],
                    },
                );
                m
            },
            root_layout: StructDef {
                name: "ResetMetadata".to_string(),
                fields: vec![
                    Field { name: "controller_id".to_string(), ty: Type::Uint32, optional: true },
                    Field {
                        name: "resets".to_string(),
                        ty: Type::Vector(Box::new(Type::Struct("ResetDescriptor".to_string()))),
                        optional: false,
                    },
                ],
            },
        };

        let res = generate_rust_parser(&[schema1, schema2], "google-cpm", "2026");
        assert!(res.is_ok());
        let code = res.unwrap();

        assert!(code.contains("pub struct PowerDomain {"));
        assert!(code.contains("pub struct DomainMetadata {"));
        assert!(code.contains("pub struct ResetDescriptor {"));
        assert!(code.contains("pub struct ResetMetadata {"));
        assert!(code.contains("impl DomainMetadata {"));
        assert!(code.contains("impl ResetMetadata {"));
    }
}
