# Copyright 2024 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# These targets are included in GN via //examples/drivers:bazel_drivers

import("//build/bazel/bazel_fuchsia_test_package.gni")

bazel_fuchsia_test_package("driver_transport_example_test") {
  bazel_target = ":driver-transport-test"
  test_component_names = [
    "child-driver-test-bin",
    "parent-driver-test-bin",
  ]
  test_specs = {
    environments = basic_envs
  }
}
