# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

[package]
name = "sapphire-buffer"
version = "0.1.0"
edition = "2024"

[dependencies]
sapphire-collections = { path = "../sapphire-collections" }

[features]
default = []
alloc = []
std = [
  "alloc",
  "sapphire-collections/std",
]

[dev-dependencies]
proptest = { version = "1.11.0", default-features = false, features = ["std"] }
