from mobly.controllers.android_device_lib import errors as errors

class Error(errors.DeviceError): ...
class ServerRestoreConnectionError(Error): ...
class ServerStartError(Error): ...
class ServerStartProtocolError(ServerStartError): ...
class ServerStartPreCheckError(Error): ...
class ApiError(Error): ...

class ProtocolError(Error):
    NO_RESPONSE_FROM_HANDSHAKE: str
    NO_RESPONSE_FROM_SERVER: str
    MISMATCHED_API_ID: str
    RESPONSE_MISSING_FIELD: str

class ServerDiedError(Error): ...
class CallbackHandlerBaseError(errors.DeviceError): ...
class CallbackHandlerTimeoutError(Error): ...
