# Copyright 2026 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/components.gni")
import("//build/rust/rustc_library.gni")

group("range_check") {
  public_deps = [ ":range_check_rs" ]
}

rustc_library("range_check_rs") {
  edition = "2024"
  name = "range_check"
  sources = [ "src/lib.rs" ]
  if (!is_kernel) {
    with_unit_tests = true
  }
}

if (!is_kernel) {
  fuchsia_unittest_package("range-check-rust-test-pkg") {
    package_name = "range-check-rust-test"
    deps = [ ":range_check_rs_test" ]
  }
}

group("tests") {
  testonly = true
  if (!is_kernel) {
    deps = [ ":range-check-rust-test-pkg" ]
  }
}

group("kernel-tests") {
  testonly = true
}

group("phys-tests") {
  testonly = true
}

group("boot_tests") {
  testonly = true
}
