# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bazel/bazel_host_tool.gni")

bazel_host_tool("fidl_api_summarize") {
  bazel_target = ":fidl_api_summarize"
  bazel_output_path =
      "{{BAZEL_TARGET_OUT_DIR}}/fidl_api_summarize_/fidl_api_summarize"
  install_host_tool = true
}
