# See https://jj-vcs.github.io/jj/latest/config/ for the schema.

[revset-aliases]
"trunk()" = "main@origin"
"immutable_heads()" = "remote_bookmarks() | tags()"

[aliases]
upload = [ "util", "exec", "jiri", "upload" ]

[git]
auto-local-bookmark = false
# This is unrelated to gerrit change IDs.
# It will eventually be supported by gerrit instead of the Change-ID footer.
write-change-id-header = true

[templates]
commit_trailers = '''
if(
  !trailers.contains_key("Change-Id"),
  format_gerrit_change_id_trailer(self)
)
'''

# Unfortunately we cannot use `fx format-code` with `jj fix` as they have
# incompatible contracts. The best we can do is make sure that `jj fix` does
# not clobber any changes.

# We cannot even directly call `shac` for the formatting, as `shac fmt` will
# not emit the "formatted" file on STDOUT, which causes `jj` to assume the
# file should have no contents and will just truncate it in place.

# Since we have google3format explicitly disabled below if we run
# `jj fix` or `jj fix --include-unchanged-files` with this disabled, then
# we will get the error:
# `Config error: At least one entry of `fix.tools` must be enabled.`
# To avoid this, we'll make a 'null' fix tool that matches nothing.
[fix.tools.null]
enabled = true
command = [ "echo" ]
patterns = [ "null" ]

# For users of jj-on-piper, this is enabled by default for *all* repos.
# We want Fuchsia's formatters, not google3's.
[fix.tools.google3format]
enabled = false
# If you're not using the google-internal jj, this will complain that
# google3format is an invalid fix tool because it has no command/patterns
command = ["/dev/null"]
patterns = ["null"]
