# See https://jj-vcs.github.io/jj/latest/config/ for the schema.

[revset-aliases]
"trunk()" = "main@origin"
"immutable_heads()" = "remote_bookmarks() | tags()"

[aliases]
upload = [ "util", "exec", "jiri", "upload" ]

[git]
auto-local-bookmark = false
# This is unrelated to gerrit change IDs.
# It will eventually be supported by gerrit instead of the Change-ID footer.
write-change-id-header = true

[templates]
commit_trailers = '''
if(
  !trailers.contains_key("Change-Id"),
  format_gerrit_change_id_trailer(self)
)
'''

# For users of jj-on-piper, this is enabled by default for *all* repos.
# We want Fuchsia's formatters, not google3's.
[fix.tools.google3format]
enabled = false
# If you're not using the google-internal jj, this will complain that
# google3format is an invalid fix tool because it has no command/patterns
command = ["/dev/null"]
patterns = ["null"]

[fix.tools.fx]
enabled = true
command = [
  "fx",
  "format-code",
  "--emit",
  "--files=$path"
]
patterns = ["all()"]
