# Copyright 2025 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/platforms:constraints.bzl", "HOST_OS_CONSTRAINTS")
load("//build/bazel/rules/idk:idk_host_tool.bzl", "idk_cc_binary_host_tool")

package(default_applicable_licenses = ["//:license"])

idk_cc_binary_host_tool(
    name = "merkleroot",
    srcs = ["merkleroot.cc"],
    api_area = "Zircon",
    category = "partner",
    idk_name = "merkleroot",
    target_compatible_with = HOST_OS_CONSTRAINTS,
    deps = [
        "//src/lib/digest",
        "//zircon/system/ulib/fbl",
    ],
)
