// Copyright 2021 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef SRC_GRAPHICS_DISPLAY_DRIVERS_AMLOGIC_DISPLAY_VOUT_H_
#define SRC_GRAPHICS_DISPLAY_DRIVERS_AMLOGIC_DISPLAY_VOUT_H_

#include <fidl/fuchsia.images2/cpp/wire.h>
#include <lib/device-protocol/display-panel.h>
#include <lib/driver/incoming/cpp/namespace.h>
#include <lib/inspect/cpp/inspect.h>
#include <lib/zx/result.h>
#include <zircon/errors.h>
#include <zircon/types.h>

#include <cstdint>
#include <memory>
#include <optional>

#include <fbl/static_vector.h>
#include <fbl/vector.h>

#include "src/graphics/display/drivers/amlogic-display/clock.h"
#include "src/graphics/display/drivers/amlogic-display/dsi-host.h"
#include "src/graphics/display/drivers/amlogic-display/hdmi-host.h"
#include "src/graphics/display/drivers/amlogic-display/panel-config.h"
#include "src/graphics/display/lib/api-types/cpp/display-id.h"
#include "src/graphics/display/lib/api-types/cpp/display-timing.h"
#include "src/graphics/display/lib/api-types/cpp/mode-and-id.h"
#include "src/graphics/display/lib/api-types/cpp/mode.h"
#include "src/graphics/display/lib/edid/edid.h"

namespace amlogic_display {

enum class VoutType : uint8_t {
  kDsi,
  kHdmi,
};

struct AddedDisplayInfo {
  // Maximum size of the `preferred_modes`.
  static constexpr int kMaxPreferredModes = 32;

  display::DisplayId display_id;
  fbl::Vector<display::ModeAndId> preferred_modes;
};

// Represents the Video Output (VOUT) module and the connected display device.
class Vout {
 public:
  // Returns a non-null pointer to the Vout instance outputting DSI signal on
  // success.
  static zx::result<std::unique_ptr<Vout>> CreateDsiVout(fdf::Namespace& incoming,
                                                         display::PanelType panel_type,
                                                         inspect::Node node);

  // Returns a non-null pointer to the Vout instance outputting HDMI signal on
  // success.
  static zx::result<std::unique_ptr<Vout>> CreateHdmiVout(fdf::Namespace& incoming,
                                                          inspect::Node node,
                                                          uint8_t visual_debug_level);

  // Sets only the display feature bits and panel settings for testing.
  // Returns a non-null pointer to the Vout instance on success.
  static zx::result<std::unique_ptr<Vout>> CreateDsiVoutForTesting(display::PanelType panel_type);

  // Creates a Vout instance that outputs MIPI-DSI signal.
  //
  // `panel_config` must be non-null and must outlive the `Vout` instance.
  Vout(std::unique_ptr<DsiHost> dsi_host, std::unique_ptr<Clock> dsi_clock,
       const PanelConfig* panel_config, inspect::Node node);

  // Creates a Vout instance that outputs HDMI signal.
  Vout(std::unique_ptr<HdmiHost> hdmi_host, inspect::Node node, uint8_t visual_debug_level);

  Vout(Vout&&) = delete;
  Vout(const Vout&) = delete;
  Vout& operator=(Vout&&) = delete;
  Vout& operator=(const Vout&) = delete;

  AddedDisplayInfo CreateAddedDisplayInfo(display::DisplayId display_id);

  VoutType type() { return type_; }
  bool supports_hpd() const { return supports_hpd_; }

  zx::result<> UpdateStateOnDisplayConnected();
  void DisplayDisconnected();

  // `mode_id` must be valid.
  std::optional<display::Mode> GetDisplayMode(display::ModeId mode_id) const;

  zx::result<> ApplyConfiguration(display::ModeId mode_id);

  // Attempt to turn off all connected displays, and disable clocks. This will
  // also stop vsync interrupts. This is aligned with the interface for
  // fuchsia.hardware.display, where a disabled display does not produce OnVsync
  // events.
  //
  // This method is not guaranteed to power off all devices. Returns ZX_OK if
  // successful, ZX_ERR_UNSUPPORTED if the panel cannot be powered off. May
  // return other errors.
  zx::result<> PowerOff();

  // Turn on all connected displays and reprogram clocks. This will resume vsync
  // interrupts as well.
  //
  // This method is not guaranteed to power on all devices. Returns ZX_OK if
  // successful, ZX_ERR_UNSUPPORTED if the panel cannot be powered on. May
  // return other errors.
  zx::result<> PowerOn();

  // Makes the frames generated by the Video Input Unit (VIU) visible if
  // `frame_visible` is true. Otherwise, hides the frame generated by the VIU.
  //
  // Returns ZX_ERR_NOT_SUPPORTED if the Video Output Module doesn't support
  // hiding video input unit frames.
  zx::result<> SetFrameVisibility(bool frame_visible);

  void Dump();

 private:
  VoutType type_;

  // Features
  bool supports_hpd_ = false;

  inspect::Node node_;

  struct dsi_t {
    std::unique_ptr<DsiHost> dsi_host;
    std::unique_ptr<Clock> clock;

    // TODO(https://fxbug.dev/318800903): Use const reference when `dsi_` moves
    // to its own implementation class.
    PanelConfig panel_config;

    // Matches the timing in `panel_config`.
    std::optional<display::ModeAndId> mode_and_id;
  } dsi_;

  struct hdmi_t {
    std::unique_ptr<HdmiHost> hdmi_host;

    std::optional<edid::Edid> edid;

    // The timing parameter at index `k` corresponds to ModeId `k+1`.
    fbl::Vector<display::DisplayTiming> timings;

    display::ModeId current_mode_id = display::kInvalidModeId;
  } hdmi_;

  uint8_t visual_debug_level_;
};

}  // namespace amlogic_display

#endif  // SRC_GRAPHICS_DISPLAY_DRIVERS_AMLOGIC_DISPLAY_VOUT_H_
