// Copyright 2021 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef SRC_GRAPHICS_DISPLAY_DRIVERS_AMLOGIC_DISPLAY_VOUT_H_
#define SRC_GRAPHICS_DISPLAY_DRIVERS_AMLOGIC_DISPLAY_VOUT_H_

#include <fidl/fuchsia.images2/cpp/wire.h>
#include <lib/device-protocol/display-panel.h>
#include <lib/driver/incoming/cpp/namespace.h>
#include <lib/inspect/cpp/inspect.h>
#include <lib/zx/result.h>
#include <zircon/errors.h>
#include <zircon/types.h>

#include <cstdint>
#include <memory>
#include <optional>

#include <fbl/static_vector.h>
#include <fbl/vector.h>

#include "src/graphics/display/lib/api-types/cpp/display-id.h"
#include "src/graphics/display/lib/api-types/cpp/display-timing.h"
#include "src/graphics/display/lib/api-types/cpp/mode-and-id.h"
#include "src/graphics/display/lib/api-types/cpp/mode.h"

namespace amlogic_display {

enum class VoutType : uint8_t {
  kDsi,
  kHdmi,
};

struct AddedDisplayInfo {
  // Maximum size of the `preferred_modes`.
  static constexpr int kMaxPreferredModes = 32;

  display::DisplayId display_id;
  fbl::Vector<display::ModeAndId> preferred_modes;
};

// Represents the Video Output (VOUT) module and the connected display device.
class Vout {
 public:
  virtual ~Vout() = default;

  // Returns the type of the video output module.
  virtual VoutType type() const = 0;

  // Returns true if the video output module supports hot-plug detection.
  virtual bool SupportsHotplugDetection() const = 0;

  // Creates display information to be sent to the display coordinator when a
  // display is connected.
  virtual AddedDisplayInfo CreateAddedDisplayInfo(display::DisplayId display_id) = 0;

  // Updates the internal state of the Vout module when a display is connected.
  virtual zx::result<> UpdateStateOnDisplayConnected() = 0;

  // Updates the internal state of the Vout module when a display is disconnected.
  virtual void DisplayDisconnected() = 0;

  // Returns the display mode corresponding to the given `mode_id`.
  // `mode_id` must be valid.
  virtual std::optional<display::Mode> GetDisplayMode(display::ModeId mode_id) const = 0;

  // Applies the configuration for the given `mode_id`.
  virtual zx::result<> ApplyConfiguration(display::ModeId mode_id) = 0;

  // Attempt to turn off all connected displays, and disable clocks. This will
  // also stop vsync interrupts. This is aligned with the interface for
  // fuchsia.hardware.display, where a disabled display does not produce OnVsync
  // events.
  //
  // This method is not guaranteed to power off all devices. Returns ZX_OK if
  // successful, ZX_ERR_UNSUPPORTED if the panel cannot be powered off. May
  // return other errors.
  virtual zx::result<> PowerOff() = 0;

  // Turn on all connected displays and reprogram clocks. This will resume vsync
  // interrupts as well.
  //
  // This method is not guaranteed to power on all devices. Returns ZX_OK if
  // successful, ZX_ERR_UNSUPPORTED if the panel cannot be powered on. May
  // return other errors.
  virtual zx::result<> PowerOn() = 0;

  // Makes the frames generated by the Video Input Unit (VIU) visible if
  // `frame_visible` is true. Otherwise, hides the frame generated by the VIU.
  //
  // Returns ZX_ERR_NOT_SUPPORTED if the Video Output Module doesn't support
  // hiding video input unit frames.
  virtual zx::result<> SetFrameVisibility(bool frame_visible) = 0;

  // Dumps the current state of the Vout module for debugging purposes.
  virtual void Dump() = 0;
};

}  // namespace amlogic_display

#endif  // SRC_GRAPHICS_DISPLAY_DRIVERS_AMLOGIC_DISPLAY_VOUT_H_
