# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_applicable_licenses = ["//:license"])

cc_library(
    name = "cpp",
    hdrs = [
        "circular_deque.h",
        "mpsc_queue.h",
        "ownership.h",
        "template_util.h",
        "vector_buffer.h",
    ],
    copts = ["-Wno-conversion"],
    visibility = ["//visibility:public"],
    deps = ["//zircon/third_party/ulib/safemath"],
    alwayslink = True,
)
