# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_applicable_licenses = ["//:license"])

cc_library(
    name = "headers",
    hdrs = [
        "arm_ehabi_module.h",
        "arm_ehabi_unwinder.h",
        "cfi_unwinder.h",
        "elf_module_cache.h",
        "error.h",
        "fp_unwinder.h",
        "frame.h",
        "loaded_elf_module.h",
        "memory.h",
        "module.h",
        "platform.h",
        "plt_unwinder.h",
        "registers.h",
        "scs_unwinder.h",
        "sigreturn_unwinder.h",
        "third_party/libunwindstack/context.h",
        "unwind.h",
        "unwind_local.h",
        "unwinder_base.h",
    ] + select({
        "@platforms//os:fuchsia": ["fuchsia.h"],
        "@platforms//os:linux": ["linux.h"],
        "//conditions:default": [],
    }),
    deps = ["//sdk/lib/fit"],
)

# These headers are included from unit-tests and must be
# exposed as a separate library for GN include checks.
cc_library(
    name = "internal_headers",
    hdrs = [
        "arm_ehabi_parser.h",
        "dwarf_expr.h",
    ],
    visibility = [":__pkg__"],
    deps = [":headers"],
)

cc_library(
    name = "unwinder",
    srcs = [
        "arm_ehabi_module.cc",
        "arm_ehabi_parser.cc",
        "arm_ehabi_unwinder.cc",
        "cfi_module.cc",
        "cfi_module.h",
        "cfi_parser.cc",
        "cfi_parser.h",
        "cfi_unwinder.cc",
        "dwarf_expr.cc",
        "elf_module_cache.cc",
        "elf_utils.cc",
        "elf_utils.h",
        "error.cc",
        "fp_unwinder.cc",
        "loaded_elf_module.cc",
        "memory.cc",
        "module.cc",
        "plt_unwinder.cc",
        "registers.cc",
        "scs_unwinder.cc",
        "sigreturn_unwinder.cc",
        "unwind.cc",
        "unwind_local.cc",
        "unwinder_base.cc",
    ] + select({
        "@platforms//cpu:x86_64": [
            "third_party/libunwindstack/context_x86_64.S",
        ],
        "//conditions:default": [],
    }) + select({
        "@platforms//os:fuchsia": [
            "fuchsia.cc",
        ],
        "@platforms//os:linux": [
            "linux.cc",
        ],
        "//conditions:default": [],
    }),
    implementation_deps = [
        ":internal_headers",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
        "//zircon/third_party/ulib/safemath",
        "@com_google_googletest//:gtest_prod",
    ],
)
