# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# A forwarding target to the Bazel-built bundle_fetcher host tool.
group("bundle_fetcher") {
  public_deps = [ ":host" ]
}

group("host") {
  public_deps = [ "//build/bazel/host:bazel_root_host_tools.bundle_fetcher.host_tool($host_toolchain)" ]
}
