# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")
load("//build/bazel/rules/host:defs.bzl", "go_binary_host_tool")
load("//build/bazel/rules/host_tests:host_go_test.bzl", "host_go_test")

package(default_applicable_licenses = ["//:license"])

go_library(
    name = "bundler",
    srcs = [
        "bundler/cloud_sink.go",
        "bundler/cloud_sink_mock.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/bundle_fetcher/bundler",
    target_compatible_with = HOST_CONSTRAINTS,
    deps = [
        "//third_party/golibs:cloud.google.com/go/storage",
        "//third_party/golibs:google.golang.org/api/iterator",
        "//tools/build",
        "//tools/lib/logger",
        "//tools/lib/osmisc",
    ],
)

go_library(
    name = "main",
    srcs = [
        "cmd/main.go",
        "cmd/product_list.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/bundle_fetcher/cmd",
    target_compatible_with = HOST_CONSTRAINTS,
    deps = [
        ":bundler",
        "//third_party/golibs:github.com/google/subcommands",
        "//tools/build",
        "//tools/lib/color",
        "//tools/lib/logger",
    ],
)

go_binary_host_tool(
    name = "bundle_fetcher",
    embed = [":main"],
    target_compatible_with = HOST_CONSTRAINTS,
)

host_go_test(
    name = "bundler_lib_tests",
    srcs = [
        "bundler/cloud_sink_test.go",
    ],
    embed = [":bundler"],
    visibility = ["//tools:__pkg__"],
    deps = [
        "//third_party/golibs:github.com/google/go-cmp/cmp",
    ],
)

host_go_test(
    name = "bundle_fetcher_main_tests",
    srcs = [
        "cmd/product_list_test.go",
    ],
    embed = [":main"],
    visibility = ["//tools:__pkg__"],
    deps = [
        "//third_party/golibs:github.com/google/go-cmp/cmp",
    ],
)
