# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bind/bind.gni")
import("//build/components.gni")
import("//build/drivers.gni")

driver_bind_rules("bind") {
  rules = "meta/probe_gpio_driver.bind"
  bind_output = "probe_gpio_driver.bindbc"
  deps = [ "//src/devices/bind/fuchsia.test" ]
}

fuchsia_cc_driver("driver") {
  output_name = "probe_gpio"
  sources = [
    "probe_gpio_driver.cc",
    "probe_gpio_driver.h",
  ]
  deps = [
    "//sdk/fidl/fuchsia.hardware.gpio:fuchsia.hardware.gpio_cpp",
    "//sdk/fidl/fuchsia.hardware.pin:fuchsia.hardware.pin_cpp",
    "//sdk/lib/driver/component/cpp",
    "//sdk/lib/driver/devfs/cpp",
    "//sdk/lib/driver/logging/cpp",
    "//src/devices/lib/driver:driver_runtime",
  ]
}

fuchsia_driver_component("component") {
  component_name = "probe_gpio_driver"
  manifest = "meta/probe_gpio_driver.cml"
  deps = [
    ":bind",
    ":driver",
  ]
  info = "meta/probe_gpio_driver_info.json"
}

fuchsia_driver_package("probe_gpio_driver") {
  package_name = "probe_gpio_driver"
  driver_components = [ ":component" ]
}
