# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/components/fuchsia_unittest_package.gni")
import("//build/test.gni")

group("tests") {
  testonly = true
  if (current_cpu == "x64") {
    deps = [ ":x86-umip-test" ]
  }
}

test("x86-umip") {
  sources = [ "main.cc" ]
  deps = [
    "//src/lib/captive-thread/testing",
    "//src/lib/fxl/test:gtest_main",
    "//zircon/kernel/lib/arch",
  ]
}

fuchsia_unittest_package("x86-umip-test") {
  deps = [ ":x86-umip" ]
}
