# Copyright 2019 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/cpp/library_headers.gni")
import("//zircon/kernel/kernel_rust_mod.gni")

library_headers("headers") {
  headers = [ "pdev/power.h" ]
}

kernel_rust_mod("power-rs") {
  output_name = "pdev_power"
  source_root = "power.rs"
  sources = [ "power.rs" ]
  deps = [
    "//sdk/rust/zx-status",
    "//src/lib/zr",
  ]
  test_deps = [ "//zircon/kernel/lib/unittest:unittest-rs" ]
}

source_set("power") {
  sources = [ "power_ffi.cc" ]
  public_deps = [ ":headers" ]
  deps = [ ":power-rs" ]
}
