// Copyright 2026 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

use zerocopy::{FromBytes, FromZeros, Immutable, IntoBytes};

/// Trait for types that can represent a register's value.
///
/// It is implemented by the `Value` structs generated by the
/// `spmi_register!` macro, bounding it by Sized, FromBytes, IntoBytes,
/// FromZeros, and Immutable for safe memory casting.
pub trait RegisterValue: Sized + FromBytes + IntoBytes + FromZeros + Immutable {}

// --- Typestate Access Modes ---
// These markers are used to enforce register access rules
// (Read-Only, Write-Only, Read-Write) at compile time using
// the typestate pattern.

/// Marker struct representing Read-Only register access.
pub struct ReadOnly;

/// Marker struct representing Write-Only register access.
pub struct WriteOnly;

/// Marker struct representing Read-Write register access.
pub struct ReadWrite;

/// Trait implemented by access modes that allow reading.
///
/// This is used as a generic bound on `Register::read` to prevent compile-time
/// errors when attempting to read from write-only registers.
pub trait Readable {}
impl Readable for ReadOnly {}
impl Readable for ReadWrite {}

/// Trait implemented by access modes that allow writing.
///
/// This is used as a generic bound on `Register::write` to prevent compile-time
/// errors when attempting to write to read-only registers.
pub trait Writable {}
impl Writable for WriteOnly {}
impl Writable for ReadWrite {}

/// A generic register accessor.
///
/// This struct provides type-safe access to a specific hardware register.
/// It is parameterized by:
/// * `T` - The typed `RegisterValue` (usually the generated `Value` struct).
/// * `M` - The access mode (`ReadOnly`, `WriteOnly`, or `ReadWrite`).
/// * `D` - The underlying device implementation (implements `SpmiDevice`).
/// * `ADDR` - The constant hardware address of the register.
pub struct _Register<'a, T, M, D, const ADDR: u16> {
    /// The underlying SPMI device.
    pub spmi: &'a D,
    _marker: std::marker::PhantomData<(T, M)>,
}

impl<'a, T, M, D, const ADDR: u16> _Register<'a, T, M, D, ADDR> {
    /// Creates a new register accessor.
    pub fn new(spmi: &'a D) -> Self {
        Self { spmi, _marker: std::marker::PhantomData }
    }
}

// Inherent read method available ONLY if M is Readable and D is SpmiDevice
impl<'a, T, M, D, const ADDR: u16> _Register<'a, T, M, D, ADDR>
where
    M: Readable,
    T: RegisterValue,
    D: SpmiDevice,
{
    /// Reads the register value from the hardware.
    ///
    /// This method performs an asynchronous read operation on the underlying
    /// SPMI device and deserializes the raw bytes into the typed value `T`.
    pub async fn read(&self) -> Result<T, crate::Error> {
        let size = std::mem::size_of::<T>();
        let bytes = self.spmi.read_reg(ADDR, size as u32).await?;
        T::read_from_bytes(&bytes).map_err(|_| crate::Error::SizeMismatch)
    }
}

// Inherent write method available ONLY if M is Writable and D is SpmiDevice
impl<'a, T, M, D, const ADDR: u16> _Register<'a, T, M, D, ADDR>
where
    M: Writable,
    T: RegisterValue,
    D: SpmiDevice,
{
    /// Writes the register value to the hardware.
    ///
    /// This method serializes the typed value `T` into raw bytes and performs
    /// an asynchronous write operation on the underlying SPMI device.
    pub async fn write(&self, val: T) -> Result<(), crate::Error> {
        let bytes = val.as_bytes();
        self.spmi.write_reg(ADDR, bytes).await?;
        Ok(())
    }
}

/// Defines a module for accessing a single SPMI hardware register.
///
/// This macro generates a public module named `$name` containing:
/// -   `ADDRESS`: A `u16` constant for the register address.
/// -   `Value`: A struct wrapping the raw register value (`$value_type`)
///     and providing const-fn accessors for defined fields.
/// -   `Register<'a>`: A struct with an asynchronous `read` and
///     potentially `write` method to interact with the SPMI device.
///
/// # Arguments
///
/// 1.  `$name`: The identifier for the generated module.
/// 2.  `$value_type:ty`: The Rust integer type representing the register's
///     width (e.g., `u8`, `u16`, `u32`).
/// 3.  `$addr:expr`: The base address of the register as a `u16`.
/// 4.  `$mode:ident`: The access mode, one of `RO` (Read Only), `WO` (Write
///     Only), or `RW` (Read/Write).
/// 5.  `$endianness:ident`: The endianness of the register. Required for `u16`
///     and larger. Can be `LE` (Little Endian) or `BE` (Big Endian). For `u8`
///     registers, this argument is omitted because endianness is irrelevant
///     for `u8` registers.
/// 6.  `{ ... }`: A block defining the fields within the register. Each
///     field definition ends with a semicolon. The following formats are
///     supported within the block:
///     *   **Single-bit field:** `$vis $field_name $(, $setter_name)? : $bit;`
///         -   `$vis`: Visibility (e.g., `pub`).
///         -   `$field_name`: The name of the getter method (returns `bool`).
///         -   `$setter_name`: (Optional) The name of the setter method
///             (takes `bool`, returns `Self`).
///         -   `$bit_index`: The index of the single bit (e.g., `7`).
///         Example: `pub enable, set_enable: 7;`
///
///     *   **Multi-bit field:** `$vis $field_name $(, $setter_name)? \
///         : $msb, $lsb;`
///         -   `$vis`: Visibility.
///         -   `$field_name`: The getter method (returns `$value_type`).
///         -   `$setter_name`: (Optional) The setter method (takes
///             `$value_type`, returns `Self`).
///         -   `$msb`: The Most Significant Bit index.
///         -   `$lsb`: The Least Significant Bit index.
///         Example: `pub field_val, set_field_val: 5, 2;`
///
///     *   **Enum field (external type):** `$vis enum $enum_type, $field_name \
///         $(, $setter_name)? : $msb, $lsb;`
///         -   `$vis`: Visibility.
///         -   `$enum_type`: The path to an existing enum type (e.g.,
///             `super::PowerMode`). This enum must have a `pub const fn \
///             from_val(val: $value_type) -> Self` associated function.
///         -   `$field_name`: The getter method (returns `$enum_type`).
///         -   `$setter_name`: (Optional) The setter method (takes
///             `$enum_type`, returns `Self`).
///         -   `$msb`, `$lsb`: The bit range.
///         Example: `pub enum super::PowerMode, mode, set_mode: 3, 2;`
///
///     *   **In-line Enum field:** `$vis enum $enum_name { ... }, $field_name \
///         $(, $setter_name)? : $msb, $lsb;`
///         -   `$vis`: Visibility.
///         -   `$enum_name`: The name for the enum type, defined within
///             the generated module.
///         -   `{ ... }`: The enum variants and their `$value_type` values.
///         -   `$field_name`: The getter method (returns `Result<$enum_name, \
///             $value_type>`).
///         -   `$setter_name`: (Optional) The setter method (takes
///             `$enum_name`, returns `Self`).
///         -   `$msb`, `$lsb`: The bit range.
///         Example: `pub enum InlineMode { A = 0, B = 1 }, \
///             mode, set_mode: 1, 0;`
///
///     *   **Custom constant:** `pub const $const_name : $type = $val;`
///         -   Allows defining constants within the generated register module.
///         Example: `pub const MAX_VALUE: u8 = 0xFF;`
///
/// # Examples
///
/// ```
/// // Define a register at address 0x10, 8-bit, Read/Write,
/// // Little Endian (default)
/// spmi_register! {
///     my_reg, u8, 0x10, RW, {
///         // Single bit flag
///         pub enable, set_enable: 7;
///         // 4-bit field
///         pub value, set_value: 3, 0;
///         // Inline enum field
///         pub enum Status {
///             Idle = 0,
///             Active = 1,
///             Error = 2,
///         }, status, set_status: 6, 5;
///     }
/// }
///
/// // Define a register at address 0x20, 16-bit, Read Only, Big Endian
/// spmi_register! {
///     status_be_reg, u16, 0x20, RO, BE, {
///         pub error_code: 15, 8;
///         pub ready: 0;
///     }
/// }
/// ```
#[macro_export]
macro_rules! spmi_register {
    // Helper to map mode and endianness to register type
    (@map_reg RO, $val:ty, $addr:expr, BE) => {
        $crate::Register<'a, $val, $crate::ReadOnly, $addr>
    };
    (@map_reg RO, $val:ty, $addr:expr, LE) => {
        $crate::Register<'a, $val, $crate::ReadOnly, $addr>
    };
    (@map_reg WO, $val:ty, $addr:expr, BE) => {
        $crate::Register<'a, $val, $crate::WriteOnly, $addr>
    };
    (@map_reg WO, $val:ty, $addr:expr, LE) => {
        $crate::Register<'a, $val, $crate::WriteOnly, $addr>
    };
    (@map_reg RW, $val:ty, $addr:expr, BE) => {
        $crate::Register<'a, $val, $crate::ReadWrite, $addr>
    };
    (@map_reg RW, $val:ty, $addr:expr, LE) => {
        $crate::Register<'a, $val, $crate::ReadWrite, $addr>
    };

    // Explicit-endian byteorder helpers inside macro
    (@byteorder_type u8, $endianness:ident) => { u8 };
    (@byteorder_type u16, LE) => { $crate::U16<$crate::LittleEndian> };
    (@byteorder_type u16, BE) => { $crate::U16<$crate::BigEndian> };
    (@byteorder_type u32, LE) => { $crate::U32<$crate::LittleEndian> };
    (@byteorder_type u32, BE) => { $crate::U32<$crate::BigEndian> };

    (@new u8, $endianness:ident, $val:expr) => { Self($val) };
    (@new u16, $endianness:ident, $val:expr) => {
        Self($crate::U16::new($val))
    };
    (@new u32, $endianness:ident, $val:expr) => {
        Self($crate::U32::new($val))
    };

    (@get u8, $endianness:ident, $val:expr) => { $val };
    (@get u16, $endianness:ident, $val:expr) => { $val.get() };
    (@get u32, $endianness:ident, $val:expr) => { $val.get() };

    // Explicit endianness provided via single arm
    (
        $name:ident,
        $value_type:ident,
        $addr:expr,
        $mode:ident,
        $endianness:ident,
        {
            $($tail:tt)*
        }
    ) => {
        #[allow(unused_imports)]
        #[allow(dead_code)]
        pub mod $name {
            use super::*;
            use $crate::zerocopy_reexport as zerocopy;

            /// The address of the register.
            pub const ADDRESS: u16 = $addr;

            $crate::spmi_register_extract_enums!($value_type, $($tail)*);

            /// Represents the value of the register.
            #[derive(
                Copy,
                Clone,
                Debug,
                PartialEq,
                Eq,
                zerocopy::FromBytes,
                zerocopy::IntoBytes,
                zerocopy::Immutable,
            )]
            #[repr(transparent)]
            pub struct Value(
                pub spmi_register!(@byteorder_type $value_type, $endianness),
            );

            impl Value {
                pub const fn new(val: $value_type) -> Self {
                    spmi_register!(@new $value_type, $endianness, val)
                }
                pub const fn reg_value(&self) -> $value_type {
                    spmi_register!(@get $value_type, $endianness, self.0)
                }

                /// Reconstructs a typed `Value` from a slice of raw bytes.
                pub fn from_bytes(bytes: &[u8]) -> Result<Self, $crate::Error> {
                    zerocopy::FromBytes::read_from_bytes(bytes)
                        .map_err(|_| $crate::Error::SizeMismatch)
                }

                /// Converts the `Value` into its raw byte representation.
                pub fn to_bytes(
                    &self,
                ) -> [u8; std::mem::size_of::<$value_type>()] {
                    let mut arr = [0u8; std::mem::size_of::<$value_type>()];
                    arr.copy_from_slice($crate::IntoBytes::as_bytes(self));
                    arr
                }

                $crate::spmi_register_fields!($value_type, $($tail)*);
            }

            impl $crate::RegisterValue for Value {}

            impl Default for Value {
                fn default() -> Self {
                    Self::new(0 as $value_type)
                }
            }

            /// The register accessor type.
            pub type Register<'a> =
                spmi_register!(@map_reg $mode, Value, $addr, $endianness);
        }
    };
    // Specialized arm for u8 where endianness is irrelevant
    (
        $name:ident, u8, $addr:expr, $mode:ident, {
            $($tail:tt)*
        }
    ) => {
        spmi_register!($name, u8, $addr, $mode, LE, { $($tail)* });
    };
    (@is_big BE) => { true };
    (@is_big LE) => { false };
}

/// Helper macro for `spmi_register!` to extract inline enums.
#[macro_export]
#[doc(hidden)]
macro_rules! spmi_register_extract_enums {
    // In-line Enum
    (
        $value_type:ty,
        $(#[$attr:meta])*
        $vis:vis enum $enum_name:ident {
            $( $variant_name:ident = $variant_val:expr ),* $(,)?
        },
        $field:ident $(, $setter:ident)? : $msb:expr, $lsb:expr;
        $($tail:tt)*
    ) => {
        #[derive(Debug, PartialEq, Eq, Copy, Clone)]
        #[repr($value_type)]
        $vis enum $enum_name {
            $( $variant_name = $variant_val ),*
        }
        $crate::spmi_register_extract_enums!($value_type, $($tail)*);
    };

    // Forwarding other cases
    (
        $value_type:ty,
        $(#[$attr:meta])*
        $vis:vis $field:ident $(, $setter:ident)? : $bit:expr;
        $($tail:tt)*
    ) => {
        $crate::spmi_register_extract_enums!($value_type, $($tail)*);
    };
    (
        $value_type:ty,
        $(#[$attr:meta])*
        $vis:vis $field:ident $(, $setter:ident)? : $msb:expr, $lsb:expr;
        $($tail:tt)*
    ) => {
        $crate::spmi_register_extract_enums!($value_type, $($tail)*);
    };
    (
        $value_type:ty,
        $(#[$attr:meta])*
        $vis:vis enum $enum_type:ty,
        $field:ident $(, $setter:ident)? : $msb:expr, $lsb:expr;
        $($tail:tt)*
    ) => {
        $crate::spmi_register_extract_enums!($value_type, $($tail)*);
    };
    (
        $value_type:ty,
        pub const $name:ident : $type:ty = $val:expr;
        $($tail:tt)*
    ) => {
        $crate::spmi_register_extract_enums!($value_type, $($tail)*);
    };
    ($value_type:ty) => {};
    ($value_type:ty,) => {};
}

/// Helper macro for `spmi_register!` to generate field accessors.
#[macro_export]
#[doc(hidden)]
macro_rules! spmi_register_fields {
    // Terminating cases
    ($value_type:ty) => {};
    ($value_type:ty,) => {};

    // 1. Single-bit field
    (
        $value_type:ty,
        $(#[$attr:meta])*
        $vis:vis $field:ident $(, $setter:ident)? : $bit:expr;
        $($tail:tt)*
    ) => {
        $(#[$attr])*
        #[allow(non_snake_case)]
        #[allow(dead_code)]
        $vis const fn $field(&self) -> bool {
            const _: () = assert!(
                $bit < <$value_type>::BITS as u8,
                "Bit index out of bounds"
            );
            let bit_mask = (1 as $value_type) << $bit;
            (self.reg_value() & bit_mask) != 0
        }
        $(
            #[allow(non_snake_case)]
            #[allow(dead_code)]
            $vis const fn $setter(self, val: bool) -> Self {
                const _: () = assert!(
                    $bit < <$value_type>::BITS as u8,
                    "Bit index out of bounds"
                );
                let bit_mask = (1 as $value_type) << $bit;
                let raw = (self.reg_value() & !bit_mask)
                    | ((val as $value_type) << $bit);
                Self::new(raw)
            }
        )?
        $crate::spmi_register_fields!($value_type, $($tail)*);
    };

    // 2. Multi-bit field
    (
        $value_type:ty,
        $(#[$attr:meta])*
        $vis:vis $field:ident $(, $setter:ident)? : $msb:expr, $lsb:expr;
        $($tail:tt)*
    ) => {
        $(#[$attr])*
        #[allow(non_snake_case)]
        #[allow(dead_code)]
        $vis const fn $field(&self) -> $value_type {
            const _: () = assert!(
                $msb < <$value_type>::BITS as u8,
                "MSB index out of bounds"
            );
            const _: () = assert!(
                $lsb < $msb,
                "LSB must be strictly less than MSB. \
                 Use single-bit syntax (e.g., 'field: bit;') for 1-bit fields."
            );
            let bit_count = $msb - $lsb + 1;
            let bit_mask = ((!0 as $value_type)
                >> (<$value_type>::BITS as u8 - bit_count))
                << $lsb;
            (self.reg_value() & bit_mask) >> $lsb
        }
        $(
            #[allow(non_snake_case)]
            #[allow(dead_code)]
            $vis const fn $setter(self, val: $value_type) -> Self {
                const _: () = assert!(
                    $msb < <$value_type>::BITS as u8,
                    "MSB index out of bounds"
                );
                const _: () = assert!(
                    $lsb < $msb,
                    "LSB must be strictly less than MSB. \
                     Use single-bit syntax (e.g., 'field: bit;') \
                     for 1-bit fields."
                );
                let bit_count = $msb - $lsb + 1;
                let bit_mask = ((!0 as $value_type)
                    >> (<$value_type>::BITS as u8 - bit_count))
                    << $lsb;
                let raw = (self.reg_value() & !bit_mask)
                    | ((val << $lsb) & bit_mask);
                Self::new(raw)
            }
        )?
        $crate::spmi_register_fields!($value_type, $($tail)*);
    };

    // 3. Enum field
    (
        $value_type:ty,
        $(#[$attr:meta])*
        $vis:vis enum $enum_type:ty,
        $field:ident $(, $setter:ident)? : $msb:expr, $lsb:expr;
        $($tail:tt)*
    ) => {
        $(#[$attr])*
        #[allow(non_snake_case)]
        #[allow(dead_code)]
        $vis const fn $field(&self) -> $enum_type {
            const _: () = assert!(
                $msb < <$value_type>::BITS as u8,
                "MSB index out of bounds"
            );
            const _: () = assert!(
                $lsb <= $msb,
                "LSB must be less than or equal to MSB"
            );
            let bit_count = $msb - $lsb + 1;
            let bit_mask = ((!0 as $value_type)
                >> (<$value_type>::BITS as u8 - bit_count))
                << $lsb;
            <$enum_type>::from_val((self.reg_value() & bit_mask) >> $lsb)
        }
        $(
            #[allow(non_snake_case)]
            #[allow(dead_code)]
            $vis const fn $setter(self, val: $enum_type) -> Self {
                const _: () = assert!(
                    $msb < <$value_type>::BITS as u8,
                    "MSB index out of bounds"
                );
                const _: () = assert!(
                    $lsb <= $msb,
                    "LSB must be less than or equal to MSB"
                );
                let bit_count = $msb - $lsb + 1;
                let bit_mask = ((!0 as $value_type)
                    >> (<$value_type>::BITS as u8 - bit_count))
                    << $lsb;
                let raw = (self.reg_value() & !bit_mask)
                    | (((val as $value_type) << $lsb) & bit_mask);
                Self::new(raw)
            }
        )?
        $crate::spmi_register_fields!($value_type, $($tail)*);
    };

    // 4. In-line Enum field
    (
        $value_type:ty,
        $(#[$attr:meta])*
        $vis:vis enum $enum_name:ident {
            $( $variant_name:ident = $variant_val:expr ),* $(,)?
        },
        $field:ident $(, $setter:ident)? : $msb:expr, $lsb:expr;
        $($tail:tt)*
    ) => {
        $(#[$attr])*
        #[allow(non_snake_case)]
        #[allow(dead_code)]
        $vis const fn $field(&self) -> Result<$enum_name, $value_type> {
            const _: () = assert!(
                $msb < <$value_type>::BITS as u8,
                "MSB index out of bounds"
            );
            const _: () = assert!(
                $lsb <= $msb,
                "LSB must be less than or equal to MSB"
            );
            let bit_count = $msb - $lsb + 1;
            let bit_mask = ((!0 as $value_type)
                >> (<$value_type>::BITS as u8 - bit_count))
                << $lsb;
            let val = (self.reg_value() & bit_mask) >> $lsb;
            $(
                if val == $enum_name::$variant_name as $value_type {
                    return Ok($enum_name::$variant_name);
                }
            )*
            Err(val)
        }
        $(
            #[allow(non_snake_case)]
            #[allow(dead_code)]
            $vis const fn $setter(self, val: $enum_name) -> Self {
                const _: () = assert!(
                    $msb < <$value_type>::BITS as u8,
                    "MSB index out of bounds"
                );
                const _: () = assert!(
                    $lsb <= $msb,
                    "LSB must be less than or equal to MSB"
                );
                let bit_count = $msb - $lsb + 1;
                let bit_mask = ((!0 as $value_type)
                    >> (<$value_type>::BITS as u8 - bit_count))
                    << $lsb;
                let raw = (self.reg_value() & !bit_mask)
                    | (((val as $value_type) << $lsb) & bit_mask);
                Self::new(raw)
            }
        )?
        $crate::spmi_register_fields!($value_type, $($tail)*);
    };

    // 5. Custom constant
    (
        $value_type:ty,
        pub const $name:ident : $type:ty = $val:expr;
        $($tail:tt)*
    ) => {
        pub const $name: $type = $val;
        $crate::spmi_register_fields!($value_type, $($tail)*);
    };
}

/// Verifies at compile-time that a list of registers is contiguous.
#[macro_export]
#[doc(hidden)]
macro_rules! assert_contiguous {
    ($prev:ident, $curr:ident $(, $rest:ident)*) => {
        const _: () = assert!(
            $curr::ADDRESS == $prev::ADDRESS
                + std::mem::size_of::<$prev::Value>() as u16,
            concat!(
                "Registers ",
                stringify!($prev),
                " and ",
                stringify!($curr),
                " are not contiguous"
            )
        );
        $crate::assert_contiguous!($curr $(, $rest)*);
    };
    ($last:ident) => {};
}

/// Defines a struct to group multiple SPMI registers.
///
/// This macro generates a public struct named `$name` that holds a
/// device client and provides methods to access individual registers
/// defined by `spmi_register!`, as well as `read_bulk` and `write_bulk`
/// methods for contiguous accesses.
///
/// # Arguments
///
/// 1.  `$name`: The identifier for the generated register block struct.
/// 2.  `{ ... }`: A block defining the registers contained within this block.
///     The format of each register definition is:
///     `$vis $field_name => $reg_mod,`
///     -   `$vis`: Visibility of the register accessor method (e.g., `pub`).
///     -   `$field_name`: The name of the method generated on the block
///         struct to access the register.
///     -   `$reg_mod`: The module identifier of the register defined
///         via `spmi_register!`.
///
/// # Examples
///
/// ```
/// spmi_register! {
///     my_reg, u8, 0x10, RW, {
///         pub enable, set_enable: 7;
///     }
/// }
///
/// spmi_register! {
///     status_reg, u16, 0x12, RO, LE, {
///         pub ready: 0;
///     }
/// }
///
/// spmi_register_block! {
///     pub struct MyDeviceRegisters {
///         pub control => my_reg,
///         pub status => status_reg,
///     }
/// }
///
/// // Usage:
/// // let regs = MyDeviceRegisters::new(spmi_device);
/// // let ctrl_val = regs.control().read().await?;
/// // let is_ready = regs.status().read().await?.ready();
/// ```
#[macro_export]
macro_rules! spmi_register_block {
    (
        pub struct $name:ident {
            $($tail:tt)*
        }
    ) => {
        pub struct $name {
            pub spmi: $crate::DeviceType,
        }

        #[allow(dead_code)]
        impl $name {
            pub fn new(spmi: $crate::DeviceType) -> Self {
                Self { spmi }
            }

            /// Reads a raw byte slice from the contiguous register range.
            ///
            /// # Note
            /// This method is public but hidden because it is required by the
            /// `spmi_read_contiguous!` macro. Direct use is discouraged.
            #[doc(hidden)]
            #[allow(dead_code)]
            pub async fn read_bulk(
                &self,
                address: u16,
                size: u32,
            ) -> Result<Vec<u8>, $crate::Error> {
                let data = $crate::SpmiDevice::read_reg(
                    &self.spmi,
                    address,
                    size,
                ).await?;
                if data.len() == size as usize {
                    Ok(data)
                } else {
                    Err($crate::Error::SizeMismatch)
                }
            }

            /// Reads a raw byte slice from the contiguous register range into a
            /// mutable buffer.
            ///
            /// # Note
            /// This method is public but hidden to discourage direct use,
            /// keeping the bulk API consistent with `read_bulk`.
            #[doc(hidden)]
            #[allow(dead_code)]
            pub async fn read_bulk_into(
                &self,
                address: u16,
                out: &mut [u8],
            ) -> Result<(), $crate::Error> {
                let data = $crate::SpmiDevice::read_reg(
                    &self.spmi,
                    address,
                    out.len() as u32,
                ).await?;
                if data.len() == out.len() {
                    out.copy_from_slice(&data);
                    Ok(())
                } else {
                    Err($crate::Error::SizeMismatch)
                }
            }

            /// Writes the specified data to the contiguous register range.
            ///
            /// # Note
            /// This method is public but hidden because it is required by the
            /// `spmi_write_contiguous!` macro. Direct use is discouraged.
            #[doc(hidden)]
            #[allow(dead_code)]
            pub async fn write_bulk(
                &self,
                address: u16,
                data: &[u8],
            ) -> Result<(), $crate::Error> {
                $crate::SpmiDevice::write_reg(&self.spmi, address, data).await?;
                Ok(())
            }

            spmi_register_block!(@fields $($tail)*);
        }
    };

    (@fields) => {};

    // Case 1: Individual register with trailing fields
    (@fields $vis:vis $field:ident => $reg_mod:ident, $($tail:tt)*) => {
        #[allow(dead_code)]
        $vis fn $field(&self) -> $reg_mod::Register<'_> {
            $reg_mod::Register::new(&self.spmi)
        }
        spmi_register_block!(@fields $($tail)*);
    };

    // Case 2: Individual register at end of token stream
    (@fields $vis:vis $field:ident => $reg_mod:ident) => {
        #[allow(dead_code)]
        $vis fn $field(&self) -> $reg_mod::Register<'_> {
            $reg_mod::Register::new(&self.spmi)
        }
    };
}

/// Reads multiple contiguous registers in a single async call to the hardware.
///
/// This macro accepts an SPMI device proxy and a list of register
/// modules, calculates the base address and combined size, and performs
/// a single async contiguous read.
///
/// # Arguments
///
/// 1.  `$spmi:expr`: The SPMI device proxy.
/// 2.  `$( $reg:ident ),*`: A comma-separated list of already-declared
///     register modules.
///
/// # Examples
///
/// ```
/// // Read both 'general' and 'status' registers together, update,
/// // and write back:
/// // let regs = MySpmiRegisters::new(spmi_proxy);
/// let (mut general_val, status_val) = spmi_read_contiguous!(
///     &regs,
///     my_reg,
///     status_be_reg
/// ).await?;
///
/// general_val = general_val.set_field1(true);
///
/// spmi_write_contiguous!(
///     &regs,
///     my_reg => general_val,
///     status_be_reg => status_val
/// ).await?;
/// ```
#[macro_export]
macro_rules! spmi_read_contiguous {
    (
        $regs:expr,
        $head:ident $(, $tail:ident )* $(,)?
    ) => {
        async {
            $crate::assert_contiguous!($head $(, $tail)*);
            let res: Result<
                ($head::Value, $( $tail::Value ),*),
                $crate::Error
            > = async {
                let base_addr = $head::ADDRESS;

                let total_size = std::mem::size_of::<$head::Value>()
                    $( + std::mem::size_of::<$tail::Value>() )*;

                let data = $regs.read_bulk(
                    base_addr,
                    total_size as u32,
                ).await?;

                let mut cursor = 0;
                let $head = $head::Value::from_bytes(
                    &data[cursor..std::mem::size_of::<$head::Value>()],
                )?;
                cursor = std::mem::size_of::<$head::Value>();
                $(
                    let end = cursor + std::mem::size_of::<$tail::Value>();
                    let $tail = $tail::Value::from_bytes(
                        &data[cursor..end],
                    )?;
                    cursor = end;
                )*
                let _ = cursor;

                Ok(($head, $( $tail ),*))
            }.await;
            res
        }
    };
}

/// Writes multiple contiguous registers in a single async call to the hardware.
///
/// This macro accepts an SPMI device proxy and a mapping of register modules
/// to their values, serializes the values using their correct endianness,
/// and performs a single async contiguous write.
///
/// # Arguments
///
/// 1.  `$regs:expr`: The block struct instance.
/// 2.  `$( $reg:ident => $val:expr ),*`: A comma-separated mapping from
///     register modules to their values.
///
/// # Examples
///
/// ```
/// // Write both 'general' and 'status' registers together:
/// // let regs = MySpmiRegisters::new(spmi_proxy);
/// spmi_write_contiguous!(
///     &regs,
///     my_reg => val_a,
///     status_be_reg => val_b
/// ).await?;
/// ```
#[macro_export]
macro_rules! spmi_write_contiguous {
    (
        $regs:expr,
        $head:ident => $head_val:expr $(, $tail:ident => $tail_val:expr )* $(,)?
    ) => {
        async {
            $crate::assert_contiguous!($head $(, $tail)*);
            let regs_ref = $regs;
            let res: Result<(), $crate::Error> = async move {
                let base_addr = $head::ADDRESS;

                let mut bytes = Vec::new();
                bytes.extend_from_slice(&$head_val.to_bytes());
                $(
                    bytes.extend_from_slice(&$tail_val.to_bytes());
                )*

                regs_ref.write_bulk(base_addr, &bytes).await?;

                Ok(())
            }.await;
            res
        }
    };
}

/// Trait for SPMI devices to abstract register read/write operations.
///
/// This trait allows the `Register` and `spmi_register_block!` macros to
/// interact with any underlying hardware interface or mock device that
/// implements these basic SPMI read and write operations.
///
/// Implementations must handle the low-level transport (e.g., FIDL calls
/// to a Fuchsia SPMI driver) and handle error mapping.
#[allow(async_fn_in_trait)]
pub trait SpmiDevice {
    /// Reads a contiguous sequence of bytes from the device.
    ///
    /// # Arguments
    ///
    /// * `address` - The 16-bit base register address to read from.
    /// * `size` - The number of bytes to read.
    ///
    /// # Returns
    ///
    /// Returns a vector containing the read bytes on success, or a
    /// `crate::Error` on failure.
    async fn read_reg(&self, address: u16, size: u32) -> Result<Vec<u8>, crate::Error>;

    /// Writes a contiguous sequence of bytes to the device.
    ///
    /// # Arguments
    ///
    /// * `address` - The 16-bit base register address to write to.
    /// * `data` - The byte slice to write to the device.
    ///
    /// # Returns
    ///
    /// Returns `Ok(())` on success, or a `crate::Error` on failure.
    async fn write_reg(&self, address: u16, data: &[u8]) -> Result<(), crate::Error>;
}

#[cfg(test)]
/// A mock SPMI device that stores register values in memory.
/// Used for testing register access without a real device or FIDL connection.
pub struct TestSpmiDevice {
    registers: std::sync::Mutex<std::collections::HashMap<u16, u8>>,
}

#[cfg(test)]
impl TestSpmiDevice {
    /// Creates a new empty `TestSpmiDevice`.
    pub fn new() -> Self {
        Self { registers: std::sync::Mutex::new(std::collections::HashMap::new()) }
    }
}

#[cfg(test)]
impl SpmiDevice for TestSpmiDevice {
    async fn read_reg(&self, address: u16, size: u32) -> Result<Vec<u8>, crate::Error> {
        let regs = self.registers.lock().unwrap();
        let mut data = Vec::new();
        for i in 0..size {
            let addr = address + i as u16;
            let val = regs.get(&addr).copied().unwrap_or(0);
            data.push(val);
        }
        Ok(data)
    }

    async fn write_reg(&self, address: u16, data: &[u8]) -> Result<(), crate::Error> {
        let mut regs = self.registers.lock().unwrap();
        for (i, &val) in data.iter().enumerate() {
            let addr = address + i as u16;
            regs.insert(addr, val);
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Note: For single-byte width registers (u8), explicit endianness is
    // not required.
    spmi_register! {
        test_u8_reg, u8, 0xCD, RW, {
            pub flag, set_flag: 4;
            pub field, set_field: 3, 0;
        }
    }

    spmi_register_block! {
        pub struct MockU8Regs {
            pub test => test_u8_reg,
        }
    }

    spmi_register! {
        test_u16_from_bytes_reg, u16, 0x99, RW, LE, {
            pub field, set_field: 15, 0;
        }
    }

    spmi_register_block! {
        pub struct MockU16FromBytesRegs {
            pub test => test_u16_from_bytes_reg,
        }
    }

    spmi_register! {
        test_u16_contig_reg, u16, 0xCE, RW, LE, {
            pub field, set_field: 15, 0;
        }
    }

    #[fuchsia::test]
    async fn test_u16_from_bytes() {
        let device = TestSpmiDevice::new();
        device.write_reg(0x99, &[0x34, 0x12]).await.unwrap();

        let regs = MockU16FromBytesRegs::new(device);
        let val = regs.test().read().await.unwrap();
        assert_eq!(val.reg_value(), 0x1234);
    }

    #[fuchsia::test]
    async fn test_u8_register() {
        let device = TestSpmiDevice::new();
        device.write_reg(0xCD, &[0x1A]).await.unwrap();

        let regs = MockU8Regs::new(device);
        let val = regs.test().read().await.unwrap();
        assert_eq!(val.reg_value(), 0x1A);
        assert_eq!(val.flag(), true);
        assert_eq!(val.field(), 0x0A);
    }

    spmi_register! {
        test_reg, u16, 0xAB, RW, LE, {
            pub test_bit, set_test_bit: 7;
            pub test_field, set_test_field: 3, 0;
        }
    }

    spmi_register_block! {
        pub struct MockRegs {
            pub test => test_reg,
        }
    }

    #[fuchsia::test]
    async fn test_read() {
        let device = TestSpmiDevice::new();
        device.write_reg(0xAB, &[0x8A, 0x00]).await.unwrap();

        let regs = MockRegs::new(device);
        let val = regs.test().read().await.unwrap();
        assert_eq!(val.reg_value(), 0x008A);
        assert_eq!(val.test_bit(), true);
        assert_eq!(val.test_field(), 0x0A);
    }

    #[fuchsia::test]
    async fn test_write() {
        let device = TestSpmiDevice::new();

        let regs = MockRegs::new(device);
        let v = test_reg::Value::new(0x008A);
        regs.test().write(v).await.unwrap();

        let data = regs.spmi.read_reg(0xAB, 2).await.unwrap();
        assert_eq!(data, &[0x8A, 0x00]);
    }

    spmi_register! {
        test_be_reg, u16, 0xEF, RW, BE, {
            pub flag, set_flag: 4;
            pub field, set_field: 3, 0;
        }
    }

    spmi_register_block! {
        pub struct MockBERegs {
            pub test => test_be_reg,
        }
    }

    #[fuchsia::test]
    async fn test_be_register() {
        let device = TestSpmiDevice::new();
        device.write_reg(0xEF, &[0x00, 0x8A]).await.unwrap();

        let regs = MockBERegs::new(device);
        let val = regs.test().read().await.unwrap();
        assert_eq!(val.reg_value(), 0x8A);
    }

    #[derive(Debug, PartialEq, Eq, Copy, Clone)]
    #[repr(u16)]
    pub enum PowerMode {
        Normal = 0,
        Hibernate = 1,
        LowPower = 2,
        Unknown = 0xFFFF,
    }

    impl PowerMode {
        pub const fn from_val(val: u16) -> Self {
            match val {
                0 => PowerMode::Normal,
                1 => PowerMode::Hibernate,
                2 => PowerMode::LowPower,
                _ => PowerMode::Unknown,
            }
        }
    }

    spmi_register! {
        test_enum_reg, u16, 0x44, RW, LE, {
            pub enum PowerMode, mode, set_mode: 3, 2;
        }
    }

    spmi_register_block! {
        pub struct MockEnumRegs {
            pub test => test_enum_reg,
        }
    }

    #[fuchsia::test]
    async fn test_enum_register() {
        let device = TestSpmiDevice::new();

        let regs = MockEnumRegs::new(device);
        let v = test_enum_reg::Value::new(0).set_mode(PowerMode::Hibernate);
        regs.test().write(v).await.unwrap();

        let data = regs.spmi.read_reg(0x44, 2).await.unwrap();
        assert_eq!(data, &[0x04, 0x00]);
    }

    spmi_register! {
        test_inline_enum_reg, u16, 0x55, RW, LE, {
            pub enum InlineMode {
                A = 0,
                B = 1,
            }, mode, set_mode: 1, 0;
        }
    }

    spmi_register_block! {
        pub struct MockInlineEnumRegs {
            pub test => test_inline_enum_reg,
        }
    }

    #[fuchsia::test]
    async fn test_inline_enum() {
        let device = TestSpmiDevice::new();

        let regs = MockInlineEnumRegs::new(device);
        let v = test_inline_enum_reg::Value::new(1).set_mode(test_inline_enum_reg::InlineMode::B);
        assert_eq!(v.mode(), Ok(test_inline_enum_reg::InlineMode::B));
        regs.test().write(v).await.unwrap();

        let data = regs.spmi.read_reg(0x55, 2).await.unwrap();
        assert_eq!(data, &[0x01, 0x00]);
    }

    #[fuchsia::test]
    async fn test_contiguous_read_write() {
        let device = TestSpmiDevice::new();
        device.write_reg(0xCD, &[0x1A, 0x34, 0x12]).await.unwrap();

        spmi_register_block! {
            pub struct ContiguousRegs {
                pub r1 => test_u8_reg,
                pub r2 => test_u16_contig_reg,
            }
        }
        let regs = ContiguousRegs::new(device);

        let (val_1, val_2) =
            spmi_read_contiguous!(&regs, test_u8_reg, test_u16_contig_reg,).await.unwrap();

        assert_eq!(val_1.reg_value(), 0x1A);
        assert_eq!(val_2.reg_value(), 0x1234);

        spmi_write_contiguous!(
            &regs,
            test_u8_reg => val_1,
            test_u16_contig_reg => val_2
        )
        .await
        .unwrap();

        let data = regs.spmi.read_reg(0xCD, 3).await.unwrap();
        assert_eq!(data, &[0x1A, 0x34, 0x12]);
    }

    #[fuchsia::test]
    async fn test_read_write_bulk() {
        let device = TestSpmiDevice::new();
        device.write_reg(0x88, &[0x1A, 0x2B, 0x3C]).await.unwrap();

        let regs = MockU8Regs::new(device);
        let bytes = regs.read_bulk(0x88, 3).await.unwrap();
        assert_eq!(bytes, vec![0x1A, 0x2B, 0x3C]);

        let mut buf = [0u8; 3];
        regs.read_bulk_into(0x88, &mut buf).await.unwrap();
        assert_eq!(buf, [0x1A, 0x2B, 0x3C]);

        regs.write_bulk(0x88, &[0x1A, 0x2B, 0x3C]).await.unwrap();
        let data = regs.spmi.read_reg(0x88, 3).await.unwrap();
        assert_eq!(data, &[0x1A, 0x2B, 0x3C]);
    }
}
