// Copyright 2026 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

//! # `spmi-hwreg`
//! Rust SPMI register access library matching the MMIO hwreg paradigm.

#![deny(missing_docs)]

use thiserror::Error as ThisError;

/// The device type used by this crate for hardware communication.
///
/// In production, this resolves to the FIDL `DeviceProxy` representing
/// the SPMI device.
#[cfg(not(test))]
pub type DeviceType = fidl_fuchsia_hardware_spmi::DeviceProxy;

/// The device type used by this crate during tests.
///
/// In test environments, this resolves to `TestSpmiDevice` to allow
/// in-memory mocking of register state.
#[cfg(test)]
pub type DeviceType = crate::common::TestSpmiDevice;

/// Common definitions and macros for SPMI registers.
///
/// This module contains the underlying traits, generic structs, and macros
/// used to construct register layouts and blocks.
#[macro_use]
pub mod common;
pub use common::*;
pub use zerocopy as zerocopy_reexport;
pub use zerocopy::byteorder::{BigEndian, LittleEndian, U16, U32};
pub use zerocopy::{FromBytes, FromZeros, Immutable, IntoBytes};

impl SpmiDevice for fidl_fuchsia_hardware_spmi::DeviceProxy {
    async fn read_reg(&self, address: u16, size: u32) -> Result<Vec<u8>, crate::Error> {
        self.register_read(address, size)
            .await
            .map_err(|e| Error::Fidl(e.into()))?
            .map_err(|e| Error::Spmi(e))
    }

    async fn write_reg(&self, address: u16, data: &[u8]) -> Result<(), crate::Error> {
        self.register_write(address, data)
            .await
            .map_err(|e| Error::Fidl(e.into()))?
            .map_err(|e| Error::Spmi(e))
    }
}

/// A generic register accessor parameterized by value type, mode, and address.
///
/// This is a convenience alias that binds `Register` to the
/// platform-specific `DeviceType`.
///
/// # Generics
/// * `T` - The typed register value (e.g., generated by `spmi_register!`).
/// * `M` - The access mode (`ReadOnly`, `WriteOnly`, `ReadWrite`).
/// * `ADDR` - The register address.
pub type Register<'a, T, M, const ADDR: u16> = _Register<'a, T, M, crate::DeviceType, ADDR>;

/// Error type for the `spmi-hwreg` crate.
#[derive(Debug, ThisError)]
pub enum Error {
    /// A transport or framework error occurred during FIDL communication.
    #[error("FIDL error: {0}")]
    Fidl(fidl::Error),
    /// The SPMI driver returned a protocol-level error (e.g.,
    /// transaction timeout or NACK).
    #[error("SPMI error: {0:?}")]
    Spmi(fidl_fuchsia_hardware_spmi::DriverError),
    /// The data returned from a read operation did not match the
    /// expected size of the register.
    #[error("Size mismatch in read operation")]
    SizeMismatch,
}

#[cfg(test)]
mod tests {
    use super::*;
    use fidl::endpoints::create_proxy_and_stream;
    use fidl_fuchsia_hardware_spmi as fspmi;
    use futures::StreamExt;

    #[fuchsia::test]
    async fn test_spmi_device_read_write() {
        let (proxy, mut stream) = create_proxy_and_stream::<fspmi::DeviceMarker>();

        fuchsia_async::Task::local(async move {
            while let Some(Ok(req)) = stream.next().await {
                match req {
                    fspmi::DeviceRequest::RegisterRead { address, size_bytes, responder } => {
                        assert_eq!(address, 0x12);
                        assert_eq!(size_bytes, 2);
                        responder.send(Ok(&[0xAA, 0x55])).unwrap();
                    }
                    fspmi::DeviceRequest::RegisterWrite { address, data, responder } => {
                        assert_eq!(address, 0x34);
                        assert_eq!(data, &[0xDE, 0xAD]);
                        responder.send(Ok(())).unwrap();
                    }
                    _ => panic!("Unexpected request"),
                }
            }
        })
        .detach();

        // Test read_reg
        let read_result = proxy.read_reg(0x12, 2).await.unwrap();
        assert_eq!(read_result, vec![0xAA, 0x55]);

        // Test write_reg
        let write_result = proxy.write_reg(0x34, &[0xDE, 0xAD]).await;
        assert!(write_result.is_ok());
    }
}
