// Copyright 2026 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

//! # `spmi-hwreg-next`
//! Rust SPMI register access library matching the MMIO hwreg paradigm,
//! built on `fidl_next`.

#![deny(missing_docs)]

use thiserror::Error as ThisError;

/// The device type used by this crate for hardware communication.
///
/// In production, this resolves to the `fidl_next` `Client` representing
/// the SPMI device.
#[cfg(not(test))]
pub type DeviceType = fidl_next::Client<fidl_next_fuchsia_hardware_spmi::Device>;

/// The device type used by this crate during tests.
///
/// In test environments, this resolves to `TestSpmiDevice` to allow
/// in-memory mocking of register state.
#[cfg(test)]
pub type DeviceType = crate::common::TestSpmiDevice;

/// Common definitions and macros for SPMI registers.
///
/// This module contains the underlying traits, generic structs, and macros
/// used to construct register layouts and blocks.
#[macro_use]
pub mod common;
pub use common::*;
pub use zerocopy as zerocopy_reexport;
pub use zerocopy::byteorder::{BigEndian, LittleEndian, U16, U32};
pub use zerocopy::{FromBytes, FromZeros, Immutable, IntoBytes};

impl SpmiDevice for fidl_next::Client<fidl_next_fuchsia_hardware_spmi::Device> {
    async fn read_reg(&self, address: u16, size: u32) -> Result<Vec<u8>, crate::Error> {
        let result = self.register_read(address, size).await.map_err(|e| match e {
            fidl_next::Error::Protocol(fidl_next::ProtocolError::FrameworkError(err)) => {
                Error::Framework(err)
            }
            e => Error::Fidl(e),
        })?;
        match result {
            Ok(response) => Ok(response.data),
            Err(err) => Err(Error::Spmi(err)),
        }
    }

    async fn write_reg(&self, address: u16, data: &[u8]) -> Result<(), crate::Error> {
        let result = self.register_write(address, data).await.map_err(|e| match e {
            fidl_next::Error::Protocol(fidl_next::ProtocolError::FrameworkError(err)) => {
                Error::Framework(err)
            }
            e => Error::Fidl(e),
        })?;
        match result {
            Ok(()) => Ok(()),
            Err(err) => Err(Error::Spmi(err)),
        }
    }
}

/// A generic register accessor parameterized by value type, mode, and address.
///
/// This is a convenience alias that binds `Register` to the
/// platform-specific `DeviceType`.
///
/// # Generics
/// * `T` - The typed register value (e.g., generated by `spmi_register!`).
/// * `M` - The access mode (`ReadOnly`, `WriteOnly`, `ReadWrite`).
/// * `ADDR` - The register address.
pub type Register<'a, T, M, const ADDR: u16> = _Register<'a, T, M, crate::DeviceType, ADDR>;

/// Error type for the `spmi-hwreg` crate.
#[derive(Debug, ThisError)]
pub enum Error {
    /// A transport error occurred during FIDL communication.
    #[error("FIDL error: {0}")]
    Fidl(fidl_next::Error),
    /// The SPMI driver returned a protocol-level error (e.g.,
    /// transaction timeout or NACK).
    #[error("SPMI error: {0:?}")]
    Spmi(fidl_next_fuchsia_hardware_spmi::DriverError),
    /// A FIDL framework error occurred.
    #[error("Framework error: {0:?}")]
    Framework(fidl_next::FrameworkError),
    /// The data returned from a read operation did not match the
    /// expected size of the register.
    #[error("Size mismatch in read operation")]
    SizeMismatch,
}

#[cfg(test)]
mod tests {
    use super::*;
    use fidl_next_fuchsia_hardware_spmi as fspmi;
    use fuchsia_async as fasync;

    struct FakeSpmiServer {
        read_data: Vec<u8>,
    }

    impl fspmi::DeviceServerHandler for FakeSpmiServer {
        async fn register_read(
            &mut self,
            request: fidl_next::Request<fspmi::device::RegisterRead>,
            responder: fidl_next::Responder<fspmi::device::RegisterRead>,
        ) {
            let payload = request.payload();
            assert_eq!(payload.address, 0x12);
            assert_eq!(payload.size_bytes, 2);
            let response = self.read_data.clone();
            let _ = responder.respond(response).await;
        }

        async fn register_write(
            &mut self,
            request: fidl_next::Request<fspmi::device::RegisterWrite>,
            responder: fidl_next::Responder<fspmi::device::RegisterWrite>,
        ) {
            let payload = request.payload();
            assert_eq!(payload.address, 0x34);
            assert_eq!(payload.data.as_slice(), &[0xDE, 0xAD]);
            let _ = responder.respond(()).await;
        }

        async fn get_properties(
            &mut self,
            _responder: fidl_next::Responder<fspmi::device::GetProperties>,
        ) {
        }

        async fn watch_controller_write_commands(
            &mut self,
            _request: fidl_next::Request<fspmi::device::WatchControllerWriteCommands>,
            _responder: fidl_next::Responder<fspmi::device::WatchControllerWriteCommands>,
        ) {
        }

        async fn cancel_watch_controller_write_commands(
            &mut self,
            _request: fidl_next::Request<fspmi::device::CancelWatchControllerWriteCommands>,
            _responder: fidl_next::Responder<fspmi::device::CancelWatchControllerWriteCommands>,
        ) {
        }
    }

    #[fuchsia::test(logging = false)]
    async fn test_spmi_device_read_write() {
        let scope = fasync::Scope::new();
        let (client_end, server_end) = fidl_next::fuchsia::create_channel::<fspmi::Device>();

        let server = FakeSpmiServer { read_data: vec![0xAA, 0x55] };
        server_end.spawn_on(server, &scope);

        let client = client_end.spawn();

        // Test read_reg with explicit type annotation to assist inference
        let read_result: Vec<u8> = client.read_reg(0x12, 2).await.unwrap();
        assert_eq!(read_result, vec![0xAA, 0x55]);

        // Test write_reg
        let write_result = client.write_reg(0x34, &[0xDE, 0xAD]).await;
        assert!(write_result.is_ok());
    }
}
