# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "name",
    srcs = [
        "src/lib.rs",
        "src/repr.rs",
    ],
    crate_name = "name",
    edition = "2024",
    test_deps = [
        "//third_party/rust_crates/vendor:assert_matches",
    ],
    visibility = ["//:__subpackages__"],
    with_unit_tests = True,
    deps = [
        "//sdk/fidl/fuchsia.io:fuchsia.io_rust",
        "//sdk/rust/zx-status",
        "//third_party/rust_crates/vendor:memchr",
        "//third_party/rust_crates/vendor:static_assertions",
        "//third_party/rust_crates/vendor:thiserror",
    ],
)
