/* automatically generated by rust-bindgen 0.72.0 */

// Copyright 2026 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// LINT.IfChange

#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::undocumented_unsafe_blocks, reason = "bindgen-generated code")]

//! WARNING - This file was auto generated by //src/lib/elf-search/rust/generate.py.
//! Do not modify this file. To re-generate, run the following command from the root of
//! your Fuchsia checkout:
//!
//!    ./src/lib/elf-search/rust/generate.py

use zerocopy::{Immutable, IntoBytes};

pub type Elf64_Half = u16;
pub type Elf64_Word = u32;
pub type Elf64_Xword = u64;
pub type Elf64_Addr = u64;
pub type Elf64_Off = u64;
#[repr(C)]
#[derive(Clone, Copy, Debug, Immutable, IntoBytes)]
pub struct Elf64_Ehdr {
    pub e_ident: [::std::os::raw::c_uchar; 16usize],
    pub e_type: Elf64_Half,
    pub e_machine: Elf64_Half,
    pub e_version: Elf64_Word,
    pub e_entry: Elf64_Addr,
    pub e_phoff: Elf64_Off,
    pub e_shoff: Elf64_Off,
    pub e_flags: Elf64_Word,
    pub e_ehsize: Elf64_Half,
    pub e_phentsize: Elf64_Half,
    pub e_phnum: Elf64_Half,
    pub e_shentsize: Elf64_Half,
    pub e_shnum: Elf64_Half,
    pub e_shstrndx: Elf64_Half,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Immutable, IntoBytes)]
pub struct Elf64_Phdr {
    pub p_type: Elf64_Word,
    pub p_flags: Elf64_Word,
    pub p_offset: Elf64_Off,
    pub p_vaddr: Elf64_Addr,
    pub p_paddr: Elf64_Addr,
    pub p_filesz: Elf64_Xword,
    pub p_memsz: Elf64_Xword,
    pub p_align: Elf64_Xword,
}
pub type zx_handle_t = u32;
pub type zx_status_t = i32;
pub type ElfSearchCallbackFn = ::std::option::Option<
    unsafe extern "C" fn(
        name: *const ::std::os::raw::c_char,
        name_len: usize,
        vaddr: u64,
        build_id: *const u8,
        build_id_len: usize,
        ehdr: *const Elf64_Ehdr,
        phdrs: *const Elf64_Phdr,
        phdrs_len: usize,
        arg: *mut ::std::os::raw::c_void,
    ),
>;
unsafe extern "C" {
    pub fn elf_search_wrapper(
        process_handle: zx_handle_t,
        callback: ElfSearchCallbackFn,
        callback_arg: *mut ::std::os::raw::c_void,
    ) -> zx_status_t;
}

// LINT.ThenChange(
//    //src/lib/elf-search/rust/src/wrapper.h |
//    //zircon/system/public/zircon/compiler.h |
//    //zircon/system/public/zircon/errors.h |
//    //zircon/system/public/zircon/limits.h |
//    //zircon/system/public/zircon/rights.h |
//    //zircon/system/public/zircon/time.h |
//    //zircon/system/public/zircon/types.h
//)
