from _typeshed import Incomplete
from mobly.controllers import attenuator as attenuator
from mobly.controllers.attenuator_lib import (
    telnet_scpi_client as telnet_scpi_client,
)

class AttenuatorDevice:
    path_count: Incomplete
    def __init__(self, path_count: int = ...) -> None: ...
    @property
    def is_open(self): ...
    properties: Incomplete
    max_atten: Incomplete
    def open(self, host, port: int = ...) -> None: ...
    def close(self) -> None: ...
    def set_atten(self, idx, value) -> None: ...
    def get_atten(self, idx: int = ...): ...
