# Copyright 2026 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/config/current_target_tuple.gni")
import("//build/rust/config.gni")
import("//build/toolchain/toolchain_environment.gni")
import("//build/zircon/c_utils.gni")
import("//zircon/kernel/kernel_rust_mod.gni")
import("//zircon/kernel/params.gni")
import("//zircon/kernel/phys/kernel_elf_binary.gni")

_kernel_executable_deps = [ "//zircon/kernel/top" ]

_kernel_executable_cpu_deps = {
  arm64 = [ "//zircon/kernel/platform/generic-arm" ]
  riscv64 = [ "//zircon/kernel/platform/generic-riscv64" ]
  x64 = [ "//zircon/kernel/platform/pc" ]
}

# Represents a kernel executable (i.e., a kernel in ELF form) evaluated under
# the current switchset.
#
# Subtargets
#
#   * $target_name.rsp
#     The link_output_rspfile() containing the output name of the kernel
#     executable.
#
# Parameters
#
#   * deps
#    - Optional: Additional sources to link into the kernel.
#    - Type: list(label)
#    - Default: []
#
#   * data_deps
#    - Optional: Can be used to bring extra files into the kernel package or
#      extra ZBI items into the image.
#    - Type: list(label)
#    - Default: []
#
#   * testonly, visibility
#     - Optional: Standard GN meanings.
#
template("kernel_executable") {
  assert(toolchain_environment == "kernel",
         "kernel_executable() can only be used in the kernel environment")

  main_target = target_name
  validate_symbols_target = "_kernel_executable.$target_name.validate"
  crate_root_target = "_kernel_executable.$target_name.crate_root"
  clippy_target = "$target_name.clippy"
  rsp_target = "$target_name.rsp"

  _kernel_deps =
      _kernel_executable_deps + _kernel_executable_cpu_deps[current_cpu]
  if (defined(invoker.deps)) {
    _kernel_deps += invoker.deps
  }

  kernel_rust_mod_crate_root(crate_root_target) {
    visibility = [ ":*" ]
    forward_variables_from(invoker, [ "testonly" ])
    deps = _kernel_deps
  }

  _clippy_output = "$target_gen_dir/$clippy_target"
  action(clippy_target) {
    forward_variables_from(invoker, [ "testonly" ])
    check_for_output_dir_leaks = false
    mnemonic = "CLIPPY"

    configs = []
    if (defined(invoker.configs)) {
      configs += invoker.configs
    }
    configs += [ "//zircon/kernel/switch:kernel_executable.config" ]
    configs += toolchain_variant.configs

    _crate_root_outputs = get_target_outputs(":$crate_root_target")
    _crate_root = _crate_root_outputs[0]

    _deps_rspfile = "$target_gen_dir/$crate_root_target.kernel_rust_externs.rsp"
    _transdeps_rspfile =
        "$target_gen_dir/$crate_root_target.rust_aux_searchdir.rsp"

    deps = [
      ":$crate_root_target",
      "//zircon/kernel/lib/rust:rust-custom-target",
    ]
    inputs = [
      _crate_root,
      _deps_rspfile,
      _transdeps_rspfile,
    ]

    depfile = "${_clippy_output}.d"

    script = "//build/rust/clippy_wrapper.sh"
    outputs = [ _clippy_output ]

    _jq = "//prebuilt/third_party/jq/${host_platform}/bin/jq"

    args = [
      "--output",
      rebase_path(_clippy_output, root_build_dir),
      "--depfile",
      rebase_path(depfile, root_build_dir),
      "--jq",
      rebase_path(_jq, root_build_dir),
      "--deps",
      rebase_path(_deps_rspfile, root_build_dir),
      "--transdeps",
      rebase_path(_transdeps_rspfile, root_build_dir),
      "--",
      "env",
      "{{rustenv}}",
      "${rebased_rustc_prefix}/bin/clippy-driver",
      rebase_path(_crate_root, root_build_dir),
      "--crate-type=bin",
      "--crate-name=kernel",
      "--edition=2024",
      "-Cpanic=abort",
      "-Cmetadata=clippy",
      "-Wclippy::all",
      "-Aclippy::duplicate_mod",  # Needed for kernel_rust_mod
      "{{rustflags}}",
    ]
  }

  kernel_elf_binary(main_target) {
    forward_variables_from(invoker,
                           [
                             "testonly",
                             "visibility",
                           ])
    if (defined(visibility)) {
      visibility += [ ":*" ]
    }

    install_name = "vmzircon"

    configs += [ "//zircon/kernel/switch:kernel_executable.config" ]
    deps = [
      ":$crate_root_target",
      "//zircon/kernel/phys:physboot.kernel",
    ]

    validations = [ ":$validate_symbols_target" ]
    data_deps = [ ":$clippy_target" ]

    # GN makes an executable() use Rust if its $sources list any Rust files.
    # The only file listed directly here at all is the $crate_root generated by
    # the kernel_rust_mod_crate_root() target.
    crate_type = "bin"
    sources = get_target_outputs(deps[0])
    crate_root = sources[0]
    rustflags = [ "--edition=2024" ]

    # The binary crate is always called "kernel" in every target.
    crate_name = "kernel"
  }

  rspfile = "$target_gen_dir/$main_target.rsp"
  link_output_rspfile(rsp_target) {
    forward_variables_from(invoker,
                           [
                             "testonly",
                             "visibility",
                           ])
    if (defined(visibility)) {
      visibility += [ ":$validate_symbols_target" ]
    }
    deps = [ ":$main_target.binary" ]
    outputs = [ rspfile ]
  }

  toolchain_utils_action(validate_symbols_target) {
    forward_variables_from(invoker, [ "testonly" ])
    visibility = [ ":*" ]
    outputs = [ "$target_gen_dir/$target_name.stamp" ]
    script = "//zircon/kernel/scripts/validate-kernel-symbols.py"
    utils = [ "nm" ]
    deps = [
      ":$main_target.binary",
      ":$rsp_target",
    ]
    sources = [ rspfile ]
    depfile = "$target_gen_dir/$target_name.d"
    args = rebase_path(sources + outputs + [ depfile ], root_build_dir)
  }
}
