# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Host tools that are continuously built and published to CIPD by the
# `host_prebuilts` builders.
group("public_host_tools") {
  deps = [
    "//src/developer/ffx:host",
    "//src/diagnostics/triage:install",
    "//src/storage/tools/blobfs-compression",
    "//tools/build/gndoc",
    "//tools/build/ninjago/buildstats",
    "//tools/build/ninjago/ninjatrace",
    "//tools/bundle_fetcher",
    "//tools/debug/buildidtool",
    "//tools/debug/debugsyms",
    "//tools/funnel:host",
    "//tools/orchestrate",
    "//tools/vboot_reference",
  ]
}
