# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load(
    "@rules_fuchsia//fuchsia:assembly.bzl",
    "fuchsia_board_configuration",
    "fuchsia_product",
    "fuchsia_product_bundle",
    "fuchsia_product_configuration",
)
load(
    "@rules_fuchsia//fuchsia:defs.bzl",
    "fuchsia_package",
)

# This test needs to use the non-sdk version of the fx_component rule
# so that the correct component manifest includes can be used.
load(
    "//build/bazel/rules/components:fx_component.bzl",
    "fx_component",
    "fx_component_manifest",
)

package(
    default_applicable_licenses = ["//:license"],
)

# We don't intend to run this component, just make its manifest visible to
# scrutiny.
fx_component_manifest(
    name = "test_session_manifest",
    component_name = "test_session",
    includes = [
        "//sdk/lib/inspect:offer.shard.cml",
        "//sdk/lib/syslog:offer.shard.cml",
    ],
    manifest = "meta/test_session.cml",
)

fx_component(
    name = "test_session",
    compiled_manifest = ":test_session_manifest",
)

# We don't intend to run this component, just make its manifest visible to
# scrutiny.
fx_component_manifest(
    name = "component_with_broken_use_manifest",
    component_name = "component_with_broken_use",
    manifest = "meta/component_with_broken_use.cml",
)

fx_component(
    name = "component_with_broken_use",
    compiled_manifest = ":component_with_broken_use_manifest",
)

# We don't intend to run this component, just make its manifest visible to
# scrutiny.
fx_component_manifest(
    name = "component_with_collection_manifest",
    component_name = "component_with_collection",
    includes = [
        "//sdk/lib/inspect:offer.shard.cml",
        "//sdk/lib/syslog:offer.shard.cml",
    ],
    manifest = "meta/component_with_collection.cml",
)

fx_component(
    name = "component_with_collection",
    compiled_manifest = ":component_with_collection_manifest",
)

fuchsia_package(
    name = "package",
    package_name = "package_for_scrutiny_testing",
    components = [
        ":component_with_broken_use",
        ":component_with_collection",
        ":test_session",
    ],
    fuchsia_api_level = "HEAD",
)

fuchsia_board_configuration(
    name = "board_config",
    board_name = "test",
    filesystems = {
        "fvm": {
        },
    },
    partitions_configuration = "//build/bazel/assembly/partitions_configurations:default",
    version = "fake_version",
)

fuchsia_product_configuration(
    name = "product_config",
    base_packages = [
        ":package",
    ],
    product_config_json = {
        "platform": {
            "build_type": "user",
            "session": {
                "enabled": True,
                "autolaunch": False,
            },

            # These are all required (to compile the core realm) when the session is
            # enabled:
            "bluetooth": {
                "type": "standard",
            },
            "media": {
                "audio": {
                    "full_stack": {},
                },
            },
            "ui": {
                "enabled": True,
            },
        },
        "product": {
            "session": {
                "url": "fuchsia-pkg://fuchsia.com/package_for_scrutiny_testing#meta/test_session.cm",
            },
        },
    },
)

fuchsia_product(
    name = "main_image",
    board_config = ":board_config",
    platform_artifacts = "//build/bazel/assembly/assembly_input_bundles:platform_user",
    product_config = ":product_config",
)

fuchsia_product_bundle(
    name = "product_bundle",
    testonly = True,
    main = ":main_image",
    product_bundle_name = "scrutiny-failed-route-verify-test",
    repository_keys = "//src/sys/pkg/repositories/devhost/keys:keys",
    update_epoch = "1",
)
