# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

[package]
name = "sapphire-gap"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
rand_core = { version = "0.10.1", default-features = false }
sapphire-collections = { path = "../sapphire-collections" }
sapphire-common = { path = "../sapphire-common" }

