# Copyright 2026 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/cpp/library_headers.gni")
import("//zircon/kernel/kernel_rust_mod.gni")

library_headers("headers") {
  headers = [ "dev/power/iris/init.h" ]
}

kernel_rust_mod("iris-rs") {
  output_name = "power_iris"
  source_root = "iris.rs"
  sources = [ "iris.rs" ]
  deps = [
    "//sdk/rust/zx-status",
    "//src/lib/regio",
    "//zircon/kernel/lib/debug",
  ]
  test_deps = [ "//zircon/kernel/lib/unittest:unittest-rs" ]
}

source_set("iris") {
  sources = [ "iris_ffi.cc" ]
  public_deps = [ ":headers" ]
  deps = [
    ":iris-rs",
    "//zircon/kernel/dev/pdev/power",
    "//zircon/kernel/dev/psci",
    "//zircon/kernel/lib/arch",
    "//zircon/kernel/lib/power-management",
    "//zircon/system/ulib/fbl",
  ]
}
