# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/components.gni")
import("//build/rust/rustc_library.gni")

rustc_library("ffl") {
  edition = "2024"
  sources = [
    "src/exponential_average.rs",
    "src/expression.rs",
    "src/fast.rs",
    "src/fixed.rs",
    "src/fixed_format.rs",
    "src/lib.rs",
    "src/num_traits.rs",
    "src/saturating_arithmetic.rs",
    "src/string.rs",
    "src/tests.rs",
    "src/utility.rs",
  ]
  with_unit_tests = true
  deps = []
}

fuchsia_unittest_package("ffl-rust-test-pkg") {
  package_name = "ffl-rust-test"
  deps = [ ":ffl_test" ]
}

group("tests") {
  testonly = true
  deps = [
    ":ffl-rust-test-pkg",
    ":ffl_test($host_toolchain)",
  ]
}
