# Copyright 2020 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/cpp/library_headers.gni")
import("//zircon/kernel/kernel_rust_mod.gni")

library_headers("headers") {
  headers = [ "lib/root_resource_filter.h" ]
}

kernel_rust_mod("root_resource_filter_rs") {
  output_name = "root_resource_filter"
  source_root = "src/mod.rs"
  sources = [ "src/mod.rs" ]
  deps = [
    "//sdk/rust/zx-types",
    "//src/lib/zr",
    "//third_party/rust_crates:pin-init",
    "//zircon/kernel/lib/debug",
    "//zircon/kernel/lib/init:init_rust",
    "//zircon/kernel/lib/page:page-rs",
    "//zircon/system/ulib/region-alloc/rust:region-alloc",
  ]
  test_deps = [ "//zircon/kernel/lib/unittest:unittest-rs" ]
}

static_library("root_resource_filter") {
  public_deps = [ ":headers" ]

  sources = [ "root_resource_filter_ffi.cc" ]
  deps = [
    ":root_resource_filter_rs",
    "//zircon/kernel/phys:handoff",
    "//zircon/kernel/phys/lib/memalloc",
    "//zircon/system/ulib/region-alloc:headers",
  ]
}

group("tests") {
  testonly = true
}

group("kernel-tests") {
  testonly = true
}

group("phys-tests") {
  testonly = true
}

group("boot_tests") {
  testonly = true
}
