import enum
import logging
from collections.abc import Generator

from _typeshed import Incomplete
from mobly import runtime_test_info as runtime_test_info
from mobly import utils as utils
from mobly.controllers.android_device_lib import adb as adb
from mobly.controllers.android_device_lib import errors as errors
from mobly.controllers.android_device_lib import fastboot as fastboot
from mobly.controllers.android_device_lib import (
    service_manager as service_manager,
)
from mobly.controllers.android_device_lib.services import logcat as logcat
from mobly.controllers.android_device_lib.services import (
    snippet_management_service as snippet_management_service,
)

MBS_PACKAGE: str
MOBLY_CONTROLLER_CONFIG_NAME: str
ANDROID_DEVICE_PICK_ALL_TOKEN: str
ANDROID_DEVICE_ADB_LOGCAT_PARAM_KEY: str
ANDROID_DEVICE_EMPTY_CONFIG_MSG: str
ANDROID_DEVICE_NOT_LIST_CONFIG_MSG: str
CACHED_SYSTEM_PROPS: Incomplete
KEY_DEVICE_REQUIRED: str
DEFAULT_VALUE_DEVICE_REQUIRED: bool
KEY_SKIP_LOGCAT: str
DEFAULT_VALUE_SKIP_LOGCAT: bool
SERVICE_NAME_LOGCAT: str
DEFAULT_BUG_REPORT_NAME: str
DEFAULT_TIMEOUT_BOOT_COMPLETION_SECOND: Incomplete
TAKE_SCREENSHOT_TIMEOUT_SECOND: int
Error = errors.Error
DeviceError = errors.DeviceError
SnippetError = snippet_management_service.Error
EMULATOR_SERIAL_REGEX: Incomplete

def create(configs): ...
def destroy(ads) -> None: ...
def get_info(ads): ...
def parse_device_list(device_list_str, key): ...
def list_adb_devices(): ...
def list_adb_devices_by_usb_id(): ...
def list_fastboot_devices(): ...
def get_instances(serials): ...
def get_instances_with_configs(configs): ...
def get_all_instances(include_fastboot: bool = ...): ...
def filter_devices(ads, func): ...
def get_devices(ads, **kwargs): ...
def get_device(ads, **kwargs): ...
def take_bug_reports(
    ads,
    test_name: Incomplete | None = ...,
    begin_time: Incomplete | None = ...,
    destination: Incomplete | None = ...,
) -> None: ...

class BuildInfoConstants(enum.Enum):
    BUILD_ID: Incomplete
    BUILD_TYPE: Incomplete
    BUILD_FINGERPRINT: Incomplete
    BUILD_VERSION_CODENAME: Incomplete
    BUILD_VERSION_INCREMENTAL: Incomplete
    BUILD_VERSION_SDK: Incomplete
    BUILD_PRODUCT: Incomplete
    BUILD_CHARACTERISTICS: Incomplete
    DEBUGGABLE: Incomplete
    PRODUCT_NAME: Incomplete
    HARDWARE: Incomplete
    build_info_key: Incomplete
    system_prop_key: Incomplete
    def __init__(self, build_info_key, system_prop_key) -> None: ...

class AndroidDevice:
    log: Incomplete
    adb: Incomplete
    fastboot: Incomplete
    services: Incomplete
    def __init__(self, serial: str = ...) -> None: ...
    @property
    def adb_logcat_file_path(self): ...
    @property
    def device_info(self): ...
    def add_device_info(self, name, info) -> None: ...
    @property
    def sl4a(self): ...
    @property
    def ed(self): ...
    @property
    def debug_tag(self): ...
    @debug_tag.setter
    def debug_tag(self, tag) -> None: ...
    @property
    def has_active_service(self): ...
    @property
    def log_path(self): ...
    @log_path.setter
    def log_path(self, new_path) -> None: ...
    @property
    def serial(self): ...
    def update_serial(self, new_serial) -> None: ...
    def handle_reboot(self) -> Generator[None, None, None]: ...
    def handle_usb_disconnect(self) -> Generator[None, None, None]: ...
    @property
    def build_info(self): ...
    @property
    def is_bootloader(self): ...
    @property
    def is_adb_root(self): ...
    @property
    def is_rootable(self): ...
    @property
    def model(self): ...
    @property
    def is_emulator(self): ...
    def load_config(self, config) -> None: ...
    def root_adb(self) -> None: ...
    def load_snippet(self, name, package) -> None: ...
    def unload_snippet(self, name) -> None: ...
    def generate_filename(
        self,
        file_type,
        time_identifier: Incomplete | None = ...,
        extension_name: Incomplete | None = ...,
    ): ...
    def take_bug_report(
        self,
        test_name: Incomplete | None = ...,
        begin_time: Incomplete | None = ...,
        timeout: int = ...,
        destination: Incomplete | None = ...,
    ): ...
    def take_screenshot(self, destination, prefix: str = ...): ...
    def run_iperf_client(self, server_host, extra_args: str = ...): ...
    def wait_for_boot_completion(self, timeout=...) -> None: ...
    def is_boot_completed(self): ...
    def is_adb_detectable(self): ...
    def reboot(self) -> None: ...
    def __getattr__(self, name): ...

class AndroidDeviceLoggerAdapter(logging.LoggerAdapter):
    def process(self, msg, kwargs): ...
