from _typeshed import Incomplete

MOBLY_CONTROLLER_CONFIG_NAME: str
KEY_ADDRESS: str
KEY_PORT: str
KEY_MODEL: str
KEY_PATHS: str
PACKAGE_PATH_TEMPLATE: str

def create(configs): ...
def destroy(objs) -> None: ...

class Error(Exception): ...

class AttenuatorPath:
    model: Incomplete
    attenuation_device: Incomplete
    idx: Incomplete
    def __init__(
        self, attenuation_device, idx: int = ..., name: Incomplete | None = ...
    ) -> None: ...
    def set_atten(self, value) -> None: ...
    def get_atten(self): ...
    def get_max_atten(self): ...
