from _typeshed import Incomplete

MOBLY_CONTROLLER_CONFIG_NAME: str

def create(configs): ...
def destroy(objs) -> None: ...

class SnifferError(Exception): ...
class InvalidDataError(Exception): ...
class ExecutionError(SnifferError): ...
class InvalidOperationError(SnifferError): ...

class Sniffer:
    CONFIG_KEY_CHANNEL: str
    def __init__(
        self, interface, logger, base_configs: Incomplete | None = ...
    ) -> None: ...
    def get_descriptor(self) -> None: ...
    def get_type(self) -> None: ...
    def get_subtype(self) -> None: ...
    def get_interface(self) -> None: ...
    def get_capture_file(self) -> None: ...
    def start_capture(
        self,
        override_configs: Incomplete | None = ...,
        additional_args: Incomplete | None = ...,
        duration: Incomplete | None = ...,
        packet_count: Incomplete | None = ...,
    ) -> None: ...
    def stop_capture(self) -> None: ...
    def wait_for_capture(self, timeout: Incomplete | None = ...) -> None: ...

class ActiveCaptureContext:
    def __init__(self, sniffer, timeout: Incomplete | None = ...) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, type, value, traceback) -> None: ...
