// Copyright 2023 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

use crate::Unlocked;
use lock_ordering_macro::lock_ordering;

lock_ordering! {
    // keep-sorted start
    AioPendingOperationsLock => WaitQueueImplLock,
    BeforeFsNodeAppend => FsNodeAppend,
    BinderFreezeLevel => BinderProcessStateLevel,
    BinderFsDevicesLevel => DeviceRegistryState,
    BinderFsDevicesLevel => FsNodeInfoLevel,
    BinderObjectLevel => BinderThreadStateLock,
    BinderProcessSharedMemoryLevel => BinderFreezeLevel,
    BinderProcessSharedMemoryLevel => FdTableWriterQueueLock,
    BinderProcessSharedMemoryLevel => FsRenameRecursive,
    BinderProcessStateLevel => BinderContextManagerLevel,
    BinderProcessStateLevel => BinderObjectLevel,
    BinderProcsLevel => BinderProcessSharedMemoryLevel,
    CgroupChildrenLock => CgroupStateLock,
    CgroupPidTableLock => ThreadGroupMutableStateLock,
    CgroupStateLock => ThreadGroupMutableStateLock,
    CgroupV1Level => CgroupPidTableLock,
    DeviceRegistryState => NetlinkSocketInnerLock,
    DirEntryChildrenLevel => BinderFsDevicesLevel,
    DirEntryChildrenLevel => CgroupChildrenLock,
    DirEntryChildrenLevel => InotifyStateLock,
    DirEntryChildrenLevel => NetstackDevicesLock,
    DirEntryChildrenRecursiveLevel => FsNodeInfoRecursiveLevel,
    DirEntryChildrenRecursiveLevel => MemoryDirectoryReaddirPositionLock,
    DynamicFileStateLock => CgroupPidTableLock,
    EbpfMapStateLevel => EbpfSuspendLock,
    EbpfStateLock => EbpfSuspendLock,
    EpollStateLock => EpollWaitableStateLock,
    EpollWaitableStateLock => WaitQueueImplLock,
    ExecutorVmarManagerLock => PidToKoidMapLock,
    FileEpollFilesLock => EpollStateLock,
    FileObjectOffset => BeforeFsNodeAppend,
    FileObjectOffset => DynamicFileStateLock,
    FileOpsCore => UninterruptibleLock,
    FsContextStateLock => MountsLevel,
    FsNodeAppend => FileOpsCore,
    FsNodeFlockInfoLock => WaitQueueImplLock,
    FsNodeInfoLevel => FsNodeWriteGuardStateLock,
    FsNodeInfoRecursiveLevel => FsRename,
    FsRename => DirEntryChildrenLevel,
    FsRenameRecursive => DirEntryChildrenRecursiveLevel,
    FuseDirEntryChildrenLevel => FuseFsNodeInfoLevel,
    FuseFsNodeInfoLevel => UninterruptibleLock,
    FuseFsRenameLevel => FuseDirEntryChildrenLevel,
    FutexTableStateLock => MemoryManagerStateLock,
    GenericNetlinkServerStateLock => NetlinkSocketInnerLock,
    InotifyStateLock => EventHandlerReadyQueueLock,
    InotifyStateLock => PortWaiterCallbacksLock,
    InotifyStateLock => WaitQueueImplLock,
    MemoryAttributionPublisherLock => DynamicThreadSpawnerLock,
    MemoryDirectoryReaddirPositionLock => DirEntryChildrenLevel,
    MemoryManagerStateLock => FsContextStateLock,
    MemoryManagerStateLock => FsNodeInfoLevel,
    MemoryManagerStateLock => InflightVmsplicedPayloadsLock,
    MemoryPressureMonitor => MemoryPressureMonitorClientState,
    MmDumpable => ThreadGroupLimits,
    NetlinkSocketInnerLock => EpollWaitableStateLock,
    NetstackDevicesLock => RwQueueInnerLock,
    NetstackDevicesLock => SimpleDirectoryEntriesLock,
    ProcessGroupState => ThreadGroupLimits,
    RecordLocksStateLock => WaitQueueImplLock,
    RemoteBinderHandleLevel => BinderProcsLevel,
    RemoteBlockDeviceRegistryDevicesLock => SimpleDirectoryEntriesLock,
    ResourceAccessorLevel => FileOpsCore,
    SessionMutableStateLock => TaskMutableStateLock,
    SignalFdMaskLock => ThreadGroupPendingSignalsLock,
    SimpleDirectoryEntriesLock => FsNodeInfoLevel,
    SyslogSubscriptionLock => PortWaiterCallbacksLock,
    SyslogSubscriptionLock => WaitQueueImplLock,
    TaskCredsLock => FdTableWriterQueueLock,
    TaskCredsLock => FsNodeInfoRecursiveLevel,
    TaskMutableStateLock => EpollWaitableStateLock,
    TaskMutableStateLock => FdTableWriterQueueLock,
    TaskMutableStateLock => FutexTableStateLock,
    TaskMutableStateLock => IntervalTimerState,
    TaskMutableStateLock => MmDumpable,
    TaskMutableStateLock => SeccompNotifierLock,
    TaskMutableStateLock => SignalFdMaskLock,
    TaskRelease => FileOpsCore,
    TerminalMutableStateLock => EventHandlerReadyQueueLock,
    TerminalMutableStateLock => PortWaiterCallbacksLock,
    TerminalMutableStateLock => SessionMutableStateLock,
    ThreadGroupMutableStateLock => ProcessGroupState,
    ThreadGroupMutableStateLock => TaskCommandLevel,
    ThreadGroupMutableStateLock => TerminalMutableStateLock,
    ThreadGroupPtraceesLock => ThreadGroupMutableStateLock,
    TimerFileInfoLock => HrTimerManagerStateLock,
    TimerFileInfoLock => PortWaiterCallbacksLock,
    TimerFileInfoLock => TaskMutableStateLock,
    TimerTableStateLock => IntervalTimerState,
    UEventNetlinkSocketDeviceListenerKeyLock => DeviceRegistryState,
    UninterruptibleLock => AioPendingOperationsLock,
    UninterruptibleLock => CgroupV1Level,
    UninterruptibleLock => ComponentMountRecordLock,
    UninterruptibleLock => DevKmsgLock,
    UninterruptibleLock => EbpfMapStateLevel,
    UninterruptibleLock => EbpfStateLock,
    UninterruptibleLock => ExecutorVmarManagerLock,
    UninterruptibleLock => FastrpcInnerState,
    UninterruptibleLock => FileEpollFilesLock,
    UninterruptibleLock => FsNodeFlockInfoLock,
    UninterruptibleLock => GenericNetlinkServerStateLock,
    UninterruptibleLock => InotifyWatchersLock,
    UninterruptibleLock => KernelIpTables,
    UninterruptibleLock => KernelSwapFiles,
    UninterruptibleLock => MemoryAttributionPublisherLock,
    UninterruptibleLock => MemoryPressureMonitor,
    UninterruptibleLock => MemoryXattrStorageLevel,
    UninterruptibleLock => PerfEventLevel,
    UninterruptibleLock => QipcrtrSocketInnerLock,
    UninterruptibleLock => RemoteBinderHandleLevel,
    UninterruptibleLock => RemoteBlockDeviceRegistryDevicesLock,
    UninterruptibleLock => SeccompNotifierLock,
    UninterruptibleLock => SyslogSubscriptionLock,
    UninterruptibleLock => TaskCredsLock,
    UninterruptibleLock => ThreadGroupPtraceesLock,
    UninterruptibleLock => TimerFileInfoLock,
    UninterruptibleLock => UnixSocketInnerLock,
    UninterruptibleLock => UserFaultInner,
    UninterruptibleLock => VsockSocketInnerLock,
    UninterruptibleLock => WaiterEventHandlerLock,
    Unlocked => FileObjectOffset,
    Unlocked => FuseFsRenameLevel,
    Unlocked => RecordLocksStateLock,
    Unlocked => ResourceAccessorLevel,
    Unlocked => TaskRelease,
    VsockSocketInnerLock => PortWaiterCallbacksLock,
    VsockSocketInnerLock => WaitQueueImplLock,
    WaitQueueImplLock => PortWaiterWaitQueuesLock,
    WaiterEventHandlerLock => EpollWaitableStateLock,
    // keep-sorted end

    // Terminal Levels. No lock level should ever be defined after this.
    // Can be used for any locks that is never acquired before any other lock.
    // keep-sorted start
    Terminal(AioEventsLock),
    Terminal(AuditDenyCountsLock),
    Terminal(AuditNetlinkClientAuditResponseLock),
    Terminal(AuditQueueLock),
    Terminal(BootedLock),
    Terminal(ComponentControllerLock),
    Terminal(DeviceTerminalsLock),
    Terminal(DynamicThreadSpawnerLock),
    Terminal(EventFdInnerLock),
    Terminal(EventHandlerReadyQueueLock),
    Terminal(FileAsyncOwnerLock),
    Terminal(FileLeaseLock),
    Terminal(FileServerStatsLock),
    Terminal(FileSystemEntriesLock),
    Terminal(FileSystemPermanentLock),
    Terminal(FsNodeFsVerityLock),
    Terminal(FsRegistryLock),
    Terminal(FuchsiaRemoteTargetLock),
    Terminal(HrTimerIsIntervalLock),
    Terminal(HrTimerManagerStateLock),
    Terminal(IcmpPingGidsLock),
    Terminal(InotifyWatchersLock),
    Terminal(IoUringStateLock),
    Terminal(MapInfoCacheBufLock),
    Terminal(MountsLevel),
    Terminal(NamespaceFlagsLock),
    Terminal(PagerFilesByInodeLock),
    Terminal(PagerFilesystemsLock),
    Terminal(PerfFormatIdLookupTableLock),
    Terminal(PerfRingBufferStateLock),
    Terminal(PidToKoidMapInnerLock),
    Terminal(PortWaiterCallbacksLock),
    Terminal(PortWaiterWaitQueuesLock),
    Terminal(PowerMessageCountersLock),
    Terminal(ProfileHandleCacheLock),
    Terminal(PtsIdsSetLock),
    Terminal(RemoteBinderControllerLock),
    Terminal(RemoteBundleInnerLock),
    Terminal(RemoteUnixDomainSocketStateLock),
    Terminal(RwQueueInnerLock),
    Terminal(SeLinuxPeerSidLock),
    Terminal(SeLinuxPendingEntriesLock),
    Terminal(SeLinuxPendingFileSystemsLock),
    Terminal(SeLinuxUpdateLock),
    Terminal(SignalActionsLock),
    Terminal(SocketStateLock),
    Terminal(StubBytesFileStateLock),
    Terminal(SuspendResumeManagerInnerLock),
    Terminal(SyscallLogFiltersLock),
    Terminal(SyslogStateLock),
    Terminal(TaskCommandLevel),
    Terminal(ThreadLockupDetectorRegistryLock),
    Terminal(TouchPowerPolicyEnabledLock),
    Terminal(UtsNamespaceLock),
    Terminal(VmspliceSegmentsLock),
    Terminal(WakeSourcesLock),
    Terminal(WakeWatchersLock),
    // keep-sorted end
}
