// Copyright 2023 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

use crate::Unlocked;
use lock_ordering_macro::lock_ordering;

lock_ordering! {
    // keep-sorted start
    AioPendingOperationsLock => WaitQueueImplLock,
    AshmemStateLock => FsNodeWriteGuardStateLock,
    BeforeFsNodeAppend => FsNodeAppend,
    BinderFreezeLevel => BinderProcessStateLevel,
    BinderFsDevicesLevel => DeviceRegistryState,
    BinderFsDevicesLevel => FsNodeInfoLevel,
    BinderFsDevicesLevel => RwQueueInnerLock,
    BinderObjectLevel => BinderThreadStateLock,
    BinderProcessSharedMemoryLevel => BinderFreezeLevel,
    BinderProcessSharedMemoryLevel => FsRenameRecursive,
    BinderProcessStateLevel => BinderContextManagerLevel,
    BinderProcessStateLevel => BinderObjectLevel,
    BinderProcsLevel => BinderProcessSharedMemoryLevel,
    BinderThreadStateLock => ThreadGroupMutableStateLock,
    BinderThreadStateLock => WaiterEventHandlerLock,
    CgroupChildrenLock => CgroupStateLock,
    CgroupDirectoryInterfaceFilesLock => CgroupChildrenLock,
    CgroupDirectoryInterfaceFilesLock => CgroupDirectoryNodesLock,
    CgroupDirectoryInterfaceFilesLock => RwQueueInnerLock,
    CgroupPidTableLock => CgroupStateLock,
    CgroupStateLock => ThreadGroupMutableStateLock,
    CgroupV1Level => CgroupPidTableLock,
    DeviceMapperRegistryDevicesLock => DmDeviceStateLock,
    DeviceMapperRegistryDevicesLock => DynamicThreadSpawnerLock,
    DeviceRegistryState => NetlinkSocketInnerLock,
    DeviceTerminalsLock => TerminalMutableStateLock,
    DirEntryChildrenLevel => BinderFsDevicesLevel,
    DirEntryChildrenLevel => CgroupDirectoryInterfaceFilesLock,
    DirEntryChildrenLevel => FileSystemEntriesLock,
    DirEntryChildrenLevel => FileSystemPermanentLock,
    DirEntryChildrenLevel => InotifyStateLock,
    DirEntryChildrenLevel => NetstackDevicesLock,
    DirEntryChildrenLevel => NmfsNetworkManagerLock,
    DirEntryChildrenLevel => SeLinuxPendingEntriesLock,
    DirEntryChildrenLevel => SeLinuxUpdateLock,
    DirEntryChildrenLevel => UnixSocketInnerLock,
    DirEntryChildrenRecursiveLevel => FsNodeInfoRecursiveLevel,
    DirEntryChildrenRecursiveLevel => MemoryDirectoryReaddirPositionLock,
    DmDeviceStateLock => DirEntryChildrenLevel,
    DynamicFileStateLock => CgroupV1Level,
    DynamicFileStateLock => FsRegistryLock,
    DynamicFileStateLock => MapInfoCacheBufLock,
    DynamicFileStateLock => MemoryPressureMonitor,
    DynamicFileStateLock => TaskCredsLock,
    EbpfMapStateLevel => EbpfSuspendLock,
    EbpfStateLock => EbpfSuspendLock,
    EpollStateLock => BinderProcsLevel,
    EpollStateLock => EventFdInnerLock,
    EpollStateLock => MemoryPressureMonitor,
    EpollStateLock => SuspendResumeManagerInnerLock,
    EpollStateLock => TimerFileInfoLock,
    EpollWaitableStateLock => WaitQueueImplLock,
    ExecutorVmarManagerLock => PidToKoidMapLock,
    ExecutorVmarManagerLock => ThreadGroupPtraceesLock,
    FileEpollFilesLock => EpollStateLock,
    FileObjectOffset => BeforeFsNodeAppend,
    FileObjectOffset => DynamicFileStateLock,
    FileObjectOffset => FuseFsNodeInfoLevel,
    FileObjectOffset => FuseNodeStateLock,
    FileObjectOffset => IcmpPingGidsLock,
    FileObjectOffset => PerfRingBufferStateLock,
    FileObjectOffset => SeLinuxFsContextSidLock,
    FileObjectOffset => SeLinuxPendingFileSystemsLock,
    FileObjectOffset => StubBytesFileStateLock,
    FileOpsCore => UninterruptibleLock,
    FramebufferInfoLock => FramebufferPresentationReceiverLock,
    FramebufferInfoLock => FramebufferViewBoundProtocolsLock,
    FramebufferInfoLock => FramebufferViewIdentityLock,
    FsContextStateLock => MountsLevel,
    FsNodeAppend => FileOpsCore,
    FsNodeFlockInfoLock => WaitQueueImplLock,
    FsNodeInfoLevel => FsNodeWriteGuardStateLock,
    FsNodeInfoRecursiveLevel => FsRename,
    FsNodeWriteGuardStateLock => FsNodeFsVerityLock,
    FsNodeWriteGuardStateLock => ThreadGroupLimits,
    FsRename => DirEntryChildrenLevel,
    FsRenameRecursive => DirEntryChildrenRecursiveLevel,
    FunctionFsStateLock => WaitQueueImplLock,
    FuseConnectionStateLock => PortWaiterCallbacksLock,
    FuseConnectionStateLock => WaitQueueImplLock,
    FuseDirEntryChildrenLevel => FuseFsNodeInfoLevel,
    FuseDirEntryChildrenLevel => FuseNodeStateLock,
    FuseFsNodeInfoLevel => UninterruptibleLock,
    FuseFsRenameLevel => FuseDirEntryChildrenLevel,
    FutexTableStateLock => FsContextStateLock,
    FutexTableStateLock => FsNodeInfoLevel,
    FutexTableStateLock => InflightVmsplicedPayloadsLock,
    GenericNetlinkServerStateLock => NetlinkSocketInnerLock,
    InotifyStateLock => EventHandlerReadyQueueLock,
    InotifyStateLock => PortWaiterCallbacksLock,
    InotifyStateLock => WaitQueueImplLock,
    InputEventRelayOpenedFilesLock => WaitQueueImplLock,
    LoopDeviceStateLock => FsNodeInfoLevel,
    LoopDeviceStateLock => RemoteBundleInnerLock,
    LoopDevicesLock => DeviceRegistryState,
    LoopDevicesLock => DynamicThreadSpawnerLock,
    LoopDevicesLock => LoopDeviceStateLock,
    LoopDevicesLock => SimpleDirectoryEntriesLock,
    LoopDevicesLock => TaskMutableStateLock,
    MemoryAttributionPublisherLock => DynamicThreadSpawnerLock,
    MemoryDirectoryReaddirPositionLock => DirEntryChildrenLevel,
    MemoryPressureMonitor => MemoryPressureMonitorClientState,
    MemoryPressureMonitor => PortWaiterCallbacksLock,
    MmDumpable => ThreadGroupLimits,
    NetlinkSocketInnerLock => EpollWaitableStateLock,
    NetlinkSocketInnerLock => EventHandlerReadyQueueLock,
    NetlinkSocketInnerLock => PortWaiterCallbacksLock,
    NetstackDevicesLock => SimpleDirectoryEntriesLock,
    OverlayFsStateLock => FsNodeInfoLevel,
    ProcessGroupState => ThreadGroupLimits,
    RecordLocksStateLock => PortWaiterCallbacksLock,
    RecordLocksStateLock => WaitQueueImplLock,
    RemoteBinderHandleLevel => BinderProcsLevel,
    RemoteBlockDeviceRegistryDevicesLock => SimpleDirectoryEntriesLock,
    ResourceAccessorLevel => FileOpsCore,
    SessionMutableStateLock => TaskMutableStateLock,
    SignalFdMaskLock => ThreadGroupPendingSignalsLock,
    SimpleDirectoryEntriesLock => FsNodeInfoLevel,
    SimpleDirectoryEntriesLock => RwQueueInnerLock,
    SyslogSubscriptionLock => PortWaiterCallbacksLock,
    SyslogSubscriptionLock => WaitQueueImplLock,
    TaskCredsLock => FsNodeInfoRecursiveLevel,
    TaskMutableStateLock => EpollWaitableStateLock,
    TaskMutableStateLock => FdTableWriterQueueLock,
    TaskMutableStateLock => FutexTableStateLock,
    TaskMutableStateLock => IntervalTimerState,
    TaskMutableStateLock => MmDumpable,
    TaskMutableStateLock => PortWaiterCallbacksLock,
    TaskMutableStateLock => ProfileHandleCacheLock,
    TaskMutableStateLock => SeccompNotifierLock,
    TaskMutableStateLock => SignalActionsLock,
    TaskMutableStateLock => SignalFdMaskLock,
    TaskMutableStateLock => TaskCommandLevel,
    TaskMutableStateLock => UtsNamespaceLock,
    TaskRelease => FileOpsCore,
    TerminalMutableStateLock => EventHandlerReadyQueueLock,
    TerminalMutableStateLock => SessionMutableStateLock,
    ThreadGroupMutableStateLock => DeviceTerminalsLock,
    ThreadGroupMutableStateLock => ProcessGroupState,
    ThreadGroupPtraceesLock => ThreadGroupMutableStateLock,
    TimerFileInfoLock => HrTimerManagerStateLock,
    TimerFileInfoLock => TaskMutableStateLock,
    TimerTableStateLock => HrTimerIsIntervalLock,
    TimerTableStateLock => IntervalTimerState,
    UEventNetlinkSocketDeviceListenerKeyLock => DeviceRegistryState,
    UinputDeviceStateLock => DirEntryChildrenLevel,
    UninterruptibleLock => AioPendingOperationsLock,
    UninterruptibleLock => AshmemStateLock,
    UninterruptibleLock => CgroupV1Level,
    UninterruptibleLock => ComponentMountRecordLock,
    UninterruptibleLock => DevKmsgLock,
    UninterruptibleLock => DeviceMapperRegistryDevicesLock,
    UninterruptibleLock => EbpfMapStateLevel,
    UninterruptibleLock => EbpfStateLock,
    UninterruptibleLock => ExecutorVmarManagerLock,
    UninterruptibleLock => FastrpcInnerState,
    UninterruptibleLock => FileEpollFilesLock,
    UninterruptibleLock => FramebufferInfoLock,
    UninterruptibleLock => FsNodeFlockInfoLock,
    UninterruptibleLock => FunctionFsStateLock,
    UninterruptibleLock => FuseConnectionStateLock,
    UninterruptibleLock => GenericNetlinkServerStateLock,
    UninterruptibleLock => InotifyWatchersLock,
    UninterruptibleLock => InputDeviceFileNodesLock,
    UninterruptibleLock => InputEventRelayOpenedFilesLock,
    UninterruptibleLock => KernelIpTables,
    UninterruptibleLock => KernelSwapFiles,
    UninterruptibleLock => LoopDevicesLock,
    UninterruptibleLock => MemoryAttributionPublisherLock,
    UninterruptibleLock => MemoryXattrStorageLevel,
    UninterruptibleLock => OverlayFsStateLock,
    UninterruptibleLock => PerfEventLevel,
    UninterruptibleLock => QipcrtrSocketInnerLock,
    UninterruptibleLock => RemoteBinderHandleLevel,
    UninterruptibleLock => RemoteBlockDeviceRegistryDevicesLock,
    UninterruptibleLock => SyslogSubscriptionLock,
    UninterruptibleLock => TaskCredsLock,
    UninterruptibleLock => UinputDeviceStateLock,
    UninterruptibleLock => UserFaultInner,
    UninterruptibleLock => VsockSocketInnerLock,
    UnixSocketInnerLock => EpollWaitableStateLock,
    UnixSocketInnerLock => EventHandlerReadyQueueLock,
    UnixSocketInnerLock => PortWaiterCallbacksLock,
    UnixSocketInnerLock => SeLinuxPeerSidLock,
    UnixSocketInnerLock => SocketStateLock,
    Unlocked => FileObjectOffset,
    Unlocked => FuseFsRenameLevel,
    Unlocked => RecordLocksStateLock,
    Unlocked => ResourceAccessorLevel,
    Unlocked => TaskRelease,
    VsockSocketInnerLock => PortWaiterCallbacksLock,
    VsockSocketInnerLock => WaitQueueImplLock,
    WaitQueueImplLock => PortWaiterWaitQueuesLock,
    WaiterEventHandlerLock => EpollWaitableStateLock,
    // keep-sorted end

    // Terminal Levels. No lock level should ever be defined after this.
    // Can be used for any locks that is never acquired before any other lock.
    // keep-sorted start
    Terminal(AioEventsLock),
    Terminal(AuditDenyCountsLock),
    Terminal(AuditNetlinkClientAuditResponseLock),
    Terminal(AuditQueueLock),
    Terminal(AuditSinkLock),
    Terminal(BootedLock),
    Terminal(CgroupDirectoryNodesLock),
    Terminal(ComponentControllerLock),
    Terminal(DynamicThreadSpawnerLock),
    Terminal(EventFdInnerLock),
    Terminal(EventHandlerReadyQueueLock),
    Terminal(FileAsyncOwnerLock),
    Terminal(FileLeaseLock),
    Terminal(FileServerStatsLock),
    Terminal(FileSystemEntriesLock),
    Terminal(FileSystemPermanentLock),
    Terminal(FramebufferMemoryLock),
    Terminal(FramebufferPresentationReceiverLock),
    Terminal(FramebufferSceneStateLock),
    Terminal(FramebufferViewBoundProtocolsLock),
    Terminal(FramebufferViewIdentityLock),
    Terminal(FsNodeFsVerityLock),
    Terminal(FsRegistryLock),
    Terminal(FuchsiaRemoteTargetLock),
    Terminal(FunctionFsResultLock),
    Terminal(FuseConnectionsLock),
    Terminal(FuseNodeStateLock),
    Terminal(HrTimerIsIntervalLock),
    Terminal(HrTimerManagerStateLock),
    Terminal(IcmpPingGidsLock),
    Terminal(InotifyWatchersLock),
    Terminal(InputFileInputFileLock),
    Terminal(IoUringStateLock),
    Terminal(KgslAllocatorLock),
    Terminal(KgslContextsLock),
    Terminal(KgslGpuObjsLock),
    Terminal(KgslSyncSourcesLock),
    Terminal(MagmaBuffersLock),
    Terminal(MagmaConnectionsLock),
    Terminal(MagmaDevicesLock),
    Terminal(MagmaSemaphoresLock),
    Terminal(MapInfoCacheBufLock),
    Terminal(MountsLevel),
    Terminal(NamespaceFlagsLock),
    Terminal(NanohubContentsLock),
    Terminal(NanohubServiceLock),
    Terminal(NetnsIdLock),
    Terminal(NmfsNetworkManagerLock),
    Terminal(OverlayFsDirEntriesLock),
    Terminal(PagerFilesByInodeLock),
    Terminal(PagerFilesystemsLock),
    Terminal(PerfFormatIdLookupTableLock),
    Terminal(PerfRingBufferStateLock),
    Terminal(PidToKoidMapInnerLock),
    Terminal(PortWaiterCallbacksLock),
    Terminal(PortWaiterWaitQueuesLock),
    Terminal(PowerMessageCountersLock),
    Terminal(ProfileHandleCacheLock),
    Terminal(PtsIdsSetLock),
    Terminal(QbgReadQueueLock),
    Terminal(QbgShutdownLock),
    Terminal(ReadWriteBytesFileLock),
    Terminal(RemoteBinderControllerLock),
    Terminal(RemoteBinderResponderLock),
    Terminal(RemoteBundleInnerLock),
    Terminal(RemoteUnixDomainSocketStateLock),
    Terminal(RwQueueInnerLock),
    Terminal(SeLinuxFsContextSidLock),
    Terminal(SeLinuxPeerSidLock),
    Terminal(SeLinuxPendingEntriesLock),
    Terminal(SeLinuxPendingFileSystemsLock),
    Terminal(SeLinuxUpdateLock),
    Terminal(SignalActionsLock),
    Terminal(SocketStateLock),
    Terminal(StubBytesFileStateLock),
    Terminal(SuspendResumeManagerInnerLock),
    Terminal(SyscallLogFiltersLock),
    Terminal(SyslogStateLock),
    Terminal(TaskCommandLevel),
    Terminal(ThermalChargeLevelLock),
    Terminal(ThreadLockupDetectorRegistryLock),
    Terminal(TouchPowerPolicyEnabledLock),
    Terminal(TraceFsDataLock),
    Terminal(TunDevTunLock),
    Terminal(UtsNamespaceLock),
    Terminal(VmspliceSegmentsLock),
    Terminal(WakeSourcesLock),
    Terminal(WakeWatchersLock),
    // keep-sorted end
}
