// Copyright 2023 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

use crate::Unlocked;
use lock_ordering_macro::lock_ordering;

lock_ordering! {
    // keep-sorted start
    BeforeFsNodeAppend => FsNodeAppend,
    BinderFreezeLevel => BinderProcessStateLevel,
    BinderFsDevicesLevel => DeviceRegistryState,
    BinderFsDevicesLevel => FsNodeInfoLevel,
    BinderObjectLevel => BinderThreadStateLock,
    BinderProcessSharedMemoryLevel => BinderFreezeLevel,
    BinderProcessSharedMemoryLevel => FdTableWriterQueueLock,
    BinderProcessSharedMemoryLevel => FsRenameRecursive,
    BinderProcessStateLevel => BinderContextManagerLevel,
    BinderProcessStateLevel => BinderObjectLevel,
    BinderProcsLevel => BinderProcessSharedMemoryLevel,
    DirEntryChildrenLevel => BinderFsDevicesLevel,
    DirEntryChildrenRecursiveLevel => FsNodeInfoRecursiveLevel,
    EbpfMapStateLevel => EbpfSuspendLock,
    EbpfStateLock => EbpfSuspendLock,
    ExecutorVmarManagerLock => PidToKoidMapLock,
    FileObjectOffset => BeforeFsNodeAppend,
    FileOpsCore => UninterruptibleLock,
    FsNodeAppend => FileOpsCore,
    FsNodeInfoLevel => FsNodeWriteGuardStateLock,
    FsNodeInfoRecursiveLevel => FsRename,
    FsRename => DirEntryChildrenLevel,
    FsRenameRecursive => DirEntryChildrenRecursiveLevel,
    FuseDirEntryChildrenLevel => FuseFsNodeInfoLevel,
    FuseFsNodeInfoLevel => UninterruptibleLock,
    FuseFsRenameLevel => FuseDirEntryChildrenLevel,
    MemoryPressureMonitor => MemoryPressureMonitorClientState,
    MmDumpable => ThreadGroupLimits,
    ProcessGroupState => ThreadGroupLimits,
    RemoteBinderHandleLevel => BinderProcsLevel,
    ResourceAccessorLevel => FileOpsCore,
    TaskRelease => FileOpsCore,
    TimerTableStateLock => IntervalTimerState,
    UninterruptibleLock => EbpfMapStateLevel,
    UninterruptibleLock => EbpfStateLock,
    UninterruptibleLock => ExecutorVmarManagerLock,
    UninterruptibleLock => FastrpcInnerState,
    UninterruptibleLock => FileEpollFilesLock,
    UninterruptibleLock => IntervalTimerState,
    UninterruptibleLock => KernelIpTables,
    UninterruptibleLock => KernelSwapFiles,
    UninterruptibleLock => MemoryPressureMonitor,
    UninterruptibleLock => MemoryXattrStorageLevel,
    UninterruptibleLock => MmDumpable,
    UninterruptibleLock => PerfEventLevel,
    UninterruptibleLock => ProcessGroupState,
    UninterruptibleLock => RemoteBinderHandleLevel,
    UninterruptibleLock => SignalFdMaskLock,
    UninterruptibleLock => UserFaultInner,
    Unlocked => FileObjectOffset,
    Unlocked => FuseFsRenameLevel,
    Unlocked => ResourceAccessorLevel,
    Unlocked => TaskRelease,
    // keep-sorted end

    // Terminal Levels. No lock level should ever be defined after this.
    // Can be used for any locks that is never acquired before any other lock.
    // keep-sorted start
    Terminal(AioEventsLock),
    Terminal(AioPendingOperationsLock),
    Terminal(AuditQueueLock),
    Terminal(BootedLock),
    Terminal(ComponentControllerLock),
    Terminal(DeviceTerminalsLock),
    Terminal(EventFdInnerLock),
    Terminal(EventHandlerReadyQueueLock),
    Terminal(FileAsyncOwnerLock),
    Terminal(FileLeaseLock),
    Terminal(FileServerStatsLock),
    Terminal(FileSystemEntriesLock),
    Terminal(FileSystemPermanentLock),
    Terminal(FsNodeFlockInfoLock),
    Terminal(FsNodeFsVerityLock),
    Terminal(FsRegistryLock),
    Terminal(FuchsiaRemoteTargetLock),
    Terminal(FutexTableStateLock),
    Terminal(HrTimerIsIntervalLock),
    Terminal(HrTimerManagerStateLock),
    Terminal(IcmpPingGidsLock),
    Terminal(InotifyWatchersLock),
    Terminal(IoUringStateLock),
    Terminal(MapInfoCacheBufLock),
    Terminal(MemoryAttributionPublisherLock),
    Terminal(MountsLevel),
    Terminal(NamespaceFlagsLock),
    Terminal(PagerFilesByInodeLock),
    Terminal(PagerFilesystemsLock),
    Terminal(PerfFormatIdLookupTableLock),
    Terminal(PerfRingBufferStateLock),
    Terminal(PowerMessageCountersLock),
    Terminal(PtsIdsSetLock),
    Terminal(RemoteBinderControllerLock),
    Terminal(RwQueueInnerLock),
    Terminal(SeLinuxPeerSidLock),
    Terminal(SeLinuxPendingEntriesLock),
    Terminal(SeLinuxPendingFileSystemsLock),
    Terminal(SeLinuxUpdateLock),
    Terminal(SocketStateLock),
    Terminal(StubBytesFileStateLock),
    Terminal(SuspendResumeManagerInnerLock),
    Terminal(SyscallLogFiltersLock),
    Terminal(SyslogStateLock),
    Terminal(TaskCommandLevel),
    Terminal(ThreadGroupPendingSignalsLock),
    Terminal(ThreadGroupPtraceesLock),
    Terminal(TouchPowerPolicyEnabledLock),
    Terminal(UtsNamespaceLock),
    Terminal(VmspliceSegmentsLock),
    Terminal(WaiterEventHandlerLock),
    Terminal(WakeSourcesLock),
    Terminal(WakeWatchersLock),
    // keep-sorted end
}
