# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_applicable_licenses = ["//:license"])

cc_library(
    name = "logging",
    srcs = [
        "debug.cc",
        "file_line_function.cc",
        "logging.cc",
    ],
    hdrs = [
        "debug.h",
        "file_line_function.h",
        "logging.h",
        "macros.h",
    ],
    implementation_deps = [
        "//sdk/lib/syslog/cpp",
        "//src/lib/fxl",
    ],
    visibility = ["//visibility:public"],
    alwayslink = True,
)
