# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/components.gni")
import("//build/test.gni")

test("hwreg-i2c-test-bin") {
  output_name = "hwreg-i2c-test"
  sources = [ "i2c-hwreg-test.cc" ]
  deps = [
    "//sdk/lib/async-loop:async-loop-cpp",
    "//sdk/lib/fdio",
    "//src/devices/i2c/lib/hwreg-i2c",
    "//src/devices/i2c/lib/i2c-channel-legacy",
    "//src/devices/i2c/testing/mock-i2c",
    "//zircon/system/ulib/fbl",
    "//zircon/system/ulib/zx",
    "//zircon/system/ulib/zxtest",
  ]
}

fuchsia_unittest_package("hwreg-i2c-test") {
  deps = [ ":hwreg-i2c-test-bin" ]
}
