# Copyright 2019 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/zircon/zircon_cpu.gni")
import("//zircon/kernel/kernel_rust_mod.gni")
import("//zircon/kernel/params.gni")

group("top") {
  deps = [
    ":debug",
    ":handoff",
    ":main",
    ":rust_panic",
    ":top_rust",
    ":version",
    "//zircon/kernel/arch:arch-rs",
    "//zircon/kernel/arch:ffi",
    "//zircon/kernel/arch/$zircon_cpu",
    "//zircon/kernel/kernel",
    "//zircon/kernel/lib/flow-id",  # Used by <kernel/thread.h>.
    "//zircon/kernel/switch:no_main",
    "//zircon/kernel/switch:no_std",
  ]
}

source_set("debug") {
  sources = [ "debug.cc" ]
  deps = [
    "//zircon/kernel/dev/hw_rng",
    "//zircon/kernel/lib/crashlog",
    "//zircon/kernel/platform",
  ]
}

source_set("handoff") {
  sources = [
    "handoff.cc",
    "handoff_ffi.cc",
  ]
  deps = [
    "//src/lib/zbitl",
    "//zircon/kernel/lib/arch",
    "//zircon/kernel/lib/boot-options",
    "//zircon/kernel/lib/code-patching:self-test",
    "//zircon/kernel/lib/counters",
    "//zircon/kernel/lib/init",
    "//zircon/kernel/lib/thread-stack",
    "//zircon/kernel/object",
    "//zircon/kernel/phys:boot-constants",
    "//zircon/kernel/phys:handoff",
    "//zircon/kernel/phys:zircon-abi-spec",
    "//zircon/kernel/platform",
    "//zircon/kernel/vm",
    "//zircon/system/ulib/fbl",
  ]
}

source_set("main") {
  sources = [ "main.cc" ]
  deps = [
    "//zircon/kernel/dev:init",
    "//zircon/kernel/lib/arch",
    "//zircon/kernel/lib/console",
    "//zircon/kernel/lib/console:console_rust",
    "//zircon/kernel/lib/counters",
    "//zircon/kernel/lib/cxxabi-dynamic-init:headers",
    "//zircon/kernel/lib/heap",
    "//zircon/kernel/lib/init",
    "//zircon/kernel/lib/jtrace",
    "//zircon/kernel/lib/lockup_detector",
    "//zircon/kernel/lib/thread_sampler",
    "//zircon/kernel/lib/userabi",
    "//zircon/kernel/phys:boot-constants",
    "//zircon/kernel/phys:handoff",
    "//zircon/kernel/phys:zircon-abi-spec",
    "//zircon/kernel/platform",
    "//zircon/kernel/platform:platform-rs",
    "//zircon/kernel/vm",
  ]
}

kernel_rust_mod("rust_panic") {
  sources = []
}

kernel_rust_mod("top_rust") {
  output_name = "top"
  source_root = "mod.rs"
  sources = [
    "handoff.rs",
    "init.rs",
    "mod.rs",
  ]
  deps = [ "//zircon/kernel/lib/init:init_rust" ]
}

source_set("version") {
  visibility = [ ":*" ]
  sources = [ "version.cc" ]
  deps = [
    "//zircon/kernel/lib/console",
    "//zircon/kernel/lib/init",
    "//zircon/kernel/phys:boot-constants",
  ]
}
