# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/components.gni")
import("//build/rust/rustc_library.gni")

rustc_library("iob") {
  name = "iob"
  edition = "2024"
  with_unit_tests = true

  sources = [
    "src/blob_id_allocator.rs",
    "src/lib.rs",
  ]

  deps = [ "//sdk/rust/zx-status" ]
}

fuchsia_unittest_package("iob-rust-tests") {
  deps = [ ":iob_test" ]
}

group("tests") {
  testonly = true
  deps = [
    ":iob-rust-tests",
    ":iob_test($host_toolchain)",
  ]
}

group("rust") {
  public_deps = [ ":iob" ]
}
