# Copyright 2025 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")
load("//build/bazel/rules/host:defs.bzl", "go_binary_host_tool")
load("//build/bazel/rules/host_tests:host_go_test.bzl", "host_go_test")
load("//build/tools/bazel2gn/bazel_rules:defs.bzl", "install_host_tools")

package(default_applicable_licenses = ["//:license"])

go_binary_host_tool(
    name = "check-licenses",
    embed = ["//tools/check-licenses/cmd:main"],
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//visibility:public"],
)

install_host_tools(
    name = "host",
    implementation_deps = [":check-licenses"],
    target_compatible_with = HOST_CONSTRAINTS,
    tool_output_names = ["check-licenses"],
)

go_library(
    name = "pipeline",
    srcs = [
        "pipeline/interfaces.go",
        "pipeline/orchestrator.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/check-licenses/pipeline",
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//tools/check-licenses:__subpackages__"],
    deps = [
        "//tools/check-licenses/metrics",
        "//tools/readme_fuchsia:readme_fuchsia_lib",
    ],
)

go_library(
    name = "stages_discover",
    srcs = [
        "stages/discover/config.go",
        "stages/discover/discover.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/check-licenses/stages/discover",
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//tools/check-licenses:__subpackages__"],
    deps = [
        ":pipeline",
        "//tools/check-licenses/metrics",
    ],
)

go_library(
    name = "stages_prune",
    srcs = [
        "stages/prune/prune.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/check-licenses/stages/prune",
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//tools/check-licenses:__subpackages__"],
    deps = [
        ":pipeline",
        "//tools/check-licenses/metrics",
    ],
)

go_library(
    name = "stages_report",
    srcs = [
        "stages/report/allowlist_renderer.go",
        "stages/report/console_errors.go",
        "stages/report/findings.go",
        "stages/report/fixer.go",
        "stages/report/metrics_printer.go",
        "stages/report/notice.go",
        "stages/report/policy_renderer.go",
        "stages/report/readme_verifier.go",
        "stages/report/readme_writer.go",
        "stages/report/spdx.go",
        "stages/report/target_verifier.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/check-licenses/stages/report",
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//tools/check-licenses:__subpackages__"],
    deps = [
        ":config",
        ":pipeline",
        ":readme",
        ":stages_validate",
        "//tools/check-licenses/metrics",
    ],
)

go_library(
    name = "stages_validate",
    srcs = [
        "stages/validate/config.go",
        "stages/validate/copyright.go",
        "stages/validate/validate.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/check-licenses/stages/validate",
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//tools/check-licenses:__subpackages__"],
    deps = [
        ":pipeline",
        "//tools/check-licenses/metrics",
    ],
)

go_library(
    name = "readme",
    srcs = [
        "readme/dart.go",
        "readme/finder.go",
        "readme/formatter.go",
        "readme/golib.go",
        "readme/locator.go",
        "readme/parser.go",
        "readme/rust.go",
        "readme/types.go",
        "readme/update.go",
        "readme/validate.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/check-licenses/readme",
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//tools/check-licenses:__subpackages__"],
    deps = [
        ":pipeline",
        "//third_party/golibs:github.com/BurntSushi/toml",
        "//third_party/golibs:gopkg.in/yaml.v2",
        "//tools/readme_fuchsia:readme_fuchsia_lib",
    ],
)

go_library(
    name = "config",
    srcs = [
        "config/allowlist.go",
        "config/builder.go",
        "config/policy.go",
        "config/types.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/check-licenses/config",
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//tools/check-licenses:__subpackages__"],
    deps = [
        ":readme",
        ":stages_boundary",
        ":stages_classify",
        ":stages_discover",
        ":stages_validate",
    ],
)

go_library(
    name = "stages_boundary",
    srcs = [
        "stages/boundary/boundary.go",
        "stages/boundary/config.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/check-licenses/stages/boundary",
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//tools/check-licenses:__subpackages__"],
    deps = [
        ":pipeline",
        ":readme",
    ],
)

go_library(
    name = "stages_classify",
    srcs = [
        "stages/classify/classify.go",
        "stages/classify/config.go",
        "stages/classify/notice.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/check-licenses/stages/classify",
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//tools/check-licenses:__subpackages__"],
    deps = [
        ":pipeline",
        "//third_party/golibs:github.com/google/licenseclassifier/v2",
        "//tools/check-licenses/metrics",
    ],
)

host_go_test(
    name = "config_test",
    size = "small",
    srcs = [
        "config/builder_test.go",
    ],
    embed = [":config"],
    target_compatible_with = HOST_CONSTRAINTS,
)

host_go_test(
    name = "pipeline_test",
    size = "small",
    srcs = [
        "pipeline/golden_tree_test.go",
        "pipeline/orchestrator_test.go",
    ],
    embed = [":pipeline"],
    target_compatible_with = HOST_CONSTRAINTS,
    deps = [
        ":config",
        ":stages_boundary",
        ":stages_classify",
        ":stages_discover",
        ":stages_prune",
        ":stages_validate",
    ],
)

host_go_test(
    name = "stages_report_test",
    size = "small",
    srcs = [
        "stages/report/allowlist_renderer_test.go",
        "stages/report/console_errors_test.go",
        "stages/report/findings_test.go",
        "stages/report/fixer_test.go",
        "stages/report/metrics_printer_test.go",
        "stages/report/notice_test.go",
        "stages/report/policy_renderer_test.go",
        "stages/report/readme_verifier_test.go",
        "stages/report/readme_writer_test.go",
        "stages/report/report_test.go",
        "stages/report/spdx_test.go",
        "stages/report/target_verifier_test.go",
    ],
    embed = [":stages_report"],
    target_compatible_with = HOST_CONSTRAINTS,
    deps = [
        ":pipeline",
        "//tools/readme_fuchsia:readme_fuchsia_lib",
    ],
)

host_go_test(
    name = "readme_test",
    size = "small",
    srcs = [
        "readme/dart_test.go",
        "readme/formatter_test.go",
        "readme/golib_test.go",
        "readme/locator_test.go",
        "readme/parser_test.go",
        "readme/rust_test.go",
    ],
    embed = [":readme"],
    target_compatible_with = HOST_CONSTRAINTS,
)

host_go_test(
    name = "stages_validate_test",
    size = "small",
    srcs = [
        "stages/validate/validate_test.go",
    ],
    embed = [":stages_validate"],
    target_compatible_with = HOST_CONSTRAINTS,
    deps = [
        ":config",
        ":pipeline",
    ],
)

host_go_test(
    name = "stages_prune_test",
    size = "small",
    srcs = [
        "stages/prune/prune_test.go",
    ],
    embed = [":stages_prune"],
    target_compatible_with = HOST_CONSTRAINTS,
    deps = [
        ":pipeline",
        "//tools/check-licenses/metrics",
    ],
)

host_go_test(
    name = "stages_boundary_test",
    size = "small",
    srcs = [
        "stages/boundary/boundary_test.go",
    ],
    embed = [":stages_boundary"],
    target_compatible_with = HOST_CONSTRAINTS,
    deps = [
        ":pipeline",
    ],
)

host_go_test(
    name = "stages_classify_test",
    size = "small",
    srcs = [
        "stages/classify/classify_test.go",
        "stages/classify/notice_test.go",
    ],
    embed = [":stages_classify"],
    target_compatible_with = HOST_CONSTRAINTS,
    deps = [
        ":pipeline",
    ],
)

host_go_test(
    name = "stages_discover_test",
    size = "small",
    srcs = [
        "stages/discover/discover_test.go",
    ],
    embed = [":stages_discover"],
    target_compatible_with = HOST_CONSTRAINTS,
    deps = [
        "//tools/check-licenses/metrics",
        "//tools/readme_fuchsia:readme_fuchsia_lib",
    ],
)

test_suite(
    name = "tests",
    target_compatible_with = HOST_CONSTRAINTS,
    tests = [
        ":config_test",
        ":pipeline_test",
        ":readme_test",
        ":stages_boundary_test",
        ":stages_classify_test",
        ":stages_discover_test",
        ":stages_prune_test",
        ":stages_report_test",
        ":stages_validate_test",
        "//tools/check-licenses/cmd:cmd_test",
        "//tools/check-licenses/metrics:metrics_test",
        "//tools/check-licenses/util:util_test",
        "//tools/readme_fuchsia:readme_fuchsia_test",
    ],
    visibility = ["//visibility:public"],
)
