# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bazel/bazel_inputs.gni")
import("//build/bazel/export_fuchsia_package_to_bazel.gni")

if (target_cpu != "riscv64") {
  export_fuchsia_package_to_bazel("lavapipe_pkg") {
    package = "//src/graphics/lib/lavapipe-vulkan:lavapipe_pkg"
  }
} else {
  generated_file("lavapipe_pkg.placeholder") {
    outputs = [ "$target_out_dir/lavapipe_pkg.placeholder.txt" ]
    contents = ""
  }
  bazel_input_file("lavapipe_pkg") {
    generator = ":lavapipe_pkg.placeholder"
    outputs = [ "$target_out_dir/lavapipe_pkg.placeholder.txt" ]
    gn_targets_name = "lavapipe_pkg"
  }
}
