# Copyright 2019 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/config/current_target_tuple.gni")
import("//build/config/sysroot.gni")
import("//build/cpp/library_headers.gni")
import("//zircon/kernel/kernel_bindgen_crate.gni")
import("//zircon/kernel/kernel_rust_mod.gni")

library_headers("headers") {
  headers = [
    "lib/debuglog.h",
    "lib/debuglog_types.h",
  ]
  public_deps = [ "//zircon/kernel/phys:boot-constants" ]
}

source_set("debuglog") {
  public_deps = [ ":headers" ]

  sources = [
    "debuglog.cc",
    "debuglog_ffi.cc",
  ]
  deps = [
    ":debuglog-rs",
    "//sdk/lib/fit",
    "//src/lib/lazy_init",
    "//zircon/kernel/lib/boot-options",
    "//zircon/kernel/lib/crashlog",
    "//zircon/kernel/lib/init",
    "//zircon/kernel/lib/io",
    "//zircon/kernel/lib/ktl",
    "//zircon/kernel/lib/object-constants:headers",
    "//zircon/kernel/lib/persistent-debuglog",
    "//zircon/kernel/phys:boot-constants",
    "//zircon/kernel/vm:headers",
  ]
}

group("tests") {
  testonly = true
}

source_set("kernel-tests") {
  testonly = true

  sources = [ "debuglog_tests.cc" ]

  deps = [
    ":headers",
    "//zircon/kernel/lib/unittest",
    "//zircon/system/ulib/zircon-internal",
  ]
}

group("phys-tests") {
  testonly = true
}

group("boot_tests") {
  testonly = true
}

kernel_bindgen_crate("debuglog-types") {
  cpp = true
  headers = [ "include/lib/debuglog_types.h" ]

  non_rust_deps = [ ":headers" ]
  deps = [ "//third_party/rust_crates:zerocopy" ]

  additional_bindgen_flags = [
    "--with-derive-default",
    "--with-derive-custom-struct=dlog_.*=zerocopy::FromBytes,zerocopy::IntoBytes,zerocopy::KnownLayout,zerocopy::Immutable",
  ]

  notice_year = 2026

  type_allowlist = [ "dlog_.*" ]
  var_allowlist = [
    "DLOG_.*",
    "ZX_LOG_FLAGS_MASK",
  ]

  expect_lints = [ "non_camel_case_types" ]

  raw_lines = [ "#![no_std]" ]
}

kernel_rust_mod("debuglog-rs") {
  output_name = "debuglog_rs"
  source_root = "debuglog.rs"
  sources = [ "debuglog.rs" ]
  deps = [
    ":debuglog-types",
    "//sdk/rust/zx-status",
    "//sdk/rust/zx-types",
    "//src/lib/zr",
    "//third_party/rust_crates:pin-init",
    "//zircon/kernel/lib/object-constants:object-constants-rs",
  ]
}
