# Copyright 2020 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//zircon/kernel/kernel_rust_mod.gni")

kernel_rust_mod("watchdog-rs") {
  output_name = "pdev_watchdog"
  source_root = "watchdog.rs"
  sources = [ "watchdog.rs" ]
  deps = [
    "//sdk/rust/zx-status",
    "//zircon/kernel/lib/debug",
  ]
  test_deps = [ "//zircon/kernel/lib/unittest:unittest-rs" ]
}

source_set("hw_watchdog") {
  sources = [ "console.cc" ]
  deps = [
    ":watchdog-rs",
    "//zircon/kernel/lib/arch",
    "//zircon/kernel/lib/console",
    "//zircon/kernel/lib/debuglog",
  ]
}
