# Copyright 2025 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

group("fuchsia") {
  testonly = true
  deps = [
    # For now, run the Bazel rules and macros tests only on these bots.
    # The test targets currently build some migrated targets as well, so we do
    # not want to run them on bots that take longer than this one.
    "//build/bazel/rules/tests:all",
  ]
  if (current_cpu == "arm64") {
    deps += [ "//bundles/buildbot/minimal/arm64($host_toolchain)" ]
  }
}
