from _typeshed import Incomplete
from mobly import utils as utils

MOBLY_CONTROLLER_CONFIG_NAME: str

def create(configs): ...
def destroy(objs) -> None: ...

class IPerfResult:
    result: Incomplete
    def __init__(self, result_path) -> None: ...
    def get_json(self): ...
    @property
    def error(self): ...
    @property
    def avg_rate(self): ...
    @property
    def avg_receive_rate(self): ...
    @property
    def avg_send_rate(self): ...

class IPerfServer:
    port: Incomplete
    log_path: Incomplete
    iperf_str: Incomplete
    iperf_process: Incomplete
    log_files: Incomplete
    started: bool
    def __init__(self, port, log_path) -> None: ...
    def start(self, extra_args: str = ..., tag: str = ...) -> None: ...
    def stop(self) -> None: ...
