# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bind/bind.gni")
import("//build/components.gni")
import("//build/drivers.gni")
import("//build/test.gni")

group("tests") {
  testonly = true
  deps = [
    ":dw-apb-uart-test",
    ":dw_apb_uart_bind_test",
  ]
}

driver_bind_rules("dw_apb_uart_bind") {
  rules = "meta/dw-apb-uart.bind"
  tests = "meta/tests.json"
  bind_output = "dw-apb-uart.bindbc"
  deps = [
    "//src/devices/bind/fuchsia",
    "//src/devices/bind/fuchsia.gpio",
    "//src/devices/bind/fuchsia.platform",
  ]
}

source_set("dw-apb-uart-source") {
  configs += [ "//build/config/fuchsia:enable_zircon_asserts" ]
  sources = [
    "dw-apb-uart.cc",
    "dw-apb-uart.h",
  ]
  deps = [ "//src/devices/lib/driver:driver_runtime" ]
  public_deps = [
    "//sdk/fidl/fuchsia.hardware.clock:fuchsia.hardware.clock_cpp",
    "//sdk/fidl/fuchsia.hardware.powerdomain:fuchsia.hardware.powerdomain_cpp",
    "//sdk/fidl/fuchsia.hardware.reset:fuchsia.hardware.reset_cpp",
    "//sdk/fidl/fuchsia.hardware.serialimpl:fuchsia.hardware.serialimpl_cpp",
    "//sdk/lib/async:async-cpp",
    "//sdk/lib/driver/component/cpp",
    "//sdk/lib/driver/mmio/cpp",
    "//sdk/lib/driver/platform-device/cpp",
    "//src/devices/bind/fuchsia:fuchsia_cpp",
    "//src/devices/bind/fuchsia.serial:fuchsia.serial_cpp",
    "//zircon/system/ulib/fbl",
    "//zircon/system/ulib/hwreg",
    "//zircon/system/ulib/uart",
  ]
}

fuchsia_cc_driver("dw-apb-uart-driver") {
  output_name = "dw-apb-uart"
  deps = [ ":dw-apb-uart-source" ]
}

fuchsia_component_manifest("dw-apb-uart-manifest") {
  component_name = "dw-apb-uart"
  manifest = "meta/dw-apb-uart.cml"
}

fuchsia_driver_component("dw-apb-uart") {
  cm_label = ":dw-apb-uart-manifest"
  info = "meta/dw-apb-uart-info.json"
  deps = [
    ":dw-apb-uart-driver",
    ":dw_apb_uart_bind",
  ]
}

fuchsia_driver_package("package") {
  package_name = "dw-apb-uart"
  export_to_bazel = true
  driver_components = [ ":dw-apb-uart" ]
}

test("dw-apb-uart-test-bin") {
  output_name = "dw-apb-uart-test"
  sources = [ "tests/dw-apb-uart-test.cc" ]
  deps = [
    ":dw-apb-uart-source",
    "//sdk/fidl/fuchsia.hardware.serial:fuchsia.hardware.serial_cpp",
    "//sdk/lib/driver/fake-clock/cpp",
    "//sdk/lib/driver/fake-platform-device/cpp",
    "//sdk/lib/driver/fake-powerdomain/cpp",
    "//sdk/lib/driver/fake-reset/cpp",
    "//sdk/lib/driver/testing/cpp",
    "//src/devices/testing/fake-mmio-reg",
    "//src/lib/fxl/test:gtest_main",
  ]
}

fuchsia_unittest_package("dw-apb-uart-test") {
  deps = [ ":dw-apb-uart-test-bin" ]
  test_specs = {
    environments = basic_envs
    log_settings = {
      max_severity = "ERROR"
    }
  }
}
