# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_applicable_licenses = ["//:license"])

# Unit tests for this directory. These are intended to be referenced by unit
# test targets for the consumers of this library.
cc_library(
    name = "tests",
    testonly = True,
    srcs = [
        "automation_instruction_unittests.cc",
        "decode_exception_unittests.cc",
        "filter_utils_unittests.cc",
        "message_unittests.cc",
        "protocol_unittests.cc",
    ],
    implementation_deps = [
        "//src/developer/debug/shared",
        "//src/developer/debug/shared:test_support",
        "@com_google_googletest//:gtest",
    ],
    deps = [":ipc"],
)

cc_library(
    name = "ipc",
    srcs = [
        "automation_instruction.cc",
        "decode_exception.cc",
        "filter_utils.cc",
        "message_reader.cc",
        "message_writer.cc",
        "protocol.cc",
        "records.cc",
        "unwinder_support.cc",
    ],
    hdrs = [
        "automation_instruction.h",
        "decode_exception.h",
        "filter_utils.h",
        "message_reader.h",
        "message_writer.h",
        "protocol.h",
        "records.h",
        "unwinder_support.h",
    ],
    implementation_deps = [
        "//src/developer/debug/shared",
        "//zircon/system/public",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/lib/fxl",
        "//src/lib/unwinder",
    ],
)
