# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//:build/rust/fidl_rust_next.bzl", "fidl_rust_next_allowlist")
load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "fidl_next_util_internal",
    srcs = [
        "src/lib.rs",
        "src/multiserver.rs",
    ],
    crate_name = "fidl_next_util",
    edition = "2024",
    with_unit_tests = True,
    deps = [
        "//src/lib/fidl/rust_next/fidl_next_bind",
        "//src/lib/fidl/rust_next/fidl_next_protocol",
        "//third_party/rust_crates/vendor:futures",
        "//third_party/rust_crates/vendor:thiserror",
    ],
)

alias(
    name = "fidl_next_util",
    actual = ":fidl_next_util_internal",
    visibility = fidl_rust_next_allowlist,
)
