# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load(
    "//build/bazel/rules/rust:defs.bzl",
    "rustc_library",
)

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "moniker",
    srcs = [
        "src/child_name.rs",
        "src/error.rs",
        "src/extended_moniker.rs",
        "src/lib.rs",
        "src/moniker.rs",
    ] + select({
        "//build/bazel/platforms:is_host_os": [
            "src/serde_ext.rs",
        ],
        "//conditions:default": [],
    }),
    crate_features = select({
        "//build/bazel/platforms:is_host_os": [
            "serde",
        ],
        "//conditions:default": [],
    }),
    crate_name = "moniker",
    edition = "2024",
    visibility = [
        "//:__subpackages__",
    ],
    with_unit_tests = True,
    deps = [
        "//src/sys/lib/cm_rust",
        "//src/sys/lib/cm_types",
        "//third_party/rust_crates/vendor:flyweights",
        "//third_party/rust_crates/vendor:thiserror",
    ] + select({
        "//build/bazel/platforms:is_host_os": [
            "//third_party/rust_crates/vendor:schemars",
            "//third_party/rust_crates/vendor:serde",
        ],
        "//conditions:default": [],
    }),
)
