# Copyright 2025 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import shutil
import sys
import uuid
from pathlib import Path

import logger


class CartfsOutDirectory:
    """Manages a cartfs-backed out directory installed in a cog workspace.

    Cog cannot handle the volume of files generated by a fuchsia build, so
    `//out` will be symlinked to a directory in cartfs containing the actual
    build output.

    Since our build assumes that `//out/foo/../../` resolves to `//`, and `..`
    path segments resolve parent directory symlinks first (instead of being
    lexically normalized first), we need to construct a symlink farm such that
    the siblings of the real out directory stored in cartfs looks like the
    siblings of the out directory symlink in cog.

    In practice, this generates a split project structure that looks like this:
    <cog_workspace>/fuchsia/
        out/          => <cartfs_workspace>/PROJECT_ROOT/out/
        src/
        zircon/
        BUILD.gn
        ...
    <cartfs_workspace>/
        PROJECT_ROOT/
            out/...   # This is our real out directory.
            src/      => <cog_workspace>/fuchsia/src/
            zircon/   => <cog_workspace>/fuchsia/zicron/
            BUILD.gn  => <cog_workspace>/fuchsia/BUILD.gn
            ...       => <cog_workspace>/fuchsia/...

    In the future, this approach may be deprecated in favor of a simpler
    solution that places `//out/<dir>/fuchsia_src` symlinks that point back to
    the cog workspace.
    However, that will first require migrating all references of
    `//out/foo/../../...` to `//out/foo/fuchsia_src/...` across our build files,
    tooling, and build outputs.
    """

    def __init__(
        self,
        cog_workspace_dir: Path,
        cartfs_workspace_dir: Path,
    ):
        self.cog_workspace_dir = cog_workspace_dir
        self.cartfs_workspace_dir = cartfs_workspace_dir

    @property
    def cog_out_symlink(self) -> Path:
        """Returns the out directory path in the cog workspace."""
        return self.cog_workspace_dir / "out"

    @property
    def cartfs_symlink_tree(self) -> Path:
        """Returns the src symlink farm directory path in cartfs."""
        return self.cartfs_workspace_dir / "PROJECT_ROOT"

    @property
    def cartfs_out_dir(self) -> Path:
        """Returns the out directory path in the cartfs."""
        return self.cartfs_symlink_tree / "out"

    @property
    def is_installed(self) -> bool:
        """Checks if the current out directory is managed by this module."""
        return (
            self.cog_out_symlink.is_symlink()
            and self.cog_out_symlink.is_dir()
            and self.cog_out_symlink.resolve() == self.cartfs_out_dir
        )

    def update(self) -> None:
        """Updates the symlink farm held in cartfs."""
        assert self.is_installed, "Out directory is not installed."

        # Cleanup cartfs.
        for file in self.cartfs_symlink_tree.iterdir():
            if file.name == "out":
                continue

            if file.is_dir() and not file.is_symlink():
                shutil.rmtree(file)
            else:
                file.unlink()

        # Initialize cartfs.
        for file in self.cog_workspace_dir.iterdir():
            if file.name == "out":
                continue

            (self.cartfs_symlink_tree / file.name).symlink_to(file)

    def install(self) -> None:
        """Installs the files managed by this module."""
        self.cartfs_symlink_tree.mkdir(parents=True, exist_ok=True)

        # Purge any existing cog `//out` dir.
        if (
            self.cog_out_symlink.is_dir()
            and not self.cog_out_symlink.is_symlink()
        ):
            dest = self.cog_workspace_dir / f"out-{uuid.uuid4()}"
            logger.log_warn(
                f'Preserving contents from existing cog `//out` directory to "{dest}".'
            )
            self.cog_out_symlink.rename(dest)
        else:
            self.cog_out_symlink.unlink(missing_ok=True)

        # Instantiate cartfs `//out` dir.
        if self.cartfs_out_dir.is_dir():
            logger.log_warn(
                f'Linking `//out` to existing cartfs `out` instance: "{self.cartfs_out_dir}".'
            )
        else:
            self.cartfs_out_dir.unlink(missing_ok=True)
            self.cartfs_out_dir.mkdir()

        # Reinstall cog-`//out` symlink => cartfs-`//out` directory.
        self.cog_out_symlink.symlink_to(self.cartfs_out_dir)

        # Refresh cartfs `//` symlink farm.
        self.update()

    def apply(self) -> None:
        """Updates or installs the out directory."""
        if self.is_installed:
            self.update()
        else:
            logger.log_info("Intitializing project out directory...")
            self.install()
            logger.log_info(
                f"Installed {self.cog_out_symlink} => {self.cartfs_out_dir}"
            )


if __name__ == "__main__":
    cog_workspace_dir = Path(__file__).parent.parent.parent
    cartfs_workspace_dir = Path(sys.argv[1])
    logger.log_info(
        f'Using cog workspace "{cog_workspace_dir}", cartfs workspace "{cartfs_workspace_dir}"'
    )
    CartfsOutDirectory(cog_workspace_dir, cartfs_workspace_dir).apply()
