// Copyright 2026 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Generated by trace_generator.py. DO NOT EDIT.

#[cfg(test)]
mod tests {
    use test_case::test_case;

    #[test_case("canon_simple_echo", include_str!("traces/canon_simple_echo.json"); "canon_simple_echo")]
    #[test_case("basic_backspace", include_str!("traces/basic_backspace.json"); "basic_backspace")]
    #[test_case("canon_word_erase", include_str!("traces/canon_word_erase.json"); "canon_word_erase")]
    #[test_case("canon_kill_line", include_str!("traces/canon_kill_line.json"); "canon_kill_line")]
    #[test_case("canon_echo_ctl", include_str!("traces/canon_echo_ctl.json"); "canon_echo_ctl")]
    #[test_case("ixon_basic", include_str!("traces/ixon_basic.json"); "ixon_basic")]
    #[test_case("ixany_basic", include_str!("traces/ixany_basic.json"); "ixany_basic")]
    #[test_case("echo_nl", include_str!("traces/echo_nl.json"); "echo_nl")]
    #[test_case("noflsh_sigint", include_str!("traces/noflsh_sigint.json"); "noflsh_sigint")]
    #[test_case("echo_extended", include_str!("traces/echo_extended.json"); "echo_extended")]
    #[test_case("echo_prt", include_str!("traces/echo_prt.json"); "echo_prt")]
    #[test_case("echo_prt_two_chars", include_str!("traces/echo_prt_two_chars.json"); "echo_prt_two_chars")]
    #[test_case("echoprt_word_erase", include_str!("traces/echoprt_word_erase.json"); "echoprt_word_erase")]
    #[test_case("echoprt_word_erase_typing", include_str!("traces/echoprt_word_erase_typing.json"); "echoprt_word_erase_typing")]
    #[test_case("echoprt_kill", include_str!("traces/echoprt_kill.json"); "echoprt_kill")]
    #[test_case("echonl_echoprt", include_str!("traces/echonl_echoprt.json"); "echonl_echoprt")]
    #[test_case("echoprt_word_erase_space", include_str!("traces/echoprt_word_erase_space.json"); "echoprt_word_erase_space")]
    #[test_case("echoprt_word_erase_tab", include_str!("traces/echoprt_word_erase_tab.json"); "echoprt_word_erase_tab")]
    #[test_case("echoprt_word_erase_nl_aln", include_str!("traces/echoprt_word_erase_nl_aln.json"); "echoprt_word_erase_nl_aln")]
    #[test_case("echoprt_word_erase_nl_nl", include_str!("traces/echoprt_word_erase_nl_nl.json"); "echoprt_word_erase_nl_nl")]
    #[test_case("echoprt_kill_nl_aln", include_str!("traces/echoprt_kill_nl_aln.json"); "echoprt_kill_nl_aln")]
    #[test_case("echoprt_backspace_multi_aln", include_str!("traces/echoprt_backspace_multi_aln.json"); "echoprt_backspace_multi_aln")]
    #[test_case("echoprt_backspace_multi_space", include_str!("traces/echoprt_backspace_multi_space.json"); "echoprt_backspace_multi_space")]
    #[test_case("echoprt_backspace_multi_nl", include_str!("traces/echoprt_backspace_multi_nl.json"); "echoprt_backspace_multi_nl")]
    #[test_case("echoprt_backspace_nl_aln", include_str!("traces/echoprt_backspace_nl_aln.json"); "echoprt_backspace_nl_aln")]
    #[test_case("echoprt_backspace_nl_space", include_str!("traces/echoprt_backspace_nl_space.json"); "echoprt_backspace_nl_space")]
    #[test_case("echoprt_backspace_nl_nl", include_str!("traces/echoprt_backspace_nl_nl.json"); "echoprt_backspace_nl_nl")]
    #[test_case("input_igncr", include_str!("traces/input_igncr.json"); "input_igncr")]
    #[test_case("input_inlcr", include_str!("traces/input_inlcr.json"); "input_inlcr")]
    #[test_case("input_icrnl_prec", include_str!("traces/input_icrnl_prec.json"); "input_icrnl_prec")]
    #[test_case("output_ocrnl", include_str!("traces/output_ocrnl.json"); "output_ocrnl")]
    #[test_case("output_ocrnl_explicit", include_str!("traces/output_ocrnl_explicit.json"); "output_ocrnl_explicit")]
    #[test_case("output_onocr", include_str!("traces/output_onocr.json"); "output_onocr")]
    #[test_case("output_onlret", include_str!("traces/output_onlret.json"); "output_onlret")]
    #[test_case("output_xtabs", include_str!("traces/output_xtabs.json"); "output_xtabs")]
    #[test_case("flush_sigint", include_str!("traces/flush_sigint.json"); "flush_sigint")]
    #[test_case("flush_sigint_after_newline", include_str!("traces/flush_sigint_after_newline.json"); "flush_sigint_after_newline")]
    #[test_case("flush_sigint_after_newline_separate_writes", include_str!("traces/flush_sigint_after_newline_separate_writes.json"); "flush_sigint_after_newline_separate_writes")]
    #[test_case("noflsh_sigquit", include_str!("traces/noflsh_sigquit.json"); "noflsh_sigquit")]
    #[test_case("flush_sigquit", include_str!("traces/flush_sigquit.json"); "flush_sigquit")]
    #[test_case("noflsh_sigsusp", include_str!("traces/noflsh_sigsusp.json"); "noflsh_sigsusp")]
    #[test_case("flush_sigsusp", include_str!("traces/flush_sigsusp.json"); "flush_sigsusp")]
    #[test_case("noflsh_echoctl_mixed", include_str!("traces/noflsh_echoctl_mixed.json"); "noflsh_echoctl_mixed")]
    #[test_case("input_inlcr_icrnl_swap", include_str!("traces/input_inlcr_icrnl_swap.json"); "input_inlcr_icrnl_swap")]
    #[test_case("output_direct_ocrnl", include_str!("traces/output_direct_ocrnl.json"); "output_direct_ocrnl")]
    #[test_case("output_direct_onlret_onocr", include_str!("traces/output_direct_onlret_onocr.json"); "output_direct_onlret_onocr")]
    #[test_case("iuclc_simple", include_str!("traces/iuclc_simple.json"); "iuclc_simple")]
    #[test_case("olcuc_simple", include_str!("traces/olcuc_simple.json"); "olcuc_simple")]
    #[test_case("vlnext_echoctl", include_str!("traces/vlnext_echoctl.json"); "vlnext_echoctl")]
    #[test_case("vreprint_basic", include_str!("traces/vreprint_basic.json"); "vreprint_basic")]
    #[test_case("vdiscard_basic", include_str!("traces/vdiscard_basic.json"); "vdiscard_basic")]
    #[test_case("vlnext_basic", include_str!("traces/vlnext_basic.json"); "vlnext_basic")]
    #[test_case("vlnext_no_echoctl", include_str!("traces/vlnext_no_echoctl.json"); "vlnext_no_echoctl")]
    fn test_replay_trace(name: &str, json_data: &str) {
        crate::testing::tests::test_replay_trace(name, json_data);
    }
}
