# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(is_host, "These tools should only be included via 'host_tools'.")

group("static_checks") {
  testonly = true
  deps = [
    "//build/tools/formatjson5",
    "//tools/check-licenses",
    "//tools/cmc:cmc.actual",
    "//tools/doc_checker:doc_checker_bin.actual",
    "//tools/fidl/fidlc:fidl-format",
    "//tools/fidl/fidlc:fidl-lint",
    "//tools/fidl/gidl-format",
    "//tools/mdlint",
    "//tools/readme_fuchsia",
    "//tools/staticanalysis/clippy-reporter",
    "//tools/staticanalysis/rfcmeta",
  ]
}
