# Copyright 2019 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/cpp/library_headers.gni")
import("//zircon/kernel/kernel_bindgen_crate.gni")
import("//zircon/kernel/kernel_rust_mod.gni")

library_headers("headers") {
  headers = [ "lib/heap.h" ]
}

library_headers("headers.internal") {
  visibility = [ "./*" ]

  headers = [ "lib/heap_internal.h" ]
}

source_set("heap") {
  public_deps = [ ":headers" ]

  sources = [
    "cxx_allocator.cc",
    "heap_ffi.cc",
    "heap_wrapper.cc",
  ]
  deps = [
    ":headers.internal",
    "cmpctmalloc",
    "profile",
    "//src/lib/lazy_init",
    "//zircon/kernel/lib/console",
    "//zircon/kernel/lib/page",
    "//zircon/kernel/lib/virtual_alloc",
    "//zircon/kernel/phys:arch-heap",
    "//zircon/kernel/vm:headers",

    # TODO(https://fxbug.dev/42128324): Remove headers when possible.
    "//zircon/kernel/lib/instrumentation:headers",
  ]
}

kernel_bindgen_crate("heap-bindings") {
  visibility = [
    ":*",
    "//zircon/kernel/*",
  ]
  headers = [ "include/lib/heap_ffi.h" ]
  non_rust_deps = [ ":heap" ]
  output_name = "heap_bindings.rs"
  cpp = true

  notice_year = 2026
  function_allowlist = [
    "cpp_profile_track_alloc",
    "cpp_profile_track_free",
  ]
  additional_bindgen_flags = [ "--no-recursive-allowlist" ]

  edition = "2024"
  raw_lines = [ "#![no_std]" ]
}

kernel_rust_mod("heap-rs") {
  sources = [ "heap.rs" ]
  deps = [ ":heap-bindings" ]
}

group("tests") {
  testonly = true
}

group("kernel-tests") {
  testonly = true
}

group("phys-tests") {
  testonly = true
}

group("boot_tests") {
  testonly = true
}
