# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

template("shader_utils_library") {
  source_set(target_name) {
    forward_variables_from(invoker, "*")

    sources = [
      "spirv_file_util.cc",
      "spirv_file_util.h",
    ]

    public_deps = [
      "//sdk/lib/fit",
      "//sdk/lib/syslog/cpp",
      "//src/ui/lib/escher:hack_filesystem",
      "//src/ui/lib/escher:shader_variant_args",
    ]

    if (use_runtime_glsl) {
      public_deps += [ "//third_party/shaderc/src:libshaderc" ]
      public_configs = [ "//src/ui/lib/escher:use_runtime_glsl_config" ]
    }
  }
}

shader_utils_library("shader_utils_with_glslang") {
  use_runtime_glsl = true
}

shader_utils_library("shader_utils_no_glslang") {
  use_runtime_glsl = false
}

source_set("shader_utils") {
  public_deps = [ ":shader_utils_with_glslang" ]
}
