# Copyright 2019 The Fuchsia Authors
# Use  this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/cpp/library_headers.gni")
import("//build/rust/rustc_library.gni")
import("//build/testing/boot_tests/boot_test.gni")
import("//zircon/kernel/kernel_rust_mod.gni")

static_library("console") {
  public_deps = [ ":headers" ]

  complete_static_lib = true

  sources = [ "console.cc" ]
  defines = [ "BOOT_TEST_SUCCESS_STRING=\"$boot_test_success_string\"" ]
  deps = [
    "//zircon/kernel/lib/boot-options:headers",
    "//zircon/kernel/lib/debuglog:headers",
    "//zircon/kernel/lib/init",
  ]
}

library_headers("headers") {
  headers = [ "lib/console.h" ]
  public_deps = [
    # <lib/console.h> has #include <lib/special-sections/special-sections.h>.
    "//zircon/kernel/lib/special-sections:headers",
  ]
}

rustc_library("console_env") {
  edition = "2024"
  output_name = "console_env"
  sources = [ "rust/src/env.rs" ]
  source_root = "rust/src/env.rs"
  rustenv = [ "BOOT_TEST_SUCCESS_STRING=$boot_test_success_string" ]
}

kernel_rust_mod("console_rust") {
  output_name = "console_rust"
  visibility = [ "//zircon/kernel/*" ]
  sources = [ "rust/src/mod.rs" ]
  source_root = "rust/src/mod.rs"
  deps = [
    ":console_env",
    "//sdk/rust/zx-status",
    "//src/lib/kalloc",
    "//src/lib/kprint",
    "//src/lib/zr",
  ]
}

group("tests") {
  testonly = true
}

group("kernel-tests") {
  testonly = true
  deps = [ "tests" ]
}

group("phys-tests") {
  testonly = true
}

group("boot_tests") {
  testonly = true
}
