# Copyright 2026 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

declare_args() {
  # Controls whether the Zircon kernel console compiles in command history
  # storage and shell navigation features. Defaults to true, but can be disabled
  # on a per-build basis.
  console_enable_history = true
}
