# Copyright 2019 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/cpp/library_headers.gni")
import("//zircon/kernel/kernel_rust_mod.gni")

library_headers("headers") {
  headers = [ "dev/interrupt/plic.h" ]
  public_deps = [ "//zircon/kernel/phys:handoff" ]
}

kernel_rust_mod("plic-rs") {
  output_name = "plic"
  source_root = "plic.rs"
  sources = [ "plic.rs" ]
  deps = [
    "//sdk/rust/zbi",
    "//sdk/rust/zx-status",
    "//src/lib/regio",
    "//zircon/kernel/lib/debug",
    "//zircon/kernel/lib/page:page-rs",
  ]
  test_deps = [ "//zircon/kernel/lib/unittest:unittest-rs" ]
}

source_set("plic") {
  sources = []
  public_deps = [ ":headers" ]
  deps = [
    ":plic-rs",
    "//zircon/kernel/dev/pdev/interrupt",
    "//zircon/kernel/lib/root_resource_filter",
  ]
}
