from typing import Any
from mobly import signals as signals

def assert_equal(
    first: Any, second: Any, msg: str | None = ..., extras: Any | None = ...
) -> None: ...
def assert_not_equal(
    first: Any, second: Any, msg: str | None = ..., extras: Any | None = ...
) -> None: ...
def assert_almost_equal(
    first: Any,
    second: Any,
    places: int | None = ...,
    msg: str | None = ...,
    delta: float | None = ...,
    extras: Any | None = ...,
) -> None: ...
def assert_not_almost_equal(
    first: Any,
    second: Any,
    places: int | None = ...,
    msg: str | None = ...,
    delta: float | None = ...,
    extras: Any | None = ...,
) -> None: ...
def assert_in(
    member: Any,
    container: Any,
    msg: str | None = ...,
    extras: Any | None = ...,
) -> None: ...
def assert_not_in(
    member: Any,
    container: Any,
    msg: str | None = ...,
    extras: Any | None = ...,
) -> None: ...
def assert_is(
    expr1: Any, expr2: Any, msg: str | None = ..., extras: Any | None = ...
) -> None: ...
def assert_is_not(
    expr1: Any, expr2: Any, msg: str | None = ..., extras: Any | None = ...
) -> None: ...
def assert_count_equal(
    first: Any, second: Any, msg: str | None = ..., extras: Any | None = ...
) -> None: ...
def assert_less(
    a: Any, b: Any, msg: str | None = ..., extras: Any | None = ...
) -> None: ...
def assert_less_equal(
    a: Any, b: Any, msg: str | None = ..., extras: Any | None = ...
) -> None: ...
def assert_greater(
    a: Any, b: Any, msg: str | None = ..., extras: Any | None = ...
) -> None: ...
def assert_greater_equal(
    a: Any, b: Any, msg: str | None = ..., extras: Any | None = ...
) -> None: ...
def assert_is_none(
    obj: Any, msg: str | None = ..., extras: Any | None = ...
) -> None: ...
def assert_is_not_none(
    obj: Any, msg: str | None = ..., extras: Any | None = ...
) -> None: ...
def assert_is_instance(
    obj: Any, cls: type | tuple[type, ...], msg: str | None = ..., extras: Any | None = ...
) -> None: ...
def assert_not_is_instance(
    obj: Any, cls: type | tuple[type, ...], msg: str | None = ..., extras: Any | None = ...
) -> None: ...
def assert_regex(
    text: str,
    expected_regex: str | Any,
    msg: str | None = ...,
    extras: Any | None = ...,
) -> None: ...
def assert_not_regex(
    text: str,
    unexpected_regex: str | Any,
    msg: str | None = ...,
    extras: Any | None = ...,
) -> None: ...
def assert_raises(
    expected_exception: type[Exception] | tuple[type[Exception], ...], extras: Any | None = ..., *args: Any, **kwargs: Any
) -> Any: ...
def assert_raises_regex(
    expected_exception: type[Exception] | tuple[type[Exception], ...],
    expected_regex: str | Any,
    extras: Any | None = ...,
    *args: Any,
    **kwargs: Any,
) -> Any: ...
def assert_true(expr: Any, msg: str, extras: Any | None = ...) -> None: ...
def assert_false(expr: Any, msg: str, extras: Any | None = ...) -> None: ...
def skip(reason: str, extras: Any | None = ...) -> None: ...
def skip_if(expr: Any, reason: str, extras: Any | None = ...) -> None: ...
def abort_class(reason: str, extras: Any | None = ...) -> None: ...
def abort_class_if(expr: Any, reason: str, extras: Any | None = ...) -> None: ...
def abort_all(reason: str, extras: Any | None = ...) -> None: ...
def abort_all_if(expr: Any, reason: str, extras: Any | None = ...) -> None: ...
def fail(msg: str, extras: Any | None = ...) -> None: ...
def explicit_pass(msg: str, extras: Any | None = ...) -> None: ...

class _AssertRaisesContext:
    expected: type[Exception] | tuple[type[Exception], ...]
    failureException: type[signals.TestFailure]
    expected_regexp: Any | None
    extras: Any | None
    exception: Exception
    def __init__(
        self,
        expected: type[Exception] | tuple[type[Exception], ...],
        expected_regexp: Any | None = ...,
        extras: Any | None = ...,
    ) -> None: ...
    def __enter__(self) -> "_AssertRaisesContext": ...
    def __exit__(self, exc_type: Any, exc_value: Any, tb: Any) -> bool: ...