from typing import Any, Callable, Sequence

from _typeshed import Incomplete
from mobly import records
from mobly import controller_manager

TEST_CASE_TOKEN: str
RESULT_LINE_TEMPLATE: Incomplete
TEST_STAGE_BEGIN_LOG_TEMPLATE: str
TEST_STAGE_END_LOG_TEMPLATE: str

ATTR_MAX_RETRY_CNT: str
ATTR_MAX_CONSEC_ERROR: str

class Error(Exception): ...

def repeat(
    count: int, max_consecutive_error: Incomplete | None = ...
) -> Any: ...
def retry(max_count: int) -> Any: ...

class BaseTestClass:
    TAG: str
    tests: list[str]
    root_output_path: str
    log_path: str
    test_bed_name: str
    testbed_name: str
    user_params: dict[str, Any]
    results: records.TestResult
    summary_writer: Incomplete
    controller_configs: dict[str, Any]
    current_test_info: Any
    _controller_manager: controller_manager.ControllerManager
    _generated_test_table: dict[str, Any]

    def __init__(self, configs: Any) -> None: ...
    def unpack_userparams(
        self,
        req_param_names: list[str] | None = ...,
        opt_param_names: list[str] | None = ...,
        **kwargs: Any,
    ) -> None: ...
    def register_controller(
        self, module: Any, required: bool = ..., min_number: int = ...
    ) -> Any: ...
    def pre_run(self) -> Any: ...
    def setup_generated_tests(self) -> Any: ...
    def setup_class(self) -> Any: ...
    def teardown_class(self) -> Any: ...
    def setup_test(self) -> Any: ...
    def teardown_test(self) -> Any: ...
    def on_fail(self, record: records.TestResultRecord) -> Any: ...
    def on_pass(self, record: records.TestResultRecord) -> Any: ...
    def on_skip(self, record: records.TestResultRecord) -> Any: ...
    def record_data(self, content: Any) -> None: ...
    def exec_one_test(
        self,
        test_name: str,
        test_method: Callable[..., Any],
        record: records.TestResultRecord | None = ...,
    ) -> None: ...
    def generate_tests(
        self,
        test_logic: Callable[..., Any],
        name_func: Callable[..., str],
        arg_sets: Sequence[Any],
        uid_func: Callable[..., str] | None = ...,
    ) -> None: ...
    def get_existing_test_names(self) -> list[str]: ...
    def run(self, test_names: list[str] | None = ...) -> None: ...
