from _typeshed import Incomplete
from mobly import expects as expects
from mobly import records as records
from mobly import signals as signals

def verify_controller_module(module) -> None: ...

class ControllerManager:
    controller_configs: Incomplete
    def __init__(self, class_name, controller_configs) -> None: ...
    def register_controller(
        self, module, required: bool = ..., min_number: int = ...
    ): ...
    def unregister_controllers(self) -> None: ...
    def get_controller_info_records(self): ...
