from typing import Any

class ControllerManager:
    _controller_objects: dict[str, Any]
    _controller_modules: dict[str, Any]
    def __init__(self, configs: Any) -> None: ...
    def register_controller(
        self, module: Any, required: bool = ..., min_number: int = ...
    ) -> Any: ...
    def unregister_controllers(self) -> None: ...
