from collections.abc import Generator
from typing import Any

from mobly import asserts as asserts
from mobly import records as records
from mobly import signals as signals

DEFAULT_TEST_RESULT_RECORD: records.TestResultRecord

class _ExpectErrorRecorder:
    def __init__(self, record: records.TestResultRecord | None = ...) -> None: ...
    def reset_internal_states(
        self, record: records.TestResultRecord | None = ...
    ) -> None: ...
    @property
    def has_error(self) -> bool: ...
    @property
    def error_count(self) -> int: ...
    def add_error(self, error: Exception | records.ExceptionRecord) -> None: ...

def expect_true(condition: Any, msg: str, extras: Any | None = ...) -> None: ...
def expect_false(condition: Any, msg: str, extras: Any | None = ...) -> None: ...
def expect_equal(
    first: Any, second: Any, msg: str | None = ..., extras: Any | None = ...
) -> None: ...
def expect_no_raises(
    message: str | None = ..., extras: Any | None = ...
) -> Generator[None, None, None]: ...

recorder: _ExpectErrorRecorder
