from collections.abc import Generator

from _typeshed import Incomplete
from mobly import asserts as asserts
from mobly import records as records
from mobly import signals as signals

DEFAULT_TEST_RESULT_RECORD: Incomplete

class _ExpectErrorRecorder:
    def __init__(self, record: Incomplete | None = ...) -> None: ...
    def reset_internal_states(
        self, record: Incomplete | None = ...
    ) -> None: ...
    @property
    def has_error(self): ...
    @property
    def error_count(self): ...
    def add_error(self, error) -> None: ...

def expect_true(condition, msg, extras: Incomplete | None = ...) -> None: ...
def expect_false(condition, msg, extras: Incomplete | None = ...) -> None: ...
def expect_equal(
    first, second, msg: Incomplete | None = ..., extras: Incomplete | None = ...
) -> None: ...
def expect_no_raises(
    message: Incomplete | None = ..., extras: Incomplete | None = ...
) -> Generator[None, None, None]: ...

recorder: Incomplete
