import enum
from typing import Any

from mobly import signals as signals
from mobly import utils as utils

OUTPUT_FILE_INFO_LOG: str
OUTPUT_FILE_DEBUG_LOG: str
OUTPUT_FILE_SUMMARY: str

class Error(Exception): ...

def uid(uid: str) -> Any: ...

class TestParentType(enum.Enum):
    REPEAT = ...
    RETRY = ...

class TestSummaryEntryType(enum.Enum):
    TEST_NAME_LIST = ...
    RECORD = ...
    SUMMARY = ...
    CONTROLLER_INFO = ...
    USER_DATA = ...

class TestSummaryWriter:
    def __init__(self, path: str) -> None: ...
    def __copy__(self) -> "TestSummaryWriter": ...
    def __deepcopy__(self, *args: Any) -> "TestSummaryWriter": ...
    def dump(self, content: dict[str, Any], entry_type: TestSummaryEntryType) -> None: ...

class TestResultEnums:
    RECORD_NAME: str
    RECORD_CLASS: str
    RECORD_BEGIN_TIME: str
    RECORD_END_TIME: str
    RECORD_RESULT: str
    RECORD_UID: str
    RECORD_EXTRAS: str
    RECORD_EXTRA_ERRORS: str
    RECORD_DETAILS: str
    RECORD_TERMINATION_SIGNAL_TYPE: str
    RECORD_STACKTRACE: str
    RECORD_SIGNATURE: str
    RECORD_RETRY_PARENT: str
    RECORD_PARENT: str
    RECORD_POSITION: str
    TEST_RESULT_PASS: str
    TEST_RESULT_FAIL: str
    TEST_RESULT_SKIP: str
    TEST_RESULT_ERROR: str

class ControllerInfoRecord:
    KEY_TEST_CLASS: str
    KEY_CONTROLLER_NAME: str
    KEY_CONTROLLER_INFO: str
    KEY_TIMESTAMP: str
    test_class: str
    controller_name: str
    controller_info: Any
    timestamp: float
    def __init__(self, test_class: str, controller_name: str, info: Any) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class ExceptionRecord:
    exception: Exception
    type: str
    stacktrace: str | None
    extras: Any | None
    position: str | None
    is_test_signal: bool
    details: str | bytes
    def __init__(self, e: Exception, position: str | None = ...) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> "ExceptionRecord": ...

class TestResultRecord:
    test_name: str
    test_class: str | None
    begin_time: float | None
    end_time: float | None
    uid: str | None
    signature: str | None
    retry_parent: "TestResultRecord" | None
    parent: tuple["TestResultRecord", TestParentType] | None
    termination_signal: ExceptionRecord | None
    extra_errors: dict[str, ExceptionRecord]
    result: str | None
    def __init__(self, t_name: str, t_class: str | None = ...) -> None: ...
    @property
    def details(self) -> str | bytes | None: ...
    @property
    def termination_signal_type(self) -> str | None: ...
    @property
    def stacktrace(self) -> str | None: ...
    @property
    def extras(self) -> Any | None: ...
    def test_begin(self) -> None: ...
    def update_record(self) -> None: ...
    def test_pass(self, e: Exception | None = ...) -> None: ...
    def test_fail(self, e: Exception | None = ...) -> None: ...
    def test_skip(self, e: Exception | None = ...) -> None: ...
    def test_error(self, e: Exception | None = ...) -> None: ...
    def add_error(self, position: str, e: Exception | ExceptionRecord) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class TestResult:
    requested: list[str]
    failed: list[TestResultRecord]
    executed: list[TestResultRecord]
    passed: list[TestResultRecord]
    skipped: list[TestResultRecord]
    error: list[TestResultRecord]
    controller_info: list[ControllerInfoRecord]
    def __init__(self) -> None: ...
    def __add__(self, r: "TestResult") -> "TestResult": ...
    def add_record(self, record: TestResultRecord) -> None: ...
    def add_controller_info_record(self, controller_info_record: ControllerInfoRecord) -> None: ...
    def add_class_error(self, test_record: TestResultRecord) -> None: ...
    def is_test_executed(self, test_name: str) -> bool: ...
    @property
    def is_all_pass(self) -> bool: ...
    def requested_test_names_dict(self) -> dict[str, list[str]]: ...
    def summary_str(self) -> str: ...
    def summary_dict(self) -> dict[str, int]: ...
