from typing import Any
from mobly import utils as utils

class RuntimeTestInfo:
    def __init__(self, test_name: Any, log_path: Any, record: Any) -> None: ...
    @property
    def name(self) -> Any: ...
    @property
    def signature(self) -> Any: ...
    @property
    def record(self) -> Any: ...
    @property
    def output_path(self) -> Any: ...
