from mobly import utils as utils

class RuntimeTestInfo:
    def __init__(self, test_name, log_path, record) -> None: ...
    @property
    def name(self): ...
    @property
    def signature(self): ...
    @property
    def record(self): ...
    @property
    def output_path(self): ...
