from _typeshed import Incomplete

class TestSignalError(Exception): ...

class TestSignal(Exception):
    details: Incomplete
    extras: Incomplete
    def __init__(self, details, extras: Incomplete | None = ...) -> None: ...

class TestError(TestSignal): ...
class TestFailure(TestSignal): ...
class TestPass(TestSignal): ...
class TestSkip(TestSignal): ...
class TestAbortSignal(TestSignal): ...
class TestAbortClass(TestAbortSignal): ...
class TestAbortAll(TestAbortSignal): ...
class ControllerError(Exception): ...
