from typing import Any

class TestSignalError(Exception): ...

class TestSignal(Exception):
    details: Any
    extras: Any | None
    def __init__(self, details: Any, extras: Any | None = ...) -> None: ...
    def __str__(self) -> str: ...

class TestError(TestSignal): ...
class TestFailure(TestSignal): ...
class TestPass(TestSignal): ...
class TestSkip(TestSignal): ...
class TestAbortSignal(TestSignal): ...
class TestAbortClass(TestAbortSignal): ...
class TestAbortAll(TestAbortSignal): ...
class ControllerError(Exception): ...
