from _typeshed import Incomplete
from mobly import base_suite as base_suite
from mobly import base_test as base_test
from mobly import config_parser as config_parser
from mobly import signals as signals
from mobly import test_runner as test_runner

class Error(Exception): ...

def run_suite_class(argv: Incomplete | None = ...) -> None: ...
def run_suite(test_classes, argv: Incomplete | None = ...) -> None: ...
def compute_selected_tests(test_classes, selected_tests): ...
