from _typeshed import Incomplete

MAX_FILENAME_LEN: int
MAX_PORT_ALLOCATION_RETRY: int
ascii_letters_and_digits: Incomplete
valid_filename_chars: Incomplete
GMT_to_olson: Incomplete

class Error(Exception): ...

def abs_path(path): ...
def create_dir(path) -> None: ...
def create_alias(target_path, alias_path) -> None: ...
def get_current_epoch_time(): ...
def get_current_human_time(): ...
def epoch_to_human_time(epoch_time): ...
def get_timezone_olson_id(): ...
def find_files(paths, file_predicate): ...
def load_file_to_base64_str(f_path): ...
def find_field(item_list, cond, comparator, target_field): ...
def rand_ascii_str(length): ...
def concurrent_exec(
    func, param_list, max_workers: int = ..., raise_on_exception: bool = ...
): ...
def run_command(
    cmd,
    stdout=...,
    stderr=...,
    shell=...,
    timeout=...,
    cwd=...,
    env=...,
    universal_newlines: bool = ...,
) -> tuple[int, bytes, bytes] | tuple[int, str, str]: ...
def start_standing_subprocess(
    cmd, shell: bool = ..., env: Incomplete | None = ...
): ...
def stop_standing_subprocess(proc) -> None: ...
def wait_for_standing_subprocess(
    proc, timeout: Incomplete | None = ...
) -> None: ...
def get_available_host_port(): ...
def grep(regex, output): ...
def cli_cmd_to_string(args): ...
def get_settable_properties(cls): ...
def find_subclasses_in_module(base_classes, module): ...
def find_subclass_in_module(base_class, module): ...
