from typing import Any
from _typeshed import Incomplete

MAX_FILENAME_LEN: int
MAX_PORT_ALLOCATION_RETRY: int
ascii_letters_and_digits: Incomplete
valid_filename_chars: Incomplete
GMT_to_olson: Incomplete

class Error(Exception): ...

def abs_path(path: Any) -> Any: ...
def create_dir(path: Any) -> None: ...
def create_alias(target_path: Any, alias_path: Any) -> None: ...
def get_current_epoch_time() -> Any: ...
def get_current_human_time() -> Any: ...
def epoch_to_human_time(epoch_time: Any) -> Any: ...
def get_timezone_olson_id() -> Any: ...
def find_files(paths: Any, file_predicate: Any) -> Any: ...
def load_file_to_base64_str(f_path: Any) -> Any: ...
def find_field(item_list: Any, cond: Any, comparator: Any, target_field: Any) -> Any: ...
def rand_ascii_str(length: Any) -> Any: ...
def concurrent_exec(
    func: Any, param_list: Any, max_workers: int = ..., raise_on_exception: bool = ...
) -> Any: ...
def run_command(
    cmd: Any,
    stdout: Any = ...,
    stderr: Any = ...,
    shell: Any = ...,
    timeout: Any = ...,
    cwd: Any = ...,
    env: Any = ...,
    universal_newlines: bool = ...,
) -> tuple[int, bytes, bytes] | tuple[int, str, str]: ...
def start_standing_subprocess(
    cmd: Any, shell: bool = ..., env: Incomplete | None = ...
) -> Any: ...
def stop_standing_subprocess(proc: Any) -> None: ...
def wait_for_standing_subprocess(
    proc: Any, timeout: Incomplete | None = ...
) -> None: ...
def get_available_host_port() -> Any: ...
def grep(regex: Any, output: Any) -> Any: ...
def cli_cmd_to_string(args: Any) -> Any: ...
def get_settable_properties(cls: Any) -> Any: ...
def find_subclasses_in_module(base_classes: Any, module: Any) -> Any: ...
def find_subclass_in_module(base_class: Any, module: Any) -> Any: ...
