# Copyright 2026 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

import("//build/cpp/library_headers.gni")
import("//zircon/kernel/kernel_rust_mod.gni")

library_headers("headers") {
  headers = [
    "dev/power/motmot/init.h",
    "dev/power/motmot/motmot_ffi.h",
  ]
}

kernel_rust_mod("motmot-rs") {
  output_name = "power_motmot"
  source_root = "motmot.rs"
  sources = [ "motmot.rs" ]
  deps = [
    "//sdk/rust/zx-status",
    "//zircon/kernel/lib/debug",
  ]
  test_deps = [ "//zircon/kernel/lib/unittest:unittest-rs" ]
}

source_set("motmot") {
  sources = [ "motmot_ffi.cc" ]
  public_deps = [ ":headers" ]
  deps = [
    ":motmot-rs",
    "//zircon/kernel/dev/pdev/power",
    "//zircon/kernel/dev/psci",
    "//zircon/kernel/lib/arch",
  ]
}
