from _typeshed import Incomplete
from mobly.controllers.android_device_lib import sl4a_client as sl4a_client
from mobly.controllers.android_device_lib.services import (
    base_service as base_service,
)

class Sl4aService(base_service.BaseService):
    def __init__(self, device, configs: Incomplete | None = ...) -> None: ...
    @property
    def is_alive(self): ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def __getattr__(self, name): ...
