# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/test.gni")

test("unittests") {
  output_name = "analytics_cpp_core_dev_tools_unittests"
  sources = [
    "environment_status_unittest.cc",
    "persistent_status_unittest.cc",
  ]

  deps = [
    ":core_dev_tools",
    ":testable_internals",
    "//src/lib/analytics/cpp/metric_properties",
    "//src/lib/files",
    "//src/lib/fxl/test:gtest_main",
    "//src/lib/uuid",
    "//third_party/googletest:gtest",
  ]
}

test("system_info_manualtest") {
  output_name = "analytics_cpp_core_dev_tools_system_info_manualtest"
  sources = [ "system_info_manualtest.cc" ]
  deps = [ ":core_dev_tools" ]
}

test("analytics_executor_manualtest") {
  output_name = "analytics_cpp_core_dev_tools_analytics_executor_manualtest"
  sources = [ "analytics_executor_manualtest.cc" ]
  deps = [
    ":core_dev_tools",
    "//src/developer/debug/zxdb/common",
    "//src/lib/fxl",
  ]
}

test("google_analytics_4_client_manualtest") {
  output_name =
      "analytics_cpp_core_dev_tools_google_analytics_4_client_manualtest"
  sources = [ "google_analytics_4_client_manualtest.cc" ]
  deps = [
    ":core_dev_tools",
    "//src/developer/debug/zxdb/common",
    "//src/lib/fxl",
  ]
}

group("tests") {
  testonly = true

  deps = [
    ":analytics_executor_manualtest",
    ":google_analytics_4_client_manualtest",
    ":system_info_manualtest",
    ":unittests",
  ]
}

## BAZEL2GN SENTINEL - DO NOT EDIT BELOW THIS LINE ##
#
#  ________  _________  ________  ________
# |\   ____\|\___   ___\\   __  \|\   __  \
# \ \  \___|\|___ \  \_\ \  \|\  \ \  \|\  \
#  \ \_____  \   \ \  \ \ \  \\\  \ \   ____\
#   \|____|\  \   \ \  \ \ \  \\\  \ \  \___|
#     ____\_\  \   \ \__\ \ \_______\ \__\
#    |\_________\   \|__|  \|_______|\|__|
#    \|_________|
#
#
# AUTO-GENERATED - DO NOT EDIT
#
# The targets below are auto-generated based on the targets defined in the
# BUILD.bazel file from the same directory. If you made changes to targets in
# Bazel, instead of editing this file manually, run:
#
#   > fx bazel2gn
#
# Please do NOT edit this file directly. Instead, edit the BUILD.bazel file and
# rerun bazel2gn.

import("//build/tools/bazel2gn/bazel_migration.gni")

# A self-verification target for generated content in this file.
if (is_host) {
  verify_bazel2gn("verify_bazel2gn") {
  }
}

source_set("testable_internals") {
  sources = [
    "environment_status.cc",
    "persistent_status.cc",
  ]
  public = [
    "environment_status.h",
    "persistent_status.h",
  ]
  visibility = [ "*" ]
  public_deps = [
    "//sdk/lib/syslog/cpp",
    "//src/lib/analytics/cpp/metric_properties",
    "//src/lib/uuid",
  ]
}
static_library("core_dev_tools") {
  sources = [
    "analytics_executor.cc",
    "analytics_internal.cc",
    "analytics_messages.cc",
    "analytics_messages.h",
    "analytics_status.h",
    "command_line_options.cc",
    "ga4_common_events.h",
    "google_analytics_4_client.cc",
    "system_info.cc",
  ]
  public = [
    "analytics.h",
    "analytics_executor.h",
    "analytics_internal.h",
    "command_line_options.h",
    "google_analytics_4_client.h",
    "system_info.h",
  ]
  deps = [
    "//src/developer/debug/shared",
    "//src/developer/debug/zxdb/common",
  ]
  visibility = [ "*" ]
  public_deps = [
    ":testable_internals",
    "//sdk/lib/fit-promise",
    "//sdk/lib/syslog/cpp",
    "//src/lib/analytics/cpp/google_analytics_4",
    "//src/lib/analytics/cpp/metric_properties",
    "//src/lib/cmdline",
    "//src/lib/fxl",
  ]
}
