# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_applicable_licenses = ["//:license"])

cc_library(
    name = "testable_internals",
    srcs = [
        "environment_status.cc",
        "persistent_status.cc",
    ],
    hdrs = [
        "environment_status.h",
        "persistent_status.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//sdk/lib/syslog/cpp",
        "//src/lib/analytics/cpp/metric_properties",
        "//src/lib/uuid",
    ],
    alwayslink = True,
)

cc_library(
    name = "core_dev_tools",
    srcs = [
        "analytics_executor.cc",
        "analytics_internal.cc",
        "analytics_messages.cc",
        "analytics_messages.h",
        "analytics_status.h",
        "command_line_options.cc",
        "ga4_common_events.h",
        "google_analytics_4_client.cc",
        "system_info.cc",
    ],
    hdrs = [
        "analytics.h",
        "analytics_executor.h",
        "analytics_internal.h",
        "command_line_options.h",
        "google_analytics_4_client.h",
        "system_info.h",
    ],
    implementation_deps = [
        "//src/developer/debug/shared",
        "//src/developer/debug/zxdb/common",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":testable_internals",
        "//sdk/lib/fit-promise",
        "//sdk/lib/syslog/cpp",
        "//src/lib/analytics/cpp/google_analytics_4",
        "//src/lib/analytics/cpp/metric_properties",
        "//src/lib/cmdline",
        "//src/lib/fxl",
    ],
)
