// Copyright 2026 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// WARNING - This file was generated by src/connectivity/network/lib/pcap/src/bindgen.sh using
// bindgen 0.72.0. Do not modify this file! It should be
// regenerated by running src/connectivity/network/lib/pcap/src/bindgen.sh.

#![allow(non_camel_case_types)]
#![allow(clippy::missing_safety_doc)]
#![allow(missing_docs)]

use zerocopy::{Immutable, IntoBytes};

pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type u_char = __u_char;
pub type u_short = __u_short;
pub type u_int = __u_int;
pub type bpf_u_int32 = u_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct bpf_program {
    pub bf_len: u_int,
    pub bf_insns: *mut bpf_insn,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, IntoBytes, Immutable)]
pub struct bpf_insn {
    pub code: u_short,
    pub jt: u_char,
    pub jf: u_char,
    pub k: bpf_u_int32,
}
#[repr(C)]
#[derive(Debug)]
pub struct pcap {
    _unused: [u8; 0],
}
pub type pcap_t = pcap;
unsafe extern "C" {
    pub fn pcap_open_dead(arg1: ::std::os::raw::c_int, arg2: ::std::os::raw::c_int) -> *mut pcap_t;
}
unsafe extern "C" {
    pub fn pcap_close(arg1: *mut pcap_t);
}
unsafe extern "C" {
    pub fn pcap_compile(
        arg1: *mut pcap_t,
        arg2: *mut bpf_program,
        arg3: *const ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
        arg5: bpf_u_int32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pcap_freecode(arg1: *mut bpf_program);
}
