# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")
load("//build/bazel/rules/host_tests:host_go_test.bzl", "host_go_test")
load("//build/bazel/rules/host_tests:host_test_data.bzl", "host_test_data_files")

package(default_applicable_licenses = ["//:license"])

go_library(
    name = "gopkg",
    srcs = [
        "model.go",
        "report.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/sdk/ctf/plasa/model",
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//visibility:public"],
    deps = [
        "//third_party/golibs:github.com/google/go-cmp/cmp",
        "//third_party/golibs:gopkg.in/yaml.v2",
    ],
)

host_test_data_files(
    name = "model_testdata",
    srcs = [
        "testdata/@nonymous_record_FFBFAD8A3BBD799586600B40A3453BBD95900F13.yaml",
        "testdata/GlobalNamespace/index.yaml",
        "testdata/zx/basic_time.yaml",
        "testdata/zx/bti.yaml",
        "testdata/zx/channel.yaml",
        "testdata/zx/clock.yaml",
        "testdata/zx/debuglog.yaml",
        "testdata/zx/duration.yaml",
    ],
    dest_dir = "testdata",
)

host_go_test(
    name = "model_test",
    srcs = ["model_test.go"],
    embed = [":gopkg"],
    target_compatible_with = HOST_CONSTRAINTS,
    test_args = ["-test_data_dir=testdata"],
    test_data = [":model_testdata"],
    visibility = ["//sdk:__pkg__"],
)
