from _typeshed import Incomplete
from mobly import logger as logger
from mobly import utils as utils
from mobly.controllers import sniffer as sniffer

class SnifferLocalBase(sniffer.Sniffer):
    def __init__(
        self, interface, logger, base_configs: Incomplete | None = ...
    ) -> None: ...
    def get_interface(self): ...
    def get_type(self): ...
    def get_capture_file(self): ...
    def start_capture(
        self,
        override_configs: Incomplete | None = ...,
        additional_args: Incomplete | None = ...,
        duration: Incomplete | None = ...,
        packet_count: Incomplete | None = ...,
    ): ...
    def stop_capture(self) -> None: ...
    def wait_for_capture(self, timeout: Incomplete | None = ...) -> None: ...
