from _typeshed import Incomplete
from mobly.controllers import sniffer as sniffer
from mobly.controllers.sniffer_lib.local import local_base as local_base

class Sniffer(local_base.SnifferLocalBase):
    def __init__(
        self, config_path, logger, base_configs: Incomplete | None = ...
    ) -> None: ...
    def get_descriptor(self): ...
    def get_subtype(self): ...
