# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# A list of Bazel root targets for host tools under //tools directory.
tools_bazel_root_targets = [
  {
    bazel_label = "//tools/build/ninjago/buildstats:buildstats"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/buildstats_/buildstats"
        ninja = "buildstats"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/build/ninjago/ninjatrace:ninjatrace"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/ninjatrace_/ninjatrace"
        ninja = "ninjatrace"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/rust_test_parser:rust_test_parser"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/rust_test_parser_/rust_test_parser"
        ninja = "rust_test_parser"
      },
    ]
  },
  {
    bazel_label = "//tools/fidl/fidl_api_diff:fidl_api_diff"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/fidl_api_diff_/fidl_api_diff"
        ninja = "fidl_api_diff"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/fidl/fidl_api_summarize:fidl_api_summarize"
    copy_outputs = [
      {
        bazel =
            "{{BAZEL_TARGET_OUT_DIR}}/fidl_api_summarize_/fidl_api_summarize"
        ninja = "fidl_api_summarize"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/fidl/fidlcparsequality:fidlcparsequality"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/fidlcparsequality_/fidlcparsequality"
        ninja = "fidlcparsequality"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/fidl/fidlgen_go:fidlgen_go"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/fidlgen_go_/fidlgen_go"
        ninja = "fidlgen_go"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/fidl/fidlgen_python:fidlgen_python"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/fidlgen_python_/fidlgen_python"
        ninja = "fidlgen_python"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/fidl/fidlgen_syzkaller:fidlgen_syzkaller"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/fidlgen_syzkaller_/fidlgen_syzkaller"
        ninja = "fidlgen_syzkaller"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/fidl/gidl-format:gidl-format"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/gidl-format_/gidl-format"
        ninja = "gidl-format"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/fidl/gidl/cmd/gidl:gidl"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/gidl_/gidl"
        ninja = "gidl"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/fidl/gidl/cmd/gidl_audit:gidl_audit"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/gidl_audit_/gidl_audit"
        ninja = "gidl_audit"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/go_test_parser:go_test_parser"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/go_test_parser_/go_test_parser"
        ninja = "go_test_parser"
      },
    ]
  },
  {
    bazel_label = "//tools/staticanalysis/rfcmeta:rfcmeta"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/rfcmeta_/rfcmeta"
        ninja = "rfcmeta"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/debug/covargs:covargs"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/covargs_/covargs"
        ninja = "covargs"
      },
    ]
    install_host_tool = true  # Required by CI recipe
  },
  {
    bazel_label = "//tools/debug/symbolize:symbolize"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/symbolize_/symbolize"
        ninja = "symbolize"
      },
    ]
  },
  {
    bazel_label = "//tools/fidl/clang-format-wrapper:clang-format-wrapper"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/clang-format-wrapper_/clang-format-wrapper"
        ninja = "clang-format-wrapper"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/pretty_serial"
    install_host_tool = true
  },
  {
    bazel_label = "//tools/mdlint"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/mdlint_/mdlint"
        ninja = "mdlint"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/pkgstats/debugdump:debugdump"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/debugdump_/debugdump"
        ninja = "debugdump"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/debroot:debroot"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/debroot_/debroot"
        ninja = "debroot"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/whereiscl:whereiscl"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/whereiscl_/whereiscl"
        ninja = "whereiscl"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/jq5:jq5"
    install_host_tool = true
  },
  {
    bazel_label = "//tools/rust_extract"
    install_host_tool = true
  },
  {
    bazel_label = "//tools/fidl/fidldoc:fidldoc"
    install_host_tool = true
  },
  {
    bazel_label = "//tools/fidl/fidlgen_rust:fidlgen_rust"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/fidlgen_rust_/fidlgen_rust"
        ninja = "fidlgen_rust"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/fidl/fidlmerge:fidlmerge"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/fidlmerge_/fidlmerge"
        ninja = "fidlmerge"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/fidl/measure-tape/src:measure-tape"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/measure-tape_/measure-tape"
        ninja = "measure-tape"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/build/gndoc:gndoc"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/gndoc_/gndoc"
        ninja = "gndoc"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/integration/testsharder:testsharder"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/testsharder_/testsharder"
        ninja = "testsharder"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/readme_fuchsia:readme_fuchsia_bin"
    ninja_name = "readme_fuchsia"
    copy_outputs = [
      {
        bazel =
            "{{BAZEL_TARGET_OUT_DIR}}/readme_fuchsia_bin_/readme_fuchsia_bin"
        ninja = "readme_fuchsia"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/testing/testparser:testparser_cmd"
    ninja_name = "testparser"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/testparser_cmd_/testparser_cmd"
        ninja = "testparser"
      },
    ]
  },
  {
    bazel_label = "//sdk/ctf/plasa/clang_doc_filter:clang_doc_filter"
    ninja_name = "clang_doc_filter"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/clang_doc_filter_/clang_doc_filter"
        ninja = "clang_doc_filter"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/check-licenses:check-licenses"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/check-licenses_/check-licenses"
        ninja = "check-licenses"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/check-licenses/util/cmd/gn/generate_project_json:check-licenses-gen-project-json"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/check-licenses-gen-project-json_/check-licenses-gen-project-json"
        ninja = "check-licenses-gen-project-json"
      },
    ]
    install_host_tool = true
  },
  {
    bazel_label = "//tools/check-licenses/util/cmd/gn/generate_intermediate_json:generate_intermediate_json_cmd"
    copy_outputs = [
      {
        bazel = "{{BAZEL_TARGET_OUT_DIR}}/generate_intermediate_json_cmd_/generate_intermediate_json_cmd"
        ninja = "generate_intermediate_json_cmd"
      },
    ]
    install_host_tool = true
  },
]
