# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")

package(default_applicable_licenses = ["//:license"])

test_suite(
    name = "host_tests",
    target_compatible_with = HOST_CONSTRAINTS,
    tests = [
        "//tools/check-licenses:tests",
        "//tools/fidl/fidlgen_rust/codegen:fidlgen_rust_lib_tests",
        "//tools/lib/subprocess:tests",
        "//tools/orchestrate:tests",
        "//tools/whereiscl:host_tests",
    ],
)
