# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")

package(default_applicable_licenses = ["//:license"])

test_suite(
    name = "host_tests",
    target_compatible_with = HOST_CONSTRAINTS,
    tests = [
        "//tools/artifactory:artifactory_lib_tests",
        "//tools/artifactory:artifactory_main_tests",
        "//tools/build/fx-set:tests",
        "//tools/build/gndoc:gndoc_test",
        "//tools/build/ninjago/buildstats:buildstats_tests",
        "//tools/build/ninjago/chrometrace:chrometrace_test",
        "//tools/build/ninjago/clangtrace:clangtrace_test",
        "//tools/build/ninjago/ninjacommand:ninjacommand_tests",
        "//tools/build/ninjago/rbetrace:rbetrace_test",
        "//tools/bundle_fetcher:bundle_fetcher_main_tests",
        "//tools/bundle_fetcher:bundler_lib_tests",
        "//tools/check-licenses:tests",
        "//tools/dart_test_parser:dart_test_parser_lib_tests",
        "//tools/debug/debugsyms:debugsyms_tests",
        "//tools/debug/generate_breakpad:generate_breakpad_tests",
        "//tools/fidl/fidlgen_rust/codegen:fidlgen_rust_lib_tests",
        "//tools/fidl/gidl-format:gidl_format_tests",
        "//tools/fidl/gidl/backend/golang:gidl_golang_tests",
        "//tools/fidl/gidl/lib/mixer:gidl_mixer_tests",
        "//tools/fidl/gidl/lib/parser:gidl_parser_tests",
        "//tools/fidl/lib/apidiff:apidiff_test",
        "//tools/fidl/measure-tape/src:measure_tape_test",
        "//tools/fuzz:undercoat_tests",
        "//tools/go_test_parser:go_test_parser_lib_tests",
        "//tools/lib/agents:agents_tests",
        "//tools/lib/subprocess:tests",
        "//tools/orchestrate:tests",
        "//tools/qemu:qemu_tests",
        "//tools/readme_fuchsia:tests",
        "//tools/rust_test_parser:rust_test_parser_lib_tests",
        "//tools/staticanalysis/clippy-reporter:clippy_reporter_tests",
        "//tools/staticanalysis/rfcmeta:rfcmeta_tests",
        "//tools/testing/runtests:runtests_tests",
        "//tools/testing/tefmocheck:tefmocheck_lib_tests",
        "//tools/whereiscl:host_tests",
    ],
)
