# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

if (is_host) {
  executable("paper_shader_compiler") {
    sources = [ "main.cc" ]

    deps = [
      "//sdk/lib/syslog/cpp",
      "//src/ui/lib/escher:hack_filesystem",
      "//src/ui/lib/escher:static_config",
      "//src/ui/lib/escher/shaders/util:shader_utils",
      "//third_party/glm",
      "//third_party/shaderc/src:libshaderc",
    ]

    include_dirs = [
      "//lib",
      "//src/ui/lib/escher",
    ]
  }
}
