# Copyright 2021 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

group("drivers") {
  testonly = true
  deps = [
    "drivers/pci:bus-pci",
    "drivers/pci/test:pci_fake",
    "drivers/pci/test:pci_protocol_test_driver",
  ]
}

group("tests") {
  testonly = true
  deps = [
    "bin/lspci:tests",
    "drivers:tests",
    "lib:tests",
    "testing:tests",
  ]
}
