// Copyright 2026 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is automatically generated by //zircon/kernel/lib/counters:counters_bindgen_golden.

#![expect(dead_code)]
#![expect(non_camel_case_types)]
#![expect(non_upper_case_globals)]

#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::core::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::core::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        unsafe { ::core::slice::from_raw_parts(self.as_ptr(), len) }
    }
    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        unsafe { ::core::slice::from_raw_parts_mut(self.as_mut_ptr(), len) }
    }
}
impl<T> ::core::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
pub const counters_Type_kPadding: counters_Type = 0;
pub const counters_Type_kSum: counters_Type = 1;
pub const counters_Type_kMin: counters_Type = 2;
pub const counters_Type_kMax: counters_Type = 3;
pub type counters_Type = u64;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct counters_Descriptor {
    pub name: [::core::ffi::c_char; 56usize],
    pub type_: counters_Type,
}
#[repr(C)]
#[derive(Debug)]
pub struct counters_DescriptorVmo {
    pub magic: u64,
    pub max_cpus: u64,
    pub descriptor_table_size: u64,
    pub descriptor_table: __IncompleteArrayField<counters_Descriptor>,
}
pub const counters_DescriptorVmo_kVmoName: &[u8; 14] = b"counters/desc\0";
pub const counters_DescriptorVmo_kMagic: u64 = 1547273975;
