# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bazel/bazel_inputs.gni")
import("//build/bind/bind.gni")
import("//build/compiled_action.gni")
import("//build/components.gni")
import("//build/devicetree/devicetree.gni")
import("//build/drivers.gni")
import("//build/testing/environments.gni")

group("tests") {
  testonly = true
  deps = [
    ":vim3-dml-bind_test",
    ":vim3-dml-test-package",
    "//src/devices/tools/dmlc($host_toolchain)",
  ]
}

group("vim3-dml") {
  deps = [ ":component" ]
}

fuchsia_board_dml("gen-board-config") {
  board_name = "vim3-dml"
  dml = "meta/vim3.dml"
  sources = [
    "meta/adc.shard.dml",
    "meta/audio.shard.dml",
    "meta/bluetooth.shard.dml",
    "meta/buttons.shard.dml",
    "meta/canvas.shard.dml",
    "meta/clock.shard.dml",
    "meta/cpu.shard.dml",
    "meta/display.shard.dml",
    "meta/dt-root.shard.dml",
    "meta/ethernet.shard.dml",
    "meta/gic.shard.dml",
    "meta/gpio.shard.dml",
    "meta/gpu.shard.dml",
    "meta/hrtimer.shard.dml",
    "meta/i2c.shard.dml",
    "meta/mcu.shard.dml",
    "meta/nna.shard.dml",
    "meta/power.shard.dml",
    "meta/pwm.shard.dml",
    "meta/registers.shard.dml",
    "meta/rtc.shard.dml",
    "meta/sdmmc.shard.dml",
    "meta/suspend.shard.dml",
    "meta/thermal.shard.dml",
    "meta/usb.shard.dml",
    "meta/video.shard.dml",
    "meta/wifi.shard.dml",
  ]
}

driver_bind_rules("vim3-dml-bind") {
  dml_label = ":gen-board-config"
  bind_output = "vim3-dml.bindbc"
  tests = "meta/bind-tests.json"
  deps = [
    "//sdk/fidl/fuchsia.hardware.platform.bus:fuchsia.hardware.platform.bus_bindlib",
    "//src/devices/bind/fuchsia",
    "//src/devices/bind/fuchsia.khadas.platform",
  ]
}

resource("board-config") {
  sources = [ "$target_gen_dir/board-config.fidl" ]
  outputs = [ "config/board-config.fidl" ]
  deps = [ ":gen-board-config" ]
}

fuchsia_rust_driver("vim3-dml-driver") {
  output_name = "vim3-dml"
  edition = "2024"
  source_root = "src/lib.rs"
  sources = [
    "src/driver_specific_data.rs",
    "src/lib.rs",
  ]
  deps = [
    "//sdk/fidl/fuchsia.buttons:fuchsia.buttons_rust",
    "//sdk/fidl/fuchsia.driver.framework:fuchsia.driver.framework_rust_next",
    "//sdk/fidl/fuchsia.driver.metadata:fuchsia.driver.metadata_rust",
    "//sdk/fidl/fuchsia.hardware.adcimpl:fuchsia.hardware.adcimpl_rust",
    "//sdk/fidl/fuchsia.hardware.amlogic.metadata:fuchsia.hardware.amlogic.metadata_rust",
    "//sdk/fidl/fuchsia.hardware.clockimpl:fuchsia.hardware.clockimpl_rust",
    "//sdk/fidl/fuchsia.hardware.i2c.businfo:fuchsia.hardware.i2c.businfo_rust",
    "//sdk/fidl/fuchsia.hardware.platform.bus:fuchsia.hardware.platform.bus_rust_next",
    "//sdk/fidl/fuchsia.hardware.power:fuchsia.hardware.power_rust",
    "//sdk/fidl/fuchsia.hardware.pwm:fuchsia.hardware.pwm_rust",
    "//sdk/fidl/fuchsia.hardware.sdmmc:fuchsia.hardware.sdmmc_rust",
    "//sdk/fidl/fuchsia.hardware.serial:fuchsia.hardware.serial_rust",
    "//sdk/fidl/fuchsia.hardware.trippoint:fuchsia.hardware.trippoint_rust",
    "//sdk/fidl/fuchsia.hardware.usb.phy:fuchsia.hardware.usb.phy_rust",
    "//sdk/fidl/fuchsia.hardware.vreg:fuchsia.hardware.vreg_rust",
    "//sdk/fidl/fuchsia.input.report:fuchsia.input.report_rust",
    "//sdk/fidl/fuchsia.io:fuchsia.io_rust",
    "//sdk/lib/driver/component/rust",
    "//sdk/lib/driver/runtime/rust/fidl",
    "//sdk/rust/zx",
    "//src/devices/board/lib/dml-config",
    "//src/devices/board/lib/dml-config:fuchsia.board.dml.config_rust",
    "//src/devices/lib/broadcom/fuchsia.wlan.broadcom:fuchsia.wlan.broadcom_rust",
    "//src/devices/usb/lib/fuchsia.hardware.usb.dwc2:fuchsia.hardware.usb.dwc2_rust",
    "//src/lib/fidl/rust/fidl",
    "//src/lib/fidl/rust_next/fidl_next",
    "//src/lib/fuchsia-component",
    "//src/lib/fuchsia-fs",
    "//third_party/rust_crates:anyhow",
    "//third_party/rust_crates:log",
    "//third_party/rust_crates:phf",
  ]
}

fuchsia_driver_component("component") {
  component_name = "vim3-dml"
  cm_label = ":gen-board-config_manifest"
  info = "meta/vim3-dml-info.json"
  deps = [
    ":board-config",
    ":vim3-dml-bind",
    ":vim3-dml-driver",
  ]
}

# This is the target that will be referenced by board input bundle.
fuchsia_driver_package("package") {
  package_name = "vim3-dml"
  driver_components = [ ":component" ]
}

# Test target
executable("vim3-dml-test-bin") {
  testonly = true
  sources = [ "vim3-dml-test.cc" ]
  deps = [
    "//sdk/fidl/fuchsia.driver.test:fuchsia.driver.test_cpp",
    "//sdk/lib/async-loop:async-loop-cpp",
    "//sdk/lib/async-loop:async-loop-default",
    "//sdk/lib/device-watcher/cpp",
    "//sdk/lib/driver_test_realm/realm_builder/cpp",
    "//sdk/lib/fit",
    "//sdk/lib/sys/component/cpp/testing:cpp",
    "//sdk/lib/zbi-format",
    "//src/lib/fxl/test:gtest_main",
    "//third_party/googletest:gtest",
    "//zircon/system/ulib/ddk-platform-defs",
    "//zircon/system/ulib/sync:sync-cpp",
  ]
}

fuchsia_unittest_component("vim3-dml-test-component") {
  manifest = "meta/vim3-dml-test.cml"
  deps = [ ":vim3-dml-test-bin" ]
}

fuchsia_test_package("vim3-dml-test-package") {
  package_name = "vim3-dml-test"
  test_specs = {
    environments = [ vim3_env ]
  }
  deps = [
    ":component",  # Include the driver component we are testing
    "//src/lib/fuchsia-component-test/realm_builder_server:realm_builder_server_component",
  ]
  subpackages = [ "//sdk/lib/driver_test_realm:package" ]
  test_components = [ ":vim3-dml-test-component" ]
}
