# Copyright 2024 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Backward compatibility targets for vendor/google.
# TODO: Remove these after vendor/google is updated.

group("uart") {
  public_deps = [ "cpp:uart" ]
}

group("uart.bazel_input") {
  public_deps = [ "cpp:uart.bazel_input" ]
}
