# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_applicable_licenses = ["//:license"])

cc_library(
    name = "metric_properties",
    srcs = [
        "metric_properties.cc",
        "optional_path.cc",
    ],
    hdrs = [
        "metric_properties.h",
        "optional_path.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//sdk/lib/syslog/cpp",
        "//src/lib/files",
        "//src/lib/fxl",
    ],
)
