# Copyright 2024 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "input-report-reader",
    srcs = [
        "reader.cc",
    ],
    hdrs = [
        "reader.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//zircon/system/ulib/fbl",
        "@fuchsia_sdk//fidl/fuchsia.input.report:fuchsia.input.report_cpp",
        "@fuchsia_sdk//pkg/stdcompat",
        "@fuchsia_sdk//pkg/trace",
        "@fuchsia_sdk//pkg/zx",
    ],
)
