# Copyright 2024 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/sdk/sdk_host_tool.gni")

# TODO(https://fxbug.dev/438572714): Remove once IDK uses Bazel atom metadata.
sdk_host_tool("orchestrate_sdk") {
  category = "partner"
  output_name = "orchestrate"
  deps = [ "//build/bazel/host:bazel_root_host_tools.orchestrate" ]
}
