# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("//build/bazel/platforms:constraints.bzl", "HOST_OS_CONSTRAINTS")
load("//build/bazel/rules/host_tests:host_go_test.bzl", "host_go_test")
load("//build/bazel/rules/idk:idk_host_tool.bzl", "idk_go_binary_host_tool")

package(default_applicable_licenses = ["//:license"])

go_library(
    name = "utils",
    srcs = [
        "utils/utils.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/orchestrate/utils",
    target_compatible_with = HOST_OS_CONSTRAINTS,
)

go_library(
    name = "ffx",
    srcs = [
        "ffx/ffx.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/orchestrate/ffx",
    target_compatible_with = HOST_OS_CONSTRAINTS,
    deps = [
        ":utils",
    ],
)

go_library(
    name = "lib",
    srcs = [
        "config.go",
        "ffx_strict.go",
        "orchestrator.go",
        "serial.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/orchestrate",
    target_compatible_with = HOST_OS_CONSTRAINTS,
    deps = [
        ":ffx",
        ":utils",
        "//tools/lib/ffxutil",
    ],
)

go_library(
    name = "main",
    srcs = [
        "cmd/main.go",
        "cmd/run.go",
    ],
    importpath = "go.fuchsia.dev/fuchsia/tools/orchestrate/cmd",
    target_compatible_with = HOST_OS_CONSTRAINTS,
    deps = [
        ":lib",
        ":utils",
        "//third_party/golibs:github.com/google/subcommands",
    ],
)

host_go_test(
    name = "utils_tests",
    srcs = [
        "utils/utils_test.go",
    ],
    embed = [":utils"],
    deps = [
        "//third_party/golibs:github.com/google/go-cmp/cmp",
    ],
)

host_go_test(
    name = "ffx_tests",
    srcs = [
        "ffx/ffx_test.go",
    ],
    embed = [":ffx"],
)

host_go_test(
    name = "orchestrate_tests",
    srcs = [
        "config_test.go",
        "ffx_strict_test.go",
        "orchestrator_test.go",
    ],
    embed = [":lib"],
    deps = [
        "//third_party/golibs:github.com/google/go-cmp/cmp",
    ],
)

host_go_test(
    name = "cmd_tests",
    srcs = [
        "cmd/run_test.go",
    ],
    embed = [":main"],
)

test_suite(
    name = "tests",
    target_compatible_with = HOST_OS_CONSTRAINTS,
    tests = [
        ":cmd_tests",
        ":ffx_tests",
        ":orchestrate_tests",
        ":utils_tests",
    ],
    visibility = ["//tools:__pkg__"],
)

idk_go_binary_host_tool(
    name = "orchestrate",
    api_area = "Testing",
    category = "partner",
    embed = [":main"],
    idk_name = "orchestrate",
    target_compatible_with = HOST_OS_CONSTRAINTS,
)
