# Copyright 2021 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/bazel/bazel_host_tool.gni")

if (is_host) {
  bazel_host_tool("mdlint") {
    bazel_target = ":mdlint"
    bazel_output_path = "{{BAZEL_TARGET_OUT_DIR}}/mdlint_/mdlint"
    install_host_tool = true
  }
}

group("tests") {
  testonly = true
  deps = [
    "core:mdlint_core_tests($host_toolchain)",
    "rules:mdlint_rules_tests($host_toolchain)",
  ]
}
