# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

group("fidl") {
  public_deps = [
    ":fidl-lint",
    ":fidlfmt",
    "compat_audit($host_toolchain)",
    "fidl_ir",
    "fidlc:host",
    "fidlgen_cpp:host($host_toolchain)",
    "fidlgen_hlcpp:host",
    "fidlgen_rust_next:host",
    "lib:lib($host_toolchain)",
    "//tools/fidl/fidl_api_diff($host_toolchain)",
    "//tools/fidl/fidl_api_summarize($host_toolchain)",
    "//tools/fidl/fidlcparsequality($host_toolchain)",
    "//tools/fidl/fidldoc($host_toolchain)",
    "//tools/fidl/fidlgen_go($host_toolchain)",
    "//tools/fidl/fidlgen_python($host_toolchain)",
    "//tools/fidl/fidlgen_rust($host_toolchain)",
    "//tools/fidl/fidlgen_syzkaller($host_toolchain)",
    "//tools/fidl/fidlmerge($host_toolchain)",
    "//tools/fidl/gidl-format($host_toolchain)",
    "//tools/fidl/gidl/cmd/gidl($host_toolchain)",
    "//tools/fidl/gidl/cmd/gidl_audit($host_toolchain)",
    "//tools/fidl/measure-tape/src:measure-tape($host_toolchain)",
  ]
}

group("fidlfmt") {
  if (current_os != "fuchsia") {
    deps = [ "fidlc:fidl-format" ]
  }
}

group("fidl-lint") {
  if (current_os != "fuchsia") {
    deps = [ "fidlc:fidl-lint" ]
  }
}

group("tests") {
  testonly = true

  deps = [
    "abi-compat:tests",
    "example-tester:tests",
    "fidl_ir:tests",
    "fidlc:tests",
    "fidldoc:tests",
    "fidlgen_cpp:tests",
    "fidlgen_go:tests",
    "fidlgen_hlcpp:tests",
    "fidlgen_python:tests",
    "fidlgen_rust:tests",
    "fidlgen_rust_next:tests",
    "fidlgen_syzkaller:tests",
    "gidl:tests",
    "lib:tests",
    "measure-tape:tests",
  ]
}
