# Copyright 2026 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

package(default_applicable_licenses = ["//:license"])

alias(
    name = "LLVMAArch64CodeGen",
    actual = "@prebuilt_llvm//:LLVMAArch64CodeGen",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMAArch64Desc",
    actual = "@prebuilt_llvm//:LLVMAArch64Desc",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMAArch64Disassembler",
    actual = "@prebuilt_llvm//:LLVMAArch64Disassembler",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMAArch64Info",
    actual = "@prebuilt_llvm//:LLVMAArch64Info",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMAArch64Utils",
    actual = "@prebuilt_llvm//:LLVMAArch64Utils",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMARMCodeGen",
    actual = "@prebuilt_llvm//:LLVMARMCodeGen",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMARMDesc",
    actual = "@prebuilt_llvm//:LLVMARMDesc",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMARMDisassembler",
    actual = "@prebuilt_llvm//:LLVMARMDisassembler",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMARMInfo",
    actual = "@prebuilt_llvm//:LLVMARMInfo",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMARMUtils",
    actual = "@prebuilt_llvm//:LLVMARMUtils",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMAggressiveInstCombine",
    actual = "@prebuilt_llvm//:LLVMAggressiveInstCombine",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMAnalysis",
    actual = "@prebuilt_llvm//:LLVMAnalysis",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMAsmParser",
    actual = "@prebuilt_llvm//:LLVMAsmParser",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMAsmPrinter",
    actual = "@prebuilt_llvm//:LLVMAsmPrinter",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMBinaryFormat",
    actual = "@prebuilt_llvm//:LLVMBinaryFormat",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMBitReader",
    actual = "@prebuilt_llvm//:LLVMBitReader",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMBitWriter",
    actual = "@prebuilt_llvm//:LLVMBitWriter",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMBitstreamReader",
    actual = "@prebuilt_llvm//:LLVMBitstreamReader",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMCFGuard",
    actual = "@prebuilt_llvm//:LLVMCFGuard",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMCGData",
    actual = "@prebuilt_llvm//:LLVMCGData",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMCodeGen",
    actual = "@prebuilt_llvm//:LLVMCodeGen",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMCodeGenTypes",
    actual = "@prebuilt_llvm//:LLVMCodeGenTypes",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMCore",
    actual = "@prebuilt_llvm//:LLVMCore",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMCoroutines",
    actual = "@prebuilt_llvm//:LLVMCoroutines",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMDebugInfoBTF",
    actual = "@prebuilt_llvm//:LLVMDebugInfoBTF",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMDebugInfoCodeView",
    actual = "@prebuilt_llvm//:LLVMDebugInfoCodeView",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMDebugInfoDWARF",
    actual = "@prebuilt_llvm//:LLVMDebugInfoDWARF",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMDebugInfoDWARFLowLevel",
    actual = "@prebuilt_llvm//:LLVMDebugInfoDWARFLowLevel",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMDebugInfoGSYM",
    actual = "@prebuilt_llvm//:LLVMDebugInfoGSYM",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMDebugInfoMSF",
    actual = "@prebuilt_llvm//:LLVMDebugInfoMSF",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMDebugInfoPDB",
    actual = "@prebuilt_llvm//:LLVMDebugInfoPDB",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMDemangle",
    actual = "@prebuilt_llvm//:LLVMDemangle",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMExecutionEngine",
    actual = "@prebuilt_llvm//:LLVMExecutionEngine",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMFrontendAtomic",
    actual = "@prebuilt_llvm//:LLVMFrontendAtomic",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMFrontendDirective",
    actual = "@prebuilt_llvm//:LLVMFrontendDirective",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMFrontendHLSL",
    actual = "@prebuilt_llvm//:LLVMFrontendHLSL",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMFrontendOffloading",
    actual = "@prebuilt_llvm//:LLVMFrontendOffloading",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMFrontendOpenMP",
    actual = "@prebuilt_llvm//:LLVMFrontendOpenMP",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMGlobalISel",
    actual = "@prebuilt_llvm//:LLVMGlobalISel",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMHipStdPar",
    actual = "@prebuilt_llvm//:LLVMHipStdPar",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMIRPrinter",
    actual = "@prebuilt_llvm//:LLVMIRPrinter",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMIRReader",
    actual = "@prebuilt_llvm//:LLVMIRReader",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMInstCombine",
    actual = "@prebuilt_llvm//:LLVMInstCombine",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMInstrumentation",
    actual = "@prebuilt_llvm//:LLVMInstrumentation",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMLinker",
    actual = "@prebuilt_llvm//:LLVMLinker",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMMC",
    actual = "@prebuilt_llvm//:LLVMMC",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMMCDisassembler",
    actual = "@prebuilt_llvm//:LLVMMCDisassembler",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMMCJIT",
    actual = "@prebuilt_llvm//:LLVMMCJIT",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMMCParser",
    actual = "@prebuilt_llvm//:LLVMMCParser",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMObjCARCOpts",
    actual = "@prebuilt_llvm//:LLVMObjCARCOpts",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMObject",
    actual = "@prebuilt_llvm//:LLVMObject",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMObjectYAML",
    actual = "@prebuilt_llvm//:LLVMObjectYAML",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMOrcShared",
    actual = "@prebuilt_llvm//:LLVMOrcShared",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMOrcTargetProcess",
    actual = "@prebuilt_llvm//:LLVMOrcTargetProcess",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMPasses",
    actual = "@prebuilt_llvm//:LLVMPasses",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMProfileData",
    actual = "@prebuilt_llvm//:LLVMProfileData",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMRISCVCodeGen",
    actual = "@prebuilt_llvm//:LLVMRISCVCodeGen",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMRISCVDesc",
    actual = "@prebuilt_llvm//:LLVMRISCVDesc",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMRISCVDisassembler",
    actual = "@prebuilt_llvm//:LLVMRISCVDisassembler",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMRISCVInfo",
    actual = "@prebuilt_llvm//:LLVMRISCVInfo",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMRemarks",
    actual = "@prebuilt_llvm//:LLVMRemarks",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMRuntimeDyld",
    actual = "@prebuilt_llvm//:LLVMRuntimeDyld",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMSandboxIR",
    actual = "@prebuilt_llvm//:LLVMSandboxIR",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMScalarOpts",
    actual = "@prebuilt_llvm//:LLVMScalarOpts",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMSelectionDAG",
    actual = "@prebuilt_llvm//:LLVMSelectionDAG",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMSupport",
    actual = "@prebuilt_llvm//:LLVMSupport",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMSymbolize",
    actual = "@prebuilt_llvm//:LLVMSymbolize",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMTarget",
    actual = "@prebuilt_llvm//:LLVMTarget",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMTargetParser",
    actual = "@prebuilt_llvm//:LLVMTargetParser",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMTextAPI",
    actual = "@prebuilt_llvm//:LLVMTextAPI",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMTransformUtils",
    actual = "@prebuilt_llvm//:LLVMTransformUtils",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMVectorize",
    actual = "@prebuilt_llvm//:LLVMVectorize",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMX86CodeGen",
    actual = "@prebuilt_llvm//:LLVMX86CodeGen",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMX86Desc",
    actual = "@prebuilt_llvm//:LLVMX86Desc",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMX86Disassembler",
    actual = "@prebuilt_llvm//:LLVMX86Disassembler",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMX86Info",
    actual = "@prebuilt_llvm//:LLVMX86Info",
    visibility = ["//visibility:public"],
)

alias(
    name = "LLVMipo",
    actual = "@prebuilt_llvm//:LLVMipo",
    visibility = ["//visibility:public"],
)
